homeassistant:
  customize:
    sensor.kitchen_sink_leak_sensor_battery:
      battery_type: "ER14250 3.6V"
      battery_warning_level: 25
    sensor.water_heater_leak_sensor_battery:
      battery_type: "ER14250 3.6V"
      battery_warning_level: 25

binary_sensor:
  - platform: "group"
    unique_id: "binary_sensor.all_leaks"
    device_class: "moisture"
    name: "All leaks"
    entities:
      - "binary_sensor.kitchen_sink_leak"
      - "binary_sensor.washing_machine_leak"
      - "binary_sensor.water_heater_leak"

automation:
  - id: "fe3960bb-6e97-4799-9a1f-5fea762e8e65"
    alias: "water_leak_alarm"
    description: "Trigger alarm notifications when water leaks are detected."
    use_blueprint:
      path: "alarm.yaml"
      input:
        name: "Water leak"
        sensor: "binary_sensor.all_leaks"
