homeassistant:
  customize:
    binary_sensor.guest_mode:
      friendly_name: "Guest mode"
    person.chris:
      entity_picture: "/local/secrets/chris.webp"
    person.karine:
      entity_picture: "/local/secrets/karine.webp"
    sensor.guests_home:
      friendly_name: "Guests at home"

person:
  - id: "chris"
    name: "Chris"
    user_id: "221fad543e1a4c05af8aaac8c68e985e"
    device_trackers:
      - device_tracker.chris_router_pixel_6
      - device_tracker.chris_mobile_app_pixel_6
  - id: "karine"
    name: "Karine"
    user_id: "ef6743938a1646d2a1e8706e1bc00e34"
    device_trackers:
      - device_tracker.karine_router_pixel_7
      - device_tracker.karine_mobile_app_pixel_7

group:
  household:
    name: "Household"
    icon: "mdi:account-multiple"
    entities: &household_entities
      - person.chris
      - person.karine
  guests:
    name: "Guests"
    icon: "mdi:account-group"
    entities: &guest_entities
      - person.guest_cava
      - person.guest_gipa
      - person.guest_laboro
      - person.guest_stfr
      - person.guest_syvi

input_boolean:
  force_guest_mode:
    name: "Force guest mode"
    icon: "mdi:human-greeting"
  notify_household_changes:
    name: "Notify household changes"
    icon: "mdi:message-cog"
  notify_individual_guest_arrivals:
    name: "Notify individual guest arrivals"
    icon: "mdi:message-cog"

template:
  - binary_sensor:
      - unique_id: "binary_sensor.guest_mode"
        name: "guest_mode"
        icon: "mdi:human-greeting"
        state: >-
          {{
            is_state('input_boolean.force_guest_mode', 'on')
              or is_state('group.household', 'home')
              and state_attr('sensor.guests_home', 'count') | int(0) > 0
          }}

    sensor:
      - unique_id: "sensor.guests_home"
        name: "guests_home"
        icon: "mdi:account-star"
        state: >-
          {{
            expand(this.attributes.entity_id | default([]))
              | map('attr', 'name')
              | sort
              | join(', ')
              | default('Nobody', true)
          }}
        attributes:
          entity_id: >-
            {{
              expand('group.guests')
                | selectattr('state', 'eq', 'home')
                | list
            }}
          count: "{{ this.attributes.entity_id | default([]) | count }}"

automation:
  - id: "91bb52da-440a-4082-a6f3-4e58253a51c8"
    alias: notify_guest_arrives
    initial_state: true
    mode: "parallel"
    triggers:
      - trigger: state
        entity_id: *guest_entities
        to: "home"
    conditions: >-
      {{
        is_state('input_boolean.notify_individual_guest_arrivals', 'on')
          or is_state_attr('sensor.guests_home', 'count', '1')
      }}
    actions:
      - action: python_script.notify
        data:
          persistent: true
          push_target: "household"
          tag: "presence_{{ trigger.to_state.object_id }}"
          title: "{{ trigger.to_state.name }} is here"
          message: "{{ state_attr('sensor.guests_home', 'count') }} guests are home."

  - id: "33ae901e-24b8-4576-b876-4d2a87a7bd3b"
    alias: notify_household_person_arrives
    initial_state: true
    mode: "parallel"
    triggers:
      - trigger: state
        entity_id: *household_entities
        to: "home"
    conditions:
      - condition: state
        entity_id: input_boolean.notify_household_changes
        state: "on"
    actions:
      - action: python_script.notify
        data:
          push_target: "admin"
          tag: "presence_{{ trigger.to_state.object_id }}"
          title: "{{ trigger.to_state.name }} arrived home."
          message: "Household is {{ states_translated('group.household') }}."

  - id: "b3882bea-08d5-4c54-a076-092754457354"
    alias: notify_household_person_leaves
    initial_state: true
    mode: "parallel"
    triggers:
      - trigger: state
        entity_id: *household_entities
        from: "home"
    conditions:
      - condition: state
        entity_id: input_boolean.notify_household_changes
        state: "on"
    actions:
      - action: python_script.notify
        data:
          push_target: "admin"
          tag: "presence_{{ trigger.to_state.object_id }}"
          title: "{{ trigger.to_state.name }} left home."
          message: "Household is {{ states_translated('group.household') }}."
