blueprint:
  name: Clear an alarm
  domain: automation
  input:
    group:
      name: Sensor group.
      description: Binary sensor group that will clear the alarm once it turns off.
      selector:
        entity:
          filter:
            - domain: binary_sensor
              integration: group
    name:
      name: Name of the thing this alarm handles.
      selector:
        text: {}
    tag:
      name: An optional tag to identify this notification.
      default: ""
      selector:
        text: {}

initial_state: true
max_exceeded: "silent"
mode: "single"

trigger:
  - platform: "state"
    entity_id: !input group
    from: "on"
    to: "off"
    for: 10

variables:
  name: !input name
  group: !input group
  tag: !input tag

action:
  - action: python_script.notify
    data:
      audio: false
      dismissible: true
      persistent: true
      priority: false
      push_target: "household"
      tag: "alarm_{{ name | slugify }}_{{ tag | slugify }}"
      title: "{{ name | capitalize }} cleared"
      url: "/lovelace/security"
