group:
  all_batteries:
    name: "Batteries"
    icon: "mdi:battery"
    entities: &battery_entities
      - sensor.basement_bathroom_door_sensor_battery
      - sensor.basement_bathroom_multisensor_battery
      - sensor.chris_bedside_remote_battery
      - sensor.dollorama_battery
      - sensor.guest_bedroom_window_sensor_battery
      - sensor.karine_bedside_remote_battery
      - sensor.kitchen_door_sensor_battery
      - sensor.kitchen_sink_leak_sensor_battery
      - sensor.living_room_door_sensor_battery
      - sensor.laundry_motion_sensor_battery
      - sensor.lounge_window_sensor_battery
      - sensor.main_bathroom_multisensor_battery
      - sensor.maitre_doyle_battery
      - sensor.rubber_ducky_battery
      - sensor.spidy_battery
      - sensor.studio_window_sensor_battery
      - sensor.tully_battery
      - sensor.ups_battery_status
      - sensor.viny_battery
      - sensor.water_heater_leak_sensor_battery
      - sensor.workshop_motion_sensor_battery

binary_sensor:
  - platform: template
    sensors:
      all_batteries:
        friendly_name: "All batteries"
        device_class: "battery"
        entity_id: "sensor.low_batteries"
        value_template: "{{ not is_state('sensor.low_batteries', '') }}"
        attribute_templates:
          entity_id: "{{ states('sensor.low_batteries') }}"

sensor:
  - platform: template
    sensors:
      low_batteries:
        friendly_name: "Low batteries"
        icon_template: "mdi:battery"
        entity_id: *battery_entities
        value_template: >-
          {% set n = namespace(entities = []) %}

          {% for entity in expand('group.all_batteries') %}
            {% set state = entity.state | int(100) %}
            {% set warning_level = state_attr(entity.entity_id, 'battery_warning_level') | int(25) %}
            {% if state <= warning_level %}
              {% set n.entities = n.entities + [entity.entity_id] %}
            {% endif %}
          {% endfor %}

          {{ n.entities | join(', ') }}

automation:
  - alias: "Notify low batteries"
    initial_state: true
    trigger:
      - platform: numeric_state
        value_template: >-
          {% if state.state in ['unknown', 'unavailable'] -%}
            100
          {%- else -%}
            {{ state.state | int - state_attr(x.entity_id, 'battery_warning_level') | int(25) }}
          {%- endif %}
        below: 0
        entity_id: *battery_entities
    action:
      - service: python_script.notify
        data_template:
          persistent: true
          push_target: "household"
          tag: "battery_low_{{ trigger.to_state.object_id }}"
          url: "https://www.amazon.ca/s/?field-keywords=battery+{{ state_attr(trigger.to_state.entity_id, 'battery_type') | d('', True)  | replace(' ', '+') }}"
          title: "Replace {{ trigger.to_state.name | lower }}"
          message: "Search on Amazon for \"{{ state_attr(trigger.to_state.entity_id, 'battery_type') }}\" batteries."
