# TODO: Appropriate battery level on icon

homeassistant:
  customize:
    sensor.all_batteries:
      friendly_name: "All batteries"
      icon: "mdi:battery-70"
      device_class: "battery"

group:
  all_batteries:
    name: "Batteries"
    icon: "mdi:battery-70"
    control: "hidden"
    entities: &battery_entities
      - sensor.basement_bathroom_door_sensor_battery
      - sensor.basement_bathroom_multisensor_battery
      - sensor.chris_bedside_remote_battery
      - sensor.dollorama_battery
      - sensor.guest_bedroom_window_sensor_battery
      - sensor.karine_bedside_remote_battery
      - sensor.kitchen_door_sensor_battery
      - sensor.kitchen_sink_leak_sensor_battery
      - sensor.living_room_door_sensor_battery
      - sensor.laundry_motion_sensor_battery
      - sensor.lounge_window_sensor_battery
      - sensor.main_bathroom_door_sensor_battery
      - sensor.main_bathroom_multisensor_battery
      - sensor.maitre_doyle_battery
      - sensor.rubber_ducky_battery
      - sensor.spidy_battery
      - sensor.studio_window_sensor_battery
      - sensor.ups_battery_status
      - sensor.viny_battery
      - sensor.water_heater_leak_sensor_battery
      - sensor.workshop_motion_sensor_battery

sensor:
  - platform: min_max
    name: "all_batteries"
    type: "min"
    round_digits: 0
    entity_ids: *battery_entities

automation:
  - alias: "Notify low batteries"
    initial_state: True
    trigger:
      - platform: numeric_state
        value_template: >-
          {% if state.state in ['unknown', 'unavailable'] -%}
            100
          {%- else -%}
            {{ state.state | int - state.attributes.battery_warning_level | default(25) | int }}
          {%- endif %}
        below: 0
        entity_id: *battery_entities
    action:
      - service: python_script.notify
        data_template:
          persistent: True
          push_target: "household"
          tag: "battery_low_{{ trigger.to_state.object_id }}"
          url: "https://www.amazon.ca/s/?field-keywords=battery+{{ state_attr(trigger.to_state.entity_id, 'battery_type') | d('', True)  | replace(' ', '+') }}"
          title: "Replace {{ trigger.to_state.name | lower }}"
          message: "Search on Amazon for \"{{ state_attr(trigger.to_state.entity_id, 'battery_type') }}\" batteries."
