homeassistant:
  customize:
    cover.dining_room_blinds:
      closed_pct: 9
    cover.kitchen_counter_blinds:
      closed_pct: 10

cover:
  - name: "All blinds"
    platform: "group"
    unique_id: "b305e505-b217-49e7-838e-2547a78246f8"
    entities:
      - "cover.dining_room_blinds"
      - "cover.kitchen_counter_blinds"
      - "cover.kitchen_sink_blinds"
      - "cover.living_room_blinds"

script:
  close_cover:
    alias: "Close a cover"
    description: "Close a cover, respecting its configured limit setting."
    icon: "mdi:roller-shade-closed"
    mode: "parallel"

    fields:
      entity_id:
        name: "Entity ID of the cover to close"
        required: true
        selector:
          entity:
            multiple: false
            filter:
              domain:
                - "cover"
      double_close_bypasses_limit:
        name: "Bypass limit when closed again"
        description: "Allow this cover to be fully closed if it is already at its configured limit."
        required: false
        default: false
        selector:
          boolean: ~

    variables:
      closed_pct: "{{ state_attr(entity_id, 'closed_pct') | int(0) }}"
      current_position: "{{ state_attr(entity_id, 'current_position') | int(0) }}"

    sequence:
      - if: "{{ entity_id == 'cover.all_blinds' }}"
        then:
          - action: "script.close_all_blinds"
        else:
          - if: "{{ closed_pct != 0 and current_position > closed_pct }}"
            then:
              - action: "cover.set_cover_position"
                target:
                  entity_id: "{{ entity_id }}"
                data:
                  position: "{{ closed_pct }}"
            else:
              - if: "{{ current_position != 0 and (closed_pct == 0 or double_close_bypasses_limit | default(false, true)) }}"
                then:
                  - action: "cover.close_cover"
                    target:
                      entity_id: "{{ entity_id }}"

  close_all_blinds:
    alias: "Close all blinds"
    icon: "mdi:roller-shade-closed"
    mode: "single"
    max_exceeded: "silent"

    sequence:
      - repeat:
          for_each: "{{ expand('cover.all_blinds') | map(attribute = 'entity_id') | list }}"
          sequence:
            - action: "script.close_cover"
              data:
                entity_id: "{{ repeat.item }}"

automation:
  - alias: "blinds_remote_mappings"
    id: "473a0f1a-c540-42e6-9f81-6ecb23494d8b"
    mode: "parallel"

    triggers:
      - trigger: "state"
        entity_id: "event.blinds_remote_channel1_down_pressed"
        not_from: "unavailable"
        variables:
          entity_id: "cover.all_blinds"
          open: false
      - trigger: "state"
        entity_id: "event.blinds_remote_channel1_up_pressed"
        not_from: "unavailable"
        variables:
          entity_id: "cover.all_blinds"
          open: true
      - trigger: "state"
        entity_id: "event.blinds_remote_channel2_down_pressed"
        not_from: "unavailable"
        variables:
          entity_id: "cover.dining_room_blinds"
          open: false
      - trigger: "state"
        entity_id: "event.blinds_remote_channel2_up_pressed"
        not_from: "unavailable"
        variables:
          entity_id: "cover.dining_room_blinds"
          open: true
      - trigger: "state"
        entity_id: "event.blinds_remote_channel3_down_pressed"
        not_from: "unavailable"
        variables:
          entity_id: "cover.kitchen_counter_blinds"
          open: false
      - trigger: "state"
        entity_id: "event.blinds_remote_channel3_up_pressed"
        not_from: "unavailable"
        variables:
          entity_id: "cover.kitchen_counter_blinds"
          open: true
      - trigger: "state"
        entity_id: "event.blinds_remote_channel4_down_pressed"
        not_from: "unavailable"
        variables:
          entity_id: "cover.kitchen_sink_blinds"
          open: false
      - trigger: "state"
        entity_id: "event.blinds_remote_channel4_up_pressed"
        not_from: "unavailable"
        variables:
          entity_id: "cover.kitchen_sink_blinds"
          open: true
      - trigger: "state"
        entity_id: "event.blinds_remote_channel5_down_pressed"
        not_from: "unavailable"
        variables:
          entity_id: "cover.living_room_blinds"
          open: false
      - trigger: "state"
        entity_id: "event.blinds_remote_channel5_up_pressed"
        not_from: "unavailable"
        variables:
          entity_id: "cover.living_room_blinds"
          open: true

    actions:
      - if: "{{ open }}"
        then:
          - action: "cover.open_cover"
            target:
              entity_id: "{{ entity_id }}"
        else:
          - action: "script.close_cover"
            data:
              entity_id: "{{ entity_id }}"
              double_close_bypasses_limit: true