group:
  all_doors:
    name: "All doors"
    icon: "mdi:door"
    control: "hidden"
    entities: &door_entities
      - binary_sensor.kitchen_door
      - binary_sensor.living_room_door

binary_sensor:
  - platform: template
    sensors:
      all_doors:
        friendly_name: "All doors"
        device_class: "door"
        value_template: "{{ is_state('group.all_doors', 'on') }}"
