binary_sensor:
  - platform: "group"
    unique_id: "binary_sensor.all_doors"
    device_class: "door"
    name: "All doors"
    entities:
      - binary_sensor.kitchen_door
      - binary_sensor.living_room_door
