group:
  all_doors:
    name: "All doors"
    icon: "mdi:door"
    entities: &door_entities
      - binary_sensor.kitchen_door
      - binary_sensor.living_room_door

binary_sensor:
  - platform: template
    sensors:
      all_doors:
        friendly_name: "All doors"
        device_class: "door"
        entity_id: *door_entities
        value_template: >-
          {{
            expand('group.all_doors')
              | selectattr('state', 'eq', 'on')
              | list
              | length != 0
          }}
        attribute_templates:
          entity_id: >-
            {{
              expand('group.all_doors')
                | selectattr('state', 'eq', 'on')
                | map('attr', 'entity_id')
                | join(', ')
            }}
