binary_sensor:
  - platform: "group"
    unique_id: "binary_sensor.all_leaks"
    device_class: "door"
    name: "All leaks"
    entities: &leak_entities
      - binary_sensor.kitchen_sink_leak
      - binary_sensor.washing_machine_leak
      - binary_sensor.water_heater_leak

automation:
  - id: "106d9d0a-8a2b-4713-8c3f-3341a24cc9b9"
    alias: "Notify water leaks"
    initial_state: true
    mode: "parallel"
    trigger:
      - platform: state
        entity_id: *leak_entities
        to: "on"
    action:
      - service: python_script.notify
        data:
          audio: true
          persistent: true
          priority: true
          push_target: "household"
          tag: "water_leak_{{ trigger.to_state.object_id }}"
          url: "/lovelace/settings"
          title: "Water leak detected"
          message: "A water leak has been detected at the {{ trigger.to_state.name | title | replace('Leak', '') | replace('Sensor', '') | trim }}."
