group:
  all_leaks:
    name: "All leaks"
    icon: "mdi:pipe-leak"
    entities: &leak_entities
      - binary_sensor.kitchen_sink_leak
      - binary_sensor.washing_machine_leak
      - binary_sensor.water_heater_leak

binary_sensor:
  - platform: template
    sensors:
      all_leaks:
        unique_id: "binary_sensor.all_leaks"
        friendly_name: "All leaks"
        device_class: "moisture"
        icon_template: >-
          {% set active = expand('group.all_leaks')
              | selectattr('state', 'eq', 'on')
              | list
              | length != 0 %}
          mdi:pipe{% if active %}-leak{% endif %}
        value_template: >-
          {{
            expand('group.all_leaks')
              | selectattr('state', 'eq', 'on')
              | list
              | length != 0
          }}
        attribute_templates:
          entity_id: >-
            {{
              expand('group.all_leaks')
                | selectattr('state', 'eq', 'on')
                | map('attr', 'entity_id')
                | list
            }}

automation:
  - alias: "Notify water leaks"
    initial_state: true
    mode: "parallel"
    trigger:
      - platform: state
        entity_id: *leak_entities
        to: "on"
    action:
      - service: python_script.notify
        data:
          audio: true
          persistent: true
          push_target: "household"
          tag: "water_leak_{{ trigger.to_state.object_id }}"
          url: "/lovelace/settings"
          title: "Water leak detected"
          message: "A water leak has been detected at the {{ trigger.to_state.name | title | replace('Leak', '') | replace('Sensor', '') | trim }}."
