group:
  all_leaks:
    name: "All leaks"
    icon: "mdi:pipe-leak"
    control: "hidden"
    entities: &leak_entities
      - binary_sensor.kitchen_sink_leak
      - binary_sensor.water_heater_leak

binary_sensor:
  - platform: template
    sensors:
      all_leaks:
        friendly_name: "All leaks"
        device_class: "moisture"
        icon_template: "mdi:pipe{% if is_state('group.all_leaks', 'on') %}-leak{% endif %}"
        value_template: "{{ is_state('group.all_leaks', 'on') }}"

automation:
  - alias: "Notify water leaks"
    hide_entity: True
    initial_state: True
    trigger:
      - platform: state
        entity_id: *leak_entities
        to: "on"
    action:
      - service: python_script.notify
        data_template:
          audio: True
          persistent: True
          push_target: "household"
          tag: "water_{{ trigger.to_state.object_id }}"
          url: "/lovelace/settings"
          title: "Water leak detected"
          message: "A water leak has been detected at the {{ trigger.to_state.name | title | replace('Leak', '') | replace('Sensor', '') | trim }}."
