binary_sensor:
  - platform: "group"
    unique_id: "binary_sensor.all_motions"
    device_class: "motion"
    name: "All motions"
    entities:
      - binary_sensor.basement_bathroom_motion
      - binary_sensor.laundry_room_motion
      - binary_sensor.main_bathroom_motion
      - binary_sensor.workshop_motion

template:
  - sensor:
      - unique_id: "sensor.last_motion"
        name: "Last motion"
        icon: "mdi:motion-sensor"
        state: >-
          {{
            expand('binary_sensor.all_motions')
              | sort(attribute='last_changed', reverse=True)
              | map(attribute='name')
              | first
              | replace(' motion', '')
          }}
