group:
  all_motions:
    name: "All motions"
    icon: "mdi:motion-sensor"
    entities: &motion_entities
      - binary_sensor.basement_bathroom_motion
      - binary_sensor.laundry_room_motion
      - binary_sensor.main_bathroom_motion
      - binary_sensor.workshop_motion

binary_sensor:
  - platform: template
    sensors:
      all_motions:
        friendly_name: "All motions"
        device_class: "motion"
        entity_id: *motion_entities
        value_template: >-
          {{
            expand('group.all_motions')
              | selectattr('state', 'eq', 'on')
              | list
              | length != 0
          }}
        attribute_templates:
          entity_id: >-
            {{
              expand('group.all_motions')
                | selectattr('state', 'eq', 'on')
                | map('attr', 'entity_id')
                | join(', ')
            }}

sensor:
  - platform: template
    sensors:
      last_motion:
        friendly_name: "Last motion"
        entity_id: *motion_entities
        icon_template: >-
          {% set active = expand('group.all_motions')
              | selectattr('state', 'eq', 'on')
              | list
              | length != 0 %}
          mdi:{% if active %}motion-sensor{% else %}walk{% endif %}
        value_template: >-
          {{
            expand('group.all_motions')
              | sort(attribute='last_changed', reverse=True)
              | map(attribute='name')
              | first
              | replace(' motion', '')
          }}
