binary_sensor:
  - platform: "group"
    unique_id: "binary_sensor.all_motions"
    device_class: "motion"
    name: "All motions"
    entities:
      - binary_sensor.basement_bathroom_motion
      - binary_sensor.laundry_room_motion
      - binary_sensor.main_bathroom_motion
      - binary_sensor.workshop_motion

template:
  - sensor:
      - unique_id: "sensor.last_motion"
        name: "Last motion"
        icon: "mdi:motion-sensor"
        state: >-
          {%
            set last_motion = expand('binary_sensor.all_motions')
              | sort(attribute='last_changed', reverse=True)
              | map(attribute='name')
              | first
          %}
          {%- if last_motion is defined -%}
          {{ last_motion | replace(' motion', '') }}
          {%- endif %}

      - unique_id: "e6d941bc-0712-423b-b4e1-7d1d5e398c52"
        name: "Current motion"
        icon: "mdi:motion-sensor"
        state: >-
          {% from 'states.jinja' import current_sensor %}
          {{ current_sensor('binary_sensor.all_motions') }}
