group:
  all_motions:
    name: "All motions"
    icon: "mdi:run"
    control: "hidden"
    entities: &motion_entities
      - binary_sensor.basement_bathroom_motion
      - binary_sensor.laundry_room_motion
      - binary_sensor.main_bathroom_motion
      - binary_sensor.workshop_motion

binary_sensor:
  - platform: template
    sensors:
      all_motions:
        friendly_name: "All motions"
        device_class: "motion"
        value_template: "{{ is_state('group.all_motions', 'on') }}"

sensor:
  - platform: template
    sensors:
      last_motion:
        friendly_name: "Last motion"
        entity_id: *motion_entities
        icon_template: >-
          mdi:{% if is_state('group.all_motions', 'on') %}motion-sensor{% else %}walk{% endif %}
        value_template: >-
          {{
            expand('group.all_motions')
              | sort(attribute='last_changed', reverse=True)
              | map(attribute='name')
              | first
              | replace(' motion', '')
          }}
