binary_sensor:
  - platform: "group"
    unique_id: "binary_sensor.all_windows"
    device_class: "window"
    name: "All windows"
    entities:
      - binary_sensor.guest_bedroom_window
      - binary_sensor.studio_window
      - binary_sensor.lounge_window
