homeassistant:
  customize:
    cover.dining_room_blinds:
      alternate_pct: 20
      closed_pct: 9
    cover.kitchen_counter_blinds:
      alternate_pct: 20
      closed_pct: 10
    cover.kitchen_sink_blinds:
      alternate_pct: 20
    cover.living_room_blinds:
      alternate_pct: 20

binary_sensor:
  - platform: "group"
    unique_id: "binary_sensor.all_windows"
    device_class: "window"
    name: "All windows"
    entities:
      - binary_sensor.guest_bedroom_window
      - binary_sensor.studio_window
      - binary_sensor.lounge_window

cover:
  - name: "All blinds"
    platform: "group"
    unique_id: "b305e505-b217-49e7-838e-2547a78246f8"
    entities:
      - "cover.dining_room_blinds"
      - "cover.kitchen_counter_blinds"
      - "cover.kitchen_sink_blinds"
      - "cover.living_room_blinds"

template:
  - sensor:
      - unique_id: "add19ecd-5341-4a06-a8b9-12683355abca"
        default_entity_id: "sensor.current_window"
        name: "Current window"
        icon: "mdi:window-closed"
        state: >-
          {% from 'states.jinja' import current_sensor %}
          {{ current_sensor('binary_sensor.all_windows') }}

script:
  alternate_all_blinds:
    alias: "Alternate all blinds"
    icon: "mdi:roller-shade"
    mode: "single"
    max_exceeded: "silent"

    sequence: 
      - repeat:
          for_each: "{{ expand('cover.all_blinds') | map(attribute = 'entity_id') | list }}"
          sequence:
            - action: "script.alternate_cover"
              data:
                entity_id: "{{ repeat.item }}"

  close_all_blinds:
    alias: "Close all blinds"
    icon: "mdi:roller-shade-closed"
    mode: "single"
    max_exceeded: "silent"

    sequence:
      - repeat:
          for_each: "{{ expand('cover.all_blinds') | map(attribute = 'entity_id') | list }}"
          sequence:
            - action: "script.close_cover"
              data:
                entity_id: "{{ repeat.item }}"

  alternate_cover:
    alias: "Alternate a cover"
    description: "Move a cover to its alternate position, if configured, otherwise open it."
    icon: "mdi:roller-shade"
    mode: "parallel"

    fields:
      entity_id:
        name: "Entity ID of the cover to alternate"
        required: true
        selector:
          entity:
            multiple: false
            filter:
              domain:
                - "cover"

    variables:
      alternate_pct: "{{ state_attr(entity_id, 'alternate_pct') | int(100) }}"

    sequence:
      - if: "{{ entity_id == 'cover.all_blinds' }}"
        then:
          - action: "script.alternate_all_blinds"
        else:
          - action: "cover.set_cover_position"
            target:
              entity_id: "{{ entity_id }}"
            data:
              position: "{{ alternate_pct }}"

  close_cover:
    alias: "Close a cover"
    description: "Close a cover, respecting its configured limit setting."
    icon: "mdi:roller-shade-closed"
    mode: "parallel"

    fields:
      entity_id:
        name: "Entity ID of the cover to close"
        required: true
        selector:
          entity:
            multiple: false
            filter:
              domain:
                - "cover"
      double_close_bypasses_limit:
        name: "Bypass limit when closed again"
        description: "Allow this cover to be fully closed if it is already at its configured limit."
        required: false
        default: false
        selector:
          boolean: ~

    variables:
      closed_pct: "{{ state_attr(entity_id, 'closed_pct') | int(0) }}"
      current_position: "{{ state_attr(entity_id, 'current_position') | int(0) }}"

    sequence:
      - if: "{{ entity_id == 'cover.all_blinds' }}"
        then:
          - action: "script.close_all_blinds"
        else:
          - if: "{{ closed_pct != 0 and current_position > closed_pct }}"
            then:
              - action: "cover.set_cover_position"
                target:
                  entity_id: "{{ entity_id }}"
                data:
                  position: "{{ closed_pct }}"
            else:
              - if: "{{ current_position != 0 and (closed_pct == 0 or double_close_bypasses_limit | default(false, true)) }}"
                then:
                  - action: "cover.close_cover"
                    target:
                      entity_id: "{{ entity_id }}"

automation:
  - alias: "blinds_remote_mappings"
    id: "473a0f1a-c540-42e6-9f81-6ecb23494d8b"
    mode: "parallel"

    triggers:
      - trigger: "state"
        entity_id: "event.blinds_remote_channel1_down_pressed"
        not_from: "unavailable"
        variables:
          entity_id: "cover.all_blinds"
          action: "close"
      - trigger: "state"
        entity_id: "event.blinds_remote_channel1_up_pressed"
        not_from: "unavailable"
        variables:
          entity_id: "cover.all_blinds"
          action: "open"

      - trigger: "state"
        entity_id: "event.blinds_remote_channel2_down_pressed"
        not_from: "unavailable"
        variables:
          entity_id: "cover.dining_room_blinds"
          action: "close"
      - trigger: "state"
        entity_id: "event.blinds_remote_channel2_up_pressed"
        not_from: "unavailable"
        variables:
          entity_id: "cover.dining_room_blinds"
          action: "open"

      - trigger: "state"
        entity_id: "event.blinds_remote_channel3_down_pressed"
        not_from: "unavailable"
        variables:
          entity_id: "cover.kitchen_counter_blinds"
          action: "close"
      - trigger: "state"
        entity_id: "event.blinds_remote_channel3_up_pressed"
        not_from: "unavailable"
        variables:
          entity_id: "cover.kitchen_counter_blinds"
          action: "open"

      - trigger: "state"
        entity_id: "event.blinds_remote_channel4_down_pressed"
        not_from: "unavailable"
        variables:
          entity_id: "cover.kitchen_sink_blinds"
          action: "close"
      - trigger: "state"
        entity_id: "event.blinds_remote_channel4_up_pressed"
        not_from: "unavailable"
        variables:
          entity_id: "cover.kitchen_sink_blinds"
          action: "open"

      - trigger: "state"
        entity_id: "event.blinds_remote_channel5_down_pressed"
        not_from: "unavailable"
        variables:
          entity_id: "cover.living_room_blinds"
          action: "close"
      - trigger: "state"
        entity_id: "event.blinds_remote_channel5_up_pressed"
        not_from: "unavailable"
        variables:
          entity_id: "cover.living_room_blinds"
          action: "open"

    actions:
      - choose:
          - conditions: "{{ action == 'open' }}"
            sequence:
              - action: "cover.open_cover"
                target:
                  entity_id: "{{ entity_id }}"
          - conditions: "{{ action == 'alternated' }}"
            sequence:
              - action: "cover.set_cover_position"
                target:
                  entity_id: "{{ entity_id }}"
                data:
                  position: "{{ state_attr(entity_id, 'alternate_pct') }}"
        default:
          - action: "script.close_cover"
            data:
              entity_id: "{{ entity_id }}"
              double_close_bypasses_limit: true
