group:
  all_windows:
    name: "All windows"
    icon: "mdi:window-closed"
    entities: &window_entities
      - binary_sensor.guest_bedroom_window
      - binary_sensor.studio_window
      - binary_sensor.lounge_window

binary_sensor:
  - platform: template
    sensors:
      all_windows:
        friendly_name: "All windows"
        device_class: "window"
        value_template: "{{ is_state('group.all_windows', 'on') }}"
