group:
  all_windows:
    name: "All windows"
    icon: "mdi:window-closed"
    entities: &window_entities
      - binary_sensor.guest_bedroom_window
      - binary_sensor.studio_window
      - binary_sensor.lounge_window

binary_sensor:
  - platform: template
    sensors:
      all_windows:
        friendly_name: "All windows"
        device_class: "window"
        entity_id: *window_entities
        value_template: >-
          {{
            expand('group.all_windows')
              | selectattr('state', 'eq', 'on')
              | list
              | length != 0
          }}
        attribute_templates:
          entity_id: >-
            {{
              expand('group.all_windows')
                | selectattr('state', 'eq', 'on')
                | map('attr', 'entity_id')
                | join(', ')
            }}
