- alias: network_davice_state
  hide_entity: true
  trigger:
    - platform: state
      entity_id:
        - sensor.network_avatar_media
        - sensor.network_hue_hub
  action:
    service: notify.admin
    data_template:
      message: '{{ trigger.to_state.name }} is {{ trigger.to_state.state | lower }}!'
      data:
        tag: 'state_change_{{ trigger.entity_id }}'
    data:
      data:
        url: !secret http_public_host
