- alias: network_davice_state
  hide_entity: true
  trigger:
    - platform: state
      entity_id:
        - switch.network_hue_hub
        - switch.network_media
  action:
    service: notify.admin
    data_template:
      message: "{{ trigger.to_state.name }} is {{ trigger.to_state.state | lower }}!"
      data:
        tag: "{{ trigger.entity_id | replace('.', '_') }}"
    data:
      data:
        url: !secret http_public_host
