- alias: 'Notification: Network Device State'
  hide_entity: True
  trigger:
    - platform: state
      entity_id:
        - sensor.hue_hub
        - sensor.avatar_media
  action:
    service: notify.admin
    data_template:
      message: '{{ trigger.to_state.name }} is {{ trigger.to_state.state | lower }}!'
      data:
        tag: 'state_change_{{ trigger.entity_id }}'
    data:
      data:
        url: !secret http_public_host
