###############################################################################
## Automation / Persistent States
##
## Add `persistent: true` in the customize section to enable persistence.
## Supported domains include:
## automation, light, switch, input_boolean, input_select, input_slider
###############################################################################

###############################################################################
## Publisher
###############################################################################

- alias: state_persistence_publish
  hide_entity: true
  trigger:
    - platform: event
      event_type: 'state_changed'
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: "{{ trigger.event.data is not none and trigger.event.data.new_state is not none and trigger.event.data.new_state.attributes is not none }}"
      - condition: template
        value_template: "{{ trigger.event.data.new_state.attributes.persistent|default(false, true) }}"
      - condition: or
        conditions:
          - condition: state
            entity_id: 'input_boolean.publish_state_persistence'
            state: 'on'
          - condition: template
            value_template: "{{ trigger.event.data.entity_id == 'input_boolean.publish_state_persistence' }} "
  action:
    - service: mqtt.publish
      data_template:
        topic: "home-assistant/{{ trigger.event.data.entity_id|replace('.', '/') }}"
        payload: "{{ trigger.event.data.new_state.state }}"
        retain: true

###############################################################################
## Subscribers
###############################################################################

- alias: state_persistence_subscribe_binary
  hide_entity: true
  trigger:
    - platform: mqtt
      topic: 'home-assistant/automation/+'
    - platform: mqtt
      topic: 'home-assistant/input_boolean/+'
    - platform: mqtt
      topic: 'home-assistant/light/+'
    - platform: mqtt
      topic: 'home-assistant/switch/+'
  condition:
    - condition: and
      conditions:
        - condition: template
          value_template: "{{ is_state_attr(trigger.topic|replace('home-assistant/', '')|replace('/', '.'), 'persistent', true) }}"
        - condition: template
          value_template: "{{ not is_state(trigger.topic|replace('home-assistant/', '')|replace('/', '.'), trigger.payload) }}"
  action:
    - service_template: "{{ trigger.topic.split('/')[1] }}.turn_{{ trigger.payload|lower }}"
      data_template:
        entity_id: "{{ trigger.topic|replace('home-assistant/', '')|replace('/', '.') }}"

- alias: state_persistence_subscribe_select_option
  hide_entity: true
  trigger:
    - platform: mqtt
      topic: 'home-assistant/input_select/+'
  condition:
    - condition: and
      conditions:
        - condition: template
          value_template: "{{ is_state_attr(trigger.topic|replace('home-assistant/', '')|replace('/', '.'), 'persistent', true) }}"
        - condition: template
          value_template: "{{ not is_state(trigger.topic|replace('home-assistant/', '')|replace('/', '.'), trigger.payload) }}"
  action:
    - service_template: "{{ trigger.topic.split('/')[1] }}.select_option"
      data_template:
        entity_id: "{{ trigger.topic|replace('home-assistant/', '')|replace('/', '.') }}"
        option: "{{ trigger.payload }}"

- alias: state_persistence_subscribe_select_slider
  hide_entity: true
  trigger:
    - platform: mqtt
      topic: 'home-assistant/input_slider/+'
  condition:
    - condition: and
      conditions:
        - condition: template
          value_template: "{{ is_state_attr(trigger.topic|replace('home-assistant/', '')|replace('/', '.'), 'persistent', true) }}"
        - condition: template
          value_template: "{{ not is_state(trigger.topic|replace('home-assistant/', '')|replace('/', '.'), trigger.payload|float) }}"
  action:
    - service_template: "{{ trigger.topic.split('/')[1] }}.select_value"
      data_template:
        entity_id: "{{ trigger.topic|replace('home-assistant/', '')|replace('/', '.') }}"
        value: "{{ trigger.payload|float }}"
