- id: notify_shutdown
  alias: Notify HASS shutdowns
  trigger:
  - event: shutdown
    platform: homeassistant
  action:
  - data:
      data:
        tag: hass-status
      message: Home-Assistant is shutting down.
    service: notify.admin
  initial_state: true
- id: notify_start
  alias: Notify HASS starts
  trigger:
  - event: start
    platform: homeassistant
  action:
  - data:
      data:
        tag: hass-status
      message: Home-Assistant has restarted.
    service: notify.admin
  initial_state: true
