- id: sample
  alias: 'Notify HASS shutdowns'
  initial_state: False
  trigger:
    - platform: homeassistant
      event: shutdown
  action:
    - service: notify.admin
      data:
        message: "Home Assistant is shutting down"
