homeassistant:
  name: !secret name
  latitude: !secret zone_home_latitude
  longitude: !secret zone_home_longitude
  elevation: !secret zone_home_elevation
  time_zone: !secret zone_home_tz
  unit_system: metric
  external_url: !secret http_public_host
  internal_url: !secret http_public_host
  auth_providers:
    - type: "homeassistant"
  auth_mfa_modules:
    - type: "totp"
      name: "Authenticator app"
  packages: !include_dir_named packages/

cloud: {}

hacs:
  token: !secret hacs_github_token

logger:
  default: "warn"
  logs:
    homeassistant.bootstrap: "info"
    homeassistant.setup: "info"
    mychevy.mychevy: "error"
  filters:
    homeassistant.components.mychevy:
      - 'This probably means the OnStar link is down again'  # error
    homeassistant.components.mychevy.sensor:
      - 'This probably means the mychevy to OnStar link is down'  # error
    homeassistant.components.broadlink.updater:
      - '\[Errno -4000\] Network timeout'  # error
    # Google Homes & groups seem to change their IPs and create a lot of log pollution
    pychromecast.socket_client:
      - 'Failed to connect to service ServiceInfo\.\*, retrying in'  # error
      - 'Error reading from socket'  # error
      - 'Heartbeat timeout, resetting connection'  # warning
      - 'Error communicating with socket, resetting connection'  # warning
