###############################################################################
## System
###############################################################################

homeassistant:
  name: Home
  latitude: !secret zone_home_latitude
  longitude: !secret zone_home_longitude
  elevation: !secret zone_home_elevation
  unit_system: metric
  time_zone: America/Toronto
  packages: !include_dir_named packages/
  customize: !include_dir_merge_named includes/customize/

###############################################################################
## Customizations
###############################################################################

group: !include_dir_merge_named includes/groups/
input_boolean: !include_dir_merge_named includes/input_booleans/
