homeassistant:
  name: !secret name
  latitude: !secret zone_home_latitude
  longitude: !secret zone_home_longitude
  elevation: !secret zone_home_elevation
  time_zone: !secret zone_home_tz
  unit_system: metric
  packages: !include_dir_named packages/

discovery:

logger:
  default: "warn"
  logs:
    homeassistant.components.glances.sensor: "fatal"
    glances: "fatal"

hacs: # Does not support packages
  token: !secret hacs_github_token
