######################################################
## System
######################################################

homeassistant:
  name: Home
  latitude: !secret zone_home_latitude
  longitude: !secret zone_home_longitude
  elevation: !secret zone_home_elevation
  unit_system: metric
  time_zone: America/Toronto
  customize: !include_dir_merge_named includes/customize/

conversation:
discovery:
frontend:
http:
  server_port: !secret http_port
  api_password: !secret http_password
  cors_allowed_origins:
    - !secret http_public_host
updater:

######################################################
## Logs and History
######################################################

history:
logbook:
logger: !include includes/logger.yaml
recorder:
  purge_days: 14

######################################################
## Base Platforms
######################################################

device_tracker: !include includes/device_trackers.yaml
light: !include includes/lights.yaml
media_player: !include includes/media_players.yaml
mqtt: !include includes/mqtt.yaml
notify: !include_dir_merge_list includes/notifiers/
sun:

######################################################
## Customizations
######################################################

automation: !include_dir_merge_list includes/automations/
group: !include_dir_merge_named includes/groups/
input_boolean: !include_dir_merge_named includes/input_booleans/
input_select: !include_dir_merge_named includes/input_selects/
scene: !include_dir_merge_list includes/scenes/
script: !include_dir_merge_named includes/scripts/
sensor: !include_dir_merge_list includes/sensors/
switch: !include_dir_merge_list includes/switches/
zone: !include_dir_merge_list includes/zones/
