homeassistant:
  name: !secret name
  latitude: !secret zone_home_latitude
  longitude: !secret zone_home_longitude
  elevation: !secret zone_home_elevation
  time_zone: !secret zone_home_tz
  unit_system: metric
  auth_providers:
    - type: "homeassistant"
  auth_mfa_modules:
    - type: "totp"
      name: "Authenticator app"
  packages: !include_dir_named packages/

cloud:

hacs:
  token: !secret hacs_github_token

logger:
  default: "warn"
  logs:
    homeassistant.components.glances: "fatal"
    glances: "fatal"
