homeassistant:
  name: !secret name
  latitude: !secret zone_home_latitude
  longitude: !secret zone_home_longitude
  elevation: !secret zone_home_elevation
  time_zone: !secret zone_home_tz
  country: "CA"
  unit_system: "metric"
  external_url: !secret http_public_host
  internal_url: !secret http_public_host
  allowlist_external_dirs:
    - "/config/custom_templates"
    - "/config/logs"
    - "/tmp"
  auth_providers:
    - type: "homeassistant"
  auth_mfa_modules:
    - type: "totp"
      name: "Authenticator app"
  packages: !include_dir_named packages/

backup: {}

cloud: {}
