###############################################################################
## System
###############################################################################

homeassistant:
  name: Home
  latitude: !secret zone_home_latitude
  longitude: !secret zone_home_longitude
  elevation: !secret zone_home_elevation
  unit_system: metric
  time_zone: America/Toronto
  packages: !include_dir_named packages/
  customize: !include_dir_merge_named includes/customize/

###############################################################################
## Customizations
###############################################################################

automation: !include_dir_merge_list includes/automations/
binary_sensor: !include_dir_merge_list includes/binary_sensors/
group: !include_dir_merge_named includes/groups/
input_boolean: !include_dir_merge_named includes/input_booleans/
input_select: !include_dir_merge_named includes/input_selects/
scene: !include_dir_merge_list includes/scenes/
script: !include_dir_merge_named includes/scripts/
sensor: !include_dir_merge_list includes/sensors/
shell_command: !include_dir_merge_named includes/shell_commands
switch: !include_dir_merge_list includes/switches/
zone: !include_dir_merge_list includes/zones/
