homeassistant:
  name: "That small house on a hill"
  latitude: !secret zone_home_latitude
  longitude: !secret zone_home_longitude
  elevation: !secret zone_home_elevation
  unit_system: metric
  time_zone: America/Toronto
  packages: !include_dir_named packages/
