###############################################################################
## System
###############################################################################

homeassistant:
  name: Home
  latitude: !secret zone_home_latitude
  longitude: !secret zone_home_longitude
  elevation: !secret zone_home_elevation
  unit_system: metric
  time_zone: America/Toronto
  packages: !include_dir_named packages/
  customize: !include_dir_merge_named includes/customize/

###############################################################################
## Customizations
###############################################################################

automation: !include_dir_merge_list includes/automations/
group: !include_dir_merge_named includes/groups/
input_boolean: !include_dir_merge_named includes/input_booleans/
scene: !include_dir_merge_list includes/scenes/
sensor: !include_dir_merge_list includes/sensors/
zone: !include_dir_merge_list includes/zones/
