# Icon reference: https://petershaggynoble.github.io/MDI-Sandbox/

title: Avatar
background: 'var(--lovelace-background)'

resources:
  - url: /community_plugin/compact-custom-header/compact-custom-header.js
    type: module
  - url: /community_plugin/swipe-card/swipe-card.js
    type: module
  - url: /community_plugin/button-card/button-card.js
    type: module
  - url: /community_plugin/lovelace-card-tools/card-tools.js
    type: js
  - url: /community_plugin/vertical-stack-in-card/vertical-stack-in-card.js
    type: js
  - url: /community_plugin/secondaryinfo-entity-row/secondaryinfo-entity-row.js
    type: js
  - url: /community_plugin/text-element/text-element.js
    type: js
  - url: /community_plugin/lovelace-gap-card/gap-card.js
    type: js
  - url: /community_plugin/lovelace-fold-entity-row/fold-entity-row.js
    type: js
  - url: /community_plugin/lovelace-toggle-lock-entity-row/toggle-lock-entity-row.js
    type: js
  - url: /local/header-card.js?v=2
    type: js

cch:
  header: true
  sidebar_swipe: true
  sidebar_closed: true
  chevrons: false
  clock_format: 24
  hide_tabs: "5"
  menu: "show"
  notifications: "show"
  voice: "hide"
  options: "clock"
  exceptions:
    - conditions:
        user_agent: "Mobile"
        user: "Chris"
      config:
        menu: "hide"
        options: "hide"
        hide_tabs: "9999"
    - conditions:
        user_agent: "Mobile"
      config:
        menu: "hide"
        options: "hide"
    - conditions:
        user: "Chris"
      config:
        hide_tabs: "9999"

views:
  - title: Home
    path: home
    icon: mdi:home
    cards: !include ui-lovelace/home.yaml

  - title: Ground Floor
    path: ground
    icon: mdi:home-floor-g
    cards: !include ui-lovelace/ground-floor.yaml

  - title: Basement
    path: basement
    icon: mdi:home-floor-b
    cards: !include ui-lovelace/basement.yaml

  - title: Livings
    path: livings
    icon: mdi:leaf
    cards: !include ui-lovelace/livings.yaml

  - title: Settings
    path: settings
    icon: mdi:settings
    cards: !include ui-lovelace/settings.yaml

  - title: Network
    path: network
    icon: mdi:server-network
    cards: !include ui-lovelace/network.yaml
