title: Avatar
views:

  - title: Home
    id: home
    icon: mdi:home
    cards:
      - type: glance
        id: people
        show_name: false
        columns: 2
        entities:
          - device_tracker.chris_pixel
          - device_tracker.karine_nexus5
      - type: vertical-stack
        id: quick-actions
        cards:
          - type: horizontal-stack
            cards:
              - type: entity-button
                entity: light.outdoor_lights
                name: Outdoor
                icon: mdi:tree
                tap_action: toggle
                hold_action: more-info
              - type: entity-button
                entity: light.ground_floor_lights
                name: Main
                icon: mdi:arrow-up-thick
                tap_action: toggle
                hold_action: more-info
              - type: entity-button
                entity: light.basement_lights
                name: Basement
                icon: mdi:arrow-down-thick
                tap_action: toggle
                hold_action: more-info
          - type: horizontal-stack
            cards:
              - type: entity-button
                entity: script.ambiance
                name: Ambiance
                icon: mdi:weather-night
                tap_action: call-service
                service: script.turn_on
              - type: entity-button
                entity: script.everything_off
                name: Everything off
                icon: mdi:sleep
                tap_action: call-service
                service: script.turn_on
              - type: horizontal-stack
                cards: [] # Empty place holder
      - type: weather-forecast
        id: weather
        entity: weather.dark_sky
      - type: glance
        id: platforms-overview
        columns: 4
        entities:
          - entity: binary_sensor.all_motions
            name: Motion
          - entity: sensor.last_motion
          - entity: binary_sensor.all_doors
            name: Doors
          - entity: binary_sensor.all_windows
            name: Windows
          - entity: group.all_plants
            name: Plants
          - entity: binary_sensor.all_leaks
            name: Leaks
          - entity: sensor.all_batteries
            name: Batteries

  - title: Ground Floor
    id: ground-floor
    icon: mdi:arrow-up-thick
    cards:
      - type: entities
        id: outdoor
        title: Outdoor
        show_header_toggle: true
        entities:
          - type: divider
          - entity: light.side_porch
            name: Side porch light
          - entity: light.front_porch
            name: Front porch light
          - entity: light.shed
            name: Shed light
      - type: vertical-stack
        id: room-kitchen
        cards:
          - type: entities
            title: Kitchen
            show_header_toggle: true
            entities:
              - type: divider
              - entity: light.kitchen
                name: Light
          - type: horizontal-stack
            cards:
              - type: glance
                columns: 2
                entities:
                  - entity: binary_sensor.kitchen_sink_leak
                    name: Sink
                  - entity: binary_sensor.kitchen_door
                    name: ''
              - type: glance
                entities:
                  - entity: plant.spidy
                    name: Spidy
                  - entity: plant.viny
                    name: Viny
      - type: entities
        id: room-dining-room
        title: Dining room
        show_header_toggle: true
        entities:
          - type: divider
          - entity: light.dining_room
            name: Dimmer
          - entity: plant.maitre_doyle
            name: Maître Doyle
      - type: vertical-stack
        id: room-living-room
        cards:
          - type: entities # Title card with a toggle, no entities shown.
            title: Living room
            show_header_toggle: true
            entities:
              - entity: light.living_room_lights
                type: divider
          - type: horizontal-stack
            cards:
              - type: entities
                entities:
                  - entity: light.bookshelf
                    name: Bookshelf light
                  - entity: light.living_room_ambiance
                    name: Ambiance light
                  - entity: switch.bookshelf_outlet
                    name: Bookshelf outlet
                  - entity: switch.living_room_tv
                    name: TV
              - type: vertical-stack
                cards:
                - type: glance
                  show_state: False
                  columns: 2
                  entities:
                    - entity: media_player.living_room_chromecast
                      name: Chromecast
                    - entity: media_player.living_room_google_home
                      name: Google Home
                - type: glance
                  show_name: False
                  columns: 2
                  entities:
                    - entity: binary_sensor.living_room_door
      - type: entities
        id: room-master-bedroom
        title: Master bedroom
        show_header_toggle: true
        entities:
          - type: divider
          - entity: light.bedside_chris
          - entity: light.bedside_karine
      - type: vertical-stack
        id: room-main-bathroom
        cards:
          - type: entities # Title card with a toggle, no entities shown.
            title: Bathroom
            show_header_toggle: true
            entities:
              - entity: light.main_bathroom_lights
                type: divider
          - type: horizontal-stack
            cards:
              - type: entities
                entities:
                  - entity: light.main_bathroom_spots
                    name: Spots
                  - entity: light.main_bathroom_vanity
                    name: Vanity
                  - entity: switch.main_bathroom_fan
                    name: Fan
                    icon: mdi:fan
              - type: glance
                show_name: False
                columns: 2
                entities:
                  - entity: sensor.main_bathroom_humidity
                    name: Humidity
                  - entity: sensor.main_bathroom_temperature
                    name: Temperature
                  - entity: binary_sensor.main_bathroom_motion
                    name: Motion
          - type: entities
            entities:
              - entity: input_boolean.main_bathroom_auto_lights
                name: Automated lights
                secondary_info: last-changed
      - type: entities
        id: room-office
        title: Office
        show_header_toggle: true
        entities:
          - type: divider
          - entity: light.office
            name: Dimmer

  - title: Basement
    id: basement
    icon: mdi:arrow-down-thick
    cards:
      - type: entities
        id: room-lounge
        title: Lounge
        show_header_toggle: true
        entities:
          - type: divider
          - entity: light.lounge
            name: Dimmer
          - entity: light.lounge_ambiance
            name: Ambiance
          - entity: light.basement_hallway
            name: Hallway dimmer
          - entity: light.downstairs
            name: Downstairs light
      - type: vertical-stack
        id: room-basement-bathroom
        cards:
          - type: entities # Title card with a toggle, no entities shown.
            title: Bathroom
            show_header_toggle: true
            entities:
              - entity: light.basement_bathroom_lights
                type: divider
          - type: horizontal-stack
            cards:
              - type: entities
                entities:
                  - entity: light.basement_bathroom
                    name: Ceiling
                  - entity: light.basement_bathroom_vanity
                    name: Vanity
                  - entity: switch.basement_bathroom_fan
                    name: Fan
                    icon: mdi:fan
              - type: glance
                show_name: False
                columns: 2
                entities:
                  - entity: sensor.basement_bathroom_humidity
                    name: Humidity
                  - entity: sensor.basement_bathroom_temperature
                    name: Temperature
                  - entity: binary_sensor.basement_bathroom_motion
                    name: Motion
          - type: entities
            entities:
              - entity: input_boolean.basement_bathroom_auto_lights
                name: Automated lights
                secondary_info: last-changed
      - type: vertical-stack
        id: room-laundry
        cards:
          - type: entities # Title card with a toggle, no entities shown.
            title: Laundry
            show_header_toggle: true
            entities:
              - entity: light.laundry_room_lights
                type: divider
          - type: horizontal-stack
            cards:
              - type: entities
                entities:
                - entity: light.laundry_room
                  name: Light
              - type: glance
                show_name: False
                columns: 2
                entities:
                  - entity: binary_sensor.laundry_room_motion
                    name: Motion
      - type: vertical-stack
        id: room-workshop
        cards:
          - type: entities # Title card with a toggle, no entities shown.
            title: Workshop
            show_header_toggle: true
            entities:
              - entity: light.workshop_lights
                type: divider
          - type: horizontal-stack
            cards:
              - type: entities
                entities:
                - entity: light.workshop
                  name: Light
              - type: glance
                show_name: False
                columns: 2
                entities:
                  - entity: binary_sensor.workshop_motion
                    name: Motion
                  - entity: binary_sensor.water_heater_leak
                    name: Water heater

  - title: Plants
    id: plants
    icon: mdi:flower
    cards:
      - type: plant-status
        id: plant-maitre-doyle
        entity: plant.maitre_doyle
      - type: plant-status
        id: plant-spidy
        entity: plant.spidy
      - type: plant-status
        id: plant-viny
        entity: plant.viny

  - title: Settings
    id: settings
    icon: mdi:settings
    cards:
      - type: entities
        id: main-settings
        title: Settings
        show_header_toggle: false
        entities:
          - input_boolean.guest_mode
          - input_boolean.automatic_night_theme
          - input_select.default_theme
      - type: entities
        id: main-notifications
        title: Notifications
        show_header_toggle: false
        entities:
          - entity: automation.notify_plant_problems
            name: Plant problems
          - entity: input_boolean.notify_power_outages
            name: Power outages
      - type: entities
        id: details-doors
        title: Doors
        entities:
          - entity: binary_sensor.kitchen_door
            name: Kitchen
          - entity: binary_sensor.living_room_door
            name: Living room
      - type: entities
        id: details-windows
        title: Windows
        entities:
          - entity: binary_sensor.lounge_window
            name: Lounge
          - entity: binary_sensor.guest_east_window
            name: Guest room (east)
          - entity: binary_sensor.guest_west_window
            name: Guest room (west)
      - type: entities
        id: details-water
        title: Water
        entities:
          - entity: binary_sensor.kitchen_sink_leak
            name: Kitchen sink
          - entity: binary_sensor.water_heater_leak
            name: Water heater
      - type: entities
        id: details-motion
        title: Motion
        entities:
          - entity: binary_sensor.basement_bathroom_motion
            name: Basement bathroom
          - entity: binary_sensor.main_bathroom_motion
            name: Main bathroom
          - entity: binary_sensor.laundry_room_motion
            name: Laundry
          - entity: binary_sensor.workshop_motion
            name: Workshop
      - type: entities
        id: details-batteries
        title: Batteries
        entities:
          - entity: sensor.basement_bathroom_multisensor_battery
            name: Basement bathroom multisensor
          - entity: sensor.kitchen_door_sensor_battery
            name: Kitchen door
          - entity: sensor.kitchen_sink_leak_sensor_battery
            name: Kitchen sink leak
          - entity: sensor.living_room_door_sensor_battery
            name: Living room door
          - entity: sensor.main_bathroom_multisensor_battery
            name: Main bathroom multisensor
          - entity: sensor.ups_battery_status
            name: UPS
          - entity: sensor.water_heater_leak_sensor_battery
            name: Water heater leak
          - type: section
            label: Plants
          - entity: sensor.maitre_doyle_battery
            name: Maître Doyle
          - entity: sensor.spidy_battery
            name: Spidy
          - entity: sensor.viny_battery
            name: Viny

  - title: Network
    id: network
    icon: mdi:server-network
    cards:
      - type: entities
        id: network-settings
        title: Settings
        show_header_toggle: false
        entities:
          - input_boolean.power_outage_manage_devices
      - type: entities
        id: network-notifications
        title: Notifications
        show_header_toggle: false
        entities:
          - entity: input_boolean.notify_household_changes
            name: Household changes
          - entity: input_boolean.notify_network_device_outages
            name: Network device outages
      - type: entities
        id: network-ups
        title: UPS
        entities:
          - entity: sensor.ups_status
            name: Status
          - entity: sensor.ups_load
            name: Load
          - entity: sensor.ups_battery
            name: Battery
          - entity: sensor.ups_input_voltage
            name: Input voltage
          - entity: sensor.ups_time_left
            name: Time left
          - entity: sensor.ups_time_on_battery
            name: Time on battery
      - type: entities
        id: network-hass
        title: Home Assistant
        entities:
          - sensor.connected_clients
          - sensor.current_home_assistant_version
          - sensor.latest_home_assistant_version
      - type: entities
        id: network-automate
        title: Automate
        entities:
          - sensor.processor_use
          - sensor.processor_temperature
          - sensor.memory_use_percent
          - sensor.since_last_boot
      - type: entities
        id: network-media
        title: Media
        show_header_toggle: false
        entities:
          - entity: switch.network_media
            name: Status
            icon: mdi:flash-circle
          - entity: sensor.media_cpu_load
            name: CPU load
          - entity: sensor.media_cpu_temp
            name: CPU temperature
          - entity: sensor.media_ram_used
            name: Memory use
      - type: entities
        id: network-relay-south
        title: Relay South
        show_header_toggle: false
        entities:
          - entity: switch.network_relay_south
            name: Status
            icon: mdi:flash-circle
          - entity: sensor.relay_south_cpu_load
            name: CPU load
          - entity: sensor.relay_south_cpu_temp
            name: CPU temperature
          - entity: sensor.relay_south_ram_used
            name: Memory use
      - type: entities
        id: network-relay-north
        title: Relay North
        show_header_toggle: false
        entities:
          - entity: switch.network_relay_north
            name: Status
            icon: mdi:flash-circle
          - entity: sensor.relay_north_cpu_load
            name: CPU load
          - entity: sensor.relay_north_cpu_temp
            name: CPU temperature
          - entity: sensor.relay_north_ram_used
            name: Memory use
      - type: entities
        id: zwave-status
        title: Z-Wave
        entities:
          - entity: zwave.usb_controller
          - type: section
            label: Hard-wired
          - entity: zwave.basement_bathroom_fan_switch
          - entity: zwave.basement_bathroom_light_switch
          - entity: zwave.basement_bathroom_vanity_light_dimmer
          - entity: zwave.basement_hallway_light_dimmer
          - entity: zwave.bookshelf_light_switch
          - entity: zwave.dining_room_light_dimmer
          - entity: zwave.downstairs_light_switch
          - entity: zwave.front_porch_light_switch
          - entity: zwave.kitchen_light_switch
          - entity: zwave.laundry_room_light_switch
          - entity: zwave.lounge_light_dimmer
          - entity: zwave.main_bathroom_fan_switch
          - entity: zwave.main_bathroom_light_dimmer
          - entity: zwave.main_bathroom_vanity_light_switch
          - entity: zwave.office_light_dimmer
          - entity: zwave.shed_outdoor_light_switch
          - entity: zwave.side_porch_light_switch
          - entity: zwave.workshop_light_switch
          - type: section
            label: Hard-wired sensors
          - entity: zwave.laundry_motion_sensor
          - entity: zwave.workshop_motion_sensor
          - type: section
            label: Battery sensors
          - entity: zwave.basement_bathroom_multisensor
          - entity: zwave.kitchen_door_sensor
          - entity: zwave.kitchen_sink_leak_sensor
          - entity: zwave.living_room_door_sensor
          - entity: zwave.main_bathroom_multisensor
          - entity: zwave.water_heater_leak_sensor
