# Icon reference: https://petershaggynoble.github.io/MDI-Sandbox/

title: Avatar
background: 'var(--lovelace-background)'

resources:
  - url: /customcards/github/custom-cards/tracker-card.js?track=true
    type: module
  - url: /customcards/github/custom-cards/vertical-stack-in-card.js?track=true
    type: js
  - url: /customcards/github/custom-cards/secondaryinfo-entity-row.js?track=true
    type: module
  - url: /customcards/github/custom-cards/text-element.js?track=true
    type: js
  - url: /customcards/github/maykar/compact-custom-header.js?track=true
    type: module
  - url: /customcards/github/thomasloven/card-tools.js?track=true
    type: js
  - url: /customcards/github/thomasloven/gap-card.js?track=true
    type: js
  - url: /customcards/github/thomasloven/fold-entity-row.js?track=true
    type: js
  - url: /customcards/github/thomasloven/toggle-lock-entity-row.js?track=true
    type: js
  - url: /customcards/header-card.js
    type: js

views:
  - title: Home
    path: home
    icon: mdi:home
    cards: !include ui-lovelace/home.yaml

  - title: Ground Floor
    path: ground
    icon: mdi:home-floor-g
    cards: !include ui-lovelace/ground-floor.yaml

  - title: Basement
    path: basement
    icon: mdi:home-floor-b
    cards: !include ui-lovelace/basement.yaml

  - title: Livings
    path: livings
    icon: mdi:leaf
    cards: !include ui-lovelace/livings.yaml

  - title: Settings
    path: settings
    icon: mdi:settings
    cards: !include ui-lovelace/settings.yaml

  - title: Network
    path: network
    icon: mdi:server-network
    cards: !include ui-lovelace/network.yaml
