# Icons: https://petershaggynoble.github.io/MDI-Sandbox/
# Color tool: https://material.io/resources/color/

title: Avatar

resources:
  - {type: "module", url: "/hacsfiles/button-card/button-card.js"}
  - {type: "module", url: "/hacsfiles/custom-header/custom-header.js"}
  - {type: "module", url: "/hacsfiles/decluttering-card/decluttering-card.js"}
  - {type: "module", url: "/hacsfiles/group-element/group-element-bundle.js"}
  - {type: "module", url: "/hacsfiles/lovelace-auto-entities/auto-entities.js"}
  - {type: "module", url: "/hacsfiles/lovelace-card-mod/card-mod.js"}
  - {type: "module", url: "/hacsfiles/lovelace-card-tools/card-tools.js"}
  - {type: "module", url: "/hacsfiles/lovelace-fold-entity-row/fold-entity-row.js"}
  - {type: "module", url: "/hacsfiles/lovelace-gap-card/gap-card.js"}
  - {type: "module", url: "/hacsfiles/lovelace-template-entity-row/template-entity-row.js"}
  - {type: "module", url: "/hacsfiles/restriction-card/restriction-card.js"}
  - {type: "module", url: "/hacsfiles/simple-thermostat/simple-thermostat.js"}
  - {type: "module", url: "/hacsfiles/weather-card/weather-card.js"}
  - {type: "js", url: "/hacsfiles/text-element/text-element.js"}

custom_header:
  compact_mode: true
  chevrons: false
  hide_help: true
  hide_unused: true
  hide_config: true
  hide_raw: true
  button_text:
    options: "{{ hours24LZ }}:{{ minutesLZ }}"
  exceptions:
    - conditions:
        user_agent: "Mobile"
      config:
        menu_hide: true
        options_hide: true

decluttering_templates:
  plant: !include dashboards/overview/templates/plant.yaml
  person: !include dashboards/overview/templates/person.yaml

button_card_templates:
  plant_badge: !include dashboards/overview/templates/plant-badge.yaml
  terra_detailed_switch: !include dashboards/overview/templates/terra-detailed-switch.yaml
  terra_footer_switch: !include dashboards/overview/templates/terra-footer-switch.yaml

views:
  - title: Home
    path: home
    icon: mdi:home
    cards: !include dashboards/overview/home.yaml

  - title: Ground Floor
    path: ground
    icon: mdi:home-floor-g
    cards: !include dashboards/overview/ground-floor.yaml

  - title: Basement
    path: basement
    icon: mdi:home-floor-b
    cards: !include dashboards/overview/basement.yaml

  - title: Livings
    path: livings
    icon: mdi:leaf
    cards: !include dashboards/overview/livings.yaml

  - title: Settings
    path: settings
    icon: mdi:settings
    cards: !include dashboards/overview/settings.yaml

  - title: Network
    path: network
    icon: mdi:server-network
    visible:
      - user: 221fad543e1a4c05af8aaac8c68e985e
    cards: !include dashboards/overview/network.yaml
