cloud:
  google_actions:
    filter:
      include_entities:
        - "script.evening_ambiance"
    entity_config:
      script.evening_ambiance:
        aliases:
          - "Ambiance"

input_datetime:
  evening_ambiance_end:
    name: "End of evening ambiance triggers"
    icon: "mdi:star-face"
    has_date: false
    has_time: true

script:
  evening_ambiance:
    alias: "Evening ambiance"
    icon: "mdi:lamp"
    mode: restart
    sequence:
      parallel:
        - service: light.turn_on
          target:
            entity_id: "light.master_bedroom_bedsides"
          data:
            brightness_pct: 5
            kelvin: 2200
        - service: light.turn_on
          target:
            entity_id: "light.bookshelf"
          data:
            kelvin: 2200
        - service: light.turn_on
          target:
            entity_id: "light.office_lamp"
          data:
            brightness_pct: 10
        - service: light.turn_on
          target:
            entity_id: "light.basement_hallway"
          data:
            brightness: 40
        - service: light.turn_on
          target:
            entity_id: "light.lounge_ambiance"
          data:
            brightness_pct: 30
            kelvin: 2200

automation:
  - id: "a4fe52e0-99f0-449d-9bc7-50378d9d6df8"
    alias: night_ambiance
    initial_state: true
    mode: restart
    trigger:
      - platform: numeric_state
        entity_id: "sun.sun"
        attribute: "elevation"
        below: &sun_elevation -3.0
      - platform: state
        entity_id: "group.household"
        to: "home"
    condition:
      - condition: time
        before: "input_datetime.evening_ambiance_end"
      - condition: numeric_state
        entity_id: sun.sun
        attribute: "elevation"
        below: *sun_elevation
      - condition: state
        entity_id: "group.household"
        state: "home"
    action:
      - parallel:
          - service: script.evening_ambiance
          - service: light.turn_on
            target:
              entity_id:
                - "light.backyard_string"
                - "light.front_porch"
                - "light.side_porch"
                - "light.shed"

  - id: "2c48ecbc-7b65-4938-af37-dcda12952465"
    alias: "arrival_lights"
    initial_state: true
    mode: "restart"
    trigger:
      - platform: state
        entity_id:
          - "person.chris"
          - "person.karine"
          - "group.guests"
        to: "home"
    condition:
      - condition: numeric_state
        entity_id: "sun.sun"
        attribute: "elevation"
        below: *sun_elevation
    action:
      - service: light.turn_on
        target:
          entity_id:
            - "light.front_porch"
            - "light.side_porch"

  - id: "a109af89-0910-45b2-9a0e-11d3ae43ec7c"
    alias: turn_off_outdoor
    initial_state: true
    mode: restart
    trigger:
      - platform: state
        entity_id: "light.outdoor_lights"
        to: "on"
        for: &min_outdoor_on_time 300
      - platform: time
        at: "input_datetime.evening_ambiance_end"
      - platform: state
        entity_id: "binary_sensor.guest_mode"
        to: "off"
    condition:
      - condition: state
        entity_id: "binary_sensor.guest_mode"
        state: "off"
      - condition: state
        entity_id: "light.outdoor_lights"
        state: "on"
        for: *min_outdoor_on_time
      - condition: time
        after: "input_datetime.evening_ambiance_end"
        before: "15:00:00"
    action:
      - service: light.turn_off
        target:
          entity_id: "light.outdoor_lights"
