cloud:
  google_actions:
    filter:
      include_entities:
        - "script.everything_off"
    entity_config:
      script.everything_off:
        aliases:
          - "Everything off"

script:
  everything_off:
    alias: "All off"
    description: "Turn off all devices in the house"
    icon: "mdi:close-circle-outline"
    sequence:
      - action: homeassistant.turn_off
        target:
          entity_id:
            - "light.basement_lights"
            - "light.ground_floor_lights"
            - "light.outdoor_lights"
            - "light.shed"
            - "remote.living_room_tv"

automation:
  - id: "54655af9-ddc7-491d-9200-41aaaddbb21a"
    alias: empty_house
    initial_state: true
    triggers:
      - trigger: state
        entity_id: "group.household"
        from: "home"
        for: 30
    conditions:
      - condition: state
        entity_id: "binary_sensor.guest_mode"
        state: "off"
    actions:
      - action: script.everything_off
      - action: lock.lock
        target:
          entity_id: "lock.kitchen_door"
