homeassistant:
  customize:
    sensor.current_home_assistant_version:
      friendly_name: "Current version"
      icon: "mdi:arrow-right"
    sensor.latest_home_assistant_version:
      friendly_name: "Latest version"
      icon: "mdi:arrow-up"

updater:
  reporting: False

sensor:
  - platform: api_streams
  - platform: version
    name: "latest_home_assistant_version"
    source: "pypi"
  - platform: version
    name: "current_home_assistant_version"
    source: "local"

automation:
  - alias: notify_update_available
    hide_entity: True
    initial_state: True
    trigger:
      - platform: state
        entity_id: sensor.latest_home_assistant_version
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ trigger.to_state.state != 'unknown' }}"
        - condition: template
          value_template: "{{ trigger.to_state.state != 'unavailable' }}"
        - condition: template
          value_template: "{{ trigger.to_state.state != states('sensor.current_home_assistant_version') }}"
    action:
      - service: python_script.notify
        data_template:
          persistent: True
          push_target: "admin"
          tag: "hass_version"
          url: "https://github.com/home-assistant/home-assistant/releases/tag/{{ trigger.to_state.state }}"
          title: "Home Assistant Update"
          message: "Home Assistant {{ trigger.to_state.state }} is available."
