homeassistant:
  customize:
    automation.notify_person_arrives:
      friendly_name: "Notify arrival of household member"
      icon: "mdi:message-settings-variant"
    automation.notify_person_leaves:
      friendly_name: "Notify departure of household member"
      icon: "mdi:message-settings-variant"

input_boolean:
  notify_household_changes:
    name: "Notify household changes"
    icon: "mdi:message-settings-variant"

automation:
  - alias: notify_person_arrives
    initial_state: True
    trigger:
      platform: state
      entity_id:
        - group.person_chris
        - group.person_karine
      to: "home"
    condition:
      condition: state
      entity_id: input_boolean.notify_household_changes
      state: "on"
    action:
      - service: python_script.notify
        data_template:
          push_target: "admin"
          tag: "presence_{{ trigger.to_state.object_id }}"
          title: "{{ trigger.to_state.name }} arrived home."
          message: "Household is {{ states('group.household') }}."

  - alias: notify_person_leaves
    initial_state: True
    trigger:
      platform: state
      entity_id:
        - group.person_chris
        - group.person_karine
      from: "home"
    condition:
      condition: state
      entity_id: input_boolean.notify_household_changes
      state: "on"
    action:
      - service: python_script.notify
        data_template:
          push_target: "admin"
          tag: "presence_{{ trigger.to_state.object_id }}"
          title: "{{ trigger.to_state.name }} left home."
          message: "Household is {{ states('group.household') }}."
