homeassistant:
  customize:
    switch.network_media:
      friendly_name: "Media"
      icon: "mdi:play-network"
      confirm_controls_show_lock: True
    switch.network_relay_south:
      friendly_name: "Relay South"
      icon: "mdi:server-network"
      confirm_controls_show_lock: True
    switch.network_relay_north:
      friendly_name: "Relay North"
      icon: "mdi:server-network"
      confirm_controls_show_lock: True
    sensor.media_cpu_load:
      friendly_name: "Media's CPU use"
      icon: "mdi:memory"
      group:
        group.media_monitor:
          friendly_name: "CPU use"
    sensor.media_cpu_temp:
      friendly_name: "Media's CPU temperature"
      icon: "mdi:fire"
      group:
        group.media_monitor:
          friendly_name: "CPU temperature"
    sensor.media_ram_used:
      friendly_name: "Media's memory use"
      icon: "mdi:memory"
      group:
        group.media_monitor:
          friendly_name: "Memory use"
    sensor.relay_south_cpu_load:
      friendly_name: "South relay's CPU use"
      icon: "mdi:memory"
      group:
        group.relay_south_monitor:
          friendly_name: "CPU use"
    sensor.relay_south_cpu_temp:
      friendly_name: "South relay's CPU temperature"
      icon: "mdi:fire"
      group:
        group.relay_south_monitor:
          friendly_name: "CPU tmeperature"
    sensor.relay_south_ram_used:
      friendly_name: "South relay's memory use"
      icon: "mdi:memory"
      group:
        group.relay_south_monitor:
          friendly_name: "Memory use"
    sensor.relay_north_cpu_load:
      friendly_name: "North relay's CPU use"
      icon: "mdi:memory"
      group:
        group.relay_north_monitor:
          friendly_name: "CPU use"
    sensor.relay_north_cpu_temp:
      friendly_name: "North relay's CPU temperature"
      icon: "mdi:fire"
      group:
        group.relay_north_monitor:
          friendly_name: "CPU tmeperature"
    sensor.relay_north_ram_used:
      friendly_name: "North relay's memory use"
      icon: "mdi:memory"
      group:
        group.relay_north_monitor:
          friendly_name: "Memory use"
    automation.notify_new_network_device:
      friendly_name: "Notify new devices detected on network"
      icon: "mdi:message-settings-variant"
    automation.notify_network_device_state:
      friendly_name: "Notify state changes of network devices"
      icon: "mdi:message-settings-variant"
    automation.action_power_on_device:
      friendly_name: "Power on network device from notification"
    automation.action_power_off_device:
      friendly_name: "Power off network device from notification"

group:
  network_devices:
    name: "Network Devices"
    icon: "mdi:ethernet"
    control: "hidden"
    entities:
      - switch.network_media
      - switch.network_relay_south
      - switch.network_relay_north

  media_monitor:
    name: "Media Monitor"
    icon: "mdi:chart-scatterplot-hexbin"
    entities:
      - sensor.media_cpu_load
      - sensor.media_cpu_temp
      - sensor.media_ram_used

  relay_south_monitor:
    name: "South Relay Monitor"
    icon: "mdi:chart-scatterplot-hexbin"
    entities:
      - sensor.relay_south_cpu_load
      - sensor.relay_south_cpu_temp
      - sensor.relay_south_ram_used

  relay_north_monitor:
    name: "North Relay Monitor"
    icon: "mdi:chart-scatterplot-hexbin"
    entities:
      - sensor.relay_north_cpu_load
      - sensor.relay_north_cpu_temp
      - sensor.relay_north_ram_used

sensor:
  - platform: glances
    host: !secret network_media_host
    port: !secret glances_port
    name: "media"
    resources:
      - processor_load
      - memory_use_percent
      - cpu_temp

  - platform: glances
    host: !secret network_relay_south_host
    port: !secret glances_port
    name: "relay_south"
    resources:
      - processor_load
      - memory_use_percent
      - cpu_temp

  - platform: glances
    host: !secret network_relay_north_host
    port: !secret glances_port
    name: "relay_north"
    resources:
      - processor_load
      - memory_use_percent
      - cpu_temp

shell_command:
  shutdown_media: "/home/hass/.homeassistant/bin/shutdown_media.sh"
  shutdown_relay_south: "/home/hass/.homeassistant/bin/shutdown_relay_south.sh"
  shutdown_relay_north: "/home/hass/.homeassistant/bin/shutdown_relay_north.sh"

switch:
  - platform: wake_on_lan
    name: "network_media"
    mac_address: !secret network_media_mac
    host: !secret network_media_host
    broadcast_address: !secret network_wol_broadcast
    turn_off:
      service: "shell_command.shutdown_media"

  - platform: wake_on_lan
    name: "network_relay_south"
    mac_address: !secret network_relay_south_mac
    host: !secret network_relay_south_host
    broadcast_address: !secret network_wol_broadcast
    turn_off:
      service: "shell_command.shutdown_relay_south"

  - platform: wake_on_lan
    name: "network_relay_north"
    mac_address: !secret network_relay_north_mac
    host: !secret network_relay_north_host
    broadcast_address: !secret network_wol_broadcast
    turn_off:
      service: "shell_command.shutdown_relay_north"

automation:
  - alias: notify_new_network_device
    initial_state: True
    trigger:
      - platform: event
        event_type: "device_tracker_new_device"
    action:
      - service: notify.admin
        data_template:
          title: "New device detected on network"
          message: "{{ trigger.event.data | tojson }}"

  - alias: notify_network_device_state
    initial_state: True
    trigger:
      platform: state
      entity_id:
        - switch.network_media
        - switch.network_relay_south
        - switch.network_relay_north
    action:
      service: notify.admin
      data_template:
        title: "Network Status"
        message: "{{ trigger.to_state.name }} is {{ trigger.to_state.state | lower }}!"
        data:
          entity_id: "{{ trigger.entity_id }}"
          tag: "{{ trigger.entity_id | replace('.', '_') }}"
          actions:
            - action: power_off
              title: "Power Off"
              icon: "/local/icons/power-plug-off.png"
            - action: power_on
              title: "Power On"
              icon: "/local/icons/power-plug.png"

  - alias: action_power_on_device
    initial_state: True
    trigger:
      platform: event
      event_type: "html5_notification.clicked"
      event_data:
        action: power_on
    action:
      service: switch.turn_on
      data_template:
        entity_id: "{{ trigger.event.data.data.entity_id }}"

  - alias: action_power_off_device
    initial_state: True
    trigger:
      platform: event
      event_type: "html5_notification.clicked"
      event_data:
        action: power_off
    action:
      service: switch.turn_off
      data_template:
        entity_id: "{{ trigger.event.data.data.entity_id }}"
