homeassistant:
  customize:
    switch.network_media:
      friendly_name: "Media"
      icon: "mdi:play-network"
    switch.network_relay_south:
      friendly_name: "Relay South"
      icon: "mdi:server-network"
    switch.network_relay_north:
      friendly_name: "Relay North"
      icon: "mdi:server-network"
    sensor.media_cpu_used:
      friendly_name: "Media's CPU use"
      icon: "mdi:chip"
    sensor.media_cpu_temp:
      friendly_name: "Media's CPU temperature"
      icon: "mdi:fire"
    sensor.media_ram_used:
      friendly_name: "Media's memory use"
      icon: "mdi:memory"
    sensor.relay_south_cpu_used:
      friendly_name: "South relay's CPU use"
      icon: "mdi:chip"
    sensor.relay_south_cpu_temp:
      friendly_name: "South relay's CPU temperature"
      icon: "mdi:fire"
    sensor.relay_south_ram_used:
      friendly_name: "South relay's memory use"
      icon: "mdi:memory"
    sensor.relay_north_cpu_used:
      friendly_name: "North relay's CPU use"
      icon: "mdi:chip"
    sensor.relay_north_cpu_temp:
      friendly_name: "North relay's CPU temperature"
      icon: "mdi:fire"
    sensor.relay_north_ram_used:
      friendly_name: "North relay's memory use"
      icon: "mdi:memory"
    automation.notify_new_network_device:
      friendly_name: "Notify new devices detected on network"
      icon: "mdi:message-settings-variant"

input_boolean:
  notify_network_device_outages:
    name: "Notify network device outages"
    icon: "mdi:message-settings-variant"

input_text:
  offline_network_devices:
    name: "Offline network devices (with threshold)"

sensor:
  - platform: glances
    host: !secret media_glances_host
    port: !secret media_glances_port
    name: "media"
    version: 3
    resources:
      - cpu_use_percent
      - memory_use_percent
      - cpu_temp

  - platform: glances
    host: !secret relay_south_glances_host
    port: !secret relay_south_glances_port
    name: "relay_south"
    version: 3
    resources:
      - cpu_use_percent
      - memory_use_percent
      - cpu_temp

  - platform: glances
    host: !secret relay_north_glances_host
    port: !secret relay_north_glances_port
    name: "relay_north"
    version: 3
    resources:
      - cpu_use_percent
      - memory_use_percent
      - cpu_temp

shell_command:
  shutdown_media: "/home/homeassistant/.homeassistant/bin/shutdown_media.sh"
  shutdown_relay_south: "/home/homeassistant/.homeassistant/bin/shutdown_relay_south.sh"
  shutdown_relay_north: "/home/homeassistant/.homeassistant/bin/shutdown_relay_north.sh"

switch:
  - platform: wake_on_lan
    name: "network_media"
    mac_address: !secret media_mac
    host: !secret media_ip
    broadcast_address: !secret network_broadcast
    turn_off:
      service: "shell_command.shutdown_media"

  - platform: wake_on_lan
    name: "network_relay_south"
    mac_address: !secret relay_south_mac
    host: !secret relay_south_ip
    broadcast_address: !secret network_broadcast
    turn_off:
      service: "shell_command.shutdown_relay_south"

  - platform: wake_on_lan
    name: "network_relay_north"
    mac_address: !secret relay_north_mac
    host: !secret relay_north_ip
    broadcast_address: !secret network_broadcast
    turn_off:
      service: "shell_command.shutdown_relay_north"

automation:
  - alias: notify_new_network_device
    initial_state: True
    hide_entity: True
    trigger:
      platform: event
      event_type: "device_tracker_new_device"
    action:
      - service: python_script.notify
        data_template:
          push_target: "admin"
          persistent: True
          title: "New device detected on network"
          message: "Device data: {{ trigger.event.data | tojson }}"

  - alias: notify_network_device_off
    initial_state: True
    hide_entity: True
    trigger:
      platform: state
      entity_id:
        - switch.network_media
        - switch.network_relay_south
        - switch.network_relay_north
      to: "off"
      for: &device_outage_leeway
        seconds: 45
    condition:
      condition: template
      value_template: "{{ '|' ~ trigger.to_state.object_id ~ '|' not in states.input_text.offline_network_devices.state }}"
    action:
      - service: input_text.set_value
        data_template:
          entity_id: "input_text.offline_network_devices"
          value: "{{ states.input_text.offline_network_devices.state }}|{{ trigger.to_state.object_id }}|"
      - condition: state
        entity_id: "input_boolean.notify_network_device_outages"
        state: "on"
      - service: python_script.notify
        data_template:
          push_target: "admin"
          tag: "device_outage_{{ trigger.to_state.object_id }}"
          url: "/lovelace/network"
          title: "{{ trigger.to_state.name }} is offline"
          push_data:
            entity_id: "{{ trigger.entity_id }}"
          push_actions:
            - action: "power_on"
              title: "Power on"
              icon: "/local/icons/power-plug-on.png"

  - alias: notify_network_device_on
    initial_state: True
    hide_entity: True
    trigger:
      platform: state
      entity_id:
        - switch.network_media
        - switch.network_relay_south
        - switch.network_relay_north
      to: "on"
      for: *device_outage_leeway
    condition:
      condition: template
      value_template: "{{ '|' ~ trigger.to_state.object_id ~ '|' in states.input_text.offline_network_devices.state }}"
    action:
      - service: input_text.set_value
        data_template:
          entity_id: "input_text.offline_network_devices"
          value: "{{ states.input_text.offline_network_devices.state | replace('|' ~ trigger.to_state.object_id ~ '|', '') }}"
      - condition: state
        entity_id: "input_boolean.notify_network_device_outages"
        state: "on"
      - service: python_script.notify
        data_template:
          push_target: "admin"
          tag: "device_outage_{{ trigger.to_state.object_id }}"
          url: "/lovelace/network"
          title: "{{ trigger.to_state.name }} is online"
          push_data:
            entity_id: "{{ trigger.entity_id }}"
          push_actions:
            - action: "power_off"
              title: "Power off"
              icon: "/local/icons/power-plug-off.png"

  - alias: notification_action_power_on_device
    initial_state: True
    hide_entity: True
    trigger:
      platform: event
      event_type: "html5_notification.clicked"
      event_data:
        action: power_on
    action:
      service: switch.turn_on
      data_template:
        entity_id: "{{ trigger.event.data.data.entity_id }}"

  - alias: notification_action_power_off_device
    initial_state: True
    hide_entity: True
    trigger:
      platform: event
      event_type: "html5_notification.clicked"
      event_data:
        action: power_off
    action:
      service: switch.turn_off
      data_template:
        entity_id: "{{ trigger.event.data.data.entity_id }}"
