homeassistant:
  customize:
    automation.notify_failed_login_attempt:
      friendly_name: "Notify failed login attempts"
      icon: "mdi:message-settings-variant"

automation:
  - alias: notify_failed_login_attempt
    initial_state: True
    trigger:
      - platform: event
        event_type: "call_service"
        event_data:
          domain: "persistent_notification"
          service: "create"
    condition:
      - condition: template
        value_template: "{{ trigger.event.data.service_data.notification_id == 'http-login' }}"
    action:
      - service: python_script.notify
        data_template:
          push_target: "admin"
          title: "{{ trigger.event.data.service_data.title }}"
          message: "{{ trigger.event.data.service_data.message }}"
