homeassistant:
  customize:
    sensor.processor_temperature:
      friendly_name: "Processor temperature"
      icon: "mdi:fire"
    sensor.memory_use_percent:
      friendly_name: "Memory use"
    automation.notify_update_available:
      friendly_name: "Notify about available HASS updates"
      icon: "mdi:message-settings-variant"

group:
  automate_monitor:
    name: "Automate Monitor"
    icon: "mdi:chart-scatterplot-hexbin"
    entities:
      - sensor.processor_use
      - sensor.processor_temperature
      - sensor.memory_use_percent
      - sensor.since_last_boot

sensor:
  - platform: time_date
    display_options:
      - date
      - time

  - platform: systemmonitor
    resources:
      - type: processor_use
      - type: memory_use_percent
      - type: since_last_boot

  - platform: command_line
    name: "processor_temperature"
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    value_template: "{{ value|multiply(0.001)|round(1) }}"
    unit_of_measurement: "°C"

