homeassistant:
  customize:
    sensor.cpu_temperature:
      friendly_name: "CPU Temperature"
      icon: "mdi:fire"
    automation.notify_update_available:
      friendly_name: "Notify about available HASS updates"

group:
  automate_monitor:
    name: "Automate Monitor"
    icon: "mdi:chart-scatterplot-hexbin"
    entities:
      - sensor.cpu_use
      - sensor.ram_use
      - sensor.cpu_temperature
      - sensor.since_last_boot

sensor:
  - platform: time_date
    display_options:
      - date
      - time

  - platform: systemmonitor
    resources:
      - type: processor_use
      - type: memory_use_percent
      - type: since_last_boot

  - platform: command_line
    name: "cpu_temperature"
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    value_template: "{{ value|multiply(0.001)|round(1) }}"
    unit_of_measurement: "°C"

automation:
  - alias: notify_update_available
    initial_state: True
    trigger:
      platform: state
      entity_id: updater.updater
    action:
      - service: persistent_notification.create
        data_template:
          title: "Home Assistant Update"
          message: "Home Assistant {{ states('updater.updater') }} is available.<br><a href=\"{{ states.updater.updater.attributes.release_notes }}\">Open release notes</a>"
          notification_id: "hass_update_available"
      - service: notify.admin
        data_template:
          title: "Home Assistant Update"
          message: "Home Assistant {{ states('updater.updater') }} is available."
          data:
            tag: "hass_update_available"
            url: "{{states.updater.updater.attributes.release_notes }}"
