homeassistant:
  customize:
    binary_sensor.ups_battery_status:
      battery_type: "APC BR1500G RS 1500 12V"

group:
  ups:
    name: "UPS"
    icon: "mdi:power-plug"
    entities:
      - sensor.ups_status
      - sensor.ups_load
      - sensor.ups_battery
      - sensor.ups_input_voltage
      - sensor.ups_time_left
      - sensor.ups_time_on_battery

  all_batteries:
    entities:
      - binary_sensor.ups_battery_status

apcupsd:
  host: !secret ups_host
  port: !secret ups_port

binary_sensor:
  - platform: apcupsd
  - platform: template
    sensors:
      ups_battery_status:
        friendly_name: "UPS battery"
        value_template: "{{ 'REPLACEBATT' in states('sensor.ups_status') }}"
        device_class: "battery"

input_boolean:
  notify_power_changes:
    name: "Notify power state changes"
    icon: "mdi:message-settings-variant"
  power_outage_manage_devices:
    name: "Manage devices based on power outages"
    initial: "on"

sensor:
  - platform: apcupsd
    resources:
      - bcharge # Battery Charge
      - linev # Input Voltage
      - loadpct # Load %
      - status
      - timeleft # Time Left on Battery
      - tonbatt # Time on Battery

automation:
  - alias: notify_power_back
    initial_state: True
    trigger:
      - platform: state
        entity_id: "binary_sensor.ups_online_status"
        to: "on"
    action:
      service: notify.admin
      data_template:
        title: "Power restored"
        message: "The power outage at home has finished after {{ relative_time(trigger.from_state.last_changed) }}."
        data: &power_outage_data
          tag: "power_outage"
          actions:
            - action: "device_management_{% if states('input_boolean.power_outage_manage_devices') == 'off' %}on{% else %}off{% endif %}"
              title: "{% if states('input_boolean.power_outage_manage_devices') == 'off' %}Enable{% else %}Disable{% endif %} device management"
              icon: "/local/icons/power-plug-{% if states('input_boolean.power_outage_manage_devices') == 'off' %}on{% else %}off{% endif %}.png"

  - alias: notify_power_outage
    initial_state: True
    trigger:
      - platform: state
        entity_id: "binary_sensor.ups_online_status"
        to: "off"
    action:
      service: notify.admin
      data:
        title: "Power outage"
        message: "A power outage is ongoing at home."
        data: *power_outage_data

  - alias: notification_action_enable_device_management
    initial_state: True
    hide_entity: True
    trigger:
      platform: event
      event_type: "html5_notification.clicked"
      event_data:
        action: "device_management_on"
    action:
      service: switch.turn_on
      data:
        entity_id: "input_boolean.power_outage_manage_devices"

  - alias: notification_action_disable_device_management
    initial_state: True
    hide_entity: True
    trigger:
      platform: event
      event_type: "html5_notification.clicked"
      event_data:
        action: "device_management_off"
    action:
      service: switch.turn_off
      data:
        entity_id: "input_boolean.power_outage_manage_devices"

  - alias: ups_power_off_devices
    initial_state: True
    hide_entity: True
    trigger:
      platform: state
      entity_id: "binary_sensor.ups_online_status"
      to: "off"
      for:
        seconds: 70 # UPS is polled every 60 secs, this *must* be higher to outlast short power outages.
    condition:
      condition: state
      entity_id: "input_boolean.power_outage_manage_devices"
      state: "on"
    action:
      service: switch.turn_off
      entity_id:
        - switch.network_media

  - alias: ups_power_on_devices
    initial_state: True
    hide_entity: True
    trigger:
      platform: state
      entity_id: "binary_sensor.ups_online_status"
      to: "on"
      for:
        seconds: 30 # Power can come back for a couple seconds then cut again. Been there done that.
    condition:
      condition: state
      entity_id: "input_boolean.power_outage_manage_devices"
      state: "on"
    action:
      service: switch.turn_on
      entity_id:
        - switch.network_media
