homeassistant:
  customize:
    light.downstairs:
      friendly_name: "Downstairs light"

cloud:
  google_actions:
    filter:
      include_entities:
        - "light.basement_hallway"
        - "light.downstairs"
    entity_config:
      light.basement_hallway:
        room: "Lounge"
        name: "Basement hallway"
        aliases:
          - "Basement hallway light"
      light.downstairs:
        room: "Lounge"
        name: "Downstairs"
        aliases:
          - "Downstairs light"

input_number:
  basement_hallway_thermostat_eco_setpoint:
    name: "Basement hallway thermostat eco setpoint"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer-lines"
    mode: "box"
    min: 8
    max: 18
    step: 0.5
  basement_hallway_thermostat_comfort_setpoint:
    name: "Basement hallway thermostat comfort setpoint"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer-lines"
    mode: "box"
    min: 15
    max: 25
    step: 0.5

input_select:
  basement_hallway_thermostat_auto_mode:
    name: "Basement hallway thermostat auto mode"
    icon: mdi:home-thermometer-outline
    options: ["Comfort", "Eco"]
  basement_hallway_thermostat_mode:
    name: "Basement hallway thermostat mode"
    icon: mdi:home-thermometer-outline
    options: ["Auto", "Manual"]

light:
  - platform: group
    name: "Common basement lights"
    entities:
      - light.basement_hallway
      - light.downstairs

  - platform: switch
    name: downstairs
    entity_id: "switch.downstairs_light"

sensor:
  - platform: template
    sensors:
      basement_hallway_temperature:
        unique_id: "sensor.basement_hallway_temperature"
        friendly_name: "Basement hallway temperature"
        device_class: "temperature"
        unit_of_measurement: "°C"
        value_template: "{{ states('sensor.basement_hallway_thermostat_temperature') | round(1) }}"

automation:
  - alias: "basement_hallway_light_dimmer_zwave_scenes"
    use_blueprint:
      path: "zwave/homeseer_ws200+_scene_control.yaml"
      input:
        node_id: 16

        tap_on_2x:
          - service: light.turn_on
            data:
              entity_id: "light.staircase"
        tap_off_2x:
          - service: light.turn_off
            data:
              entity_id: "light.staircase"

        tap_3x: &tap_3x
          tap_on_3x:
            - service: light.turn_on
              data:
                entity_id: "light.basement_lights"
          tap_off_3x:
            - service: light.turn_off
              data:
                entity_id: "light.basement_lights"

  - alias: "downstairs_light_switch_zwave_scenes"
    use_blueprint:
      path: "zwave/homeseer_ws200+_scene_control.yaml"
      input:
        node_id: 15

        tap_on_2x:
          - service: light.turn_on
            data:
              entity_id: "light.staircase"
        tap_off_2x:
          - service: light.turn_off
            data:
              entity_id: "light.staircase"

        <<: *tap_3x
