homeassistant:
  customize:
    light.downstairs:
      friendly_name: "Downstairs light"

cloud:
  google_actions:
    filter:
      include_entities:
        - "light.basement_hallway"
        - "light.downstairs"
    entity_config:
      light.basement_hallway:
        room: "Lounge"
        name: "Basement hallway"
        aliases:
          - "Basement hallway light"
      light.downstairs:
        room: "Lounge"
        name: "Downstairs"
        aliases:
          - "Downstairs light"

input_number:
  basement_hallway_thermostat_eco_setpoint:
    name: "Basement hallway thermostat eco setpoint"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer-lines"
    mode: "box"
    min: 8
    max: 18
    step: 0.5
  basement_hallway_thermostat_comfort_setpoint:
    name: "Basement hallway thermostat comfort setpoint"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer-lines"
    mode: "box"
    min: 15
    max: 25
    step: 0.5

input_select:
  basement_hallway_thermostat_auto_mode:
    name: "Basement hallway thermostat auto mode"
    icon: mdi:home-thermometer-outline
    options: ["Comfort", "Eco"]
  basement_hallway_thermostat_mode:
    name: "Basement hallway thermostat mode"
    icon: mdi:home-thermometer-outline
    options: ["Auto", "Manual"]

light:
  - platform: group
    name: "Common basement lights"
    entities:
      - light.basement_hallway
      - light.downstairs

  - platform: switch
    name: downstairs
    entity_id: "switch.downstairs_light"

sensor:
  - platform: template
    sensors:
      basement_hallway_temperature:
        unique_id: "sensor.basement_hallway_temperature"
        friendly_name: "Basement hallway temperature"
        device_class: "temperature"
        unit_of_measurement: "°C"
        value_template: "{{ states('sensor.basement_hallway_thermostat_temperature') | round(1) }}"

automation:
  - alias: "downstairs_lights_double_tap"
    initial_state: true
    mode: "queued"
    trigger:
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.basement_hallway_light_dimmer"
          scene_data: 7860
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.downstairs_light_switch"
          scene_data: 7860
    variables:
      entity_id: "light.staircase"
    action:
      - choose:
          - conditions: "{{ trigger.event.data.scene_id | int == 1 }}"
            sequence:
              - service: light.turn_on
                data:
                  entity_id: "{{ entity_id }}"
          - conditions: "{{ trigger.event.data.scene_id | int == 2 }}"
            sequence:
              - service: light.turn_off
                data:
                  entity_id: "{{ entity_id }}"

  - alias: "downstairs_lights_triple_tap"
    initial_state: true
    mode: "queued"
    trigger:
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.basement_hallway_light_dimmer"
          scene_data: 7920
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.downstairs_light_switch"
          scene_data: 7920
    variables:
      entity_id: "light.basement_lights"
    action:
      - choose:
          - conditions: "{{ trigger.event.data.scene_id | int == 1 }}"
            sequence:
              - service: light.turn_on
                data:
                  entity_id: "{{ entity_id }}"
          - conditions: "{{ trigger.event.data.scene_id | int == 2 }}"
            sequence:
              - service: light.turn_off
                data:
                  entity_id: "{{ entity_id }}"
