homeassistant:
  customize:
    binary_sensor.basement_bathroom_door:
      friendly_name: "Basement bathroom door"
      device_class: "door"
    sensor.basement_bathroom_door_sensor_battery:
      battery_type: "Sensative Strip"
      battery_warning_level: 20
    sensor.basement_bathroom_multisensor_battery:
      battery_type: "CR123A"
      battery_warning_level: 40
    sensor.basement_bathroom_temperature:
      friendly_name: "Basement bathroom temperature"
    light.basement_bathroom:
      friendly_name: "Basement bathroom light"

cloud:
  google_actions:
    filter:
      include_entities:
        - "light.basement_bathroom"
        - "light.basement_bathroom_vanity"
        - "fan.basement_bathroom"
    entity_config:
      light.basement_bathroom:
        room: "Basement bathroom"
        name: "Basement bathroom light"
      light.basement_bathroom_vanity:
        room: "Basement bathroom"
        name: "Basement bathroom vanity light"
        aliases:
          - "Basement bathroom vanity"
      fan.basement_bathroom:
        room: "Basement bathroom"
        name: "Basement bathroom fan"

binary_sensor:
  - platform: template
    sensors:
      basement_bathroom_motion:
        unique_id: "binary_sensor.basement_bathroom_motion"
        friendly_name: "Basement bathroom motion"
        device_class: "motion"
        value_template: "{{ is_state('sensor.basement_bathroom_multisensor_burglar', '8') }}"

      basement_bathroom_presence:
        unique_id: "binary_sensor.basement_bathroom_presence"
        friendly_name: "Basement bathroom presence"
        device_class: "presence"
        value_template: >-
          {{
            is_state('binary_sensor.basement_bathroom_motion', 'on')
              or is_state('binary_sensor.basement_bathroom_door', 'off')
          }}
        delay_off: 15

sensor:
  - platform: min_max
    name: "basement_bathroom_temperature"
    type: "mean"
    round_digits: 1
    entity_ids:
      - "sensor.basement_bathroom_multisensor_temperature"
      - "sensor.basement_bathroom_thermostat_temperature"

  - platform: template
    sensors:
      basement_bathroom_humidity:
        unique_id: "sensor.basement_bathroom_humidity"
        friendly_name: "Basement bathroom humidity"
        device_class: "humidity"
        unit_of_measurement: "%"
        value_template: "{{ states('sensor.basement_bathroom_multisensor_relative_humidity') | round }}"

fan:
  - platform: template
    fans:
      basement_bathroom:
        unique_id: "fan.basement_bathroom"
        friendly_name: "Basement bathroom fan"
        value_template: "{% if is_state('switch.basement_bathroom_fan', 'on') %}on{% else %}off{% endif %}"
        availability_template: "{{ not is_state('switch.basement_bathroom_fan', 'unavailable') }}"
        speed_template: "Normal"
        speeds:
          - "Normal"
        turn_on:
          service: "switch.turn_on"
          data:
            entity_id: "switch.basement_bathroom_fan"
        turn_off:
          service: "switch.turn_off"
          data:
            entity_id: "switch.basement_bathroom_fan"

input_number:
  basement_bathroom_thermostat_eco_setpoint:
    name: "Basement bathroom thermostat eco setpoint"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer-lines"
    mode: "box"
    min: 8
    max: 18
    step: 0.5
  basement_bathroom_thermostat_comfort_setpoint:
    name: "Basement bathroom thermostat comfort setpoint"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer-lines"
    mode: "box"
    min: 15
    max: 25
    step: 0.5

input_select:
  basement_bathroom_thermostat_auto_mode:
    name: "Basement bathroom thermostat auto mode"
    icon: mdi:home-thermometer-outline
    options: ["Comfort", "Eco"]
  basement_bathroom_thermostat_mode:
    name: "Basement bathroom thermostat mode"
    icon: mdi:home-thermometer-outline
    options: ["Auto", "Manual"]

light:
  - platform: group
    name: "Basement bathroom lights"
    entities:
      - light.basement_bathroom
      - light.basement_bathroom_vanity

  - platform: switch
    name: basement_bathroom
    entity_id: "switch.basement_bathroom_light"

automation:
  - alias: "basement_bathroom_auto_fan"
    use_blueprint:
      path: "exhaust_fan.yaml"
      input:
        fan_entity: "fan.basement_bathroom"
        humidity_entity: "sensor.basement_bathroom_humidity"

  - alias: "basement_bathroom_auto_lights"
    use_blueprint:
      path: "presence_light.yaml"
      input:
        light_entity: "light.basement_bathroom_vanity"
        light_off_entity: "light.basement_bathroom_lights"
        presence_entity: "binary_sensor.basement_bathroom_presence"
        brightness_pct: >
          {% set time = now().strftime('%H%M') | int %}
          {%- if time <= 600 -%} 1
          {%- elif time >= 900 and time <= 1800 -%} 85
          {%- else -%} 50
          {%- endif -%}

  - alias: "basement_bathroom_fan_switch_zwave_scenes"
    use_blueprint:
      path: "zwave/homeseer_ws200+_scene_control.yaml"
      input:
        zwave_entity: "zwave.basement_bathroom_fan_switch"

        tap_on_2x:
          - service: light.turn_on
            data:
              entity_id: "fan.basement_bathroom"
        tap_off_2x:
          - service: light.turn_off
            data:
              entity_id: "fan.basement_bathroom"

  - alias: "basement_bathroom_vanity_light_dimmer_zwave_scenes"
    use_blueprint:
      path: "zwave/homeseer_ws200+_scene_control.yaml"
      input:
        zwave_entity: "zwave.basement_bathroom_vanity_light_dimmer"

        tap_on_2x:
          - service: light.turn_on
            data:
              entity_id: "light.basement_bathroom"
        tap_off_2x:
          - service: light.turn_off
            data:
              entity_id: "light.basement_bathroom"

        <<: &tap_3x
          tap_on_3x:
            - service: light.turn_on
              data:
                entity_id: "light.basement_bathroom_lights"
          tap_off_3x:
            - service: light.turn_off
              data:
                entity_id: "light.basement_bathroom_lights"

  - alias: "basement_bathroom_light_switch_zwave_scenes"
    use_blueprint:
      path: "zwave/homeseer_ws200+_scene_control.yaml"
      input:
        zwave_entity: "zwave.basement_bathroom_light_switch"

        tap_on_2x:
          - service: light.turn_on
            data:
              entity_id: "light.basement_bathroom_vanity"
        tap_off_2x:
          - service: light.turn_off
            data:
              entity_id: "light.basement_bathroom_vanity"

        <<: *tap_3x
