homeassistant:
  customize:
    sensor.basement_hallway_temperature:
      friendly_name: "Basement hallway temperature"
    light.downstairs:
      friendly_name: "Downstairs light"

cloud:
  google_actions:
    filter:
      include_entities:
        - "light.basement_hallway"
        - "light.downstairs"

input_number:
  basement_hallway_thermostat_eco_setpoint:
    name: "Basement hallway thermostat eco setpoint"
    <<: &setpoint_config
      unit_of_measurement: "°C"
      icon: "mdi:thermometer-lines"
      mode: "box"
      min: 8
      max: 25
      step: 0.5
  basement_hallway_thermostat_comfort_setpoint:
    name: "Basement hallway thermostat comfort setpoint"
    <<: *setpoint_config

input_select:
  basement_hallway_thermostat_auto_mode:
    name: "Basement hallway thermostat auto mode"
    icon: mdi:home-thermometer-outline
    options: ["Comfort", "Eco"]
  basement_hallway_thermostat_mode:
    name: "Basement hallway thermostat mode"
    icon: mdi:home-thermometer-outline
    options: ["Auto", "Manual"]

light:
  - platform: group
    unique_id: "common_basement_lights"
    name: "Common basement lights"
    entities:
      - light.basement_hallway
      - light.downstairs

  - platform: switch
    name: downstairs
    entity_id: "switch.downstairs_light"

template:
  - sensor:
      - unique_id: "sensor.basement_hallway_temperature"
        name: "basement_hallway_temperature"
        device_class: "temperature"
        unit_of_measurement: "°C"
        state: "{{ states('sensor.basement_hallway_thermostat_temperature') | float(0) | round(1) }}"
        availability: "{{ not is_state('sensor.basement_hallway_thermostat_temperature', 'unavailable') }}"
        attributes:
          heating: "{{ is_state_attr('climate.basement_hallway_thermostat', 'hvac_action', 'heating') }}"

automation:
  - id: "a2df600b-4450-4a6f-8c3d-ad3f4ea5773c"
    alias: "basement_hallway_light_dimmer_zwave_scenes"
    use_blueprint:
      path: "zwave/paddle_scenes.yaml"
      input:
        on_entity_id: "event.basement_hallway_dimmer_on_pressed"
        off_entity_id: "event.basement_hallway_dimmer_off_pressed"

        <<: &basement_on_off
          tap_on_3x:
            - service: light.turn_on
              data:
                entity_id: "light.basement_lights"
          tap_off_3x:
            - service: light.turn_off
              data:
                entity_id: "light.basement_lights"

  - id: "f0425412-92de-4251-9265-f9901c8b0a4e"
    alias: "downstairs_light_switch_zwave_scenes"
    use_blueprint:
      path: "zwave/paddle_scenes.yaml"
      input:
        on_entity_id: "event.downstairs_light_switch_on_pressed"
        off_entity_id: "event.downstairs_light_switch_off_pressed"

        <<: *basement_on_off
