homeassistant:
  customize:
    light.downstairs:
      friendly_name: "Downstairs light"

cloud:
  google_actions:
    filter:
      include_entities:
        - "light.basement_hallway"
        - "light.downstairs"
    entity_config:
      light.basement_hallway:
        room: "Lounge"
        name: "Basement hallway"
        aliases:
          - "Basement hallway light"
      light.downstairs:
        room: "Lounge"
        name: "Downstairs"
        aliases:
          - "Downstairs light"

input_number:
  basement_hallway_thermostat_eco_setpoint:
    name: "Basement hallway thermostat eco setpoint"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer-lines"
    mode: "box"
    min: 8
    max: 18
    step: 0.5
  basement_hallway_thermostat_comfort_setpoint:
    name: "Basement hallway thermostat comfort setpoint"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer-lines"
    mode: "box"
    min: 15
    max: 25
    step: 0.5

input_select:
  basement_hallway_thermostat_mode:
    name: "Basement hallway thermostat mode"
    icon: mdi:home-thermometer-outline
    options: ["Comfort", "Eco", "Manual"]

light:
  - platform: group
    name: "General basement lights"
    entities:
      - light.basement_hallway
      - light.downstairs

  - platform: switch
    name: downstairs
    entity_id: "switch.downstairs_light"

sensor:
  - platform: template
    sensors:
      basement_hallway_temperature:
        friendly_name: "Basement hallway temperature"
        device_class: "temperature"
        unit_of_measurement: "°C"
        value_template: "{{ states('sensor.basement_hallway_thermostat_temperature') | round(1) }}"

automation:
  - alias: "basement_hallway_update_setpoint"
    hide_entity: True
    initial_state: True
    trigger:
      - platform: state
        entity_id: "input_select.basement_hallway_thermostat_mode"
    condition:
      - condition: template
        value_template: |
          {{ (trigger.from_state is none or trigger.from_state.state != trigger.to_state.state)
            and not trigger.to_state.state == 'Manual' }}
    action:
      - service: "climate.set_temperature"
        data_template:
          entity_id: "climate.basement_hallway_thermostat"
          temperature: "{{ states('input_number.basement_hallway_thermostat_' + (states('input_select.basement_hallway_thermostat_mode') | lower) + '_setpoint') }}"

  - alias: "basement_hallway_update_thermostat_mode"
    hide_entity: True
    initial_state: True
    trigger:
      - platform: state
        entity_id: "climate.basement_hallway_thermostat"
    condition:
      - condition: template
        value_template: |
          {{ (trigger.from_state is none or trigger.from_state.attributes.temperature != trigger.to_state.attributes.temperature)
            and trigger.to_state.attributes.preset_mode == 'none' }}
    action:
      - service: "input_select.select_option"
        data_template:
          entity_id: "input_select.basement_hallway_thermostat_mode"
          option: |
            {% set ns = namespace(mode='Manual', found=False) -%}
            {% for mode in state_attr('input_select.basement_hallway_thermostat_mode', 'options') -%}
            {% if not ns.found and trigger.to_state.attributes.temperature | float == states('input_number.basement_hallway_thermostat_' + (mode | lower) + '_setpoint') | float -%}
            {% set ns.mode = mode -%}
            {% set ns.found = True %}
            {%- endif %}
            {%- endfor -%}
            {{ ns.mode }}

  - alias: "triple_up_downstairs_lights"
    hide_entity: True
    initial_state: True
    trigger:
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.basement_hallway_light_dimmer"
          scene_id: 1
          scene_data: 7920
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.downstairs_light_switch"
          scene_id: 1
          scene_data: 7920
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.lounge_light_dimmer"
          scene_id: 1
          scene_data: 7920
    action:
      service: light.turn_on
      data:
        entity_id: "light.basement_lights"
  - alias: "triple_down_downstairs_lights"
    hide_entity: True
    initial_state: True
    trigger:
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.basement_hallway_light_dimmer"
          scene_id: 2
          scene_data: 7920
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.downstairs_light_switch"
          scene_id: 2
          scene_data: 7920
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.lounge_light_dimmer"
          scene_id: 2
          scene_data: 7920
    action:
      service: light.turn_off
      data:
        entity_id: "light.basement_lights"
