homeassistant:
  customize:
    binary_sensor.basement_bathroom_door:
      friendly_name: "Basement bathroom door"
      device_class: "door"
    sensor.basement_bathroom_door_sensor_battery:
      battery_type: "Sensative Strip"
    sensor.basement_bathroom_multisensor_battery:
      battery_type: "CR123A"
    sensor.basement_bathroom_temperature:
      friendly_name: "Basement bathroom temperature"
    light.basement_bathroom:
      friendly_name: "Basement bathroom light"

cloud:
  google_actions:
    filter:
      include_entities:
        - "light.basement_bathroom"
        - "light.basement_bathroom_vanity"
        - "fan.basement_bathroom"
    entity_config:
      light.basement_bathroom:
        room: "Basement bathroom"
        name: "Basement bathroom light"
      light.basement_bathroom_vanity:
        room: "Basement bathroom"
        name: "Basement bathroom vanity light"
        aliases:
          - "Basement bathroom vanity"
      fan.basement_bathroom:
        room: "Basement bathroom"
        name: "Basement bathroom fan"

binary_sensor:
  - platform: template
    sensors:
      basement_bathroom_motion:
        friendly_name: "Basement bathroom motion"
        device_class: "motion"
        value_template: "{{ is_state('sensor.basement_bathroom_multisensor_burglar', '8') }}"

sensor:
  - platform: min_max
    name: "basement_bathroom_temperature"
    type: "mean"
    round_digits: 1
    entity_ids:
      - "sensor.basement_bathroom_multisensor_temperature"
      - "sensor.basement_bathroom_thermostat_temperature"
  - platform: template
    sensors:
      basement_bathroom_humidity:
        friendly_name: "Basement bathroom humidity"
        device_class: "humidity"
        unit_of_measurement: "%"
        value_template: "{{ states('sensor.basement_bathroom_multisensor_relative_humidity') | round }}"

fan:
  - platform: template
    fans:
      basement_bathroom:
        friendly_name: "Basement bathroom fan"
        value_template: "{% if is_state('switch.basement_bathroom_fan', 'on') %}on{% else %}off{% endif %}"
        availability_template: "{{ is_state('switch.basement_bathroom_fan', 'unavailable') }}"
        speed_template: "Normal"
        speeds:
          - "Normal"
        turn_on:
          service: "switch.turn_on"
          data:
            entity_id: "switch.basement_bathroom_fan"
        turn_off:
          service: "switch.turn_off"
          data:
            entity_id: "switch.basement_bathroom_fan"

input_number:
  basement_bathroom_thermostat_eco_setpoint:
    name: "Basement bathroom thermostat eco setpoint"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer-lines"
    mode: "box"
    min: 8
    max: 18
    step: 0.5
  basement_bathroom_thermostat_comfort_setpoint:
    name: "Basement bathroom thermostat comfort setpoint"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer-lines"
    mode: "box"
    min: 15
    max: 25
    step: 0.5

input_select:
  basement_bathroom_thermostat_auto_mode:
    name: "Basement bathroom thermostat auto mode"
    icon: mdi:home-thermometer-outline
    options: ["Comfort", "Eco"]
  basement_bathroom_thermostat_mode:
    name: "Basement bathroom thermostat mode"
    icon: mdi:home-thermometer-outline
    options: ["Auto", "Manual"]

light:
  - platform: group
    name: "Basement bathroom lights"
    entities:
      - light.basement_bathroom
      - light.basement_bathroom_vanity

  - platform: switch
    name: basement_bathroom
    entity_id: "switch.basement_bathroom_light"

automation:
  # Automated fan management
  - alias: "basement_bathroom_auto_fan_on"
    hide_entity: True
    initial_state: True
    trigger:
      - platform: numeric_state
        entity_id: "sensor.basement_bathroom_humidity"
        above: &basement_bathroom_fan_on_humidity 64
      - platform: state
        entity_id: "fan.basement_bathroom"
        to: "off"
        for: &basement_bathroom_fan_manual_time
          minutes: 30
    condition:
      - condition: numeric_state
        entity_id: "sensor.basement_bathroom_humidity"
        above: *basement_bathroom_fan_on_humidity
    action:
      - service: fan.turn_on
        data:
          entity_id: "fan.basement_bathroom"
  - alias: "basement_bathroom_auto_fan_off"
    hide_entity: True
    initial_state: True
    trigger:
      - platform: numeric_state
        entity_id: "sensor.basement_bathroom_humidity"
        below: &basement_bathroom_fan_off_humidity 61
      - platform: state
        entity_id: "fan.basement_bathroom"
        to: "on"
        for: *basement_bathroom_fan_manual_time
    condition:
      - condition: numeric_state
        entity_id: "sensor.basement_bathroom_humidity"
        below: *basement_bathroom_fan_off_humidity
    action:
      - service: fan.turn_off
        data:
          entity_id: "fan.basement_bathroom"

  # Automated light management
  - alias: "basement_bathroom_auto_lights_on"
    hide_entity: True
    initial_state: True
    trigger:
      - platform: state
        entity_id: "binary_sensor.basement_bathroom_motion"
        to: "on"
    condition:
      - condition: state
        entity_id: "binary_sensor.basement_bathroom_door"
        state: "on"
      - condition: state
        entity_id: "light.basement_bathroom_lights"
        state: "off"
    action:
      - service: light.turn_on
        data_template:
          entity_id: "light.basement_bathroom_vanity"
          brightness_pct: >-
            {% set time = now().strftime('%H%M') | int %}
            {%- if time <= 600 -%} 5
            {%- elif time >= 900 and time <= 1800 -%} 85
            {%- else -%} 50
            {%- endif -%}
  - alias: "basement_bathroom_auto_lights_off"
    hide_entity: True
    initial_state: True
    trigger:
      - platform: state
        entity_id: "binary_sensor.basement_bathroom_motion"
        to: "off"
        for:
          minutes: 2
    condition:
      - condition: state
        entity_id: "binary_sensor.basement_bathroom_door"
        state: "on"
    action:
      - service: light.turn_off
        data:
          entity_id: "light.basement_bathroom_lights"

  # Double tap fan switch will turn fan on/off
  - alias: "basement_bathroom_fan_double_up"
    hide_entity: True
    initial_state: True
    trigger:
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.basement_bathroom_fan_switch"
          scene_id: 1
          scene_data: 7860
    action:
      service: fan.turn_on
      data:
        entity_id: "fan.basement_bathroom"
  - alias: "basement_bathroom_fan_double_down"
    hide_entity: True
    initial_state: True
    trigger:
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.basement_bathroom_fan_switch"
          scene_id: 2
          scene_data: 7860
    action:
      service: fan.turn_off
      data:
        entity_id: "fan.basement_bathroom"

  # Double tap vanity switch will turn spots on/off (spots switch on opposite side of the room)
  - alias: "basement_bathroom_vanity_double_up"
    hide_entity: True
    initial_state: True
    trigger:
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.basement_bathroom_vanity_light_dimmer"
          scene_id: 1
          scene_data: 7860
    action:
      service: light.turn_on
      data:
        entity_id: "light.basement_bathroom"
  - alias: "basement_bathroom_vanity_double_down"
    hide_entity: True
    initial_state: True
    trigger:
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.basement_bathroom_vanity_light_dimmer"
          scene_id: 2
          scene_data: 7860
    action:
      service: light.turn_off
      data:
        entity_id: "light.basement_bathroom"

  # Double tap ceiling switch will turn vanity on/off (vanity switch on opposite side of the room)
  - alias: "basement_bathroom_ceiling_double_up"
    hide_entity: True
    initial_state: True
    trigger:
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.basement_bathroom_light_switch"
          scene_id: 1
          scene_data: 7860
    action:
      service: light.turn_on
      data:
        entity_id: "light.basement_bathroom_vanity"
  - alias: "basement_bathroom_ceiling_double_down"
    hide_entity: True
    initial_state: True
    trigger:
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.basement_bathroom_light_switch"
          scene_id: 2
          scene_data: 7860
    action:
      service: light.turn_off
      data:
        entity_id: "light.basement_bathroom_vanity"

  # Triple tap any light switch will turn bathroom lights on/off
  - alias: "basement_bathroom_lights_triple_up"
    hide_entity: True
    initial_state: True
    trigger:
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.basement_bathroom_light_switch"
          scene_id: 1
          scene_data: 7920
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.basement_bathroom_vanity_light_dimmer"
          scene_id: 1
          scene_data: 7920
    action:
      service: light.turn_on
      data:
        entity_id: "light.basement_bathroom_lights"
  - alias: "basement_bathroom_lights_triple_down"
    hide_entity: True
    initial_state: True
    trigger:
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.basement_bathroom_light_switch"
          scene_id: 2
          scene_data: 7920
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.basement_bathroom_vanity_light_dimmer"
          scene_id: 2
          scene_data: 7920
    action:
      service: light.turn_off
      data:
        entity_id: "light.basement_bathroom_lights"
