homeassistant:
  customize:
    binary_sensor.basement_bathroom_presence:
      friendly_name: "Basement bathroom presence"
    sensor.basement_bathroom_humidity:
      friendly_name: "Basement bathroom humidity"
    sensor.basement_bathroom_multisensor_battery:
      battery_type: "CR123A"
      battery_warning_level: 40
    sensor.basement_bathroom_temperature:
      friendly_name: "Basement bathroom temperature"

cloud:
  google_actions:
    filter:
      include_entities:
        - "light.basement_bathroom"
        - "light.basement_bathroom_vanity"
        - "fan.basement_bathroom"

template:
  - binary_sensor:
      - unique_id: "binary_sensor.basement_bathroom_presence"
        name: "basement_bathroom_presence"
        device_class: "presence"
        state: >-
          {{
            is_state('binary_sensor.basement_bathroom_motion', 'on')
          }}
        delay_off: 15

    sensor:
      - unique_id: "sensor.basement_bathroom_humidity"
        name: "basement_bathroom_humidity"
        device_class: "humidity"
        unit_of_measurement: "%"
        state: "{{ states('sensor.basement_bathroom_multisensor_relative_humidity') | int(0) | round }}"
        availability: "{{ not is_state('sensor.basement_bathroom_multisensor_relative_humidity', 'unavailable') }}"

      - unique_id: "sensor.basement_bathroom_temperature"
        name: "basement_bathroom_temperature"
        device_class: "temperature"
        unit_of_measurement: "°C"
        state: "{{ states('sensor.basement_bathroom_multisensor_temperature') | int(0) | round(1) }}"
        availability: "{{ not is_state('sensor.basement_bathroom_multisensor_temperature', 'unavailable') }}"
        attributes:
          heating: false

input_number:
  basement_bathroom_thermostat_eco_setpoint:
    name: "Basement bathroom thermostat eco setpoint"
    <<: &setpoint_config
      unit_of_measurement: "°C"
      icon: "mdi:thermometer-lines"
      mode: "box"
      min: 8
      max: 25
      step: 0.5
  basement_bathroom_thermostat_comfort_setpoint:
    name: "Basement bathroom thermostat comfort setpoint"
    <<: *setpoint_config

input_select:
  basement_bathroom_thermostat_auto_mode:
    name: "Basement bathroom thermostat auto mode"
    icon: mdi:home-thermometer-outline
    options: ["Comfort", "Eco"]
  basement_bathroom_thermostat_mode:
    name: "Basement bathroom thermostat mode"
    icon: mdi:home-thermometer-outline
    options: ["Auto", "Manual"]

light:
  - platform: group
    unique_id: "basement_bathroom_lights"
    name: "Basement bathroom lights"
    entities:
      - light.basement_bathroom
      - light.basement_bathroom_vanity

automation:
  - id: "13a8923b-8f42-4a1f-9d21-91980a400c75"
    alias: "basement_bathroom_auto_fan"
    use_blueprint:
      path: "exhaust_fan.yaml"
      input:
        fan_entity: "fan.basement_bathroom"
        humidity_entity: "sensor.basement_bathroom_humidity"

  - id: "334efc56-2a2f-49f6-961b-57dcc1a07bc7"
    alias: "basement_bathroom_auto_lights"
    initial_state: false
    use_blueprint:
      path: "presence_light.yaml"
      input:
        light_entity: "light.basement_bathroom_vanity"
        light_off_entity: "light.basement_bathroom_lights"
        presence_entity: "binary_sensor.basement_bathroom_presence"
        brightness_based_on_time: true

  - id: "28830f28-ec7e-4c19-9508-355e16978c13"
    alias: "basement_bathroom_fan_switch_zwave_scenes"
    use_blueprint:
      path: "zwave/paddle_scenes.yaml"
      input:
        on_entity_id: "event.basement_bathroom_fan_switch_on_pressed"
        off_entity_id: "event.basement_bathroom_fan_switch_off_pressed"

        <<: &all_on_off
          tap_on_3x:
            - service: light.turn_on
              data:
                entity_id: "light.basement_bathroom_lights"
          tap_off_3x:
            - service: light.turn_off
              data:
                entity_id: "light.basement_bathroom_lights"

  - id: "6821f60b-2e78-4610-9e7b-9dbb33cb4f79"
    alias: "basement_bathroom_vanity_light_dimmer_zwave_scenes"
    use_blueprint:
      path: "zwave/paddle_scenes.yaml"
      input:
        on_entity_id: "event.basement_bathroom_vanity_dimmer_on_pressed"
        off_entity_id: "event.basement_bathroom_vanity_dimmer_off_pressed"

        <<: *all_on_off


  - id: "41427797-3a24-4db7-8c6b-d919cd6bd415"
    alias: "basement_bathroom_light_switch_zwave_scenes"
    use_blueprint:
      path: "zwave/paddle_scenes.yaml"
      input:
        on_entity_id: "event.basement_bathroom_light_switch_on_pressed"
        off_entity_id: "event.basement_bathroom_light_switch_off_pressed"

        <<: *all_on_off
