homeassistant:
  customize:
    sensor.basement_bathroom_humidity:
      friendly_name: "Basement bathroom humidity"
    sensor.basement_bathroom_multisensor_battery:
      battery_type: "CR123A"
      battery_warning_level: 40
    sensor.basement_bathroom_temperature:
      friendly_name: "Basement bathroom temperature"

cloud:
  google_actions:
    filter:
      include_entities:
        - "light.basement_bathroom_shower"
        - "light.basement_bathroom_vanity"
        - "fan.basement_bathroom"

template:
  - sensor:
      - unique_id: "sensor.basement_bathroom_humidity"
        default_entity_id: "sensor.basement_bathroom_humidity"
        name: "Basement bathroom humidity"
        device_class: "humidity"
        unit_of_measurement: "%"
        state: "{{ states('sensor.basement_bathroom_multisensor_relative_humidity') | int(0) | round }}"
        availability: "{{ not is_state('sensor.basement_bathroom_multisensor_relative_humidity', 'unavailable') }}"

      - unique_id: "sensor.basement_bathroom_temperature"
        default_entity_id: "sensor.basement_bathroom_temperature"
        name: "Basement bathroom temperature"
        device_class: "temperature"
        unit_of_measurement: "°C"
        state: "{{ states('sensor.basement_bathroom_multisensor_temperature') | int(0) | round(1) }}"
        availability: "{{ not is_state('sensor.basement_bathroom_multisensor_temperature', 'unavailable') }}"
        attributes:
          heating: false

input_number:
  basement_bathroom_thermostat_eco_setpoint:
    name: "Basement bathroom thermostat eco setpoint"
    <<: &setpoint_config
      unit_of_measurement: "°C"
      icon: "mdi:thermometer-lines"
      mode: "box"
      min: 8
      max: 25
      step: 0.5
  basement_bathroom_thermostat_comfort_setpoint:
    name: "Basement bathroom thermostat comfort setpoint"
    <<: *setpoint_config

input_select:
  basement_bathroom_thermostat_auto_mode:
    name: "Basement bathroom thermostat auto mode"
    icon: mdi:home-thermometer-outline
    options: ["Comfort", "Eco"]
  basement_bathroom_thermostat_mode:
    name: "Basement bathroom thermostat mode"
    icon: mdi:home-thermometer-outline
    options: ["Auto", "Manual"]

light:
  - platform: "group"
    unique_id: "basement_bathroom_lights"
    name: "Basement bathroom lights"
    entities:
      - "light.basement_bathroom_shower"
      - "light.basement_bathroom_vanity"

binary_sensor:
  - platform: "group"
    unique_id: "c9b958eb-eaba-4bf7-9976-3f5de622cfb6"
    name: "Basement bathroom motion"
    device_class: "motion"
    entities:
      - "binary_sensor.basement_bathroom_shower_light_dimmer_motion"

automation:
  - id: "13a8923b-8f42-4a1f-9d21-91980a400c75"
    alias: "basement_bathroom_auto_fan"
    use_blueprint:
      path: "exhaust_fan.yaml"
      input:
        fan_entity: "fan.basement_bathroom"
        humidity_entity: "sensor.basement_bathroom_humidity"

  - id: "334efc56-2a2f-49f6-961b-57dcc1a07bc7"
    alias: "basement_bathroom_motion_lights"
    initial_state: false
    use_blueprint:
      path: "presence_light.yaml"
      input:
        light_entity: "light.basement_bathroom_vanity"
        light_off_entity: "light.basement_bathroom_lights"
        presence_entity: "binary_sensor.basement_bathroom_motion"
        brightness_based_on_time: true

  - id: "6105a87c-c726-4372-856b-65ce62625ac3"
    alias: "basement_bathroom_motion_lights_toggle"
    initial_state: true
    triggers:
      - id: "toggle"
        trigger: "state"
        entity_id: "event.basement_bathroom_shower_light_dimmer_favorite_pressed"
        not_from: "unavailable"
      - id: "turn_on"
        trigger: "time"
        at: "03:00:00"
    actions:
      - action: "automation.{{ trigger.id }}"
        target:
          entity_id: "automation.basement_bathroom_motion_lights"

  - id: "728edbd4-841e-4285-8408-ff694a99d290"
    alias: "basement_bathroom_spots_dimmer_led"
    initial_state: true
    mode: "queued"
    triggers:
      - id: "motion_lights_disabled"
        trigger: "state"
        entity_id: "automation.basement_bathroom_motion_lights"
        from: "on"
        to: "off"
        variables:
          duration: 142
          level: 25
      - id: "motion_lights_enabled"
        trigger: "state"
        entity_id: "automation.basement_bathroom_motion_lights"
        from: "off"
        to: "on"
        variables:
          duration: 0
          level: 0
    actions:
      - action: "zwave_js.bulk_set_partial_config_parameters"
        target:
          entity_id: "light.basement_bathroom_shower"
        data:
          parameter: 94
          value:
            0xFF: "{{ duration }}"
            0xFF00: "{{ level }}"
            0xFF0000: 0
            0xFF000000: "Solid"
