homeassistant:
  customize:
    sensor.dining_room_temperature:
      friendly_name: "Dining room temperature"

cloud:
  google_actions:
    filter:
      include_entities:
        - "light.dining_room"
        - "light.hallway_spots"
    entity_config:
      light.dining_room:
        aliases:
          - "Table light"

input_number:
  dining_room_thermostat_eco_setpoint:
    name: "Dining room thermostat eco setpoint"
    <<: &setpoint_config
      unit_of_measurement: "°C"
      icon: "mdi:thermometer-lines"
      mode: "box"
      min: 8
      max: 25
      step: 0.5
  dining_room_thermostat_comfort_setpoint:
    name: "Dining room thermostat comfort setpoint"
    <<: *setpoint_config

input_select:
  dining_room_thermostat_auto_mode:
    name: "Dining room thermostat auto mode"
    icon: mdi:home-thermometer-outline
    options: ["Comfort", "Eco"]
  dining_room_thermostat_mode:
    name: "Dining room thermostat mode"
    icon: mdi:home-thermometer-outline
    options: ["Auto", "Manual"]

light:
  - platform: group
    unique_id: "dining_room_lights"
    name: "Dining room lights"
    entities:
      - "light.dining_room"
      - "light.hallway_spots"

template:
  - sensor:
      - unique_id: "sensor.dining_room_temperature"
        name: "dining_room_temperature"
        device_class: "temperature"
        unit_of_measurement: "°C"
        state: "{{ states('sensor.dining_room_thermostat_temperature') | float(0) | round(1) }}"
        availability: "{{ not is_state('sensor.dining_room_thermostat_temperature', 'unavailable') }}"
        attributes:
          heating: "{{ is_state_attr('climate.dining_room_thermostat', 'hvac_action', 'heating') }}"

automation:
  - id: "c531a467-eef3-484d-9b4e-b5fc90414bf4"
    alias: "dining_room_dimmer_zwave_scenes"
    use_blueprint:
      path: "zwave/paddle_scenes.yaml"
      input:
        on_entity_id: "event.dining_room_light_dimmer_on_pressed"
        off_entity_id: "event.dining_room_light_dimmer_off_pressed"
        favorite_entity_id: "event.dining_room_light_dimmer_favorite_pressed"

        tap_favorite:
          - service: "light.toggle"
            target:
              entity_id: "light.hallway_spots"

        tap_on_2x:
          - service: "light.turn_on"
            data:
              entity_id: "light.dining_room_lights"
        tap_off_2x:
          - service: "light.turn_off"
            data:
              entity_id: "light.dining_room_lights"

  - id: "7a81bc8a-fc13-426e-b324-e2c76c1142d7"
    alias: "hallway_light_switch_zwave_scenes"
    use_blueprint:
      path: "zwave/paddle_scenes.yaml"
      input:
        on_entity_id: "event.hallway_spots_dimmer_on_pressed"
        off_entity_id: "event.hallway_spots_dimmer_off_pressed"

        tap_on_2x:
          - service: "light.turn_on"
            data:
              entity_id: "light.kitchen_track"
        tap_off_2x:
          - service: "light.turn_off"
            data:
              entity_id: "light.kitchen_track"
