homeassistant:
  customize:
    light.hallway:
      friendly_name: "Hallway light"

google_assistant:
  entity_config:
    light.dining_room:
      expose: True
      room: "Dining room"
      aliases:
        - "Dining room light"
        - "Dining room"
        - "Table light"
        - "Table"
    light.hallway:
      expose: True
      room: "Kitchen"
      name: "Hallway light"
      aliases:
        - "Hallway"

light:
  - platform: group
    name: "Dining room lights"
    entities:
      - light.dining_room
      - light.hallway
  - platform: switch
    name: hallway
    entity_id: "switch.hallway_light"

automation:
  - alias: "hallway_light_double_up"
    hide_entity: True
    initial_state: True
    trigger:
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.hallway_light_switch"
          scene_id: 1
          scene_data: 7860
    action:
      service: light.turn_on
      data:
        entity_id: "light.dining_room"
  - alias: "hallway_light_double_down"
    hide_entity: True
    initial_state: True
    trigger:
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.hallway_light_switch"
          scene_id: 2
          scene_data: 7860
    action:
      service: light.turn_off
      data:
        entity_id: "light.dining_room"
