homeassistant:
  customize:
    light.hallway:
      friendly_name: "Hallway light"
    sensor.dining_room_temperature:
      friendly_name: "Dining room temperature"

cloud:
  google_actions:
    filter:
      include_entities:
        - "light.dining_room"
        - "light.hallway"
    entity_config:
      light.dining_room:
        room: "Dining room"
        name: "Dining room light"
        aliases:
          - "Dining room"
          - "Table light"
          - "Table"
      light.hallway:
        room: "Dining room"
        name: "Hallway light"
        aliases:
          - "Hallway"

input_number:
  dining_room_thermostat_eco_setpoint:
    name: "Dining room thermostat eco setpoint"
    <<: &setpoint_config
      unit_of_measurement: "°C"
      icon: "mdi:thermometer-lines"
      mode: "box"
      min: 8
      max: 25
      step: 0.5
  dining_room_thermostat_comfort_setpoint:
    name: "Dining room thermostat comfort setpoint"
    <<: *setpoint_config
  dining_room_thermostat_boost_setpoint:
    name: "Dining room thermostat boost setpoint"
    <<: *setpoint_config

input_select:
  dining_room_thermostat_auto_mode:
    name: "Dining room thermostat auto mode"
    icon: mdi:home-thermometer-outline
    options: ["Boost", "Comfort", "Eco"]
  dining_room_thermostat_mode:
    name: "Dining room thermostat mode"
    icon: mdi:home-thermometer-outline
    options: ["Auto", "Manual"]

light:
  - platform: group
    name: "Dining room lights"
    entities:
      - light.dining_room
      - light.hallway

  - platform: switch
    name: hallway
    entity_id: "switch.hallway_light"

template:
  sensor:
    - unique_id: "sensor.dining_room_temperature"
      name: "dining_room_temperature"
      device_class: "temperature"
      unit_of_measurement: "°C"
      state: "{{ states('sensor.dining_room_thermostat_temperature') | round(1) }}"

automation:
  - id: "7a81bc8a-fc13-426e-b324-e2c76c1142d7"
    alias: "hallway_light_switch_zwave_scenes"
    use_blueprint:
      path: "zwave/homeseer_ws200+_scene_control.yaml"
      input:
        node_id: 32

        tap_on_2x:
          - service: light.turn_on
            data:
              entity_id: "light.dining_room"
        tap_off_2x:
          - service: light.turn_off
            data:
              entity_id: "light.dining_room"
