homeassistant:
  customize:
    light.hallway:
      friendly_name: "Hallway light"

cloud:
  google_actions:
    filter:
      include_entities:
        - "light.dining_room"
        - "light.hallway"
    entity_config:
      light.dining_room:
        room: "Dining room"
        name: "Dining room light"
        aliases:
          - "Dining room"
          - "Table light"
          - "Table"
      light.hallway:
        room: "Dining room"
        name: "Hallway light"
        aliases:
          - "Hallway"

input_number:
  dining_room_thermostat_eco_setpoint:
    name: "Dining room thermostat eco setpoint"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer-lines"
    mode: "box"
    min: 8
    max: 18
    step: 0.5
  dining_room_thermostat_comfort_setpoint:
    name: "Dining room thermostat comfort setpoint"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer-lines"
    mode: "box"
    min: 15
    max: 25
    step: 0.5

input_select:
  dining_room_thermostat_auto_mode:
    name: "Dining room thermostat auto mode"
    icon: mdi:home-thermometer-outline
    options: ["Comfort", "Eco"]
  dining_room_thermostat_mode:
    name: "Dining room thermostat mode"
    icon: mdi:home-thermometer-outline
    options: ["Auto", "Manual"]

light:
  - platform: group
    name: "Dining room lights"
    entities:
      - light.dining_room
      - light.hallway
  - platform: switch
    name: hallway
    entity_id: "switch.hallway_light"

sensor:
  - platform: template
    sensors:
      dining_room_temperature:
        friendly_name: "Dining room temperature"
        device_class: "temperature"
        unit_of_measurement: "°C"
        value_template: "{{ states('sensor.dining_room_thermostat_temperature') | round(1) }}"

automation:
  - alias: "hallway_light_double_up"
    initial_state: true
    trigger:
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.hallway_light_switch"
          scene_id: 1
          scene_data: 7860
    action:
      service: light.turn_on
      data:
        entity_id: "light.dining_room"
  - alias: "hallway_light_double_down"
    initial_state: true
    trigger:
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.hallway_light_switch"
          scene_id: 2
          scene_data: 7860
    action:
      service: light.turn_off
      data:
        entity_id: "light.dining_room"
