homeassistant:
  customize:
    sensor.guest_east_window_sensor_battery:
      battery_type: "Sensative Strip"
    sensor.guest_west_window_sensor_battery:
      battery_type: "Sensative Strip"

binary_sensor:
  - platform: template
    sensors:
      guest_east_window:
        friendly_name: "Guest window (east)"
        device_class: "window"
        value_template: "{{ is_state('sensor.guest_east_window_sensor_access_control', '22') }}"
      guest_west_window:
        friendly_name: "Guest window (west)"
        device_class: "window"
        value_template: "{{ is_state('sensor.guest_west_window_sensor_access_control', '22') }}"

sensor:
  - platform: template
    sensors:
      guest_east_window_sensor_battery:
        friendly_name: "Guest east window sensor battery"
        device_class: "battery"
        unit_of_measurement: "%"
        value_template: "{{ state_attr('zwave.guest_east_window_sensor', 'battery_level') | int('unknown') }}"
      guest_west_window_sensor_battery:
        friendly_name: "Guest west window sensor battery"
        device_class: "battery"
        unit_of_measurement: "%"
        value_template: "{{ state_attr('zwave.guest_west_window_sensor', 'battery_level') | int('unknown') }}"

