homeassistant:
  customize:
    binary_sensor.guest_bedroom_window:
      device_class: "window"
    light.guest_bedroom:
      friendly_name: "Guest bedroom light"
    light.guest_bedroom_closet:
      friendly_name: "Guest bedroom closet light"
    sensor.guest_bedroom_window_sensor_battery:
      battery_type: "Sensative Strip"
      battery_warning_level: 20

cloud:
  google_actions:
    filter:
      include_entities:
        - "light.guest_bedroom"
        - "light.guest_bedroom_closet"
    entity_config:
      light.guest_bedroom:
        room: "Guest's bedroom"
        name: "Guest's bedroom light"
        aliases:
          - "Guest's bedroom"
      light.guest_bedroom_closet:
        room: "Guest's bedroom"
        name: "Guest's bedroom closet light"
        aliases:
          - "Guest's bedroom closet"

input_number:
  guest_bedroom_thermostat_eco_setpoint:
    name: "Guest bedroom thermostat eco setpoint"
    <<: &setpoint_config
      unit_of_measurement: "°C"
      icon: "mdi:thermometer-lines"
      mode: "box"
      min: 8
      max: 25
      step: 0.5
  guest_bedroom_thermostat_comfort_setpoint:
    name: "Guest bedroom thermostat comfort setpoint"
    <<: *setpoint_config
  guest_bedroom_thermostat_boost_setpoint:
    name: "Guest bedroom thermostat boost setpoint"
    <<: *setpoint_config

input_select:
  guest_bedroom_thermostat_auto_mode:
    name: "Guest bedroom thermostat auto mode"
    icon: mdi:home-thermometer-outline
    options: ["Boost", "Comfort", "Eco"]
  guest_bedroom_thermostat_mode:
    name: "Guest bedroom thermostat mode"
    icon: mdi:home-thermometer-outline
    options: ["Auto", "Manual"]

light:
  - platform: group
    name: "Guest bedroom lights"
    entities:
      - "light.guest_bedroom"
      - "light.guest_bedroom_closet"

  - platform: switch
    name: "guest_bedroom"
    entity_id: "switch.guest_bedroom_light"

  - platform: switch
    name: "guest_bedroom_closet"
    entity_id: "switch.guest_bedroom_closet_light"

template:
  sensor:
    - unique_id: "sensor.guest_bedroom_temperature"
      name: "guest_bedroom_temperature"
      device_class: "temperature"
      unit_of_measurement: "°C"
      state: "{{ states('sensor.guest_bedroom_thermostat_temperature') | round(1) }}"
      attributes:
        friendly_name: "Guest bedroom temperature"
