homeassistant:
  customize:
    binary_sensor.guest_bedroom_window:
      friendly_name: "Guest bedroom window"
      device_class: "window"
    light.guest_bedroom_closet:
      friendly_name: "Guest bedroom closet light"
    sensor.guest_bedroom_window_sensor_battery:
      battery_type: "Sensative Strip"
      battery_warning_level: 20
    sensor.guest_bedroom_temperature:
      friendly_name: "Guest bedroom temperature"

cloud:
  google_actions:
    filter:
      include_entities:
        - "light.guest_bedroom_spots"
        - "light.guest_bedroom_closet"

input_number:
  guest_bedroom_thermostat_eco_setpoint:
    name: "Guest bedroom thermostat eco setpoint"
    <<: &setpoint_config
      unit_of_measurement: "°C"
      icon: "mdi:thermometer-lines"
      mode: "box"
      min: 8
      max: 25
      step: 0.5
  guest_bedroom_thermostat_comfort_setpoint:
    name: "Guest bedroom thermostat comfort setpoint"
    <<: *setpoint_config

input_select:
  guest_bedroom_thermostat_auto_mode:
    name: "Guest bedroom thermostat auto mode"
    icon: mdi:home-thermometer-outline
    options: ["Comfort", "Eco"]
  guest_bedroom_thermostat_mode:
    name: "Guest bedroom thermostat mode"
    icon: mdi:home-thermometer-outline
    options: ["Auto", "Manual"]

light:
  - platform: group
    unique_id: "guest_bedroom_lights"
    name: "Guest bedroom lights"
    entities:
      - "light.guest_bedroom_spots"
      - "light.guest_bedroom_closet"

  - platform: switch
    name: "guest_bedroom_closet"
    entity_id: "switch.guest_bedroom_closet_light"

template:
  - sensor:
      - unique_id: "sensor.guest_bedroom_temperature"
        name: "guest_bedroom_temperature"
        device_class: "temperature"
        unit_of_measurement: "°C"
        state: "{{ states('sensor.guest_bedroom_thermostat_temperature') | float(0) | round(1) }}"
        availability: "{{ not is_state('sensor.guest_bedroom_thermostat_temperature', 'unavailable') }}"
        attributes:
          heating: "{{ is_state_attr('climate.guest_bedroom_thermostat', 'hvac_action', 'heating') }}"

timer:
  guest_bedroom_thermostat_manual_mode_reset:
    name: "Reset guest bedroom to auto manual mode"
    duration: "01:00:00"
    restore: true
