homeassistant:
  customize:
    binary_sensor.guest_bedroom_window:
      friendly_name: "Guest bedroom window"
      device_class: "window"
    light.guest_bedroom:
      friendly_name: "Guest's bedroom light"
    sensor.guest_bedroom_window_sensor_battery:
      battery_type: "Sensative Strip"
      battery_warning_level: 20

cloud:
  google_actions:
    filter:
      include_entities:
        - "light.guest_bedroom"
    entity_config:
      light.guest_bedroom:
        room: "Guest's bedroom"
        name: "Guest's bedroom light"
        aliases:
          - "Guest's bedroom"

input_number:
  guest_bedroom_thermostat_eco_setpoint:
    name: "Guest bedroom thermostat eco setpoint"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer-lines"
    mode: "box"
    min: 8
    max: 18
    step: 0.5
  guest_bedroom_thermostat_comfort_setpoint:
    name: "Guest bedroom thermostat comfort setpoint"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer-lines"
    mode: "box"
    min: 15
    max: 25
    step: 0.5

input_select:
  guest_bedroom_thermostat_auto_mode:
    name: "Guest bedroom thermostat auto mode"
    icon: mdi:home-thermometer-outline
    options: ["Comfort", "Eco"]
  guest_bedroom_thermostat_mode:
    name: "Guest bedroom thermostat mode"
    icon: mdi:home-thermometer-outline
    options: ["Auto", "Manual"]

light:
  - platform: group
    name: "Guest bedroom lights"
    entities:
      - light.guest_bedroom

  - platform: switch
    name: "guest_bedroom"
    entity_id: "switch.guest_bedroom_light"

sensor:
  - platform: template
    sensors:
      guest_bedroom_temperature:
        friendly_name: "Guest bedroom temperature"
        device_class: "temperature"
        unit_of_measurement: "°C"
        value_template: "{{ states('sensor.guest_bedroom_thermostat_temperature') | round(1) }}"
