homeassistant:
  customize:
    light.guest_bedroom:
      friendly_name: "Guest's bedroom light"
    sensor.guest_bedroom_window_sensor_battery:
      battery_type: "Sensative Strip"

cloud:
  google_actions:
    filter:
      include_entities:
        - "light.guest_bedroom"
    entity_config:
      light.guest_bedroom:
        room: "Guest's bedroom"
        name: "Guest's bedroom light"
        aliases:
          - "Guest's bedroom"

light:
  - platform: group
    name: "Guest bedroom lights"
    entities:
      - light.guest_bedroom

  - platform: switch
    name: "guest_bedroom"
    entity_id: "switch.guest_bedroom_light"

binary_sensor:
  - platform: template
    sensors:
      guest_bedroom_window:
        friendly_name: "Guest bedroom window"
        device_class: "window"
        value_template: "{{ is_state('sensor.guest_bedroom_window_sensor_access_control', '22') }}"
