homeassistant:
  customize:
    binary_sensor.kitchen_door:
      friendly_name: "Kitchen door"
      device_class: "door"
    binary_sensor.kitchen_door_lock_jammed:
      device_class: "problem"
      icon: "mdi:lock-alert"
    sensor.kitchen_door_lock_battery:
      baterry_type: "AA (4)"
      battery_warning_level: 40
    sensor.kitchen_door_sensor_battery:
      battery_type: "Sensative Strip"
      battery_warning_level: 20
    sensor.kitchen_temperature:
      friendly_name: "Kitchen temperature"

cloud:
  google_actions:
    filter:
      include_entities:
        - "lock.kitchen_door"
        - "light.kitchen_track"
        - "light.kitchen_sink"

light:
  - platform: group
    unique_id: "kitchen_lights"
    name: "Kitchen lights"
    entities:
      - light.kitchen_track
      - light.kitchen_sink

template:
  - sensor:
      - unique_id: "sensor.kitchen_temperature"
        name: "kitchen_temperature"
        device_class: "temperature"
        unit_of_measurement: "°C"
        # Living room and Kitchen thermostat are the same
        state: "{{ states('sensor.living_room_thermostat_temperature') | float(0) | round(1) }}"
        availability: "{{ not is_state('sensor.living_room_thermostat_temperature', 'unavailable') }}"
        attributes:
          heating: "{{ is_state_attr('climate.living_room_thermostat', 'hvac_action', 'heating') }}"

automation:
  - id: "ab8460a3-e7b3-4cef-989e-11a65da297f9"
    alias: "kitchen_track_dimmer_zwave_scenes"
    use_blueprint:
      path: "zwave/paddle_scenes.yaml"
      input:
        on_entity_id: "event.kitchen_track_light_dimmer_on_pressed"
        off_entity_id: "event.kitchen_track_light_dimmer_off_pressed"
        favorite_entity_id: "event.kitchen_track_light_dimmer_favorite_pressed"

        tap_favorite:
          - service: "light.toggle"
            target:
              entity_id: "light.kitchen_sink"

        tap_on_2x:
          - service: "light.turn_on"
            data:
              entity_id: "light.kitchen_lights"
        tap_off_2x:
          - service: "light.turn_off"
            data:
              entity_id: "light.kitchen_lights"

  - id: "3353147e-584b-4a98-8a1f-6a46bda78960"
    alias: "kitchen_sink_light_switch_zwave_scenes"
    use_blueprint:
      path: "zwave/paddle_scenes.yaml"
      input:
        on_entity_id: "event.kitchen_sink_light_switch_on_pressed"
        off_entity_id: "event.kitchen_sink_light_switch_off_pressed"

        tap_on_2x:
          - service: "light.turn_on"
            data:
              entity_id: "light.kitchen_track"
        tap_off_2x:
          - service: "light.turn_off"
            data:
              entity_id: "light.kitchen_track"
