homeassistant:
  customize:
    binary_sensor.kitchen_door:
      friendly_name: "Kitchen door"
      device_class: "door"
    binary_sensor.kitchen_door_lock_jammed:
      device_class: "problem"
      icon: "mdi:lock-alert"
    sensor.kitchen_door_lock_battery:
      baterry_type: "AA (4)"
      battery_warning_level: 40
    sensor.kitchen_door_sensor_battery:
      battery_type: "Sensative Strip"
      battery_warning_level: 20
    sensor.kitchen_sink_leak_sensor_battery:
      battery_type: "ER14250 3.6V"
      battery_warning_level: 25
    sensor.kitchen_temperature:
      friendly_name: "Kitchen temperature"
    light.kitchen:
      friendly_name: "Kitchen light"
    light.kitchen_sink:
      friendly_name: "Kitchen sink light"

cloud:
  google_actions:
    filter:
      include_entities:
        - "light.kitchen"
    entity_config:
      light.kitchen:
        room: "Kitchen"
        name: "Kitchen light"
        aliases:
          - "Kitchen"
      light.kitchen_sink:
        room: "Kitchen"
        name: "Kitchen sink light"
        aliases:
          - "Kitchen sink"

light:
  - platform: group
    name: "Kitchen lights"
    entities:
      - light.kitchen
      - light.kitchen_sink
  - platform: switch
    name: kitchen
    entity_id: "switch.kitchen_light"
  - platform: switch
    name: kitchen_sink
    entity_id: "switch.kitchen_sink_light"

template:
  sensor:
    - unique_id: "sensor.kitchen_temperature"
      name: "kitchen_temperature"
      device_class: "temperature"
      unit_of_measurement: "°C"
      # Living room and Kitchen thermostat are the same
      state: "{{ states('sensor.living_room_thermostat_temperature') | round(1) }}"
      attributes:
        heating: "{{ is_state_attr('climate.living_room_thermostat', 'hvac_action', 'heating') }}"

automation:
  - id: "ab8460a3-e7b3-4cef-989e-11a65da297f9"
    alias: "kitchen_light_switch_zwave_scenes"
    use_blueprint:
      path: "zwave/homeseer_100_series_scene_control.yaml"
      input:
        node_id: 3

        tap_on_2x:
          - service: light.turn_on
            data:
              entity_id: "light.kitchen_sink"
        tap_off_2x:
          - service: light.turn_off
            data:
              entity_id: "light.kitchen_sink"

        tap_on_3x:
          - service: light.turn_on
            data:
              entity_id: "light.kitchen_lights"
        tap_off_3x:
          - service: light.turn_off
            data:
              entity_id: "light.kitchen_lights"

  - id: "3353147e-584b-4a98-8a1f-6a46bda78960"
    alias: "kitchen_sink_light_switch_zwave_scenes"
    use_blueprint:
      path: "zwave/inovelli_nzw_scene_control.yaml"
      input:
        node_id: 50

        tap_on_2x:
          - service: light.turn_on
            data:
              entity_id: "light.kitchen"
        tap_off_2x:
          - service: light.turn_off
            data:
              entity_id: "light.kitchen"

        tap_on_3x:
          - service: light.turn_on
            data:
              entity_id: "light.kitchen_lights"
        tap_off_3x:
          - service: light.turn_off
            data:
              entity_id: "light.kitchen_lights"
