homeassistant:
  customize:
    binary_sensor.kitchen_door:
      friendly_name: "Kitchen door"
      device_class: "door"
    sensor.kitchen_door_sensor_battery:
      battery_type: "Sensative Strip"
      battery_warning_level: 20
    sensor.kitchen_sink_leak_sensor_battery:
      battery_type: "ER14250 3.6V"
      battery_warning_level: 25
    light.kitchen:
      friendly_name: "Kitchen light"
    light.kitchen_sink:
      friendly_name: "Kitchen sink light"

cloud:
  google_actions:
    filter:
      include_entities:
        - "light.kitchen"
    entity_config:
      light.kitchen:
        room: "Kitchen"
        name: "Kitchen light"
        aliases:
          - "Kitchen"
      light.kitchen_sink:
        room: "Kitchen"
        name: "Kitchen sink light"
        aliases:
          - "Kitchen sink"

light:
  - platform: group
    name: "Kitchen lights"
    entities:
      - light.kitchen
      - light.kitchen_sink
  - platform: switch
    name: kitchen
    entity_id: "switch.kitchen_light"
  - platform: switch
    name: kitchen_sink
    entity_id: "switch.kitchen_sink_light"

binary_sensor:
  - platform: template
    sensors:
      kitchen_sink_leak:
        unique_id: "binary_sensor.kitchen_sink_leak"
        friendly_name: "Kitchen sink leak"
        device_class: "moisture"
        value_template: "{{ is_state('sensor.kitchen_sink_leak_sensor_flood', '2') }}"

sensor:
  - platform: template
    sensors:
      kitchen_temperature:
        unique_id: "sensor.kitchen_temperature"
        friendly_name: "Kitchen temperature"
        device_class: "temperature"
        unit_of_measurement: "°C"
        # Living room and Kitchen thermostat are the same
        value_template: "{{ states('sensor.living_room_thermostat_temperature') | round(1) }}"

automation:
  - alias: "kitchen_double_tap"
    initial_state: true
    mode: "queued"
    variables:
      entity_id: "light.kitchen_sink"
    trigger:
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.kitchen_light_switch"
          scene_data: 7860
    action:
      - choose:
          - conditions: "{{ trigger.event.data.scene_id | int == 1 }}"
            sequence:
              - service: light.turn_on
                data:
                  entity_id: "{{ entity_id }}"
          - conditions: "{{ trigger.event.data.scene_id | int == 2 }}"
            sequence:
              - service: light.turn_off
                data:
                  entity_id: "{{ entity_id }}"

  - alias: "kitchen_triple_tap"
    initial_state: true
    mode: "queued"
    variables:
      entity_id: "light.kitchen_lights"
    trigger:
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.kitchen_light_switch"
          scene_data: 7920
    action:
      - choose:
          - conditions: "{{ trigger.event.data.scene_id | int == 1 }}"
            sequence:
              - service: light.turn_on
                data:
                  entity_id: "{{ entity_id }}"
          - conditions: "{{ trigger.event.data.scene_id | int == 2 }}"
            sequence:
              - service: light.turn_off
                data:
                  entity_id: "{{ entity_id }}"

  - alias: "kitchen_sink_double_tap"
    initial_state: true
    mode: "queued"
    variables:
      entity_id: "light.kitchen"
    trigger:
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.kitchen_sink_light_switch"
          scene_data: 3
    action:
      - choose:
          - conditions: "{{ trigger.event.data.scene_id | int == 2 }}"
            sequence:
              - service: light.turn_on
                data:
                  entity_id: "{{ entity_id }}"
          - conditions: "{{ trigger.event.data.scene_id | int == 1 }}"
            sequence:
              - service: light.turn_off
                data:
                  entity_id: "{{ entity_id }}"

  - alias: "kitchen_sink_triple_tap"
    initial_state: true
    mode: "queued"
    variables:
      entity_id: "light.kitchen_lights"
    trigger:
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.kitchen_sink_light_switch"
          scene_data: 4
    action:
      - choose:
          - conditions: "{{ trigger.event.data.scene_id | int == 2 }}"
            sequence:
              - service: light.turn_on
                data:
                  entity_id: "{{ entity_id }}"
          - conditions: "{{ trigger.event.data.scene_id | int == 1 }}"
            sequence:
              - service: light.turn_off
                data:
                  entity_id: "{{ entity_id }}"
