homeassistant:
  customize:
    binary_sensor.kitchen_door:
      friendly_name: "Kitchen door"
      device_class: "door"
    sensor.kitchen_door_sensor_battery:
      battery_type: "Sensative Strip"
      battery_warning_level: 20
    sensor.kitchen_sink_leak_sensor_battery:
      battery_type: "ER14250 3.6V"
      battery_warning_level: 25
    light.kitchen:
      friendly_name: "Kitchen light"

cloud:
  google_actions:
    filter:
      include_entities:
        - "light.kitchen"
    entity_config:
      light.kitchen:
        room: "Kitchen"
        name: "Kitchen light"
        aliases:
          - "Kitchen"

light:
  - platform: group
    name: "Kitchen lights"
    entities:
      - light.kitchen
  - platform: switch
    name: kitchen
    entity_id: "switch.kitchen_light"

binary_sensor:
  - platform: template
    sensors:
      kitchen_sink_leak:
        friendly_name: "Kitchen sink leak"
        device_class: "moisture"
        value_template: "{{ is_state('sensor.kitchen_sink_leak_sensor_flood', '2') }}"

sensor:
  - platform: template
    sensors:
      kitchen_temperature:
        friendly_name: "Kitchen temperature"
        device_class: "temperature"
        unit_of_measurement: "°C"
        # Living room and Kitchen thermostat are the same
        value_template: "{{ states('sensor.living_room_thermostat_temperature') | round(1) }}"
