homeassistant:
  customize:
    binary_sensor.washing_machine_leak:
      device_class: "moisture"
    sensor.laundry_room_temperature:
      friendly_name: "Laundry room temperature"

cloud:
  google_actions:
    filter:
      include_entities:
        - "light.laundry_room"
    entity_config:
      light.laundry_room:
        room: "Laundry room"
        name: "Laundry room light"
        aliases:
          - "Laundry room"

sensor:
  - platform: min_max
    name: "laundry_room_temperature"
    type: "mean"
    round_digits: 1
    entity_ids:
      - "sensor.basement_hallway_thermostat_temperature"
      - "sensor.washing_machine_leak_temperature"

light:
  - platform: group
    name: "Laundry room lights"
    entities:
      - light.laundry_room

automation:
  - id: "e78350bc-d991-4fab-8c9a-658c242e60ab"
    alias: "laundry_room_auto_lights"
    use_blueprint:
      path: "presence_light.yaml"
      input:
        light_entity: "light.laundry_room"
        light_off_entity: "light.laundry_room_lights"
        presence_entity: "binary_sensor.laundry_room_motion"
