homeassistant:
  customize:
    binary_sensor.washing_machine_leak:
      device_class: "moisture"
    light.laundry_room:
      friendly_name: "Laundry room light"
    sensor.laundry_room_temperature:
      friendly_name: "Laundry room temperature"

cloud:
  google_actions:
    filter:
      include_entities:
        - "light.laundry_room"
    entity_config:
      light.laundry_room:
        room: "Laundry room"
        name: "Laundry room light"
        aliases:
          - "Laundry room"

binary_sensor:
  - platform: template
    sensors:
      laundry_room_motion:
        unique_id: "binary_sensor.laundry_room_motion"
        friendly_name: "Laundry room motion"
        device_class: "motion"
        value_template: "{{ is_state('sensor.laundry_motion_sensor_burglar', '8') }}"

sensor:
  - platform: min_max
    name: "laundry_room_temperature"
    type: "mean"
    round_digits: 1
    entity_ids:
      - "sensor.basement_hallway_thermostat_temperature"
      - "sensor.washing_machine_leak_temperature"

light:
  - platform: group
    name: "Laundry room lights"
    entities:
      - light.laundry_room

  - platform: switch
    name: laundry_room
    entity_id: "switch.laundry_room_light"

automation:
  - alias: "laundry_room_auto_lights"
    initial_state: true
    mode: "restart"

    trigger:
      - platform: state
        entity_id: &motion_entity "binary_sensor.laundry_room_motion"
        to: "on"

    action:
      - service: light.turn_on
        data:
          entity_id: "light.laundry_room"

      - wait_for_trigger:
          - platform: state
            entity_id: *motion_entity
            to: "off"
            for: 120

      - service: light.turn_off
        data:
          entity_id: "light.laundry_room_lights"
