homeassistant:
  customize:
    sensor.laundry_room_temperature:
      friendly_name: "Laundry temperature"

cloud:
  google_actions:
    filter:
      include_entities:
        - "light.laundry_room"

light:
  - platform: group
    unique_id: "laundry_lights"
    name: "Laundry lights"
    entities:
      - "light.laundry_room"

template:
  - sensor:
      - unique_id: "sensor.laundry_room_temperature"
        name: "laundry_room_temperature"
        device_class: "temperature"
        unit_of_measurement: "°C"
        state: >
          {%
            set temperatures = [
              'sensor.basement_hallway_thermostat_temperature',
              'sensor.washing_machine_leak_temperature',
            ]
              | map('states')
              | reject('==', 'unavailable')
              | map('float')
              | list
          %}
          {% set count = temperatures | length %}
          {{ iif(count == 0, 'unavailable', (temperatures | sum / count) | round(1)) }}
        availability: >
          {{
            not is_state('sensor.basement_hallway_thermostat_temperature', 'unavailable')
              or not is_state('sensor.washing_machine_leak_temperature', 'unavailable')
          }}
        attributes:
          heating: "{{ is_state_attr('climate.basement_hallway_thermostat', 'hvac_action', 'heating') }}"

automation:
  - id: "e78350bc-d991-4fab-8c9a-658c242e60ab"
    alias: "laundry_room_auto_lights"
    use_blueprint:
      path: "presence_light.yaml"
      input:
        light_entity: "light.laundry_room"
        light_off_entity: "light.laundry_lights"
        presence_entity: "binary_sensor.laundry_room_motion"
