homeassistant:
  customize:
    sensor.living_room_door_sensor_battery:
      battery_type: "Sensative Strip"
    light.living_room_ambiance:
      friendly_name: "Living room ambiance"
    light.bookshelf:
      friendly_name: "Bookshelf light"

google_assistant:
  entity_config:
    light.living_room_ambiance:
      expose: True
      room: "Living room"
      name: "Ambiance"
      aliases:
        - "Living room light"
        - "Living room"
    light.bookshelf:
      expose: True
      room: "Living room"
      aliases:
        - "Bookshelf light"
        - "Bookshelf"
    switch.bookshelf_outlet:
      expose: True
      room: "Living room"
      aliases:
        - "Bookshelf outlet"
        - "Christmas tree"
        - "Xmas tree"

cast:
  media_player:
    - host: !secret media_player_home_lr_host

roku:
  - host: !secret media_player_roku_lr_host

switch:
  - platform: command_line
    switches:
      living_room_tv_power:
        friendly_name: "Living room TV"
        command_on: |
          curl -sSX POST http://$(getent hosts tv-lr.devices.local | awk '{ print $1 ; exit }'):8060/keypress/PowerOn
        command_off: |
          curl -sSX POST http://$(getent hosts tv-lr.devices.local | awk '{ print $1 ; exit }'):8060/keypress/PowerOff
        command_state: |
          curl -sSX GET http://$(getent hosts tv-lr.devices.local | awk '{ print $1 ; exit }'):8060/query/device-info \
            | grep power-mode \
            | sed -e "s:\\s*<power-mode>PowerOn</power-mode>:ON:"
        value_template: '{{ value == "ON" }}'

light:
  - platform: group
    name: "Living room lights"
    entities:
      - light.living_room_ambiance
      - light.bookshelf

  - platform: switch
    name: living_room_ambiance
    entity_id: "switch.living_room_ambiance"

  - platform: switch
    name: bookshelf
    entity_id: "switch.bookshelf_light"

binary_sensor:
  - platform: template
    sensors:
      living_room_door:
        friendly_name: "Living room door"
        device_class: "door"
        value_template: "{{ is_state('sensor.living_room_door_sensor_access_control', '22') }}"

sensor:
  - platform: template
    sensors:
      living_room_door_sensor_battery:
        friendly_name: "Living room door sensor battery"
        device_class: "battery"
        unit_of_measurement: "%"
        value_template: "{{ state_attr('zwave.living_room_door_sensor', 'battery_level') | int('unknown') }}"

automation:
  - alias: "double_up_bookshelf"
    hide_entity: True
    initial_state: True
    trigger:
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.bookshelf_light_switch"
          scene_id: 1
          scene_data: 7860
    action:
      service: light.turn_on
      data:
        entity_id: "light.living_room_ambiance"
  - alias: "double_down_bookshelf"
    hide_entity: True
    initial_state: True
    trigger:
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.bookshelf_light_switch"
          scene_id: 2
          scene_data: 7860
    action:
      service: light.turn_off
      data:
        entity_id: "light.living_room_ambiance"
