homeassistant:
  customize:
    binary_sensor.living_room_door:
      friendly_name: "Living room door"
      device_class: "door"
    light.living_room_ambiance:
      friendly_name: "Living room lamp"
    light.bookshelf:
      friendly_name: "Bookshelf light"
    sensor.living_room_door_sensor_battery:
      battery_type: "Sensative Strip"
      battery_warning_level: 20
    sensor.living_room_remote_battery:
      battery_type: "CR2032"
      battery_warning_level: 25
    sensor.living_room_temperature:
      friendly_name: "Living room temperature"

cloud:
  google_actions:
    filter:
      include_entities:
        - "light.bookshelf"
        - "light.foyer"
        - "light.living_room"
        - "light.living_room_ambiance"
        - "light.staircase"
    entity_config:
      light.living_room_ambiance:
        aliases:
          - "Living room lamp"
      light.living_room:
        aliases:
          - "Living room spots"

input_number:
  living_room_thermostat_eco_setpoint:
    name: "Living room thermostat eco setpoint"
    <<: &setpoint_config
      unit_of_measurement: "°C"
      icon: "mdi:thermometer-lines"
      mode: "box"
      min: 8
      max: 25
      step: 0.5
  living_room_thermostat_comfort_setpoint:
    name: "Living room thermostat comfort setpoint"
    <<: *setpoint_config

input_select:
  living_room_thermostat_auto_mode:
    name: "Living room thermostat auto mode"
    icon: mdi:home-thermometer-outline
    options: ["Comfort", "Eco"]
  living_room_thermostat_mode:
    name: "Living room thermostat mode"
    icon: mdi:home-thermometer-outline
    options: ["Auto", "Manual"]

light:
  - platform: group
    unique_id: "living_room_lights"
    name: "Living room lights"
    entities:
      - "light.living_room"
      - "light.foyer"
      - "light.living_room_ambiance"
      - "light.bookshelf"

  - platform: switch
    name: living_room_ambiance
    entity_id: "switch.living_room_ambiance_light"

  - platform: switch
    name: bookshelf
    entity_id: "switch.bookshelf_light"

template:
  - sensor:
      - unique_id: "sensor.living_room_temperature"
        name: "living_room_temperature"
        device_class: "temperature"
        unit_of_measurement: "°C"
        state: "{{ states('sensor.living_room_thermostat_temperature') | float(0) | round(1) }}"
        availability: "{{ not is_state('sensor.living_room_thermostat_temperature', 'unavailable') }}"
        attributes:
          heating: "{{ is_state_attr('climate.living_room_thermostat', 'hvac_action', 'heating') }}"

automation:
  - id: "automation.living_room_remote"
    alias: "living_room_remote_zwave_scenes"
    use_blueprint:
      path: "zwave/paddle_scenes.yaml"
      input:
        on_entity_id: "event.living_room_remote_top_pressed"
        off_entity_id: "event.living_room_remote_bottom_pressed"

        tap_on_1x:
          - service: light.toggle
            data:
              entity_id: "light.living_room_ambiance"
        tap_on_2x:
          - service: light.turn_off
            data:
              entity_id:
                - "light.bookshelf"
                - "light.foyer"
                - "light.living_room"
                - "light.dining_room_lights"
                - "light.kitchen_lights"

        tap_off_1x:
          - service: remote.toggle
            data:
              entity_id: "remote.living_room_tv"
        tap_off_2x:
          - service: media_player.select_source
            data:
              entity_id: "media_player.living_room_tv"
              source: "Jellyfin"
        tap_off_3x:
          - service: media_player.select_source
            data:
              entity_id: "media_player.living_room_tv"
              source: "Nintendo Switch"

  - id: "00a013b0-caf0-4046-b701-21975ffbfe3f"
    alias: "bookshelf_light_switch_zwave_scenes"
    use_blueprint:
      path: "zwave/paddle_scenes.yaml"
      input:
        on_entity_id: "event.bookshelf_light_switch_on_pressed"
        off_entity_id: "event.bookshelf_light_switch_off_pressed"

        tap_on_2x:
          - service: light.turn_on
            data:
              entity_id: "light.living_room_ambiance"
        tap_off_2x:
          - service: light.turn_off
            data:
              entity_id: "light.living_room_ambiance"

  - id: "38d50352-7c79-4dd5-aad7-c334af4bfd9f"
    alias: "staircase_light_dimmer_zwave_scenes"
    use_blueprint:
      path: "zwave/paddle_scenes.yaml"
      input:
        on_entity_id: "event.staircase_dimmer_on_pressed"
        off_entity_id: "event.staircase_dimmer_off_pressed"
        favorite_entity_id: "event.staircase_dimmer_favorite_pressed"

        tap_favorite:
          - service: light.toggle
            data:
              entity_id: "light.living_room_ambiance"

        tap_on_2x:
          - service: light.turn_on
            data:
              entity_id: "light.downstairs"
        tap_off_2x:
          - service: light.turn_off
            data:
              entity_id: "light.downstairs"

        tap_on_4x:
          - service: light.turn_on
            data:
              entity_id: "light.basement_lights"
        tap_off_4x:
          - service: light.turn_off
            data:
              entity_id: "light.basement_lights"
