homeassistant:
  customize:
    binary_sensor.living_room_door:
      friendly_name: "Living room door"
      device_class: "door"
    sensor.living_room_door_sensor_battery:
      battery_type: "Sensative Strip"
      battery_warning_level: 20
    light.living_room_ambiance:
      friendly_name: "Living room ambiance"
    light.bookshelf:
      friendly_name: "Bookshelf light"

cloud:
  google_actions:
    filter:
      include_entities:
        - "light.living_room_ambiance"
        - "light.bookshelf"
        - "switch.bookshelf_outlet"
    entity_config:
      light.living_room_ambiance:
        room: "Living room"
        name: "Ambiance"
        aliases:
          - "Living room light"
          - "Living room"
      light.bookshelf:
        room: "Living room"
        name: "Bookshelf light"
        aliases:
          - "Bookshelf"
      switch.bookshelf_outlet:
        room: "Living room"
        name: "Bookshelf outlet"
        aliases:
          - "Christmas tree"
          - "Xmas tree"

cast:
  media_player:
    - host: !secret media_player_home_lr_host

roku:
  - host: !secret media_player_roku_lr_host

switch:
  - platform: template
    switches:
      living_room_tv_power:
        friendly_name: "Living room TV"
        turn_on:
          service: "media_player.turn_on"
          data:
            entity_id: "media_player.living_room_tv"
        turn_off:
          service: "media_player.turn_off"
          data:
            entity_id: "media_player.living_room_tv"
        value_template: '{{ not is_state("media_player.living_room_tv", "standby") }}'

input_number:
  living_room_thermostat_eco_setpoint:
    name: "Living room thermostat eco setpoint"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer-lines"
    mode: "box"
    min: 8
    max: 18
    step: 0.5
  living_room_thermostat_comfort_setpoint:
    name: "Living room thermostat comfort setpoint"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer-lines"
    mode: "box"
    min: 15
    max: 25
    step: 0.5

input_select:
  living_room_thermostat_auto_mode:
    name: "Living room thermostat auto mode"
    icon: mdi:home-thermometer-outline
    options: ["Comfort", "Eco"]
  living_room_thermostat_mode:
    name: "Living room thermostat mode"
    icon: mdi:home-thermometer-outline
    options: ["Auto", "Manual"]

light:
  - platform: group
    name: "Living room lights"
    entities:
      - light.living_room_ambiance
      - light.bookshelf

  - platform: switch
    name: living_room_ambiance
    entity_id: "switch.living_room_ambiance"

  - platform: switch
    name: bookshelf
    entity_id: "switch.bookshelf_light"

sensor:
  - platform: template
    sensors:
      living_room_temperature:
        friendly_name: "Living room temperature"
        device_class: "temperature"
        unit_of_measurement: "°C"
        value_template: "{{ states('sensor.living_room_thermostat_temperature') | round(1) }}"

automation:
  - alias: "double_up_bookshelf"
    initial_state: true
    trigger:
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.bookshelf_light_switch"
          scene_id: 1
          scene_data: 7860
    action:
      service: light.turn_on
      data:
        entity_id: "light.living_room_ambiance"
  - alias: "double_down_bookshelf"
    initial_state: true
    trigger:
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.bookshelf_light_switch"
          scene_id: 2
          scene_data: 7860
    action:
      service: light.turn_off
      data:
        entity_id: "light.living_room_ambiance"
