homeassistant:
  customize:
    binary_sensor.living_room_door:
      friendly_name: "Living room door"
      device_class: "door"
    light.living_room_ambiance:
      friendly_name: "Living room ambiance"
    light.bookshelf:
      friendly_name: "Bookshelf light"
    sensor.living_room_door_sensor_battery:
      battery_type: "Sensative Strip"
      battery_warning_level: 20
    switch.bookshelf_outlet:
      friendly_name: "Bookshelf outlet"
    switch.living_room_ambiance:
      friendly_name: "Ambiance outlet"

cloud:
  google_actions:
    filter:
      include_entities:
        - "light.living_room_ambiance"
        - "light.bookshelf"
        - "switch.bookshelf_outlet"
    entity_config:
      light.living_room_ambiance:
        room: "Living room"
        name: "Ambiance"
        aliases:
          - "Living room light"
          - "Living room"
      light.bookshelf:
        room: "Living room"
        name: "Bookshelf light"
        aliases:
          - "Bookshelf"
      switch.bookshelf_outlet:
        room: "Living room"
        name: "Bookshelf outlet"
        aliases:
          - "Christmas tree"
          - "Xmas tree"

switch:
  - platform: broadlink
    mac: !secret broadlink_mac
    switches:
      - name: "living_room_ambiance"
        command_on: "svAyABMHBhMTBwYTBhMHExMHBxMTBwYTEwcHExMHBxMTBwYTBxMTBxMHBxMHExMHEwcGvwYTAAAA"
        command_off: "ssoyAAYUEggGFBIIBhQGFAYUEggGFRIIBhQSCAYUEggGFBMHBhQGFBIIEggTCBIIBhQGFAbAAAAA"
      - name: "bookshelf_outlet"
        command_on: "sggyAAYUEggGFBMIBhQGFAYUEgcGFBIIBhQSCAYUEggGFBIIEwcSCAYUBhQGFAcUEggSCAa/AAAA"
        command_off: "sgkyAAYUEgcGFBIHBhQGFAYUEgcGFBIHBhQSCAYUEggGFBIHEggSCAYUBhQSBxMHBhQGFAa/AAAA"

input_number:
  living_room_thermostat_eco_setpoint:
    name: "Living room thermostat eco setpoint"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer-lines"
    mode: "box"
    min: 8
    max: 18
    step: 0.5
  living_room_thermostat_comfort_setpoint:
    name: "Living room thermostat comfort setpoint"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer-lines"
    mode: "box"
    min: 15
    max: 25
    step: 0.5

input_select:
  living_room_thermostat_auto_mode:
    name: "Living room thermostat auto mode"
    icon: mdi:home-thermometer-outline
    options: ["Comfort", "Eco"]
  living_room_thermostat_mode:
    name: "Living room thermostat mode"
    icon: mdi:home-thermometer-outline
    options: ["Auto", "Manual"]

light:
  - platform: group
    name: "Living room lights"
    entities:
      - light.living_room_ambiance
      - light.bookshelf

  - platform: switch
    name: living_room_ambiance
    entity_id: "switch.living_room_ambiance"

  - platform: switch
    name: bookshelf
    entity_id: "switch.bookshelf_light"

sensor:
  - platform: template
    sensors:
      living_room_temperature:
        unique_id: "sensor.living_room_temperature"
        friendly_name: "Living room temperature"
        device_class: "temperature"
        unit_of_measurement: "°C"
        value_template: "{{ states('sensor.living_room_thermostat_temperature') | round(1) }}"

automation:
  - alias: "bookshelf_light_switch_zwave_scenes"
    use_blueprint:
      path: "zwave/homeseer_ws200+_scene_control.yaml"
      input:
        zwave_entity: "zwave.bookshelf_light_switch"

        <<: &tap_2x
          tap_on_2x:
            - service: light.turn_on
              data:
                entity_id: "light.living_room_ambiance"
          tap_off_2x:
            - service: light.turn_off
              data:
                entity_id: "light.living_room_ambiance"

        tap_on_3x:
          - service: light.turn_on
            data:
              entity_id: "light.staircase"
        tap_off_3x:
          - service: light.turn_off
            data:
              entity_id: "light.staircase"

  - alias: "staircase_light_dimmer_zwave_scenes"
    use_blueprint:
      path: "zwave/homeseer_ws200+_scene_control.yaml"
      input:
        zwave_entity: "zwave.staircase_light_dimmer"

        <<: *tap_2x

        tap_on_3x:
          - service: light.turn_on
            data:
              entity_id: "light.downstairs"
        tap_off_3x:
          - service: light.turn_off
            data:
              entity_id: "light.downstairs"
