homeassistant:
  customize:
    binary_sensor.lounge_window:
      friendly_name: "Lounge window"
      device_class: "window"
    sensor.lounge_window_sensor_battery:
      battery_type: "Sensative Strip"
      battery_warning_level: 20
    sensor.lounge_temperature:
      friendly_name: "Lounge temperature"
    switch.lounge_tv:
      friendly_name: "Lounge TV"

cloud:
  google_actions:
    filter:
      include_entities:
        - "switch.lounge_tv"
        - "light.lounge"
        - "light.lounge_ambiance"

input_number:
  lounge_thermostat_eco_setpoint:
    name: "Lounge thermostat eco setpoint"
    <<: &setpoint_config
      unit_of_measurement: "°C"
      icon: "mdi:thermometer-lines"
      mode: "box"
      min: 8
      max: 25
      step: 0.5
  lounge_thermostat_comfort_setpoint:
    name: "Lounge thermostat comfort setpoint"
    <<: *setpoint_config

input_select:
  lounge_thermostat_auto_mode:
    name: "Lounge thermostat auto mode"
    icon: mdi:home-thermometer-outline
    options: ["Comfort", "Eco"]
  lounge_thermostat_mode:
    name: "Lounge thermostat mode"
    icon: mdi:home-thermometer-outline
    options: ["Auto", "Manual"]

light:
  - platform: group
    unique_id: "lounge_lights"
    name: "Lounge lights"
    entities:
      - light.lounge
      - light.lounge_ambiance

template:
  - sensor:
      - unique_id: "sensor.lounge_temperature"
        name: "lounge_temperature"
        device_class: "temperature"
        unit_of_measurement: "°C"
        state: "{{ states('sensor.lounge_thermostat_temperature') | float(0) | round(1) }}"
        availability: "{{ not is_state('sensor.lounge_thermostat_temperature', 'unavailable') }}"
        attributes:
          heating: "{{ is_state_attr('climate.lounge_thermostat', 'hvac_action', 'heating') }}"

automation:
  - id: "75e713fa-34ef-400f-afb0-1f88c6811aa8"
    alias: "lounge_light_dimmer_zwave_scenes"
    use_blueprint:
      path: "zwave/paddle_scenes.yaml"
      input:
        on_entity_id: "event.lounge_dimmer_on_pressed"
        off_entity_id: "event.lounge_dimmer_off_pressed"
        favorite_entity_id: "event.lounge_dimmer_favorite_pressed"

        tap_favorite:
          - service: light.toggle
            data:
              entity_id: "light.lounge_ambiance"
