homeassistant:
  customize:
    sensor.lounge_window_sensor_battery:
      battery_type: "Sensative Strip"

cloud:
  google_actions:
    filter:
      include_entities:
        - "switch.lounge_tv"
        - "light.lounge"
        - "light.lounge_ambiance"
    entity_config:
      switch.lounge_tv:
        room: "Lounge"
        name: "Lounge TV"
      light.lounge:
        room: "Lounge"
        name: "Lounge spots"
        aliases:
          - "Lounge light"
          - "Lounge"
      light.lounge_ambiance:
        room: "Lounge"
        name: "Lounge ambiance"
        aliases:
          - "Lounge ambiance light"

cast:
  media_player:
    - host: !secret media_player_cast_lounge_host
    - host: !secret media_player_home_lounge_host

input_number:
  lounge_thermostat_eco_setpoint:
    name: "Lounge thermostat eco setpoint"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer-lines"
    mode: "box"
    min: 8
    max: 18
    step: 0.5
  lounge_thermostat_comfort_setpoint:
    name: "Lounge thermostat comfort setpoint"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer-lines"
    mode: "box"
    min: 15
    max: 25
    step: 0.5

input_select:
  lounge_thermostat_mode:
    name: "Lounge thermostat mode"
    icon: mdi:home-thermometer-outline
    options: ["Comfort", "Eco", "Manual"]

light:
  - platform: group
    name: "Lounge lights"
    entities:
      - light.lounge
      - light.lounge_ambiance

binary_sensor:
  - platform: template
    sensors:
      lounge_window:
        friendly_name: "Lounge window"
        device_class: "window"
        value_template: "{{ is_state('sensor.lounge_window_sensor_access_control', '22') }}"

sensor:
  - platform: template
    sensors:
      lounge_temperature:
        friendly_name: "Lounge temperature"
        device_class: "temperature"
        unit_of_measurement: "°C"
        value_template: "{{ states('sensor.lounge_thermostat_temperature') | round(1) }}"

automation:
  - alias: "lounge_update_setpoint"
    hide_entity: True
    initial_state: True
    trigger:
      - platform: state
        entity_id: "input_select.lounge_thermostat_mode"
    condition:
      - condition: template
        value_template: |
          {{ (trigger.from_state is none or trigger.from_state.state != trigger.to_state.state)
            and not trigger.to_state.state == 'Manual' }}
    action:
      - service: "climate.set_temperature"
        data_template:
          entity_id: "climate.lounge_thermostat"
          temperature: "{{ states('input_number.lounge_thermostat_' + (states('input_select.lounge_thermostat_mode') | lower) + '_setpoint') }}"

  - alias: "lounge_update_thermostat_mode"
    hide_entity: True
    initial_state: True
    trigger:
      - platform: state
        entity_id: "climate.lounge_thermostat"
    condition:
      - condition: template
        value_template: |
          {{ (trigger.from_state is none or trigger.from_state.attributes.temperature != trigger.to_state.attributes.temperature)
            and trigger.to_state.attributes.preset_mode == 'none' }}
    action:
      - service: "input_select.select_option"
        data_template:
          entity_id: "input_select.lounge_thermostat_mode"
          option: |
            {% set ns = namespace(mode='Manual', found=False) -%}
            {% for mode in state_attr('input_select.lounge_thermostat_mode', 'options') -%}
            {% if not ns.found and trigger.to_state.attributes.temperature | float == states('input_number.lounge_thermostat_' + (mode | lower) + '_setpoint') | float -%}
            {% set ns.mode = mode -%}
            {% set ns.found = True %}
            {%- endif %}
            {%- endfor -%}
            {{ ns.mode }}

  - alias: "double_up_lounge"
    hide_entity: True
    initial_state: True
    trigger:
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.lounge_light_dimmer"
          scene_id: 1
          scene_data: 7860
    action:
      service: light.turn_on
      data:
        entity_id: "light.lounge_ambiance"
  - alias: "double_down_lounge"
    hide_entity: True
    initial_state: True
    trigger:
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.lounge_light_dimmer"
          scene_id: 2
          scene_data: 7860
    action:
      service: light.turn_off
      data:
        entity_id: "light.lounge_ambiance"
