homeassistant:
  customize:
    binary_sensor.lounge_window:
      friendly_name: "Lounge window"
      device_class: "window"
    sensor.lounge_window_sensor_battery:
      battery_type: "Sensative Strip"
      battery_warning_level: 20

cloud:
  google_actions:
    filter:
      include_entities:
        - "switch.lounge_tv"
        - "light.lounge"
        - "light.lounge_ambiance"
    entity_config:
      switch.lounge_tv:
        room: "Lounge"
        name: "Lounge TV"
      light.lounge:
        room: "Lounge"
        name: "Lounge spots"
        aliases:
          - "Lounge light"
          - "Lounge"
      light.lounge_ambiance:
        room: "Lounge"
        name: "Lounge ambiance"
        aliases:
          - "Lounge ambiance light"

input_number:
  lounge_thermostat_eco_setpoint:
    name: "Lounge thermostat eco setpoint"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer-lines"
    mode: "box"
    min: 8
    max: 18
    step: 0.5
  lounge_thermostat_comfort_setpoint:
    name: "Lounge thermostat comfort setpoint"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer-lines"
    mode: "box"
    min: 15
    max: 25
    step: 0.5

input_select:
  lounge_thermostat_auto_mode:
    name: "Lounge thermostat auto mode"
    icon: mdi:home-thermometer-outline
    options: ["Comfort", "Eco"]
  lounge_thermostat_mode:
    name: "Lounge thermostat mode"
    icon: mdi:home-thermometer-outline
    options: ["Auto", "Manual"]

light:
  - platform: group
    name: "Lounge lights"
    entities:
      - light.lounge
      - light.lounge_ambiance

sensor:
  - platform: template
    sensors:
      lounge_temperature:
        friendly_name: "Lounge temperature"
        device_class: "temperature"
        unit_of_measurement: "°C"
        value_template: "{{ states('sensor.lounge_thermostat_temperature') | round(1) }}"

automation:
  - alias: "double_up_lounge"
    initial_state: true
    trigger:
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.lounge_light_dimmer"
          scene_id: 1
          scene_data: 7860
    action:
      service: light.turn_on
      data:
        entity_id: "light.lounge_ambiance"
  - alias: "double_down_lounge"
    initial_state: true
    trigger:
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.lounge_light_dimmer"
          scene_id: 2
          scene_data: 7860
    action:
      service: light.turn_off
      data:
        entity_id: "light.lounge_ambiance"
