homeassistant:
  customize:
    binary_sensor.lounge_window:
      friendly_name: "Lounge window"
      device_class: "window"
    sensor.lounge_window_sensor_battery:
      battery_type: "Sensative Strip"
      battery_warning_level: 20
    switch.lounge_tv:
      friendly_name: "Living room TV"

cloud:
  google_actions:
    filter:
      include_entities:
        - "switch.lounge_tv"
        - "light.lounge"
        - "light.lounge_ambiance"
    entity_config:
      switch.lounge_tv:
        room: "Lounge"
        name: "Lounge TV"
      light.lounge:
        room: "Lounge"
        name: "Lounge spots"
        aliases:
          - "Lounge light"
          - "Lounge"
      light.lounge_ambiance:
        room: "Lounge"
        name: "Lounge ambiance"
        aliases:
          - "Lounge ambiance light"

input_number:
  lounge_thermostat_eco_setpoint:
    name: "Lounge thermostat eco setpoint"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer-lines"
    mode: "box"
    min: 8
    max: 18
    step: 0.5
  lounge_thermostat_comfort_setpoint:
    name: "Lounge thermostat comfort setpoint"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer-lines"
    mode: "box"
    min: 15
    max: 25
    step: 0.5

input_select:
  lounge_thermostat_auto_mode:
    name: "Lounge thermostat auto mode"
    icon: mdi:home-thermometer-outline
    options: ["Comfort", "Eco"]
  lounge_thermostat_mode:
    name: "Lounge thermostat mode"
    icon: mdi:home-thermometer-outline
    options: ["Auto", "Manual"]

light:
  - platform: group
    name: "Lounge lights"
    entities:
      - light.lounge
      - light.lounge_ambiance

sensor:
  - platform: template
    sensors:
      lounge_temperature:
        unique_id: "sensor.lounge_temperature"
        friendly_name: "Lounge temperature"
        device_class: "temperature"
        unit_of_measurement: "°C"
        value_template: "{{ states('sensor.lounge_thermostat_temperature') | round(1) }}"

switch:
  - platform: broadlink
    mac: !secret broadlink_mac
    switches:
      - name: "lounge_tv"
        command_on: "JgBQAAABKJMTERQRFDUUERQRFBEUERQQFDYTNhQRFDUUNhM2FDYTNhQRFBEUEBQ2ExIUEBQRFBEUNRQ2EzYUERQ1FDYTNhQ2EwAFIwABKEgUAA0FAAAAAAAAAAA="
        command_off: "JgBYAAABKZITERQRFDUXDhUQFBEUEBUQFDYTNhUQFTQUNhQ1FTUUNRQRFBEUEBQ2FRESERQRFBEUNRQ2FDUUERQ1EzcUNRQ2FAAFIgABKEkUAAxPAAEoSBQADQU="

automation:
  - alias: "lounge_light_dimmer_zwave_scenes"
    use_blueprint:
      path: "zwave/inovelli_nzw30_scene_control.yaml"
      input:
        node_id: 54

        tap_on_2x:
          - service: light.turn_on
            data:
              entity_id: "light.lounge_ambiance"
        tap_off_2x:
          - service: light.turn_off
            data:
              entity_id: "light.lounge_ambiance"
