homeassistant:
  customize:
    sensor.main_bathroom_multisensor_battery:
      battery_type: "CR123A"
    light.main_bathroom_vanity:
      friendly_name: "Main bathroom vanity light"

google_assistant:
  entity_config:
    light.main_bathroom_spots:
      expose: True
      room: "Main bathroom spots"
      aliases:
        - "Bathroom spots"
        - "Bathroom light"
        - "Main bathroom light"
    light.main_bathroom_vanity:
      expose: True
      room: "Main bathroom"
      aliases:
        - "Vanity light"
        - "Vanity"
        - "Bathroom vanity light"
        - "Main bathroom vanity light"
    fan.main_bathroom:
      expose: True
      room: "Main bathroom"
      name: "Bathroom fan"
      aliases:
        - "Main bathroom fan"

binary_sensor:
  - platform: template
    sensors:
      main_bathroom_motion:
        friendly_name: "Main bathroom motion"
        device_class: "motion"
        value_template: "{{ is_state('sensor.main_bathroom_multisensor_burglar', '8') }}"
      main_bathroom_door:
        friendly_name: "Main bathroom door"
        device_class: "door"
        value_template: "{{ is_state('sensor.main_bathroom_door_sensor_access_control', '22') }}"

sensor:
  - platform: template
    sensors:
      main_bathroom_humidity:
        friendly_name: "Main bathroom humidity"
        device_class: "humidity"
        unit_of_measurement: "%"
        value_template: "{{ states('sensor.main_bathroom_multisensor_relative_humidity') | round }}"
      main_bathroom_temperature:
        friendly_name: "Main bathroom temperature"
        device_class: "temperature"
        unit_of_measurement: "°C"
        value_template: "{{ states('sensor.main_bathroom_multisensor_temperature') | round }}"
      main_bathroom_multisensor_battery:
        friendly_name: "Main bathroom multisensor battery"
        device_class: "battery"
        unit_of_measurement: "%"
        value_template: "{{ state_attr('zwave.main_bathroom_multisensor', 'battery_level') | int('unknown') }}"

fan:
  - platform: template
    fans:
      main_bathroom:
        friendly_name: "Main bathroom fan"
        value_template: "{{ states('switch.main_bathroom_fan') }}"
        speed_template: "Normal"
        speeds:
          - "Normal"
        turn_on:
          service: "switch.turn_on"
          data:
            entity_id: "switch.main_bathroom_fan"
        turn_off:
          service: "switch.turn_off"
          data:
            entity_id: "switch.main_bathroom_fan"

light:
  - platform: group
    name: "Main bathroom lights"
    entities:
      - light.main_bathroom_spots
      - light.main_bathroom_vanity

  - platform: switch
    name: main_bathroom_vanity
    entity_id: "switch.main_bathroom_vanity_light"

automation:
  # Automated fan management
  - alias: "main_bathroom_auto_fan_on"
    hide_entity: True
    initial_state: True
    trigger:
      - platform: numeric_state
        entity_id: "sensor.main_bathroom_humidity"
        above: &main_bathroom_fan_on_humidity 64 # Exclusive
      - platform: state
        entity_id: "fan.main_bathroom"
        to: "off"
        for: &main_bathroom_fan_manual_time
          minutes: 30
    condition:
      - condition: numeric_state
        entity_id: "sensor.main_bathroom_humidity"
        above: *main_bathroom_fan_on_humidity
    action:
      - service: fan.turn_on
        data:
          entity_id: "fan.main_bathroom"
  - alias: "main_bathroom_auto_fan_off"
    hide_entity: True
    initial_state: True
    trigger:
      - platform: numeric_state
        entity_id: "sensor.main_bathroom_humidity"
        below: &main_bathroom_fan_off_humidity 65 # Exclusive
      - platform: state
        entity_id: "fan.main_bathroom"
        to: "on"
        for: *main_bathroom_fan_manual_time
    condition:
      - condition: numeric_state
        entity_id: "sensor.main_bathroom_humidity"
        below: *main_bathroom_fan_off_humidity
    action:
      - service: fan.turn_off
        data:
          entity_id: "fan.main_bathroom"

  # Automated light management
  - alias: "main_bathroom_auto_lights_on"
    hide_entity: True
    initial_state: True
    trigger:
      - platform: state
        entity_id: "binary_sensor.main_bathroom_motion"
        to: "on"
    condition:
      - condition: state
        entity_id: "binary_sensor.main_bathroom_door"
        state: "on"
      - condition: state
        entity_id: "light.main_bathroom_lights"
        state: "off"
    action:
      - service: light.turn_on
        data_template:
          entity_id: "light.main_bathroom_spots"
          brightness_pct: >-
            {% set time = now().strftime('%H%M') | int %}
            {%- if time <= 600 -%} 5
            {%- elif time >= 900 and time <= 1800 -%} 85
            {%- else -%} 50
            {%- endif -%}
  - alias: "main_bathroom_auto_lights_off"
    hide_entity: True
    initial_state: True
    trigger:
      - platform: state
        entity_id: "binary_sensor.main_bathroom_motion"
        to: "off"
        for:
          minutes: 2
    condition:
      - condition: state
        entity_id: "binary_sensor.main_bathroom_door"
        state: "on"
    action:
      - service: light.turn_off
        data:
          entity_id: "light.main_bathroom_lights"

  # Double tap fan switch will turn fan on/off
  - alias: "main_bathroom_fan_double_up"
    hide_entity: True
    initial_state: True
    trigger:
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.main_bathroom_fan_switch"
          scene_id: 1
          scene_data: 7860
    action:
      service: switch.turn_on
      data:
        entity_id: "fan.main_bathroom"
  - alias: "main_bathroom_fan_double_down"
    hide_entity: True
    initial_state: True
    trigger:
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.main_bathroom_fan_switch"
          scene_id: 2
          scene_data: 7860
    action:
      service: fan.turn_off
      data:
        entity_id: "fan.main_bathroom"

  # Double tap vanity switch will turn vanity light on/off
  - alias: "main_bathroom_vanity_double_up"
    hide_entity: True
    initial_state: True
    trigger:
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.main_bathroom_vanity_light_switch"
          scene_id: 1
          scene_data: 7860
    action:
      service: light.turn_on
      data:
        entity_id: "light.main_bathroom_vanity"
  - alias: "main_bathroom_vanity_double_down"
    hide_entity: True
    initial_state: True
    trigger:
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.main_bathroom_vanity_light_switch"
          scene_id: 2
          scene_data: 7860
    action:
      service: light.turn_off
      data:
        entity_id: "light.main_bathroom_vanity"

  # Double tap spots switch will turn spots on/off
  - alias: "main_bathroom_spots_double_up"
    hide_entity: True
    initial_state: True
    trigger:
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.main_bathroom_light_dimmer"
          scene_id: 1
          scene_data: 7860
    action:
      service: light.turn_on
      data:
        entity_id: "light.main_bathroom_spots"
  - alias: "main_bathroom_spots_double_down"
    hide_entity: True
    initial_state: True
    trigger:
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.main_bathroom_light_dimmer"
          scene_id: 2
          scene_data: 7860
    action:
      service: light.turn_off
      data:
        entity_id: "light.main_bathroom_spots"

  # Triple tap any light switch will turn bathroom lights on/off
  - alias: "main_bathroom_lights_triple_up"
    hide_entity: True
    initial_state: True
    trigger:
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.main_bathroom_light_dimmer"
          scene_id: 1
          scene_data: 7920
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.main_bathroom_vanity_light_switch"
          scene_id: 1
          scene_data: 7920
    action:
      service: light.turn_on
      data:
        entity_id: "light.main_bathroom_lights"
  - alias: "main_bathroom_lights_triple_down"
    hide_entity: True
    initial_state: True
    trigger:
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.main_bathroom_light_dimmer"
          scene_id: 2
          scene_data: 7920
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.main_bathroom_vanity_light_switch"
          scene_id: 2
          scene_data: 7920
    action:
      service: light.turn_off
      data:
        entity_id: "light.main_bathroom_lights"
