homeassistant:
  customize:
    binary_sensor.main_bathroom_presence:
      friendly_name: "Main bathroom presence"
    sensor.main_bathroom_multisensor_battery:
      battery_type: "CR123A"
      battery_warning_level: 40
    sensor.main_bathroom_humidity:
      friendly_name: "Main bathroom humidity"
    sensor.main_bathroom_temperature:
      friendly_name: "Main bathroom temperature"

cloud:
  google_actions:
    filter:
      include_entities:
        - "light.main_bathroom_spots"
        - "light.main_bathroom_vanity"
        - "fan.main_bathroom"
    entity_config:
      light.main_bathroom_spots:
        aliases:
          - "Bathroom light"
          - "Main bathroom light"
      light.main_bathroom_vanity:
        aliases:
          - "Vanity light"
          - "Bathroom vanity light"
      fan.main_bathroom:
        aliases:
          - "Bathroom fan"

template:
  - binary_sensor:
      - unique_id: "binary_sensor.main_bathroom_presence"
        name: "main_bathroom_presence"
        device_class: "presence"
        state: >-
          {{
            is_state('binary_sensor.main_bathroom_motion', 'on')
          }}
        delay_off: 15

    sensor:
      - unique_id: "sensor.main_bathroom_humidity"
        name: "main_bathroom_humidity"
        device_class: "humidity"
        unit_of_measurement: "%"
        state: "{{ states('sensor.main_bathroom_multisensor_relative_humidity') | int(0) | round }}"
        availability: "{{ not is_state('sensor.main_bathroom_multisensor_relative_humidity', 'unavailable') }}"

      - unique_id: "sensor.main_bathroom_temperature"
        name: "main_bathroom_temperature"
        device_class: "temperature"
        unit_of_measurement: "°C"
        state: "{{ states('sensor.main_bathroom_multisensor_temperature') | int(0) | round(1) }}"
        availability: "{{ not is_state('sensor.main_bathroom_multisensor_temperature', 'unavailable') }}"
        attributes:
          heating: false

light:
  - platform: group
    unique_id: "main_bathroom_lights"
    name: "Main bathroom lights"
    entities:
      - light.main_bathroom_spots
      - light.main_bathroom_vanity

automation:
  - id: "8a017369-65d4-4e9b-87dc-0f172fc44594"
    alias: "main_bathroom_auto_fan"
    use_blueprint:
      path: "exhaust_fan.yaml"
      input:
        fan_entity: "fan.main_bathroom"
        humidity_entity: "sensor.main_bathroom_humidity"

  - id: "5bfe8db2-3329-4320-a8b8-7f07cd12430e"
    alias: "main_bathroom_auto_lights"
    initial_state: false
    use_blueprint:
      path: "presence_light.yaml"
      input:
        light_entity: "light.main_bathroom_spots"
        light_off_entity: "light.main_bathroom_lights"
        presence_entity: "binary_sensor.main_bathroom_presence"
        brightness_based_on_time: true

  - id: "3285fa23-169e-43ff-94e7-29a79d1223d4"
    alias: "main_bathroom_fan_switch_zwave_scenes"
    use_blueprint:
      path: "zwave/paddle_scenes.yaml"
      input:
        on_entity_id: "event.main_bathroom_fan_switch_on_pressed"
        off_entity_id: "event.main_bathroom_fan_switch_on_pressed"

        <<: &all_on_off
          tap_on_3x:
            - service: light.turn_on
              data:
                entity_id: "light.main_bathroom_lights"
          tap_off_3x:
            - service: light.turn_off
              data:
                entity_id: "light.main_bathroom_lights"

  - id: "2078788e-2376-431a-9d53-b6fe0c3badb7"
    alias: "main_bathroom_vanity_light_switch_zwave_scenes"
    use_blueprint:
      path: "zwave/paddle_scenes.yaml"
      input:
        on_entity_id: "event.main_bathroom_vanity_light_switch_on_pressed"
        off_entity_id: "event.main_bathroom_vanity_light_switch_off_pressed"

        <<: *all_on_off

  - id: "39927953-3f47-4286-8ef4-4cbad509d510"
    alias: "main_bathroom_light_dimmer_zwave_scenes"
    use_blueprint:
      path: "zwave/paddle_scenes.yaml"
      input:
        on_entity_id: "event.main_bathroom_dimmer_on_pressed"
        off_entity_id: "event.main_bathroom_dimmer_off_pressed"

        <<: *all_on_off
