homeassistant:
  customize:
    light.master_bedroom_bedsides:
      friendly_name: "Master bedroom bedside lights"

google_assistant:
  entity_config:
    light.bedside_chris:
      expose: True
      room: "Master bedroom"
      aliases:
        - "Bedside Chris"
    light.bedside_karine:
      expose: True
      room: "Master bedroom"
      aliases:
        - "Bedside Karine"

cast:
  media_player:
    - host: !secret media_player_home_mbr_host

light:
  - platform: group
    name: "Master bedroom lights"
    entities:
      - light.master_bedroom_bedsides
  - platform: group
    name: "master_bedroom_bedsides"
    entities:
      - light.bedside_chris
      - light.bedside_karine
