homeassistant:
  customize:
    sensor.office_temperature:
      friendly_name: "Office temperature"

cloud:
  google_actions:
    filter:
      include_entities:
        - "light.office"

input_number:
  office_thermostat_eco_setpoint:
    name: "Office thermostat eco setpoint"
    <<: &setpoint_config
      unit_of_measurement: "°C"
      icon: "mdi:thermometer-lines"
      mode: "box"
      min: 8
      max: 25
      step: 0.5
  office_thermostat_comfort_setpoint:
    name: "Office thermostat comfort setpoint"
    <<: *setpoint_config
  office_thermostat_boost_setpoint:
    name: "Office thermostat boost setpoint"
    <<: *setpoint_config

input_select:
  office_thermostat_auto_mode:
    name: "Office thermostat auto mode"
    icon: mdi:home-thermometer-outline
    options: ["Boost", "Comfort", "Eco"]
  office_thermostat_mode:
    name: "Office thermostat mode"
    icon: mdi:home-thermometer-outline
    options: ["Auto", "Manual"]

light:
  - platform: group
    unique_id: "office_lights"
    name: "Office lights"
    entities:
      - light.office

template:
  - sensor:
      - unique_id: "sensor.office_temperature"
        name: "office_temperature"
        device_class: "temperature"
        unit_of_measurement: "°C"
        state: "{{ states('sensor.office_thermostat_temperature') | round(1) }}"
        attributes:
          heating: "{{ is_state_attr('climate.office_thermostat', 'hvac_action', 'heating') }}"

sonos:
  media_player:
    advertise_addr: !secret automate_ip
    hosts:
      - !secret media_player_sonos_office_host
