homeassistant:
  customize:
    sensor.office_temperature:
      friendly_name: "Office temperature"

cloud:
  google_actions:
    filter:
      include_entities:
        - "light.office_spots"

input_number:
  office_thermostat_eco_setpoint:
    name: "Office thermostat eco setpoint"
    <<: &setpoint_config
      unit_of_measurement: "°C"
      icon: "mdi:thermometer-lines"
      mode: "box"
      min: 8
      max: 25
      step: 0.5
  office_thermostat_comfort_setpoint:
    name: "Office thermostat comfort setpoint"
    <<: *setpoint_config

input_select:
  office_thermostat_auto_mode:
    name: "Office thermostat auto mode"
    icon: mdi:home-thermometer-outline
    options: ["Comfort", "Eco"]
  office_thermostat_mode:
    name: "Office thermostat mode"
    icon: mdi:home-thermometer-outline
    options: ["Auto", "Manual"]

light:
  - platform: group
    unique_id: "office_lights"
    name: "Office lights"
    entities:
      - "light.office_spots"
      - "light.office_lamp"

sonos:
  media_player:
    advertise_addr: !secret automate_ip

template:
  - sensor:
      - unique_id: "sensor.office_temperature"
        name: "office_temperature"
        device_class: "temperature"
        unit_of_measurement: "°C"
        state: "{{ states('sensor.office_thermostat_temperature') | float(0) | round(1) }}"
        availability: "{{ not is_state('sensor.office_thermostat_temperature', 'unavailable') }}"
        attributes:
          heating: "{{ is_state_attr('climate.office_thermostat', 'hvac_action', 'heating') }}"

timer:
  office_thermostat_manual_mode_reset:
    name: "Reset office thermostat to auto mode"
    duration: "01:00:00"
    restore: true

automation:
  - id: "dc1be8a1-ce4b-4f5e-89d1-1a84ad2ee47b"
    alias: "office_spots_dimmer_scenes"
    use_blueprint:
      path: "zwave/paddle_scenes.yaml"
      input:
        on_entity_id: "event.office_spots_dimmer_on_pressed"
        off_entity_id: "event.office_spots_dimmer_off_pressed"

        tap_on_2x:
          - action: "light.turn_on"
            target:
              entity_id: "light.office_lamp"
        tap_off_2x:
          - action: "light.turn_off"
            target:
              entity_id: "light.office_lamp"
