cloud:
  google_actions:
    filter:
      include_entities:
        - "light.office"
    entity_config:
      light.office:
        room: "Office"
        name: "Office light"
        aliases:
          - "Office"

input_number:
  office_thermostat_eco_setpoint:
    name: "Office thermostat eco setpoint"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer-lines"
    mode: "box"
    min: 8
    max: 18
    step: 0.5
  office_thermostat_comfort_setpoint:
    name: "Office thermostat comfort setpoint"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer-lines"
    mode: "box"
    min: 15
    max: 25
    step: 0.5

input_select:
  office_thermostat_auto_mode:
    name: "Office thermostat auto mode"
    icon: mdi:home-thermometer-outline
    options: ["Comfort", "Eco"]
  office_thermostat_mode:
    name: "Office thermostat mode"
    icon: mdi:home-thermometer-outline
    options: ["Auto", "Manual"]

light:
  - platform: group
    name: "Office lights"
    entities:
      - light.office

sensor:
  - platform: template
    sensors:
      office_temperature:
        friendly_name: "Office temperature"
        device_class: "temperature"
        unit_of_measurement: "°C"
        value_template: "{{ states('sensor.office_thermostat_temperature') | round(1) }}"
