cloud:
  google_actions:
    filter:
      include_entities:
        - "light.office"
    entity_config:
      light.office:
        room: "Office"
        name: "Office light"
        aliases:
          - "Office"

light:
  - platform: group
    name: "Office lights"
    entities:
      - light.office

sensor:
  - platform: template
    sensors:
      office_temperature:
        friendly_name: "Office temperature"
        device_class: "temperature"
        unit_of_measurement: "°C"
        value_template: "{{ states('sensor.office_thermostat_temperature') | round(1) }}"