homeassistant:
  customize:
    light.side_porch:
      friendly_name: "Front porch light"
    light.front_porch:
      friendly_name: "Side porch light"
    light.shed:
      friendly_name: "Shed door light"

cloud:
  google_actions:
    filter:
      include_entities:
        - "light.side_porch"
        - "light.front_porch"
        - "light.shed"
    entity_config:
      light.side_porch:
        room: "Outdoor"
        name: "Side porch light"
        aliases:
          - "Side porch"
          - "Porch"
          - "Side"
      light.front_porch:
        room: "Outdoor"
        name: "Front porch light"
        aliases:
          - "Front porch"
          - "Front"
      light.shed:
        room: "Outdoor"
        name: "Shed light"
        aliases:
          - "Shed"
          - "Garage"

light:
  - platform: group
    name: "Outdoor lights"
    entities:
      - light.side_porch
      - light.front_porch
      - light.shed

  - platform: switch
    name: side_porch
    entity_id: "switch.side_porch_light"
  - platform: switch
    name: front_porch
    entity_id: "switch.front_porch_light"
  - platform: switch
    name: shed
    entity_id: "switch.shed_light"

sensor:
  - platform: template
    sensors:
      outdoor_humidity:
        unique_id: "sensor.outdoor_humidity"
        friendly_name: "Outdoor humidity"
        device_class: "humidity"
        unit_of_measurement: "%"
        value_template: "{{ states('sensor.weather_quebec_humidity') }}"
        availability_template: "{{ not is_state('sensor.weather_quebec_humidity', 'unavailable') }}"
      outdoor_temperature:
        unique_id: "sensor.outdoor_temperature"
        friendly_name: "Outdoor temperature"
        device_class: "temperature"
        unit_of_measurement: "°C"
        value_template: "{{ states('sensor.weather_quebec_temperature') }}"
        availability_template: "{{ not is_state('sensor.weather_quebec_temperature', 'unavailable') }}"
      weather_summary:
        unique_id: "sensor.weather_summary"
        friendly_name: "Weather summary"
        value_template: "{{ states('sensor.weather_quebec_forecast') }}"
        icon_template: >
          {% set state_icon = states('weather.quebec')
            | replace('partlycloudy', 'partly-cloudy')
            | replace('unknown', '')
            | replace('undefined','')
            | replace('exceptional', '') %}
          mdi:{% if state_icon %}weather-{{ state_icon }}{% else %}help-circle{% endif %}
        availability_template: "{{ not is_state('sensor.weather_quebec_forecast', 'unavailable') }}"

automation:
  - alias: "front_porch_light_switch_zwave_scenes"
    use_blueprint:
      path: "zwave/homeseer_ws200+_scene_control.yaml"
      input:
        node_id: 6

        <<: &tap_2x
          tap_on_2x:
            - service: light.turn_on
              data:
                entity_id: "light.outdoor_lights"
          tap_off_2x:
            - service: light.turn_off
              data:
                entity_id: "light.outdoor_lights"

  - alias: "side_porch_light_switch_zwave_scenes"
    use_blueprint:
      path: "zwave/homeseer_ws200+_scene_control.yaml"
      input:
        node_id: 2
        <<: *tap_2x

  - alias: "shed_outdoor_light_switch_zwave_scenes"
    use_blueprint:
      path: "zwave/homeseer_ws200+_scene_control.yaml"
      input:
        node_id: 5
        <<: *tap_2x
