homeassistant:
  customize:
    light.side_porch:
      friendly_name: "Front porch light"
    light.front_porch:
      friendly_name: "Side porch light"
    light.shed:
      friendly_name: "Shed door light"

cloud:
  google_actions:
    filter:
      include_entities:
        - "light.side_porch"
        - "light.front_porch"
        - "light.shed"
    entity_config:
      light.side_porch:
        room: "Outdoor"
        name: "Side porch light"
        aliases:
          - "Side porch"
          - "Porch"
          - "Side"
      light.front_porch:
        room: "Outdoor"
        name: "Front porch light"
        aliases:
          - "Front porch"
          - "Front"
      light.shed:
        room: "Outdoor"
        name: "Shed light"
        aliases:
          - "Shed"
          - "Garage"

light:
  - platform: group
    name: "Outdoor lights"
    entities:
      - light.side_porch
      - light.front_porch
      - light.shed

  - platform: switch
    name: side_porch
    entity_id: "switch.side_porch_light"
  - platform: switch
    name: front_porch
    entity_id: "switch.front_porch_light"
  - platform: switch
    name: shed
    entity_id: "switch.shed_light"

sensor:
  - platform: template
    sensors:
      outdoor_humidity:
        friendly_name: "Outdoor humidity"
        device_class: "humidity"
        unit_of_measurement: "%"
        value_template: "{{ states('sensor.dark_sky_humidity') }}"
        availability_template: "{{ not is_state('sensor.dark_sky_humidity', 'unavailable') }}"
      outdoor_temperature:
        friendly_name: "Outdoor temperature"
        device_class: "temperature"
        unit_of_measurement: "°C"
        value_template: "{{ states('sensor.dark_sky_temperature') }}"
        availability_template: "{{ not is_state('sensor.dark_sky_temperature', 'unavailable') }}"
      weather_summary:
        friendly_name: "Weather summary"
        value_template: "{{ states('sensor.dark_sky_summary') }}"
        icon_template: "{{ state_attr('sensor.dark_sky_summary', 'icon') | default('mdi:help-circle') }}"
        availability_template: "{{ not is_state('sensor.dark_sky_summary', 'unavailable') }}"

automation:
  - alias: "double_up_outdoor_lights"
    initial_state: True
    trigger:
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.front_porch_light_switch"
          scene_id: 1
          scene_data: 7860
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.side_porch_light_switch"
          scene_id: 1
          scene_data: 7860
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.shed_outdoor_light_switch"
          scene_id: 1
          scene_data: 7860
    action:
      service: light.turn_on
      data:
        entity_id: "light.outdoor_lights"
  - alias: "double_down_outdoor_lights"
    initial_state: True
    trigger:
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.front_porch_light_switch"
          scene_id: 2
          scene_data: 7860
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.side_porch_light_switch"
          scene_id: 2
          scene_data: 7860
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.shed_outdoor_light_switch"
          scene_id: 2
          scene_data: 7860
    action:
      service: light.turn_off
      data:
        entity_id: "light.outdoor_lights"
