homeassistant:
  customize:
    light.studio:
      friendly_name: "Studio light"
    sensor.studio_window_sensor_battery:
      battery_type: "Sensative Strip"

cloud:
  google_actions:
    filter:
      include_entities:
        - "light.studio"
    entity_config:
      light.studio:
        room: "Studio"
        name: "Studio light"
        aliases:
          - "Studio"

input_number:
  studio_thermostat_eco_setpoint:
    name: "Studio thermostat eco setpoint"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer-lines"
    mode: "box"
    min: 8
    max: 18
    step: 0.5
  studio_thermostat_comfort_setpoint:
    name: "Studio thermostat comfort setpoint"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer-lines"
    mode: "box"
    min: 15
    max: 25
    step: 0.5

input_select:
  studio_thermostat_mode:
    name: "Studio thermostat mode"
    icon: mdi:home-thermometer-outline
    options: ["Comfort", "Eco", "Manual"]

light:
  - platform: group
    name: "Studio lights"
    entities:
      - light.studio

  - platform: switch
    name: "studio"
    entity_id: "switch.studio_light"

binary_sensor:
  - platform: template
    sensors:
      studio_window:
        friendly_name: "Studio window"
        device_class: "window"
        value_template: "{{ is_state('sensor.studio_window_sensor_access_control', '22') }}"

sensor:
  - platform: template
    sensors:
      studio_temperature:
        friendly_name: "Studio temperature"
        device_class: "temperature"
        unit_of_measurement: "°C"
        value_template: "{{ states('sensor.studio_thermostat_temperature') | round(1) }}"

automation:
  - alias: "studio_update_setpoint"
    hide_entity: True
    initial_state: True
    trigger:
      - platform: state
        entity_id: "input_select.studio_thermostat_mode"
    condition:
      - condition: template
        value_template: |
          {{ (trigger.from_state is none or trigger.from_state.state != trigger.to_state.state)
            and not trigger.to_state.state == 'Manual' }}
    action:
      - service: "climate.set_temperature"
        data_template:
          entity_id: "climate.studio_thermostat"
          temperature: "{{ states('input_number.studio_thermostat_' + (states('input_select.studio_thermostat_mode') | lower) + '_setpoint') }}"

  - alias: "studio_update_thermostat_mode"
    hide_entity: True
    initial_state: True
    trigger:
      - platform: state
        entity_id: "climate.studio_thermostat"
    condition:
      - condition: template
        value_template: |
          {{ (trigger.from_state is none or trigger.from_state.attributes.temperature != trigger.to_state.attributes.temperature)
            and trigger.to_state.attributes.preset_mode == 'none' }}
    action:
      - service: "input_select.select_option"
        data_template:
          entity_id: "input_select.studio_thermostat_mode"
          option: |
            {% set ns = namespace(mode='Manual', found=False) -%}
            {% for mode in state_attr('input_select.studio_thermostat_mode', 'options') -%}
            {% if not ns.found and trigger.to_state.attributes.temperature | float == states('input_number.studio_thermostat_' + (mode | lower) + '_setpoint') | float -%}
            {% set ns.mode = mode -%}
            {% set ns.found = True %}
            {%- endif %}
            {%- endfor -%}
            {{ ns.mode }}
