homeassistant:
  customize:
    sensor.studio_window_sensor_battery:
      battery_type: "Sensative Strip"

binary_sensor:
  - platform: template
    sensors:
      studio_window:
        friendly_name: "Studio window"
        device_class: "window"
        value_template: "{{ is_state('sensor.studio_window_sensor_access_control', '22') }}"

sensor:
  - platform: template
    sensors:
      studio_window_sensor_battery:
        friendly_name: "Studio window sensor battery"
        device_class: "battery"
        unit_of_measurement: "%"
        value_template: "{{ state_attr('zwave.studio_window_sensor', 'battery_level') | int('unknown') }}"
