homeassistant:
  customize:
    binary_Sensor.studio_window:
      friendly_name: "Studio window"
      device_class: "window"
    sensor.studio_window_sensor_battery:
      battery_type: "Sensative Strip"
      battery_warning_level: 20
    sensor.studio_temperature:
      friendly_name: "Studio temperature"

cloud:
  google_actions:
    filter:
      include_entities:
        - "light.studio_spots"
        - "light.studio_panel"

input_number:
  studio_thermostat_eco_setpoint:
    name: "Studio thermostat eco setpoint"
    <<: &setpoint_config
      unit_of_measurement: "°C"
      icon: "mdi:thermometer-lines"
      mode: "box"
      min: 8
      max: 25
      step: 0.5
  studio_thermostat_comfort_setpoint:
    name: "Studio thermostat comfort setpoint"
    <<: *setpoint_config

input_select:
  studio_thermostat_auto_mode:
    name: "Studio thermostat auto mode"
    icon: mdi:home-thermometer-outline
    options: ["Comfort", "Eco"]
  studio_thermostat_mode:
    name: "Studio thermostat mode"
    icon: mdi:home-thermometer-outline
    options: ["Auto", "Manual"]

light:
  - platform: group
    unique_id: "studio_lights"
    name: "Studio lights"
    entities:
      - "light.studio_panel"
      - "light.studio_spots"

template:
  - sensor:
      - unique_id: "sensor.studio_temperature"
        name: "studio_temperature"
        device_class: "temperature"
        unit_of_measurement: "°C"
        state: "{{ states('sensor.studio_thermostat_temperature') | float(0) | round(1) }}"
        availability: "{{ not is_state('sensor.studio_thermostat_temperature', 'unavailable') }}"
        attributes:
          heating: "{{ is_state_attr('climate.studio_thermostat', 'hvac_action', 'heating') }}"

timer:
  studio_thermostat_manual_mode_reset:
    name: "Reset studio thermostat to auto mode"
    duration: "01:00:00"
    restore: true
