homeassistant:
  customize:
    binary_Sensor.studio_window:
      friendly_name: "Studio window"
      device_class: "window"
    light.studio:
      friendly_name: "Studio light"
    sensor.studio_window_sensor_battery:
      battery_type: "Sensative Strip"
      battery_warning_level: 20

cloud:
  google_actions:
    filter:
      include_entities:
        - "light.studio"
    entity_config:
      light.studio:
        room: "Studio"
        name: "Studio light"
        aliases:
          - "Studio"

input_number:
  studio_thermostat_eco_setpoint:
    name: "Studio thermostat eco setpoint"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer-lines"
    mode: "box"
    min: 8
    max: 18
    step: 0.5
  studio_thermostat_comfort_setpoint:
    name: "Studio thermostat comfort setpoint"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer-lines"
    mode: "box"
    min: 15
    max: 25
    step: 0.5

input_select:
  studio_thermostat_auto_mode:
    name: "Studio thermostat auto mode"
    icon: mdi:home-thermometer-outline
    options: ["Comfort", "Eco"]
  studio_thermostat_mode:
    name: "Studio thermostat mode"
    icon: mdi:home-thermometer-outline
    options: ["Auto", "Manual"]

light:
  - platform: group
    name: "Studio lights"
    entities:
      - light.studio

  - platform: switch
    name: "studio"
    entity_id: "switch.studio_light"

sensor:
  - platform: template
    sensors:
      studio_temperature:
        friendly_name: "Studio temperature"
        device_class: "temperature"
        unit_of_measurement: "°C"
        value_template: "{{ states('sensor.studio_thermostat_temperature') | round(1) }}"
