homeassistant:
  customize:
    light.studio:
      friendly_name: "Studio light"
    sensor.studio_window_sensor_battery:
      battery_type: "Sensative Strip"

cloud:
  google_actions:
    filter:
      include_entities:
        - "light.studio"
    entity_config:
      light.studio:
        room: "Studio"
        name: "Studio light"
        aliases:
          - "Studio"

light:
  - platform: group
    name: "Studio lights"
    entities:
      - light.studio

  - platform: switch
    name: "studio"
    entity_id: "switch.studio_light"

binary_sensor:
  - platform: template
    sensors:
      studio_window:
        friendly_name: "Studio window"
        device_class: "window"
        value_template: "{{ is_state('sensor.studio_window_sensor_access_control', '22') }}"

sensor:
  - platform: template
    sensors:
      studio_temperature:
        friendly_name: "Studio temperature"
        device_class: "temperature"
        unit_of_measurement: "°C"
        value_template: "{{ states('sensor.studio_thermostat_temperature') | round(1) }}"
