homeassistant:
  customize:
    light.workshop:
      friendly_name: "Workshop light"
    sensor.water_heater_leak_sensor_battery:
      battery_type: "ER14250 3.6V"
      battery_warning_level: 25
    switch.main_water_shut_off_valve:
      icon: "mdi:valve"

cloud:
  google_actions:
    filter:
      include_entities:
        - "light.workshop"

light:
  - platform: group
    name: "Workshop lights"
    entities:
      - light.workshop

  - platform: switch
    name: workshop
    entity_id: "switch.workshop_light"

automation:
  - id: "2289c205-a0ae-47a3-bdfe-7ea55a437db6"
    alias: "workshop_auto_lights"
    use_blueprint:
      path: "presence_light.yaml"
      input:
        delay_off: 300
        light_entity: "light.workshop"
        light_off_entity: "light.workshop_lights"
        presence_entity: "binary_sensor.workshop_motion"
