homeassistant:
  customize:
    light.workshop:
      friendly_name: "Workshop light"
      battery_warning_level: 25
    sensor.water_heater_leak_sensor_battery:
      battery_type: "ER14250 3.6V"
    switch.main_water_shut_off_valve:
      icon: "mdi:valve"

cloud:
  google_actions:
    filter:
      include_entities:
        - "light.workshop"
    entity_config:
      light.workshop:
        room: "Workshop"
        name: "Workshop light"
        aliases:
          - "Workshop"

light:
  - platform: group
    name: "Workshop lights"
    entities:
      - light.workshop

  - platform: switch
    name: workshop
    entity_id: "switch.workshop_light"

automation:
  - alias: "workshop_auto_lights"
    use_blueprint:
      path: "presence_light.yaml"
      input:
        delay_off: 300
        light_entity: "light.workshop"
        light_off_entity: "light.workshop_lights"
        presence_entity: "binary_sensor.workshop_motion"
