homeassistant:
  customize:
    sensor.water_heater_leak_sensor_battery:
      battery_type: "ER14250 3.6V"
    light.workshop:
      friendly_name: "Workshop light"
      battery_warning_level: 25

cloud:
  google_actions:
    filter:
      include_entities:
        - "light.workshop"
    entity_config:
      light.workshop:
        room: "Workshop"
        name: "Workshop light"
        aliases:
          - "Workshop"

light:
  - platform: group
    name: "Workshop lights"
    entities:
      - light.workshop

  - platform: switch
    name: workshop
    entity_id: "switch.workshop_light"

binary_sensor:
  - platform: template
    sensors:
      water_heater_leak:
        unique_id: "binary_sensor.water_heater_leak"
        friendly_name: "Water heater leak"
        device_class: "moisture"
        value_template: "{{ is_state('sensor.water_heater_leak_sensor_flood', '2') }}"

      workshop_motion:
        unique_id: "binary_sensor.workshop_motion"
        friendly_name: "Workshop motion"
        device_class: "motion"
        value_template: "{{ is_state('sensor.workshop_motion_sensor_burglar', '8') }}"

automation:
  - alias: "workshop_auto_lights"
    use_blueprint:
      path: "presence_light.yaml"
      input:
        delay_off: 300
        light_entity: "light.workshop"
        light_off_entity: "light.workshop_lights"
        presence_entity: "binary_sensor.workshop_motion"
