homeassistant:
  customize:
    sensor.water_heater_leak_sensor_battery:
      battery_type: "ER14250 3.6V"
    light.workshop:
      friendly_name: "Workshop light"

google_assistant:
  entity_config:
    light.workshop:
      expose: True
      room: "Workshop"
      aliases:
        - "Workshop light"
        - "Workshop"

light:
  - platform: group
    name: "Workshop lights"
    entities:
      - light.workshop

  - platform: switch
    name: workshop
    entity_id: "switch.workshop_light"

binary_sensor:
  - platform: template
    sensors:
      water_heater_leak:
        friendly_name: "Water heater leak"
        device_class: "moisture"
        value_template: "{{ is_state('sensor.water_heater_leak_sensor_flood', '2') }}"

      workshop_motion:
        friendly_name: "Workshop motion"
        device_class: "motion"
        value_template: "{{ is_state('sensor.workshop_motion_sensor_burglar', '8') }}"

sensor:
  - platform: template
    sensors:
      water_heater_leak_sensor_battery:
        friendly_name: "Water heater leak sensor battery"
        device_class: "battery"
        unit_of_measurement: "%"
        value_template: "{{ state_attr('zwave.water_heater_leak_sensor', 'battery_level') | int('unknown') }}"

automation:
  # Automated light management
  - alias: "workshop_auto_lights_on"
    hide_entity: True
    initial_state: True
    trigger:
      - platform: state
        entity_id: "binary_sensor.workshop_motion"
        to: "on"
    action:
      - service: light.turn_on
        data:
          entity_id: "light.workshop"
  - alias: "workshop_auto_lights_off"
    hide_entity: True
    initial_state: True
    trigger:
      - platform: state
        entity_id: "binary_sensor.workshop_motion"
        to: "off"
    action:
      - service: light.turn_off
        data:
          entity_id: "light.workshop"
