group:
  all_batteries:
    name: "Batteries"
    icon: "mdi:battery"
    control: "hidden"

automation:
  - id: notify_low_batteries
    alias: "Notify low batteries"
    hide_entity: True
    initial_state: True
    trigger:
      platform: event
      event_type: "state_changed"
    condition:
      - condition: template
        value_template: "{{ trigger.event.data.entity_id in state_attr('group.all_batteries', 'entity_id') }}"
      - condition: or
        conditions:
          - condition: template
            # Binary sensors are on when battery is low, off otherwise
            value_template: "{{ trigger.event.data.old_state.state == 'off' and trigger.event.data.new_state.state == 'on' }}"
          - condition: template
            value_template: "{{ trigger.event.data.old_state.state | int(100) > 20 and trigger.event.data.new_state.state | int(100) <= 20 }}"
    action:
      - service: python_script.notify
        data_template:
          persistent: True
          push_target: "household"
          tag: "battery_low_{{ trigger.event.data.new_state.object_id }}"
          url: "https://www.amazon.ca/s/?field-keywords=battery+{{ state_attr(trigger.event.data.entity_id, 'battery_type') | d('', True)  | replace(' ', '+') }}"
          title: "Replace {{ trigger.event.data.new_state.name | lower }}"
          message: "Search on Amazon for \"{{ state_attr(trigger.event.data.entity_id, 'battery_type') }}\" batteries."
