input_boolean:
  automatic_night_theme:
    name: "Automatic night theme"
    initial: True
    icon: 'mdi:theme-light-dark'

input_select:
  default_theme:
    name: 'Default theme'
    options:
      - 'default'
      - &day_theme 'clear'
      - &night_theme 'clear-dark'
    icon: 'mdi:palette'

automation:
  - alias: set_default_theme
    initial_state: True
    trigger:
      - platform: state
        entity_id: "input_select.default_theme"
    action:
      - service: frontend.set_theme
        data_template:
          name: "{{trigger.to_state.state}}"

  - alias: sunrise_theme
    initial_state: True
    trigger:
      - platform: sun
        event: "sunrise"
      - platform: homeassistant
        event: "start"
    condition:
      - condition: state
        entity_id: "input_boolean.automatic_night_theme"
        state: "on"
      - condition: sun
        after: "sunrise"
      - condition: sun
        before: "sunset"
    action:
      - service: input_select.select_option
        data:
          entity_id: "input_select.default_theme"
          option: *day_theme
  - alias: sunset_theme
    initial_state: True
    trigger:
      - platform: sun
        event: "sunset"
      - platform: homeassistant
        event: "start"
    condition:
      - condition: state
        entity_id: "input_boolean.automatic_night_theme"
        state: "on"
      - condition: or
        conditions:
          - condition: sun
            after: "sunset"
          - condition: sun
            before: "sunrise"
    action:
      - service: input_select.select_option
        data:
          entity_id: "input_select.default_theme"
          option: *night_theme
