automation:
  - alias: household_leaves
    initial_state: True
    trigger:
      - platform: state
        entity_id: "group.household"
        to: "not_home"
        for: "00:00:30"
    condition:
      - condition: state
        entity_id: "binary_sensor.guest_mode"
        state: "off"
    action:
      - service: script.everything_off
