homeassistant:
  customize:
    scene.empty_house:
      friendly_name: "Empty House"
    automation.household_leaves:
      friendly_name: "Turn everything off when household leaves"


script:
  empty_house:
    # TODO: Gonna need to list devices individually. ie: TV is turned on/off w/ the same code or fans must run based on humidity
    alias: "Set house mood to nobody in da hood"
    sequence:
      - service: homeassistant.turn_off
        data:
          entity_id: "group.outdoor"
      - service: homeassistant.turn_off
        data:
          entity_id: "group.master_bedroom"
      - service: homeassistant.turn_off
        data:
          entity_id: "group.living_room"
      - service: homeassistant.turn_off
        data:
          entity_id: "group.kitchen"
      - service: homeassistant.turn_off
        data:
          entity_id: "group.dining_room"
      - service: homeassistant.turn_off
        data:
          entity_id: "group.main_bathroom"
      - service: homeassistant.turn_off
        data:
          entity_id: "group.basement_bathroom"
      - service: homeassistant.turn_off
        data:
          entity_id: "group.office"

automation:
  - alias: household_leaves
    initial_state: True
    trigger:
      platform: state
      entity_id: "group.household"
      from: "home"
    condition:
      condition: state
      entity_id: "input_boolean.guest_mode"
      state: "off"
    action:
      service: script.turn_on
      entity_id: "script.empty_house"
