homeassistant:
  customize:
    scene.empty_house:
      friendly_name: "Empty House"
    automation.household_leaves:
      friendly_name: "Turn everything off when household leaves"

scene:
  - name: empty_house
    entities:
      group.master_bedroom:
        state: False
      group.top_living_room:
        state: False
      group.outdoor:
        state: False

automation:
  - alias: household_leaves
    initial_state: True
    trigger:
      platform: state
      entity_id: "group.household"
      from: "home"
    condition:
      condition: state
      entity_id: "input_boolean.guest_mode"
      state: "off"
    action:
      service: scene.turn_on
      entity_id: "scene.empty_house"
