homeassistant:
  customize:
    automation.close_outdoor_lights:
      friendly_name: "Keep outdoor lights open for 5 minutes after 11 pm"

automation:
  - alias: close_outdoor_lights
    initial_state: True
    trigger:
      - platform: state
        entity_id: "light.outdoor_lights"
        to: "on"
        for:
          minutes: 5
      - platform: time
        at: "23:15:00"
    condition:
      condition: and
      conditions: 
        - condition: state
          entity_id: "light.outdoor_lights"
          state: "on"
          for:
            minutes: 5
        - condition: time
          after: "23:15:00"
          before: "17:00:00"
    action:
      service: homeassistant.turn_off
      entity_id: "light.outdoor_lights"
