automation:
  - alias: sunrise_theme
    initial_state: True
    trigger:
      - platform: sun
        event: "sunrise"
      - platform: homeassistant
        event: "start"
    condition:
      - condition: state
        entity_id: "input_boolean.automatic_night_theme"
        state: "on"
      - condition: sun
        after: "sunrise"
      - condition: sun
        before: "sunset"
    action:
      - service: input_select.select_option
        data:
          entity_id: "input_select.default_theme"
          option: "default"
