homeassistant:
  customize:
    automation.sunrise:
      friendly_name: "Setup the house for a day mood"

automation:
  - alias: sunrise
    initial_state: True
    trigger:
      - platform: sun
        event: "sunrise"
    condition:
      condition: sun
      after: "sunrise"
    action:
      service: script.turn_on
      entity_id: "script.sunrise_general"

script:
  sunrise_general:
    alias: "General sunrise ambiance"
    sequence:
      - service: frontend.set_theme
        data:
          name: "default"

