homeassistant:
  customize:
    scene.sunset:
      friendly_name: "Sunset"
    automation.sunset_ambiance:
      friendly_name: "Turn on ambiance lights at sunset"

automation:
  - alias: sunset_ambiance
    trigger:
      - platform: sun
        event: "sunset"
      - platform: state
        entity_id: "group.household"
        to: "home"
    condition:
      condition: and
      conditions:
        - condition: time
          before: "00:00:00"
        - condition: sun
          after: "sunset"
        - condition: state
          entity_id: "group.household"
          state: "home"
    action:
      service: scene.turn_on
      entity_id: "scene.sunset"

scene:
  - name: sunset
    entities:
      group.master_bedroom_light_bedside:
        state: "on"
        brightness: 1
        rgb_color: [21, 8, 0]
      group.outdoor_light:
        state: "on"
      switch.living_room_ambiance: "on"
