automation:
  - alias: sunset_ambiance
    initial_state: true
    trigger:
      - platform: sun
        event: "sunset"
      - platform: state
        entity_id: "group.household"
        to: "home"
    condition:
      - condition: and
        conditions:
          - condition: sun
            after: "sunset"
          - condition: time
            before: "00:00:00"
          - condition: state
            entity_id: "group.household"
            state: "home"
    action:
      - service: homeassistant.turn_on
        data:
          entity_id: "light.outdoor_lights"
      - service: script.ambiance
