homeassistant:
  customize:
    scene.wake_up_alarm:
      friendly_name: "Wake Up Alarm"
    automation.wake_up_alarm_monday:
      friendly_name: "Monday Alarm"
    automation.wake_up_alarm_tuesday:
      friendly_name: "Tuesday Alarm"
    automation.wake_up_alarm_wednesday:
      friendly_name: "Wednesday Alarm"
    automation.wake_up_alarm_thursday:
      friendly_name: "Thursday Alarm"
    automation.wake_up_alarm_friday:
      friendly_name: "Friday Alarm"
    automation.wake_up_alarm_saturday:
      friendly_name: "Saturday Alarm"
    automation.wake_up_alarm_sunday:
      friendly_name: "Sunday Alarm"

group:
  wake_up_alarm:
    name: "Wake Up Alarms"
    icon: "mdi:bell-ring"
    entities:
      - automation.wake_up_alarm_monday
      - input_datetime.wake_up_alarm_monday
      - automation.wake_up_alarm_tuesday
      - input_datetime.wake_up_alarm_tuesday
      - automation.wake_up_alarm_wednesday
      - input_datetime.wake_up_alarm_wednesday
      - automation.wake_up_alarm_thursday
      - input_datetime.wake_up_alarm_thursday
      - automation.wake_up_alarm_friday
      - input_datetime.wake_up_alarm_friday
      - automation.wake_up_alarm_saturday
      - input_datetime.wake_up_alarm_saturday
      - automation.wake_up_alarm_sunday
      - input_datetime.wake_up_alarm_sunday

scene:
  - name: wake_up_alarm
    entities:
      group.master_bedroom_light_bedside:
        state: True
        color_temp: 375
        brightness: 200
        transition: 600

input_datetime:
  wake_up_alarm_monday:
    name: "Monday Time"
    icon: "mdi:clock"
    has_date: False
    has_time: True

  wake_up_alarm_tuesday:
    name: "Tuesday Time"
    icon: "mdi:clock"
    has_date: False
    has_time: True

  wake_up_alarm_wednesday:
    name: "Wednesday Time"
    icon: "mdi:clock"
    has_date: False
    has_time: True

  wake_up_alarm_thursday:
    name: "Thursday Time"
    icon: "mdi:clock"
    has_date: False
    has_time: True

  wake_up_alarm_friday:
    name: "Friday Time"
    icon: "mdi:clock"
    has_date: False
    has_time: True

  wake_up_alarm_saturday:
    name: "Saturday Time"
    icon: "mdi:clock"
    has_date: False
    has_time: True

  wake_up_alarm_sunday:
    name: "Sunday Time"
    icon: "mdi:clock"
    has_date: False
    has_time: True

automation:
  - alias: toggle_alarm_time_monday
    trigger:
      - platform: state
        entity_id: automation.wake_up_alarm_monday
      - platform: homeassistant
        event: start
    action:
      service: customizer.set_attribute
      data_template:
        entity_id: "input_datetime.wake_up_alarm_monday"
        attribute: "hidden"
        value: "{% if is_state('automation.wake_up_alarm_monday', 'off') %}True{% endif %}"

  - alias: wake_up_alarm_monday
    initial_state: False
    trigger:
      - platform: template
        value_template: "{{ is_state('input_datetime.wake_up_alarm_monday', as_timestamp(now()) | timestamp_custom('%H:%M:%S')) }}"
    condition:
      - condition: state
        entity_id: "group.household"
        state: "home"
      - condition: time
        weekday: "mon"
    action:
      service: scene.turn_on
      entity_id: "scene.wake_up_alarm"

  - alias: toggle_alarm_time_tuesday
    trigger:
      - platform: state
        entity_id: automation.wake_up_alarm_tuesday
      - platform: homeassistant
        event: start
    action:
      service: customizer.set_attribute
      data_template:
        entity_id: "input_datetime.wake_up_alarm_tuesday"
        attribute: "hidden"
        value: "{% if is_state('automation.wake_up_alarm_tuesday', 'off') %}True{% endif %}"

  - alias: wake_up_alarm_tuesday
    initial_state: False
    trigger:
      - platform: template
        value_template: "{{ is_state('input_datetime.wake_up_alarm_tuesday', as_timestamp(now()) | timestamp_custom('%H:%M:%S')) }}"
    condition:
      - condition: state
        entity_id: "group.household"
        state: "home"
      - condition: time
        weekday: "tue"
    action:
      service: scene.turn_on
      entity_id: "scene.wake_up_alarm"

  - alias: toggle_alarm_time_wednesday
    trigger:
      - platform: state
        entity_id: automation.wake_up_alarm_wednesday
      - platform: homeassistant
        event: start
    action:
      service: customizer.set_attribute
      data_template:
        entity_id: "input_datetime.wake_up_alarm_wednesday"
        attribute: "hidden"
        value: "{% if is_state('automation.wake_up_alarm_wednesday', 'off') %}True{% endif %}"

  - alias: wake_up_alarm_wednesday
    initial_state: False
    trigger:
      - platform: template
        value_template: "{{ is_state('input_datetime.wake_up_alarm_wednesday', as_timestamp(now()) | timestamp_custom('%H:%M:%S')) }}"
    condition:
      - condition: state
        entity_id: "group.household"
        state: "home"
      - condition: time
        weekday: "wed"
    action:
      service: scene.turn_on
      entity_id: "scene.wake_up_alarm"

  - alias: toggle_alarm_time_thursday
    trigger:
      - platform: state
        entity_id: automation.wake_up_alarm_thursday
      - platform: homeassistant
        event: start
    action:
      service: customizer.set_attribute
      data_template:
        entity_id: "input_datetime.wake_up_alarm_thursday"
        attribute: "hidden"
        value: "{% if is_state('automation.wake_up_alarm_thursday', 'off') %}True{% endif %}"

  - alias: wake_up_alarm_thursday
    initial_state: False
    trigger:
      - platform: template
        value_template: "{{ is_state('input_datetime.wake_up_alarm_thursday', as_timestamp(now()) | timestamp_custom('%H:%M:%S')) }}"
    condition:
      - condition: state
        entity_id: "group.household"
        state: "home"
      - condition: time
        weekday: "thu"
    action:
      service: scene.turn_on
      entity_id: "scene.wake_up_alarm"

  - alias: toggle_alarm_time_friday
    trigger:
      - platform: state
        entity_id: automation.wake_up_alarm_friday
      - platform: homeassistant
        event: start
    action:
      service: customizer.set_attribute
      data_template:
        entity_id: "input_datetime.wake_up_alarm_friday"
        attribute: "hidden"
        value: "{% if is_state('automation.wake_up_alarm_friday', 'off') %}True{% endif %}"

  - alias: wake_up_alarm_friday
    initial_state: False
    trigger:
      - platform: template
        value_template: "{{ is_state('input_datetime.wake_up_alarm_friday', as_timestamp(now()) | timestamp_custom('%H:%M:%S')) }}"
    condition:
      - condition: state
        entity_id: "group.household"
        state: "home"
      - condition: time
        weekday: "fri"
    action:
      service: scene.turn_on
      entity_id: "scene.wake_up_alarm"

  - alias: toggle_alarm_time_saturday
    trigger:
      - platform: state
        entity_id: automation.wake_up_alarm_saturday
      - platform: homeassistant
        event: start
    action:
      service: customizer.set_attribute
      data_template:
        entity_id: "input_datetime.wake_up_alarm_saturday"
        attribute: "hidden"
        value: "{% if is_state('automation.wake_up_alarm_saturday', 'off') %}True{% endif %}"

  - alias: wake_up_alarm_saturday
    initial_state: False
    trigger:
      - platform: template
        value_template: "{{ is_state('input_datetime.wake_up_alarm_saturday', as_timestamp(now()) | timestamp_custom('%H:%M:%S')) }}"
    condition:
      - condition: state
        entity_id: "group.household"
        state: "home"
      - condition: time
        weekday: "sat"
    action:
      service: scene.turn_on
      entity_id: "scene.wake_up_alarm"

  - alias: toggle_alarm_time_sunday
    trigger:
      - platform: state
        entity_id: automation.wake_up_alarm_sunday
      - platform: homeassistant
        event: start
    action:
      service: customizer.set_attribute
      data_template:
        entity_id: "input_datetime.wake_up_alarm_sunday"
        attribute: "hidden"
        value: "{% if is_state('automation.wake_up_alarm_sunday', 'off') %}True{% endif %}"

  - alias: wake_up_alarm_sunday
    initial_state: False
    trigger:
      - platform: template
        value_template: "{{ is_state('input_datetime.wake_up_alarm_sunday', as_timestamp(now()) | timestamp_custom('%H:%M:%S')) }}"
    condition:
      - condition: state
        entity_id: "group.household"
        state: "home"
      - condition: time
        weekday: "sat"
    action:
      service: scene.turn_on
      entity_id: "scene.wake_up_alarm"
