- alias: 'Wake Up Monday'
  trigger:
    - platform: template
      value_template: "{{ is_state('input_select.wake_up_monday', states('sensor.time')) }}"
  condition:
    - condition: state
      entity_id: 'group.family'
      state: 'home'
    - condition: time
      weekday: 'mon'
  action:
    service: scene.turn_on
    entity_id: 'scene.wake_up'

- alias: 'Wake Up Tuesday'
  trigger:
    - platform: template
      value_template: "{{ is_state('input_select.wake_up_tuesday', states('sensor.time')) }}"
  condition:
    - condition: state
      entity_id: 'group.family'
      state: 'home'
    - condition: time
      weekday: 'tue'
  action:
    service: scene.turn_on
    entity_id: 'scene.wake_up'

- alias: 'Wake Up Wednesday'
  trigger:
    - platform: template
      value_template: "{{ is_state('input_select.wake_up_wednesday', states('sensor.time')) }}"
  condition:
    - condition: state
      entity_id: 'group.family'
      state: 'home'
    - condition: time
      weekday: 'wed'
  action:
    service: scene.turn_on
    entity_id: 'scene.wake_up'

- alias: 'Wake Up Thursday'
  trigger:
    - platform: template
      value_template: "{{ is_state('input_select.wake_up_thursday', states('sensor.time')) }}"
  condition:
    - condition: state
      entity_id: 'group.family'
      state: 'home'
    - condition: time
      weekday: 'thu'
  action:
    service: scene.turn_on
    entity_id: 'scene.wake_up'

- alias: 'Wake Up Friday'
  trigger:
    - platform: template
      value_template: "{{ is_state('input_select.wake_up_friday', states('sensor.time')) }}"
  condition:
    - condition: state
      entity_id: 'group.family'
      state: 'home'
    - condition: time
      weekday: 'fri'
  action:
    service: scene.turn_on
    entity_id: 'scene.wake_up'

- alias: 'Wake Up Saturday'
  trigger:
    - platform: template
      value_template: "{{ is_state('input_select.wake_up_saturday', states('sensor.time')) }}"
  condition:
    - condition: state
      entity_id: 'group.family'
      state: 'home'
    - condition: time
      weekday: 'sat'
  action:
    service: scene.turn_on
    entity_id: 'scene.wake_up'
