- alias: 'Wake Up Alarm Monday'
  initial_state: False
  trigger:
    - platform: template
      value_template: "{{ is_state('input_select.wake_up_alarm_monday', states('sensor.time')) }}"
  condition:
    - condition: state
      entity_id: 'group.family'
      state: 'home'
    - condition: time
      weekday: 'mon'
  action:
    service: scene.turn_on
    entity_id: 'scene.wake_up_alarm'

- alias: 'Wake Up Alarm Tuesday'
  initial_state: False
  trigger:
    - platform: template
      value_template: "{{ is_state('input_select.wake_up_alarm_tuesday', states('sensor.time')) }}"
  condition:
    - condition: state
      entity_id: 'group.family'
      state: 'home'
    - condition: time
      weekday: 'tue'
  action:
    service: scene.turn_on
    entity_id: 'scene.wake_up_alarm'

- alias: 'Wake Up Alarm Wednesday'
  initial_state: False
  trigger:
    - platform: template
      value_template: "{{ is_state('input_select.wake_up_alarm_wednesday', states('sensor.time')) }}"
  condition:
    - condition: state
      entity_id: 'group.family'
      state: 'home'
    - condition: time
      weekday: 'wed'
  action:
    service: scene.turn_on
    entity_id: 'scene.wake_up_alarm'

- alias: 'Wake Up Alarm Thursday'
  initial_state: False
  trigger:
    - platform: template
      value_template: "{{ is_state('input_select.wake_up_alarm_thursday', states('sensor.time')) }}"
  condition:
    - condition: state
      entity_id: 'group.family'
      state: 'home'
    - condition: time
      weekday: 'thu'
  action:
    service: scene.turn_on
    entity_id: 'scene.wake_up_alarm'

- alias: 'Wake Up Alarm Friday'
  initial_state: False
  trigger:
    - platform: template
      value_template: "{{ is_state('input_select.wake_up_alarm_friday', states('sensor.time')) }}"
  condition:
    - condition: state
      entity_id: 'group.family'
      state: 'home'
    - condition: time
      weekday: 'fri'
  action:
    service: scene.turn_on
    entity_id: 'scene.wake_up_alarm'

- alias: 'Wake Up Alarm Saturday'
  initial_state: False
  trigger:
    - platform: template
      value_template: "{{ is_state('input_select.wake_up_alarm_saturday', states('sensor.time')) }}"
  condition:
    - condition: state
      entity_id: 'group.family'
      state: 'home'
    - condition: time
      weekday: 'sat'
  action:
    service: scene.turn_on
    entity_id: 'scene.wake_up_alarm'

- alias: 'Wake Up Alarm Sunday'
  initial_state: False
  trigger:
    - platform: template
      value_template: "{{ is_state('input_select.wake_up_alarm_sunday', states('sensor.time')) }}"
  condition:
    - condition: state
      entity_id: 'group.family'
      state: 'home'
    - condition: time
      weekday: 'sat'
  action:
    service: scene.turn_on
    entity_id: 'scene.wake_up_alarm'
