blueprint:
  name: Inovelli Red Series (LZW-SN) scene control
  description: >
    Associate actions to scenes from Inovelli's Red Series LZW30-SN swiches and LZW31-SN dimmers.
  domain: automation
  input:
    node_id:
      name: Z-Wave entity
      description: Listen to scene events from this node ID.
      selector:
        number:
          min: 2
          max: 254
          mode: box

    hold_on:
      name: Hold on paddle
      description: Action to execute when the on paddle is held.
      default: []
      selector:
        action: {}
    hold_off:
      name: Hold off paddle
      description: Action to execute when the off paddle is held.
      default: []
      selector:
        action: {}

    release_on:
      name: Release on paddle
      description: Action to execute when the on paddle is released, typically after a hold event.
      default: []
      selector:
        action: {}
    release_off:
      name: Release off paddle
      description: Action to execute when the off paddle is released, typically after a hold event.
      default: []
      selector:
        action: {}

    tap_favorite:
      name: Tap the favorite button
      description: Action to run when the favorite button is pressed.
      default: []
      selector:
        action: {}

    tap_on_1x:
      name: Tap the on paddle once
      description: Action to run when the on paddle is pressed.
      default: []
      selector:
        action: {}
    tap_off_1x:
      name: Tap the off paddle once
      description: Action to run when the off paddle is pressed.
      default: []
      selector:
        action: {}

    tap_on_2x:
      name: Tap the on paddle twice
      description: Action to run when the on paddle is quickly pressed twice.
      default: []
      selector:
        action: {}
    tap_off_2x:
      name: Tap the off paddle twice
      description: Action to run when the off paddle is quickly pressed twice.
      default: []
      selector:
        action: {}

    tap_on_3x:
      name: Tap the on paddle 3 times
      description: Action to run when the on paddle is quickly pressed 3 times.
      default: []
      selector:
        action: {}
    tap_off_3x:
      name: Tap the off paddle 3 times
      description: Action to run when the off paddle is quickly pressed 3 times.
      default: []
      selector:
        action: {}

    tap_on_4x:
      name: Tap the on paddle 4 times
      description: Action to run when the on paddle is quickly pressed 4 times.
      default: []
      selector:
        action: {}
    tap_off_4x:
      name: Tap the off paddle 4 times
      description: Action to run when the off paddle is quickly pressed 4 times.
      default: []
      selector:
        action: {}

    tap_on_5x:
      name: Tap the on paddle 5 times
      description: Action to run when the on paddle is quickly pressed 5 times.
      default: []
      selector:
        action: {}
    tap_off_5x:
      name: Tap the off paddle 5 times
      description: Action to run when the off paddle is quickly pressed 5 times.
      default: []
      selector:
        action: {}

initial_state: true
max_exceeded: silent
mode: "queued"

trigger:
  - platform: event
    event_type: "zwave_js_value_notification"
    event_data:
      node_id: !input node_id

variables:
  action_type: "{{ trigger.event.data.value }}"
  button: "{{ trigger.event.data.property_key }}"

  favorite_button: "003"
  off_button: "001"
  on_button: "002"

action:
  - choose:
      # Tap 1x
      - conditions: "{{ action_type == 'KeyPressed' }}"
        sequence:
          - choose:
              - conditions: "{{ button == on_button }}"
                sequence: !input tap_on_1x
              - conditions: "{{ button == off_button }}"
                sequence: !input tap_off_1x
              - conditions: "{{ button == favorite_button }}"
                sequence: !input tap_favorite

      # Hold
      - conditions: "{{ action_type == 'KeyHeldDown' }}"
        sequence:
          - choose:
              - conditions: "{{ button == on_button }}"
                sequence: !input hold_on
              - conditions: "{{ button == off_button }}"
                sequence: !input hold_off

      # Release
      - conditions: "{{ action_type == 'KeyReleased' }}"
        sequence:
          - choose:
              - conditions: "{{ button == on_button }}"
                sequence: !input release_on
              - conditions: "{{ button == off_button }}"
                sequence: !input release_off

      # Tap 2x
      - conditions: "{{ action_type == 'KeyPressed2x' }}"
        sequence:
          - choose:
              - conditions: "{{ button == on_button }}"
                sequence: !input tap_on_2x
              - conditions: "{{ button == off_button }}"
                sequence: !input tap_off_2x

      # Tap 3x
      - conditions: "{{ action_type == 'KeyPressed3x' }}"
        sequence:
          - choose:
              - conditions: "{{ button == on_button }}"
                sequence: !input tap_on_3x
              - conditions: "{{ button == off_button }}"
                sequence: !input tap_off_3x

      # Tap 4x
      - conditions: "{{ action_type == 'KeyPressed4x' }}"
        sequence:
          - choose:
              - conditions: "{{ button == on_button }}"
                sequence: !input tap_on_4x
              - conditions: "{{ button == off_button }}"
                sequence: !input tap_off_4x

      # Tap 5x
      - conditions: "{{ action_type == 'KeyPressed5x' }}"
        sequence:
          - choose:
              - conditions: "{{ button == on_button }}"
                sequence: !input tap_on_5x
              - conditions: "{{ button == off_button }}"
                sequence: !input tap_off_5x
