# https://products.z-wavealliance.org/products/2930

blueprint:
  name: Jasco 2 Button Hub/Panel Remote
  description: >
    Associate actions to scenes from Jasco 2 Button Hub/Panel Remote.
  domain: automation
  input:
    node_id:
      name: Node ID
      description: Listen to scene events from this Node ID.
      selector:
        number:
          min: 2
          max: 254
          mode: box

    tap_on_1x:
      name: Tap the on paddle once
      description: Action to run when the on paddle is pressed.
      default: []
      selector:
        action: {}
    tap_off_1x:
      name: Tap the off paddle once
      description: Action to run when the off paddle is pressed.
      default: []
      selector:
        action: {}

    tap_on_2x:
      name: Tap the on paddle twice
      description: Action to run when the on paddle is quickly pressed twice.
      default: []
      selector:
        action: {}
    tap_off_2x:
      name: Tap the off paddle twice
      description: Action to run when the off paddle is quickly pressed twice.
      default: []
      selector:
        action: {}

    tap_on_3x:
      name: Tap the on paddle 3 times
      description: Action to run when the on paddle is quickly pressed 3 times.
      default: []
      selector:
        action: {}
    tap_off_3x:
      name: Tap the off paddle 3 times
      description: Action to run when the off paddle is quickly pressed 3 times.
      default: []
      selector:
        action: {}

initial_state: true
max_exceeded: silent
mode: "queued"

trigger:
  - platform: event
    event_type: "zwave_js_value_notification"
    event_data:
      node_id: !input node_id

variables:
  action_type: "{{ trigger.event.data.value }}"
  button: "{{ trigger.event.data.property_key }}"
  off_button: "002"
  on_button: "001"

action:
  - choose:
      # Tap 1x
      - conditions: "{{ action_type == 'KeyPressed' }}"
        sequence:
          - choose:
              - conditions: "{{ button == on_button }}"
                sequence: !input tap_on_1x
              - conditions: "{{ button == off_button }}"
                sequence: !input tap_off_1x

      # Tap 2x
      - conditions: "{{ action_type == 'KeyPressed2x' }}"
        sequence:
          - choose:
              - conditions: "{{ button == on_button }}"
                sequence: !input tap_on_2x
              - conditions: "{{ button == off_button }}"
                sequence: !input tap_off_2x

      # Tap 3x
      - conditions: "{{ action_type == 'KeyPressed3x' }}"
        sequence:
          - choose:
              - conditions: "{{ button == on_button }}"
                sequence: !input tap_on_3x
              - conditions: "{{ button == off_button }}"
                sequence: !input tap_off_3x
