homeassistant:
  customize:
    binary_sensor.carl_requires_attention:
      friendly_name: "Carl requires attention"
    switch.carl_heater:
      icon: "mdi:radiator"
    switch.carl_uv_light:
      icon: "mdi:weather-sunny"

input_boolean:
  carl_scheduled_lights:
    name: "Automate Carl's terrarium"
    icon: "mdi:home-automation"

input_datetime:
  carl_day_time:
    name: Time at which Carl's terrarium lights turn on
    has_date: false
    has_time: true
  carl_night_time:
    name: Time at which Carl's terrarium lights turn off
    has_date: false
    has_time: true

template:
  - binary_sensor:
      - unique_id: "binary_sensor.carl_requires_attention"
        name: "carl_requires_attention"
        device_class: "problem"
        picture: "/local/animals/carl_avatar.jpg"
        attributes:
          scheduling: "{{ is_state('input_boolean.carl_scheduled_lights', 'on') }}"
        state: >-
          {{
            not this.attributes.scheduling | default(True)
          }}

automation:
  - id: "b61cbb0c-2aa9-4094-959e-a5eb20037f52"
    alias: carl_scheduling
    use_blueprint:
      path: "terrarium_scheduling.yaml"
      input:
        scheduling_entity: "input_boolean.carl_scheduled_lights"
        day_time_entity: "input_datetime.carl_day_time"
        night_time_entity: "input_datetime.carl_night_time"
        heater_switch: "switch.carl_heater"
        uv_light_switch: "switch.carl_uv_light"
