homeassistant:
  customize:
    plant.dollorama:
      friendly_name: "Dollorama"
    sensor.dollorama_battery:
      friendly_name: "Dollorama's battery"
      battery_type: "CR2032"
      battery_warning_level: 20
    sensor.dollorama_brightness:
      friendly_name: "Dollorama's brightness"
    sensor.dollorama_conductivity:
      friendly_name: "Dollorama's conductivity"
    sensor.dollorama_moisture:
      friendly_name: "Dollorama's moisture"
    sensor.dollorama_temperature:
      friendly_name: "Dollorama's temperature"

plant:
  dollorama:
    sensors:
      battery: "sensor.dollorama_battery"
      brightness: "sensor.dollorama_brightness"
      conductivity: "sensor.dollorama_conductivity"
      moisture: "sensor.dollorama_moisture"
      temperature: "sensor.dollorama_temperature"
    min_battery: 15
    min_conductivity: 0  # 35
    max_conductivity: 9999
    min_moisture: 10
    max_moisture: 60
    min_temperature: 10
