homeassistant:
  customize:
    plant.dollorama:
      friendly_name: "Dollorama"
    sensor.dollorama_battery:
      friendly_name: "Dollorama's battery"
      battery_type: "CR2032"
      battery_warning_level: 20
    sensor.dollorama_brightness:
      friendly_name: "Dollorama's brightness"
    sensor.dollorama_conductivity:
      friendly_name: "Dollorama's conductivity"
    sensor.dollorama_moisture:
      friendly_name: "Dollorama's moisture"
    sensor.dollorama_temperature:
      friendly_name: "Dollorama's temperature"

plant:
  dollorama:
    sensors:
      battery: "sensor.dollorama_battery"
      brightness: "sensor.dollorama_brightness"
      conductivity: "sensor.dollorama_conductivity"
      moisture: "sensor.dollorama_moisture"
      temperature: "sensor.dollorama_temperature"
    min_battery: 15
    min_conductivity: 0  # 35
    max_conductivity: 9999
    min_moisture: 10
    max_moisture: 60
    min_temperature: 10

template:
  sensor:
    - unique_id: "sensor.dollorama_problems"
      name: "dollorama_problems"
      state: "{{ state_attr('plant.dollorama', 'problem') or 'none' }}"
      attributes:
        friendly_name: "Dollorama"

sensor:
  - platform: mqtt
    name: "dollorama_battery"
    force_update: true
    device_class: "battery"
    unit_of_measurement: "%"
    state_topic: &state_topic "plants/dollorama"
    value_template: "{{ value_json.battery | int('unknown') }}"
    json_attributes_topic: *state_topic
    json_attributes_template: "{{ { 'last_update': value_json.timestamp } | tojson }}"
  - platform: mqtt
    name: "dollorama_brightness"
    force_update: true
    device_class: "illuminance"
    unit_of_measurement: "lx"
    state_topic: *state_topic
    value_template: "{{ value_json.brightness | int('unknown') }}"
    json_attributes_topic: *state_topic
    json_attributes_template: "{{ { 'last_update': value_json.timestamp } | tojson }}"
  - platform: mqtt
    name: "dollorama_conductivity"
    force_update: true
    unit_of_measurement: "µS/cm"
    icon: "mdi:poop"
    state_topic: *state_topic
    value_template: "{{ value_json.conductivity | int('unknown') }}"
    json_attributes_topic: *state_topic
    json_attributes_template: "{{ { 'last_update': value_json.timestamp } | tojson }}"
  - platform: mqtt
    name: "dollorama_moisture"
    force_update: true
    device_class: "humidity"
    unit_of_measurement: "%"
    state_topic: *state_topic
    value_template: "{{ value_json.moisture | int('unknown') }}"
    json_attributes_topic: *state_topic
    json_attributes_template: "{{ { 'last_update': value_json.timestamp } | tojson }}"
  - platform: mqtt
    name: "dollorama_temperature"
    force_update: true
    device_class: "temperature"
    unit_of_measurement: "°C"
    state_topic: *state_topic
    value_template: "{{ value_json.temperature | float('unknown') }}"
    json_attributes_topic: *state_topic
    json_attributes_template: "{{ { 'last_update': value_json.timestamp } | tojson }}"
