homeassistant:
  customize:
    plant.drake:
      friendly_name: "Drake"
    sensor.drake_battery:
      friendly_name: "Drake's battery"
      battery_type: "CR2032"
      battery_warning_level: 20
    sensor.drake_brightness:
      friendly_name: "Drake's brightness"
    sensor.drake_conductivity:
      friendly_name: "Drake's conductivity"
    sensor.drake_moisture:
      friendly_name: "Drake's moisture"
    sensor.drake_temperature:
      friendly_name: "Drake's temperature"

plant:
  drake:
    sensors:
      battery: "sensor.drake_battery"
      brightness: "sensor.drake_brightness"
      conductivity: "sensor.drake_conductivity"
      moisture: "sensor.drake_moisture"
      temperature: "sensor.drake_temperature"
    min_battery: 15
    min_conductivity: 0  # 200
    max_conductivity: 9999  # 1500
    min_moisture: 15
    max_moisture: 60
    min_temperature: 10
    max_temperature: 35

sensor:
  - platform: mqtt
    name: "drake_battery"
    force_update: true
    device_class: "battery"
    unit_of_measurement: "%"
    state_topic: &state_topic "plants/drake"
    value_template: "{{ value_json.battery | int('unknown') }}"
    json_attributes_topic: *state_topic
    json_attributes_template: "{{ { 'last_update': value_json.timestamp } | tojson }}"
  - platform: mqtt
    name: "drake_brightness"
    force_update: true
    device_class: "illuminance"
    unit_of_measurement: "lx"
    state_topic: *state_topic
    value_template: "{{ value_json.brightness | int('unknown') }}"
    json_attributes_topic: *state_topic
    json_attributes_template: "{{ { 'last_update': value_json.timestamp } | tojson }}"
  - platform: mqtt
    name: "drake_conductivity"
    force_update: true
    unit_of_measurement: "µS/cm"
    icon: "mdi:poop"
    state_topic: *state_topic
    value_template: "{{ value_json.conductivity | int('unknown') }}"
    json_attributes_topic: *state_topic
    json_attributes_template: "{{ { 'last_update': value_json.timestamp } | tojson }}"
  - platform: mqtt
    name: "drake_moisture"
    force_update: true
    device_class: "humidity"
    unit_of_measurement: "%"
    state_topic: *state_topic
    value_template: "{{ value_json.moisture | int('unknown') }}"
    json_attributes_topic: *state_topic
    json_attributes_template: "{{ { 'last_update': value_json.timestamp } | tojson }}"
  - platform: mqtt
    name: "drake_temperature"
    force_update: true
    device_class: "temperature"
    unit_of_measurement: "°C"
    state_topic: *state_topic
    value_template: "{{ value_json.temperature | float('unknown') }}"
    json_attributes_topic: *state_topic
    json_attributes_template: "{{ { 'last_update': value_json.timestamp } | tojson }}"
