homeassistant:
  customize:
    plant.drake:
      friendly_name: "Drake"
    sensor.drake_battery:
      friendly_name: "Drake's battery"
      battery_type: "CR2032"
      battery_warning_level: 20
    sensor.drake_brightness:
      friendly_name: "Drake's brightness"
    sensor.drake_conductivity:
      friendly_name: "Drake's conductivity"
    sensor.drake_moisture:
      friendly_name: "Drake's moisture"
    sensor.drake_temperature:
      friendly_name: "Drake's temperature"

plant:
  drake:
    sensors:
      battery: "sensor.drake_battery"
      brightness: "sensor.drake_brightness"
      conductivity: "sensor.drake_conductivity"
      moisture: "sensor.drake_moisture"
      temperature: "sensor.drake_temperature"
    min_battery: 15
    min_conductivity: 0  # 200
    max_conductivity: 9999  # 1500
    min_moisture: 5
    max_moisture: 60
    min_temperature: 10
    max_temperature: 35
