homeassistant:
  customize:
    plant.maitre_doyle:
      friendly_name: "Maître Doyle"
    sensor.maitre_doyle_battery:
      friendly_name: "Maître Doyle's battery"
      battery_type: "CR2032"
      battery_warning_level: 20
    sensor.maitre_doyle_brightness:
      friendly_name: "Maître Doyle's brightness"
    sensor.maitre_doyle_conductivity:
      friendly_name: "Maître Doyle's conductivity"
    sensor.maitre_doyle_moisture:
      friendly_name: "Maître Doyle's moisture"
    sensor.maitre_doyle_temperature:
      friendly_name: "Maître Doyle's temperature"

plant:
  maitre_doyle:
    sensors:
      battery: "sensor.maitre_doyle_battery"
      brightness: "sensor.maitre_doyle_brightness"
      conductivity: "sensor.maitre_doyle_conductivity"
      moisture: "sensor.maitre_doyle_moisture"
      temperature: "sensor.maitre_doyle_temperature"
    min_battery: 15
    min_conductivity: 0  # 30
    max_conductivity: 9999
    min_moisture: 15
    max_moisture: 50
    min_temperature: 15
