homeassistant:
  customize:
    plant.maitre_doyle:
      friendly_name: "Maître Doyle"
    sensor.maitre_doyle_battery:
      friendly_name: "Maître Doyle's battery"
      battery_type: "CR2032"
      battery_warning_level: 20
    sensor.maitre_doyle_brightness:
      friendly_name: "Maître Doyle's brightness"
    sensor.maitre_doyle_conductivity:
      friendly_name: "Maître Doyle's conductivity"
    sensor.maitre_doyle_moisture:
      friendly_name: "Maître Doyle's moisture"
    sensor.maitre_doyle_temperature:
      friendly_name: "Maître Doyle's temperature"

plant:
  maitre_doyle:
    sensors:
      battery: "sensor.maitre_doyle_battery"
      brightness: "sensor.maitre_doyle_brightness"
      conductivity: "sensor.maitre_doyle_conductivity"
      moisture: "sensor.maitre_doyle_moisture"
      temperature: "sensor.maitre_doyle_temperature"
    min_battery: 15
    min_conductivity: 0  # 30
    max_conductivity: 9999
    min_moisture: 15
    max_moisture: 50
    min_temperature: 15

sensor:
  - platform: template
    sensors:
      maitre_doyle_problems:
        friendly_name: "Maître Doyle"
        value_template: "{{ state_attr('plant.maitre_doyle', 'problem') or 'none' }}"

  - platform: mqtt
    name: "maitre_doyle_battery"
    force_update: true
    device_class: "battery"
    unit_of_measurement: "%"
    state_topic: &maitre_doyle_topic "plants/maitre_doyle"
    value_template: "{{ value_json.battery | int('unknown') }}"
    json_attributes_topic: *maitre_doyle_topic
    json_attributes_template: "{{ { 'last_update': value_json.timestamp } | tojson }}"
  - platform: mqtt
    name: "maitre_doyle_brightness"
    force_update: true
    device_class: "illuminance"
    unit_of_measurement: "lx"
    state_topic: *maitre_doyle_topic
    value_template: "{{ value_json.brightness | int('unknown') }}"
    json_attributes_topic: *maitre_doyle_topic
    json_attributes_template: "{{ { 'last_update': value_json.timestamp } | tojson }}"
  - platform: mqtt
    name: "maitre_doyle_conductivity"
    force_update: true
    unit_of_measurement: "µS/cm"
    icon: "mdi:poop"
    state_topic: *maitre_doyle_topic
    value_template: "{{ value_json.conductivity | int('unknown') }}"
    json_attributes_topic: *maitre_doyle_topic
    json_attributes_template: "{{ { 'last_update': value_json.timestamp } | tojson }}"
  - platform: mqtt
    name: "maitre_doyle_moisture"
    force_update: true
    device_class: "humidity"
    unit_of_measurement: "%"
    state_topic: *maitre_doyle_topic
    value_template: "{{ value_json.moisture | int('unknown') }}"
    json_attributes_topic: *maitre_doyle_topic
    json_attributes_template: "{{ { 'last_update': value_json.timestamp } | tojson }}"
  - platform: mqtt
    name: "maitre_doyle_temperature"
    force_update: true
    device_class: "temperature"
    unit_of_measurement: "°C"
    state_topic: *maitre_doyle_topic
    value_template: "{{ value_json.temperature | float('unknown') }}"
    json_attributes_topic: *maitre_doyle_topic
    json_attributes_template: "{{ { 'last_update': value_json.timestamp } | tojson }}"
