homeassistant:
  customize:
    plant.rubber_ducky:
      friendly_name: "Rubber Ducky"
    sensor.rubber_ducky_battery:
      friendly_name: "Rubber Ducky's battery"
      battery_type: "CR2032 3V"
    sensor.rubber_ducky_brightness:
      friendly_name: "Rubber Ducky's brightness"
    sensor.rubber_ducky_conductivity:
      friendly_name: "Rubber Ducky's conductivity"
    sensor.rubber_ducky_moisture:
      friendly_name: "Rubber Ducky's moisture"
    sensor.rubber_ducky_temperature:
      friendly_name: "Rubber Ducky's temperature"

plant:
  rubber_ducky:
    sensors:
      battery: "sensor.rubber_ducky_battery"
      brightness: "sensor.rubber_ducky_brightness"
      conductivity: "sensor.rubber_ducky_conductivity"
      moisture: "sensor.rubber_ducky_moisture"
      temperature: "sensor.rubber_ducky_temperature"
    min_battery: 15
    min_moisture: 7
    max_moisture: 40
    min_temperature: 8
    # max_temperature: 35
    # min_conductivity: 50

sensor:
  - platform: template
    sensors:
      rubber_ducky_problems:
        friendly_name: "Rubber Ducky"
        value_template: "{{ state_attr('plant.rubber_ducky', 'problem') or 'none' }}"

  - platform: mqtt
    name: "rubber_ducky_battery"
    force_update: True
    device_class: "battery"
    unit_of_measurement: "%"
    state_topic: &rubber_ducky_topic "plants/rubber_ducky"
    value_template: "{{ value_json.battery | int('unknown') }}"
    json_attributes_topic: *rubber_ducky_topic
    json_attributes_template: "{{ { 'last_update': value_json.timestamp } | tojson }}"
  - platform: mqtt
    name: "rubber_ducky_brightness"
    force_update: True
    device_class: "illuminance"
    unit_of_measurement: "lx"
    state_topic: *rubber_ducky_topic
    value_template: "{{ value_json.brightness | int('unknown') }}"
    json_attributes_topic: *rubber_ducky_topic
    json_attributes_template: "{{ { 'last_update': value_json.timestamp } | tojson }}"
  - platform: mqtt
    name: "rubber_ducky_conductivity"
    force_update: True
    unit_of_measurement: "µS/cm"
    icon: "mdi:poop"
    state_topic: *rubber_ducky_topic
    value_template: "{{ value_json.conductivity | int('unknown') }}"
    json_attributes_topic: *rubber_ducky_topic
    json_attributes_template: "{{ { 'last_update': value_json.timestamp } | tojson }}"
  - platform: mqtt
    name: "rubber_ducky_moisture"
    force_update: True
    device_class: "humidity"
    unit_of_measurement: "%"
    state_topic: *rubber_ducky_topic
    value_template: "{{ value_json.moisture | int('unknown') }}"
    json_attributes_topic: *rubber_ducky_topic
    json_attributes_template: "{{ { 'last_update': value_json.timestamp } | tojson }}"
  - platform: mqtt
    name: "rubber_ducky_temperature"
    force_update: True
    device_class: "temperature"
    unit_of_measurement: "°C"
    state_topic: *rubber_ducky_topic
    value_template: "{{ value_json.temperature | float('unknown') }}"
    json_attributes_topic: *rubber_ducky_topic
    json_attributes_template: "{{ { 'last_update': value_json.timestamp } | tojson }}"
