homeassistant:
  customize:
    plant.snicket:
      friendly_name: "Snicket"
    sensor.snicket_battery:
      friendly_name: "Snicket's battery"
      battery_type: "CR2032"
      battery_warning_level: 20
    sensor.snicket_brightness:
      friendly_name: "Snicket's brightness"
    sensor.snicket_conductivity:
      friendly_name: "Snicket's conductivity"
    sensor.snicket_moisture:
      friendly_name: "Snicket's moisture"
    sensor.snicket_temperature:
      friendly_name: "Snicket's temperature"

plant:
  snicket:
    sensors:
      battery: "sensor.snicket_battery"
      brightness: "sensor.snicket_brightness"
      conductivity: "sensor.snicket_conductivity"
      moisture: "sensor.snicket_moisture"
      temperature: "sensor.snicket_temperature"
    min_battery: 15
    min_conductivity: 0  # 350
    max_conductivity: 9999
    min_moisture: 15
    max_moisture: 60
    min_temperature: 8
    max_temperature: 35
