homeassistant:
  customize:
    plant.snicket:
      friendly_name: "Snicket"
    sensor.snicket_battery:
      friendly_name: "Snicket's battery"
      battery_type: "CR2032"
      battery_warning_level: 20
    sensor.snicket_brightness:
      friendly_name: "Snicket's brightness"
    sensor.snicket_conductivity:
      friendly_name: "Snicket's conductivity"
    sensor.snicket_moisture:
      friendly_name: "Snicket's moisture"
    sensor.snicket_temperature:
      friendly_name: "Snicket's temperature"

plant:
  snicket:
    sensors:
      battery: "sensor.snicket_battery"
      brightness: "sensor.snicket_brightness"
      conductivity: "sensor.snicket_conductivity"
      moisture: "sensor.snicket_moisture"
      temperature: "sensor.snicket_temperature"
    min_battery: 15
    min_conductivity: 0  # 350
    max_conductivity: 9999
    min_moisture: 15
    max_moisture: 60
    min_temperature: 8
    max_temperature: 35

sensor:
  - platform: template
    sensors:
      snicket_problems:
        unique_id: "sensor.snicket_problems"
        friendly_name: "Snicket"
        value_template: "{{ state_attr('plant.snicket', 'problem') or 'none' }}"

  - platform: mqtt
    name: "snicket_battery"
    force_update: true
    device_class: "battery"
    unit_of_measurement: "%"
    state_topic: &state_topic "plants/snicket"
    value_template: "{{ value_json.battery | int('unknown') }}"
    json_attributes_topic: *state_topic
    json_attributes_template: "{{ { 'last_update': value_json.timestamp } | tojson }}"
  - platform: mqtt
    name: "snicket_brightness"
    force_update: true
    device_class: "illuminance"
    unit_of_measurement: "lx"
    state_topic: *state_topic
    value_template: "{{ value_json.brightness | int('unknown') }}"
    json_attributes_topic: *state_topic
    json_attributes_template: "{{ { 'last_update': value_json.timestamp } | tojson }}"
  - platform: mqtt
    name: "snicket_conductivity"
    force_update: true
    unit_of_measurement: "µS/cm"
    icon: "mdi:poop"
    state_topic: *state_topic
    value_template: "{{ value_json.conductivity | int('unknown') }}"
    json_attributes_topic: *state_topic
    json_attributes_template: "{{ { 'last_update': value_json.timestamp } | tojson }}"
  - platform: mqtt
    name: "snicket_moisture"
    force_update: true
    device_class: "humidity"
    unit_of_measurement: "%"
    state_topic: *state_topic
    value_template: "{{ value_json.moisture | int('unknown') }}"
    json_attributes_topic: *state_topic
    json_attributes_template: "{{ { 'last_update': value_json.timestamp } | tojson }}"
  - platform: mqtt
    name: "snicket_temperature"
    force_update: true
    device_class: "temperature"
    unit_of_measurement: "°C"
    state_topic: *state_topic
    value_template: "{{ value_json.temperature | float('unknown') }}"
    json_attributes_topic: *state_topic
    json_attributes_template: "{{ { 'last_update': value_json.timestamp } | tojson }}"
