homeassistant:
  customize:
    plant.spidy:
      friendly_name: "Spidy"
    sensor.spidy_battery:
      friendly_name: "Spidy's battery"
      battery_type: "CR2032"
      battery_warning_level: 20
    sensor.spidy_brightness:
      friendly_name: "Spidy's brightness"
    sensor.spidy_conductivity:
      friendly_name: "Spidy's conductivity"
    sensor.spidy_moisture:
      friendly_name: "Spidy's moisture"
    sensor.spidy_temperature:
      friendly_name: "Spidy's temperature"

plant:
  spidy:
    sensors:
      battery: "sensor.spidy_battery"
      brightness: "sensor.spidy_brightness"
      conductivity: "sensor.spidy_conductivity"
      moisture: "sensor.spidy_moisture"
      temperature: "sensor.spidy_temperature"
    min_battery: 15
    min_conductivity: 0  # 30
    max_conductivity: 9999
    min_moisture: 10
    max_moisture: 60
    min_temperature: 16
