homeassistant:
  customize:
    plant.spidy:
      friendly_name: "Spidy"
    sensor.spidy_battery:
      friendly_name: "Spidy's battery"
      battery_type: "CR2032"
      battery_warning_level: 20
    sensor.spidy_brightness:
      friendly_name: "Spidy's brightness"
    sensor.spidy_conductivity:
      friendly_name: "Spidy's conductivity"
    sensor.spidy_moisture:
      friendly_name: "Spidy's moisture"
    sensor.spidy_temperature:
      friendly_name: "Spidy's temperature"

plant:
  spidy:
    sensors:
      battery: "sensor.spidy_battery"
      brightness: "sensor.spidy_brightness"
      conductivity: "sensor.spidy_conductivity"
      moisture: "sensor.spidy_moisture"
      temperature: "sensor.spidy_temperature"
    min_battery: 15
    min_conductivity: 0  # 30
    max_conductivity: 9999
    min_moisture: 10
    max_moisture: 60
    min_temperature: 16

sensor:
  - platform: template
    sensors:
      spidy_problems:
        unique_id: "sensor.spidy_problems"
        friendly_name: "Spidy"
        value_template: "{{ state_attr('plant.spidy', 'problem') or 'none' }}"

  - platform: mqtt
    name: "spidy_battery"
    force_update: true
    device_class: "battery"
    unit_of_measurement: "%"
    state_topic: &state_topic "plants/spidy"
    value_template: "{{ value_json.battery | int('unknown') }}"
    json_attributes_topic: *state_topic
    json_attributes_template: "{{ { 'last_update': value_json.timestamp } | tojson }}"
  - platform: mqtt
    name: "spidy_brightness"
    force_update: true
    device_class: "illuminance"
    unit_of_measurement: "lx"
    state_topic: *state_topic
    value_template: "{{ value_json.brightness | int('unknown') }}"
    json_attributes_topic: *state_topic
    json_attributes_template: "{{ { 'last_update': value_json.timestamp } | tojson }}"
  - platform: mqtt
    name: "spidy_conductivity"
    force_update: true
    unit_of_measurement: "µS/cm"
    icon: "mdi:poop"
    state_topic: *state_topic
    value_template: "{{ value_json.conductivity | int('unknown') }}"
    json_attributes_topic: *state_topic
    json_attributes_template: "{{ { 'last_update': value_json.timestamp } | tojson }}"
  - platform: mqtt
    name: "spidy_moisture"
    force_update: true
    device_class: "humidity"
    unit_of_measurement: "%"
    state_topic: *state_topic
    value_template: "{{ value_json.moisture | int('unknown') }}"
    json_attributes_topic: *state_topic
    json_attributes_template: "{{ { 'last_update': value_json.timestamp } | tojson }}"
  - platform: mqtt
    name: "spidy_temperature"
    force_update: true
    device_class: "temperature"
    unit_of_measurement: "°C"
    state_topic: *state_topic
    value_template: "{{ value_json.temperature | float('unknown') }}"
    json_attributes_topic: *state_topic
    json_attributes_template: "{{ { 'last_update': value_json.timestamp } | tojson }}"
