homeassistant:
  customize:
    plant.viny:
      friendly_name: "Viny"
    sensor.viny_battery:
      friendly_name: "Viny's battery"
      battery_type: "CR2032"
      battery_warning_level: 20
    sensor.viny_brightness:
      friendly_name: "Viny's brightness"
    sensor.viny_conductivity:
      friendly_name: "Viny's conductivity"
    sensor.viny_moisture:
      friendly_name: "Viny's moisture"
    sensor.viny_temperature:
      friendly_name: "Viny's temperature"

plant:
  viny:
    sensors:
      battery: "sensor.viny_battery"
      brightness: "sensor.viny_brightness"
      conductivity: "sensor.viny_conductivity"
      moisture: "sensor.viny_moisture"
      temperature: "sensor.viny_temperature"
    min_battery: 15
    min_conductivity: 0  # 30
    max_conductivity: 9999
    min_moisture: 10
    max_moisture: 60
    min_temperature: 15

mqtt:
  sensor:
    - name: "viny_battery"
      force_update: true
      device_class: "battery"
      unit_of_measurement: "%"
      state_topic: &state_topic "plants/viny"
      value_template: "{{ value_json.battery | int('unknown') }}"
      json_attributes_topic: *state_topic
      json_attributes_template: "{{ { 'last_update': value_json.timestamp } | tojson }}"
    - name: "viny_brightness"
      force_update: true
      device_class: "illuminance"
      unit_of_measurement: "lx"
      state_topic: *state_topic
      value_template: "{{ value_json.brightness | int('unknown') }}"
      json_attributes_topic: *state_topic
      json_attributes_template: "{{ { 'last_update': value_json.timestamp } | tojson }}"
    - name: "viny_conductivity"
      force_update: true
      unit_of_measurement: "µS/cm"
      icon: "mdi:poop"
      state_topic: *state_topic
      value_template: "{{ value_json.conductivity | int('unknown') }}"
      json_attributes_topic: *state_topic
      json_attributes_template: "{{ { 'last_update': value_json.timestamp } | tojson }}"
    - name: "viny_moisture"
      force_update: true
      device_class: "humidity"
      unit_of_measurement: "%"
      state_topic: *state_topic
      value_template: "{{ value_json.moisture | int('unknown') }}"
      json_attributes_topic: *state_topic
      json_attributes_template: "{{ { 'last_update': value_json.timestamp } | tojson }}"
    - name: "viny_temperature"
      force_update: true
      device_class: "temperature"
      unit_of_measurement: "°C"
      state_topic: *state_topic
      value_template: "{{ value_json.temperature | float('unknown') }}"
      json_attributes_topic: *state_topic
      json_attributes_template: "{{ { 'last_update': value_json.timestamp } | tojson }}"
