homeassistant:
  customize:
    plant.viny:
      friendly_name: "Viny"
    sensor.viny_battery:
      friendly_name: "Viny's battery"
      battery_type: "CR2032"
      battery_warning_level: 20
    sensor.viny_brightness:
      friendly_name: "Viny's brightness"
    sensor.viny_conductivity:
      friendly_name: "Viny's conductivity"
    sensor.viny_moisture:
      friendly_name: "Viny's moisture"
    sensor.viny_temperature:
      friendly_name: "Viny's temperature"

plant:
  viny:
    sensors:
      battery: "sensor.viny_battery"
      brightness: "sensor.viny_brightness"
      conductivity: "sensor.viny_conductivity"
      moisture: "sensor.viny_moisture"
      temperature: "sensor.viny_temperature"
    min_battery: 15
    min_conductivity: 0  # 30
    max_conductivity: 9999
    min_moisture: 10
    max_moisture: 60
    min_temperature: 15
