input_boolean:
  force_presence_armed:
    name: "Force armed"
    icon: "mdi:shield-check"
  silence_alarm:
    name: "Silence alarm"
    icon: "mdi:volume-mute"
    initial: false

template:
  binary_sensor:
    - unique_id: "449f4beb-83a1-43d2-a7ba-64de0a305960"
      name: "presence_armed"
      icon: >-
        {% if is_state('binary_sensor.presence_armed', 'on') -%}
          mdi:shield-check
        {%- else -%}
          mdi:shield-off
        {%- endif %}
      state: >-
        {{
          is_state('input_boolean.force_presence_armed', 'on')
            or not is_state('group.household', 'home')
            and is_state('binary_sensor.guest_mode', 'off')
        }}
      attributes:
        friendly_name: "Armed"

    - unique_id: "ccc872ad-92f9-4b3e-87a5-452292b6b118"
      name: "intrusion"
      device_class: "safety"
      delay_on: 15
      delay_off: 15
      attributes:
        friendly_name: "Intrusion"
        activity: >-
          {% set armed = states.binary_sensor.presence_armed -%}
          {% if armed is not none and armed.state == 'on' -%}
            {% set armed_since = armed.last_changed -%}
            {% set changed_since_armed = expand('group.all_windows', 'group.all_doors', 'group.all_motions')
                | selectattr('last_changed', '>=', armed_since)
                | map(attribute = 'entity_id')
                | list -%}
            {% set intrusion_events = state_attr('binary_sensor.intrusion_events', 'entity_id')
                | default([], True)
                | list -%}
            {{ (changed_since_armed + intrusion_events) | unique | sort -}}
          {% else -%}
            {{ state_attr('binary_sensor.intrusion', 'activity') | default([], True) -}}
          {% endif %}
      availability: >-
        {{ states.binary_sensor.presence_armed is not none }}
      icon: >-
        {%- if is_state('binary_sensor.intrusion', 'on') -%}
          mdi:shield-alert
        {%- elif is_state('binary_sensor.presence_armed', 'on') -%}
          mdi:shield-check
        {%- else -%}
          mdi:shield-off
        {%- endif %}
      state: >-
        {% set armed = states.binary_sensor.presence_armed -%}
        {{
          armed is not none
            and armed.state == 'on'
            and (
              is_state('binary_sensor.intrusion_events', 'on')
                or expand('group.all_windows', 'group.all_doors', 'group.all_motions')
                  | selectattr('last_changed', '>=', armed.last_changed)
                  | first is defined
            )
        }}

binary_sensor:
  - platform: mqtt
    name: "intrusion_events"
    device_class: "safety"
    state_topic: &actifity_events_topic "home-assistant/intrusion/events"
    value_template: "{{ value_json.state }}"
    payload_on: "on"
    payload_off: "off"
    json_attributes_topic: *actifity_events_topic
    json_attributes_template: "{{ value_json.attributes | to_json }}"

automation:
  - id: "2c7d9807-9f19-4b55-b944-17005a27e6c0"
    alias: "reset_alarm_states"
    initial_state: true
    trigger:
      - platform: state
        entity_id: "binary_sensor.presence_armed"
        from: "off"
        to: "on"
    action:
      - service: input_boolean.turn_off
        entity_id: "input_boolean.silence_alarm"
      - service: mqtt.publish
        data:
          topic: *actifity_events_topic
          qos: 1
          retain: false
          payload: >-
            {
              "state": "off",
              "attributes": { "entity_id": [], "node_id": [] }
            }

  - id: "6edc94d0-d9f9-44eb-bad1-6873523ae9e8"
    alias: "armed_switch_paddle_tapped"
    initial_state: true
    mode: "parallel"

    trigger:
      - platform: event
        event_type: "ozw.scene_activated"

    variables:
      node_id: "{{ trigger.event.data.node_id | int }}"
      scene_value_id: "{{ trigger.event.data.scene_value_id | int(None) }}"
      entity_id: >
        {{
          states
            | selectattr('attributes.node_id', '==', node_id)
            | selectattr('domain', 'in', ['switch', 'light'])
            | sort(attribute = 'attributes.friendly_name')
            | map(attribute = 'entity_id')
            | first
            | default('', True)
        }}

    condition:
      - condition: state
        entity_id: "binary_sensor.presence_armed"
        state: "on"
        # 0: inactive. This is fired after each scene event by OZW.
      - "{{ entity_id != '' and scene_value_id == 0 }}"

    action:
      - service: mqtt.publish
        data:
          topic: *actifity_events_topic
          qos: 1
          retain: false
          payload_template: >-
            {% set entities = state_attr('binary_sensor.intrusion_events', 'entity_id') | default([], True) -%}
            {% set nodes = state_attr('binary_sensor.intrusion_events', 'node_id') | default([], True) -%}
            {{ {
              'state': 'on',
              'attributes': {
                'entity_id': entities + [entity_id],
                'node_id': nodes + [node_id],
              }
            } | to_json }}

  - id: "b0045b02-1756-4635-bc2c-4344de74d0b6"
    alias: "notify_intrusion"
    initial_state: true
    mode: "restart"

    trigger:
      - platform: state
        entity_id: "binary_sensor.intrusion"
        from: "off"
        to: "on"

    variables:
      notification_tag: "intrusion_{{ now() | as_timestamp | int }}"

    action:
      - service: python_script.notify
        data:
          <<: &alarm_notification
            audio: false
            persistent: true
            priority: true
            tag: "{{ notification_tag }}"
            message: "Activity was detected in: {{ state_attr('binary_sensor.intrusion', 'activity') }}"
          title: "Intrusion detected"
          push_target: "household"
          push_actions:
            - action: &silence_action "silence_alarm"
              title: "Silence"

      - repeat:
          sequence:
            - service: python_script.notify
              data:
                <<: *alarm_notification
                title: "Intrusion detected"
            - choose:
                - conditions:
                    - condition: state
                      entity_id: "input_boolean.silence_alarm"
                      state: "off"
                  sequence:
                    - service: script.broadcast_notification
                      data:
                        message: "Intrusion detected. Authorities have been notified."
            - delay: 10
          until:
            - condition: state
              entity_id: "binary_sensor.intrusion"
              state: "off"

      - service: python_script.notify
        data:
          <<: *alarm_notification
          push_target: "household"
          title: "Intrusion cleared"

  - id: "65383759-a03c-4c81-9965-7154e83626fd"
    alias: "silence_alarm"
    initial_state: true
    mode: "single"
    max_exceeded: "silent"

    trigger:
      - platform: event
        event_type:
          - "html5_notification.clicked"
          - "mobile_app_notification_action"
        event_data:
          action: *silence_action

    condition:
      - condition: state
        entity_id: "binary_sensor.intrusion"
        state: "on"

    action:
      - service: input_boolean.turn_on
        data:
          entity_id: "input_boolean.silence_alarm"
