homeassistant:
  customize:
    person.chris:
      entity_picture: /local/secrets/chris.webp
    person.karine:
      entity_picture: /local/secrets/karine.webp

person:
  - id: "chris"
    name: "Chris"
    user_id: "221fad543e1a4c05af8aaac8c68e985e"
    device_trackers:
      - device_tracker.chris_router_moto_g7
      - device_tracker.chris_mobile_app_moto_g7
  - id: "karine"
    name: "Karine"
    user_id: "ef6743938a1646d2a1e8706e1bc00e34"
    device_trackers:
      - device_tracker.karine_router_pixel_1
      - device_tracker.karine_mobile_app_pixel_1

group:
  household:
    name: "Household"
    icon: "mdi:account-multiple"
    entities: &household_entities
      - person.chris
      - person.karine
  guests:
    name: "Guests"
    icon: "mdi:account-group"
    entities: &guest_entities
      - person.guest_cava
      - person.guest_gipa
      - person.guest_laboro
      - person.guest_stfr
      - person.guest_syvi

input_boolean:
  force_guest_mode:
    name: "Force guest mode"
    icon: "mdi:human-greeting"
  notify_household_changes:
    name: "Notify household changes"
    icon: "mdi:message-cog"
  notify_individual_guest_arrivals:
    name: "Notify individual guest arrivals"
    icon: "mdi:message-cog"

binary_sensor:
  - platform: template
    sensors:
      guest_mode:
        unique_id: "binary_sensor.guest_mode"
        friendly_name: "Guest mode"
        icon_template: "mdi:human-greeting"
        value_template: >-
          {{
            is_state('input_boolean.force_guest_mode', 'on')
              or is_state('group.household', 'home')
              and state_attr('sensor.guests_home', 'count') | int | default(0) > 0
          }}

sensor:
  - platform: template
    sensors:
      guests_home:
        unique_id: "sensor.guests_home"
        friendly_name: "Guests at home"
        icon_template: "mdi:account-star"
        value_template: >-
          {{
            expand('group.guests')
              | selectattr('state', 'eq', 'home')
              | map('attr', 'name')
              | sort
              | join(', ')
              | default('Nobody', true)
          }}
        attribute_templates:
          count: >-
            {{
              expand('group.guests')
                | selectattr('state', 'eq', 'home')
                | list
                | count
            }}

automation:
  - alias: notify_guest_arrives
    initial_state: true
    mode: "parallel"
    trigger:
      - platform: state
        entity_id: *guest_entities
        to: "home"
    condition: >-
      {{
        is_state('input_boolean.notify_individual_guest_arrivals', 'on')
          or is_state_attr('sensor.guests_home', 'count', '1')
      }}
    action:
      - service: python_script.notify
        data:
          persistent: true
          push_target: "household"
          tag: "presence_{{ trigger.to_state.object_id }}"
          title: "{{ trigger.to_state.name }} is here"
          message: "{{ state_attr('sensor.guests_home', 'count') }} guests are home."

  - alias: notify_household_person_arrives
    initial_state: true
    mode: "parallel"
    trigger:
      - platform: state
        entity_id: *household_entities
        to: "home"
    condition:
      - condition: state
        entity_id: input_boolean.notify_household_changes
        state: "on"
    action:
      - service: python_script.notify
        data:
          push_target: "admin"
          tag: "presence_{{ trigger.to_state.object_id }}"
          title: "{{ trigger.to_state.name }} arrived home."
          message: "Household is {{ states('group.household') }}."

  - alias: notify_household_person_leaves
    initial_state: true
    mode: "parallel"
    trigger:
      - platform: state
        entity_id: *household_entities
        from: "home"
    condition:
      - condition: state
        entity_id: input_boolean.notify_household_changes
        state: "on"
    action:
      - service: python_script.notify
        data:
          push_target: "admin"
          tag: "presence_{{ trigger.to_state.object_id }}"
          title: "{{ trigger.to_state.name }} left home."
          message: "Household is {{ states('group.household') }}."
