homeassistant:
  customize:
    sensor.chris_bedside_remote_battery:
      battery_type: "CR2032"
      battery_warning_level: 25

input_select:
  chris_remote_entity:
    name: "Entity controlled by Chris' remote"
    initial: &default_entity "light.bedside_chris"
    options:
      - "light.bedside_karine"
      - *default_entity
      - "light.master_bedroom_bedsides"
  chris_remote_color:
    name: "Color applied by Chris' remote"
    initial: &default_color "[255, 186, 82]"
    options:
      - *default_color
      - "[255, 206, 166]"
      - "[243, 242, 255]"
      - "[210, 223, 255]"
      - "[0, 0, 255]"
      - "[255, 0, 0]"
      - "[255, 105, 180]"
      - "[0, 255, 0]"

automation:
  - alias: chris_remote_restore_initial_option
    description: "Restore entity selected by Chris' remote after some time"
    use_blueprint:
      path: "reset_input_select.yaml"
      input:
        default_option: *default_entity
        delay: 300
        entity_id: "input_select.chris_remote_entity"

  - alias: chris_remote_apply_color_change
    description: "Turn on and change the color on Chris' remote entity"
    initial_state: true
    max_exceeded: silent
    mode: "queued"
    trigger:
      - platform: state
        entity_id: "input_select.chris_remote_color"
    action:
      - service: light.turn_on
        data:
          entity_id: "{{ states('input_select.chris_remote_entity') }}"
          rgb_color: "{{ trigger.to_state.state }}"

  - alias: chris_remote
    description: Map Chris' remote buttons to useful actions
    use_blueprint:
      path: "zha/bedside_remote.yaml"
      input:
        color_input_select: "input_select.chris_remote_color"
        device_ieee: "00:0d:6f:ff:fe:61:69:25"
        entity_input_select: "input_select.chris_remote_entity"
