homeassistant:
  customize:
    sensor.karine_bedside_remote_battery:
      battery_type: "CR2032"
      battery_warning_level: 25

input_select:
  karine_remote_entity:
    name: "Entity controlled by Karine's remote"
    initial: &default_entity "light.bedside_karine"
    options:
      - *default_entity
      - "light.bedside_chris"
      - "light.master_bedroom_bedsides"
  karine_remote_color:
    name: "Color applied by Karine's remote"
    initial: &default_color "[255, 186, 82]"
    options:
      - *default_color
      - "[255, 206, 166]"
      - "[243, 242, 255]"
      - "[210, 223, 255]"
      - "[0, 0, 255]"
      - "[255, 0, 0]"
      - "[255, 105, 180]"
      - "[0, 255, 0]"

automation:
  - alias: karine_remote_restore_initial_option
    description: "Restore entity selected by Karine's remote after some time"
    use_blueprint:
      path: "reset_input_select.yaml"
      input:
        default_option: *default_entity
        delay: 300
        entity_id: "input_select.karine_remote_entity"

  - alias: karine_remote_apply_color_change
    description: "Turn on and change the color on Karine's remote entity"
    mode: "queued"
    trigger:
      - platform: state
        entity_id: "input_select.karine_remote_color"
    action:
      - service: light.turn_on
        data:
          entity_id: "{{ states('input_select.karine_remote_entity') }}"
          rgb_color: "{{ trigger.to_state.state }}"

  - alias: karine_remote
    description: Map Karine's remote buttons to useful actions
    use_blueprint:
      path: "zha/bedside_remote.yaml"
      input:
        color_input_select: "input_select.karine_remote_color"
        device_ieee: "14:b4:57:ff:fe:7c:23:0e"
        entity_input_select: "input_select.karine_remote_entity"
