homeassistant:
  customize:
    light.master_bedroom_bedsides:
      friendly_name: "Master bedroom's bedside lamps"
    sensor.master_bedroom_temperature:
      friendly_name: "Master bedroom temperature"

cloud:
  google_actions:
    filter:
      include_entities:
        - "light.master_bedroom_spots"
        - "light.master_bedroom_bedsides"
        - "light.bedside_chris"
        - "light.bedside_karine"
    entity_config:
      light.master_bedroom:
        aliases:
          - "Bedroom spots"
      light.master_bedroom_bedsides:
        aliases:
          - "Bedside lamps"

input_number:
  master_bedroom_thermostat_eco_setpoint:
    name: "Master bedroom thermostat eco setpoint"
    <<: &setpoint_config
      unit_of_measurement: "°C"
      icon: "mdi:thermometer-lines"
      mode: "box"
      min: 8
      max: 25
      step: 0.5
  master_bedroom_thermostat_comfort_setpoint:
    name: "Master bedroom thermostat comfort setpoint"
    <<: *setpoint_config

input_select:
  master_bedroom_thermostat_auto_mode:
    name: "Master bedroom thermostat auto mode"
    icon: mdi:home-thermometer-outline
    options: ["Comfort", "Eco"]
  master_bedroom_thermostat_mode:
    name: "Master bedroom thermostat mode"
    icon: mdi:home-thermometer-outline
    options: ["Auto", "Manual"]

light:
  - platform: group
    unique_id: "master_bedroom_lights"
    name: "Master bedroom lights"
    entities:
      - light.master_bedroom_sconces
      - light.master_bedroom_spots
      - light.bedside_chris
      - light.bedside_karine
  - platform: group
    unique_id: "master_bedroom_bedsides"
    name: "Master bedroom bedsides"
    entities:
      - light.bedside_chris
      - light.bedside_karine

template:
  - sensor:
      - unique_id: "sensor.master_bedroom_temperature"
        name: "master_bedroom_temperature"
        device_class: "temperature"
        unit_of_measurement: "°C"
        state: "{{ states('sensor.master_bedroom_thermostat_temperature') | float(0) | round(1) }}"
        availability: "{{ not is_state('sensor.master_bedroom_thermostat_temperature', 'unavailable') }}"
        attributes:
          heating: "{{ is_state_attr('climate.master_bedroom_thermostat', 'hvac_action', 'heating') }}"

automation:
  - id: "650fdbf6-2f22-4bd0-b430-c8a1c29d3217"
    alias: "master_bedroom_spots_dimmer_scenes"
    use_blueprint:
      path: "zwave/paddle_scenes.yaml"
      input:
        on_entity_id: "event.master_bedroom_spots_dimmer_on_pressed"
        off_entity_id: "event.master_bedroom_spots_dimmer_off_pressed"

        tap_on_2x:
          - service: "light.turn_on"
            data:
              entity_id: "light.bedside_chris"
        tap_off_2x:
          - service: "light.turn_off"
            data:
              entity_id: "light.bedside_chris"

        tap_on_3x:
          - service: "light.turn_on"
            data:
              entity_id: "light.master_bedroom_lights"
        tap_off_3x:
          - service: "light.turn_off"
            data:
              entity_id: "light.master_bedroom_lights"

  - id: "7d71c23b-929c-4553-a150-2f990fc7ff87"
    alias: "master_bedroom_sconces_dimmer_scenes"
    use_blueprint:
      path: "zwave/paddle_scenes.yaml"
      input:
        on_entity_id: "event.master_bedroom_sconces_dimmer_on_pressed"
        off_entity_id: "event.master_bedroom_sconces_dimmer_off_pressed"

        tap_on_2x:
          - service: "light.turn_on"
            data:
              entity_id: "light.bedside_karine"
        tap_off_2x:
          - service: "light.turn_off"
            data:
              entity_id: "light.bedside_karine"

        tap_on_3x:
          - service: "light.turn_on"
            data:
              entity_id: "light.master_bedroom_lights"
        tap_off_3x:
          - service: "light.turn_off"
            data:
              entity_id: "light.master_bedroom_lights"
