homeassistant:
  customize:
    light.master_bedroom_bedsides:
      friendly_name: "Master bedroom's bedside lamps"
    light.master_bedroom:
      friendly_name: "Master bedroom light"

cloud:
  google_actions:
    filter:
      include_entities:
        - "light.master_bedroom"
        - "light.master_bedroom_bedsides"
        - "light.bedside_chris"
        - "light.bedside_karine"
    entity_config:
      light.master_bedroom:
        room: "Master bedroom"
        name: "Master bedroom light"
        aliases:
          - "Bedroom light"
      light.master_bedroom_bedsides:
        room: "Master bedroom"
        name: "Master bedroom's bedside lamps"
        aliases:
          - "Bedside lamps"
      light.bedside_chris:
        room: "Master bedroom"
        name: "Chris' bedside lamp"
        aliases:
          - "Chris' bedside"
      light.bedside_karine:
        room: "Master bedroom"
        name: "Karine's bedside lamp"
        aliases:
          - "Karine's bedside"

input_number:
  master_bedroom_thermostat_eco_setpoint:
    name: "Master bedroom thermostat eco setpoint"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer-lines"
    mode: "box"
    min: 8
    max: 18
    step: 0.5
  master_bedroom_thermostat_comfort_setpoint:
    name: "Master bedroom thermostat comfort setpoint"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer-lines"
    mode: "box"
    min: 15
    max: 25
    step: 0.5

input_select:
  master_bedroom_thermostat_auto_mode:
    name: "Master bedroom thermostat auto mode"
    icon: mdi:home-thermometer-outline
    options: ["Comfort", "Eco"]
  master_bedroom_thermostat_mode:
    name: "Master bedroom thermostat mode"
    icon: mdi:home-thermometer-outline
    options: ["Auto", "Manual"]

light:
  - platform: group
    name: "Master bedroom lights"
    entities:
      - light.master_bedroom
      - light.bedside_chris
      - light.bedside_karine
  - platform: group
    name: "master_bedroom_bedsides"
    entities:
      - light.bedside_chris
      - light.bedside_karine

  - platform: switch
    name: "master_bedroom"
    entity_id: "switch.master_bedroom_light"

sensor:
  - platform: template
    sensors:
      master_bedroom_temperature:
        unique_id: "sensor.master_bedroom_temperature"
        friendly_name: "Master bedroom temperature"
        device_class: "temperature"
        unit_of_measurement: "°C"
        value_template: "{{ states('sensor.master_bedroom_thermostat_temperature') | round(1) }}"

automation:
  - alias: "master_bedroom_light_switch_zwave_scenes"
    use_blueprint:
      path: "zwave/inovelli_nzw30_scene_control.yaml"
      input:
        zwave_entity: "zwave.master_bedroom_light_switch"

        tap_on_2x:
          - service: light.turn_on
            data:
              entity_id: "light.master_bedroom_bedsides"
        tap_off_2x:
          - service: light.turn_off
            data:
              entity_id: "light.master_bedroom_bedsides"

        tap_on_4x:
          - service: script.bedtime
        tap_off_4x:
          - service: script.bedtime

        tap_on_5x:
          - service: script.everything_off
        tap_off_5x:
          - service: script.everything_off
