homeassistant:
  customize:
    light.master_bedroom_bedsides:
      friendly_name: "Master bedroom's bedside lamps"
    light.master_bedroom:
      friendly_name: "Master bedroom light"

cloud:
  google_actions:
    filter:
      include_entities:
        - "light.master_bedroom"
        - "light.master_bedroom_bedsides"
        - "light.bedside_chris"
        - "light.bedside_karine"
    entity_config:
      light.master_bedroom:
        room: "Master bedroom"
        name: "Master bedroom light"
        aliases:
          - "Bedroom light"
      light.master_bedroom_bedsides:
        room: "Master bedroom"
        name: "Master bedroom's bedside lamps"
        aliases:
          - "Bedside lamps"
      light.bedside_chris:
        room: "Master bedroom"
        name: "Chris' bedside lamp"
        aliases:
          - "Chris' bedside"
      light.bedside_karine:
        room: "Master bedroom"
        name: "Karine's bedside lamp"
        aliases:
          - "Karine's bedside"

cast:
  media_player:
    - host: !secret media_player_home_mbr_host

input_number:
  master_bedroom_thermostat_eco_setpoint:
    name: "Master bedroom thermostat eco setpoint"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer-lines"
    mode: "box"
    min: 8
    max: 18
    step: 0.5
  master_bedroom_thermostat_comfort_setpoint:
    name: "Master bedroom thermostat comfort setpoint"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer-lines"
    mode: "box"
    min: 15
    max: 25
    step: 0.5

input_select:
  master_bedroom_thermostat_mode:
    name: "Master bedroom thermostat mode"
    icon: mdi:home-thermometer-outline
    options: ["Comfort", "Eco", "Manual"]

light:
  - platform: group
    name: "Master bedroom lights"
    entities:
      - light.master_bedroom
      - light.bedside_chris
      - light.bedside_karine
  - platform: group
    name: "master_bedroom_bedsides"
    entities:
      - light.bedside_chris
      - light.bedside_karine

  - platform: switch
    name: "master_bedroom"
    entity_id: "switch.master_bedroom_light"

sensor:
  - platform: template
    sensors:
      master_bedroom_temperature:
        friendly_name: "Master bedroom temperature"
        device_class: "temperature"
        unit_of_measurement: "°C"
        value_template: "{{ states('sensor.master_bedroom_thermostat_temperature') | round(1) }}"

automation:
  - alias: "master_bedroom_double_up"
    hide_entity: True
    initial_state: True
    trigger:
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.master_bedroom_light_switch"
          scene_id: 2
          scene_data: 3
    action:
      service: light.turn_on
      data:
        entity_id: "light.master_bedroom_bedsides"
  - alias: "master_bedroom_double_down"
    hide_entity: True
    initial_state: True
    trigger:
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.master_bedroom_light_switch"
          scene_id: 1
          scene_data: 3
    action:
      service: light.turn_off
      data:
        entity_id: "light.master_bedroom_bedsides"

  - alias: "master_bedroom_quad_tap"
    hide_entity: True
    initial_state: True
    trigger:
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.master_bedroom_light_switch"
          scene_id: 1
          scene_data: 5
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.master_bedroom_light_switch"
          scene_id: 2
          scene_data: 5
    action:
      service: script.bedtime

  - alias: "master_bedroom_quint_tap"
    hide_entity: True
    initial_state: True
    trigger:
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.master_bedroom_light_switch"
          scene_id: 1
          scene_data: 6
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.master_bedroom_light_switch"
          scene_id: 2
          scene_data: 6
    action:
      service: script.everything_off
