homeassistant:
  customize:
    sensor.current_home_assistant_version:
      friendly_name: "Current version"
      icon: "mdi:arrow-right"
    sensor.latest_home_assistant_version:
      friendly_name: "Latest version"
      icon: "mdi:arrow-up"

system_health: {}

sensor:
  - platform: websocket_api
  - platform: version
    name: "latest_home_assistant_version"
    source: "docker"
  - platform: version
    name: "current_home_assistant_version"
    source: "local"

automation:
  - alias: notify_update_available
    initial_state: true
    mode: "parallel"
    trigger:
      - platform: state
        entity_id: sensor.latest_home_assistant_version
    condition: >-
      {{
        trigger.to_state.state not in ('unknown', 'unavailable')
          and trigger.to_state.state != states('sensor.current_home_assistant_version')
      }}
    action:
      - service: python_script.notify
        data:
          persistent: true
          push_target: "admin"
          tag: "hass_version"
          url: "https://github.com/home-assistant/home-assistant/releases/tag/{{ trigger.to_state.state }}"
          title: "Home Assistant Update"
          message: "Home Assistant {{ trigger.to_state.state }} is available."

  - alias: notify_failed_login_attempt
    initial_state: true
    mode: "parallel"
    trigger:
      - platform: event
        event_type: "call_service"
        event_data:
          domain: "persistent_notification"
          service: "create"
          service_data:
            notification_id: "http-login"
    action:
      - service: python_script.notify
        data:
          push_target: "admin"
          title: "{{ trigger.event.data.service_data.title }}"
          message: "{{ trigger.event.data.service_data.message }}"

  - alias: Notify HA startup
    trigger:
      - platform: homeassistant
        event: "start"
    action:
      - service: notify.admin
        data:
          message: Home-Assistant has started.
          data: &ha_status_data
            tag: "homeassistant-status"
  - alias: Notify HA shutdown
    trigger:
      - platform: homeassistant
        event: "shutdown"
    action:
      - service: notify.admin
        data:
          message: Home-Assistant has shut down.
          data: *ha_status_data
