homeassistant:
  customize:
    sensor.current_home_assistant_version:
      friendly_name: "Current version"
      icon: "mdi:arrow-right"
    sensor.latest_home_assistant_version:
      friendly_name: "Latest version"
      icon: "mdi:arrow-up"

system_health: {}

sensor:
  - platform: websocket_api

automation:
  - id: "6ea34d47-1181-4c94-9ab6-43fe4c0b42cc"
    alias: notify_update_available
    initial_state: true
    mode: "parallel"
    trigger:
      - platform: "state"
        entity_id: "sensor.latest_home_assistant_version"
        not_to:
          - "unknown"
          - "unavailable"
    condition: "{{ trigger.to_state.state | version > states('sensor.current_home_assistant_version') }}"
    action:
      - service: python_script.notify
        data:
          persistent: true
          push_target: "admin"
          tag: "hass_version"
          url: "https://github.com/home-assistant/home-assistant/releases/tag/{{ trigger.to_state.state }}"
          title: "Home Assistant Update"
          message: "Home Assistant {{ trigger.to_state.state }} is available."

  - id: "0c595e90-4186-4152-b80e-41a491749dde"
    alias: notify_failed_login_attempt
    initial_state: true
    mode: "parallel"
    trigger:
      - platform: event
        event_type: "call_service"
        event_data:
          domain: "persistent_notification"
          service: "create"
          service_data:
            notification_id: "http-login"
    action:
      - service: python_script.notify
        data:
          push_target: "admin"
          title: "{{ trigger.event.data.service_data.title }}"
          message: "{{ trigger.event.data.service_data.message }}"

  - id: "673d5462-19e1-4a63-ad41-75c0690dcaa2"
    alias: Notify HA status.
    trigger:
      - platform: homeassistant
        event: "start"
        variables:
          action: "started"
      - platform: homeassistant
        event: "shutdown"
        variables:
          action: "shut down"
    action:
      - service: "notify.admin"
        data:
          message: "Home-Assistant has {{ action }}."
          data:
            tag: "homeassistant-status"

  - alias: "Reload jinja2 templates"
    id: "c7929657-8241-478e-9a89-d2562c720120"
    mode: "single"
    max_exceeded: "silent"
    trigger:
      - platform: "state"
        entity_id: "event.jinja2_custom_templates_updated"
    action:
      - service: "homeassistant.reload_custom_templates"
