homeassistant:
  customize:
    sensor.current_home_assistant_version:
      friendly_name: "Current version"
      icon: "mdi:arrow-right"
    sensor.latest_home_assistant_version:
      friendly_name: "Latest version"
      icon: "mdi:arrow-up"

system_health:

sensor:
  - platform: websocket_api
  - platform: version
    name: "latest_home_assistant_version"
    source: "pypi"
  - platform: version
    name: "current_home_assistant_version"
    source: "local"

automation:
  - alias: notify_update_available
    initial_state: True
    trigger:
      - platform: state
        entity_id: sensor.latest_home_assistant_version
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ trigger.to_state.state != 'unknown' }}"
        - condition: template
          value_template: "{{ trigger.to_state.state != 'unavailable' }}"
        - condition: template
          value_template: "{{ trigger.to_state.state != states('sensor.current_home_assistant_version') }}"
    action:
      - service: python_script.notify
        data_template:
          persistent: True
          push_target: "admin"
          tag: "hass_version"
          url: "https://github.com/home-assistant/home-assistant/releases/tag/{{ trigger.to_state.state }}"
          title: "Home Assistant Update"
          message: "Home Assistant {{ trigger.to_state.state }} is available."

  - alias: notify_failed_login_attempt
    initial_state: True
    trigger:
      - platform: event
        event_type: "call_service"
        event_data:
          domain: "persistent_notification"
          service: "create"
    condition:
      - condition: template
        value_template: "{{ trigger.event.data.service_data.notification_id == 'http-login' }}"
    action:
      - service: python_script.notify
        data_template:
          push_target: "admin"
          title: "{{ trigger.event.data.service_data.title }}"
          message: "{{ trigger.event.data.service_data.message }}"

  - alias: Notify HA startup
    trigger:
      - event: start
        platform: homeassistant
    action:
      - service: notify.admin
        data:
          message: Home-Assistant has restarted.
          data:
            tag: hass-status
  - alias: Notify HA shutdown
    trigger:
      - event: shutdown
        platform: homeassistant
    action:
      - service: notify.admin
        data:
          message: Home-Assistant is shutting down.
          data:
            tag: hass-status