sensor:
  - platform: rest
    unique_id: "minecraft_latest_version"
    name: "Latest Minecraft version"
    icon: "mdi:update"
    resource: "https://launchermeta.mojang.com/mc/game/version_manifest.json"
    value_template: "{{ value_json.latest.release }}"
    scan_interval: 900

input_boolean:
  notify_minecraft_status:
    name: "Notify Minecraft status"
    icon: mdi:minecraft
  notify_minecraft_player_changes:
    name: "Notify Minecraft player changes"
    icon: mdi:minecraft

automation:
  - id: "9a2523ee-12c0-4c23-b016-75b2c6d4c045"
    alias: notify_minecraft_status
    initial_state: true
    mode: "queued"
    trigger:
      - platform: state
        entity_id: "binary_sensor.minecraft_server_status"
        to: ~
    condition:
      - condition: state
        entity_id: "input_boolean.notify_minecraft_status"
        state: "on"
    action:
      - action: python_script.notify
        data:
          push_target: "admin"
          tag: "minecraft-status"
          title: "Minecraft status"
          message: "Minecraft server has gone {{ trigger.to_state.state }}line."

  - id: "53d9d5dc-0aba-4ec9-ac37-5db952727af0"
    alias: notify_minecraft_update
    initial_state: true
    mode: "parallel"
    trigger:
      - platform: state
        entity_id: "sensor.minecraft_latest_version"
        not_to:
          - "unknown"
          - "unavailable"
    condition:
      - condition: state
        entity_id: "input_boolean.notify_minecraft_status"
        state: "on"
      - "{{ trigger.to_state.state > states('sensor.minecraft_server_version') | version }}"
    action:
      - action: python_script.notify
        data:
          persistent: true
          push_target: "admin"
          tag: "minecraft-update"
          title: "Minecraft {{ states('sensor.minecraft_latest_version') }} available"
          message: >-
            Minecraft server can now be updated
            from {{ states('sensor.minecraft_server_version') }}
            to {{ states('sensor.minecraft_latest_version') }}.

  - id: "b2052723-8459-49af-8400-a0f087445caa"
    alias: notify_minecraft_player_changes
    initial_state: true
    mode: "restart"
    trigger:
      - platform: state
        entity_id: "sensor.minecraft_server_players_online"
        attribute: "players_list"
    condition:
      - condition: state
        entity_id: "input_boolean.notify_minecraft_player_changes"
        state: "on"
    action:
      - action: python_script.notify
        data:
          push_target: "admin"
          tag: "minecraft-players"
          title: >-
            {% set count = trigger.to_state.state | int %}
            {{ 'No' if count == 0 else count }} minecraft player{{ 's' if count != 1 }} online
          message: >-
            {% set count = trigger.to_state.state | int %}
            {% if count != 0 %}
            {% for player in trigger.to_state.attributes.players_list | default([]) -%}
            {{ player }}{{ ', ' if not loop.last and loop.revindex != 2 }}{{ ' and ' if loop.revindex == 2 }}
            {%- endfor %}
            {{ count == 1 | iif(' is ', ' are ') }}
            online.
            {% endif %}
