homeassistant:
  customize:
    sensor.media_cpu_used:
      friendly_name: "Media's CPU use"
      icon: "mdi:chip"
    sensor.media_cpu_temp:
      friendly_name: "Media's CPU temperature"
      icon: "mdi:fire"
    sensor.media_ram_used_percent:
      friendly_name: "Media's memory use"
      icon: "mdi:memory"
    sensor.relay_south_cpu_used:
      friendly_name: "South relay's CPU use"
      icon: "mdi:chip"
    sensor.relay_south_cpu_temp:
      friendly_name: "South relay's CPU temperature"
      icon: "mdi:fire"
    sensor.relay_south_ram_used_percent:
      friendly_name: "South relay's memory use"
      icon: "mdi:memory"
    sensor.relay_north_cpu_used:
      friendly_name: "North relay's CPU use"
      icon: "mdi:chip"
    sensor.relay_north_cpu_temp:
      friendly_name: "North relay's CPU temperature"
      icon: "mdi:fire"
    sensor.relay_north_ram_used_percent:
      friendly_name: "North relay's memory use"
      icon: "mdi:memory"

input_boolean:
  notify_server_outages:
    name: "Notify server outages"
    icon: "mdi:message-settings-variant"

input_text:
  offline_servers:
    name: "Offline servers (with threshold)"

glances:
  - host: !secret media_glances_host
    port: !secret media_glances_port
    name: "media"
    version: 3
  - host: !secret relay_south_glances_host
    port: !secret relay_south_glances_port
    name: "relay_south"
    version: 3
  - host: !secret relay_north_glances_host
    port: !secret relay_north_glances_port
    name: "relay_north"
    version: 3

shell_command:
  turn_off_server: >-
    /usr/bin/ssh -F /config/.secrets/ssh_config {{ server_key }} "sudo poweroff"
  wake_on_lan: >-
    /usr/bin/ssh -F /config/.secrets/ssh_config router "/usr/sbin/wol -p 9 -i '{{ broadcast }}' '{{ mac }}'"

switch:
  - platform: template
    switches:
      network_media:
        friendly_name: "Media"
        value_template: "{{ is_state('device_tracker.avatar_media', 'home') }}"
        icon_template: "mdi:server-network{% if not is_state('device_tracker.avatar_media', 'home') %}-off{% endif %}"
        turn_on:
          service: "shell_command.wake_on_lan"
          data:
            broadcast: !secret network_broadcast
            mac: !secret media_mac
        turn_off:
          service: "shell_command.turn_off_server"
          data:
            server_key: "media"

      network_relay_north:
        friendly_name: "Relay North"
        value_template: "{{ is_state('device_tracker.avatar_relay_north', 'home') }}"
        icon_template: "mdi:server-network{% if not is_state('device_tracker.avatar_relay_north', 'home') %}-off{% endif %}"
        turn_on:
          service: "shell_command.wake_on_lan"
          data:
            broadcast: !secret network_broadcast
            mac: !secret relay_north_mac
        turn_off:
          service: "shell_command.turn_off_server"
          data:
            server_key: "relay_north"

      network_relay_south:
        friendly_name: "Relay South"
        value_template: "{{ is_state('device_tracker.avatar_relay_south', 'home') }}"
        icon_template: "mdi:server-network{% if not is_state('device_tracker.avatar_relay_south', 'home') %}-off{% endif %}"
        turn_on:
          service: "shell_command.wake_on_lan"
          data:
            broadcast: !secret network_broadcast
            mac: !secret relay_south_mac
        turn_off:
          service: "shell_command.turn_off_server"
          data:
            server_key: "relay_south"

automation:
  - alias: notify_new_network_device
    initial_state: True
    hide_entity: True
    trigger:
      platform: event
      event_type: "device_tracker_new_device"
    action:
      - service: python_script.notify
        data_template:
          push_target: "admin"
          persistent: True
          title: "New device detected on network"
          message: "Device data: {{ trigger.event.data | tojson }}"

  - alias: notify_server_off
    initial_state: True
    hide_entity: True
    trigger:
      platform: state
      entity_id:
        - switch.network_media
        - switch.network_relay_south
        - switch.network_relay_north
      to: "off"
      for: &server_outage_leeway
        seconds: 45
    condition:
      condition: template
      value_template: "{{ '|' ~ trigger.to_state.object_id ~ '|' not in states.input_text.offline_servers.state }}"
    action:
      - service: input_text.set_value
        data_template:
          entity_id: "input_text.offline_servers"
          value: "{{ states.input_text.offline_servers.state }}|{{ trigger.to_state.object_id }}|"
      - condition: state
        entity_id: "input_boolean.notify_server_outages"
        state: "on"
      - service: python_script.notify
        data_template:
          push_target: "admin"
          tag: "server_{{ trigger.to_state.object_id }}"
          url: "/lovelace/network"
          title: "{{ trigger.to_state.name }} is offline"
          push_data:
            entity_id: "{{ trigger.entity_id }}"
          push_actions:
            - action: "power_on"
              title: "Power on"
              icon: "/local/icons/power-plug-on.png"

  - alias: notify_server_on
    initial_state: True
    hide_entity: True
    trigger:
      platform: state
      entity_id:
        - switch.network_media
        - switch.network_relay_south
        - switch.network_relay_north
      to: "on"
      for: *server_outage_leeway
    condition:
      condition: template
      value_template: "{{ '|' ~ trigger.to_state.object_id ~ '|' in states.input_text.offline_servers.state }}"
    action:
      - service: input_text.set_value
        data_template:
          entity_id: "input_text.offline_servers"
          value: "{{ states.input_text.offline_servers.state | replace('|' ~ trigger.to_state.object_id ~ '|', '') }}"
      - condition: state
        entity_id: "input_boolean.notify_server_outages"
        state: "on"
      - service: python_script.notify
        data_template:
          push_target: "admin"
          tag: "server_outage_{{ trigger.to_state.object_id }}"
          url: "/lovelace/network"
          title: "{{ trigger.to_state.name }} is online"
          push_data:
            entity_id: "{{ trigger.entity_id }}"
          push_actions:
            - action: "power_off"
              title: "Power off"
              icon: "/local/icons/power-plug-off.png"

  - alias: notification_action_power_on_server
    initial_state: True
    hide_entity: True
    trigger:
      platform: event
      event_type: "html5_notification.clicked"
      event_data:
        action: power_on
    action:
      service: switch.turn_on
      data_template:
        entity_id: "{{ trigger.event.data.data.entity_id }}"

  - alias: notification_action_power_off_server
    initial_state: True
    hide_entity: True
    trigger:
      platform: event
      event_type: "html5_notification.clicked"
      event_data:
        action: power_off
    action:
      service: switch.turn_off
      data_template:
        entity_id: "{{ trigger.event.data.data.entity_id }}"
