sensor:
  - platform: time_date
    display_options:
      - date
      - time

template:
  - sensor:
      - unique_id: "sensor.hour"
        default_entity_id: "sensor.hour"
        name: "Hour"
        icon: "mdi:clock"
        state: "{{ states.sensor.time.last_changed.hour }}"
