- type: entities
  title: Settings
  show_header_toggle: false
  entities:
    - input_boolean.force_guest_mode
    - input_boolean.automatic_night_theme
    - input_select.default_theme

- type: entities
  title: Notifications
  show_header_toggle: false
  entities:
    - entity: input_boolean.notify_individual_guest_arrivals
      name: Individual guest arrivals, or only first
    - entity: automation.notify_plant_problems
      name: Plant problems
    - entity: input_boolean.notify_power_outages
      name: Power outages

- type: custom:auto-entities
  sort:
    method: last_changed
  filter:
    include:
      - group: group.all_doors
        options:
          <<: &aggregate_row_options
            type: custom:template-entity-row
            active: "{{ is_state('this.entity_id', 'on') }}"
            secondary: "{{ relative_time(states['this.entity_id'].last_changed) }} ago"
            state: >-
              {% set state = states['this.entity_id'] %}
              {% if state.state in ['unknown', 'unavailable'] -%}
                _(state.default.{{ state.state }})
              {%- else -%}
                _(state.binary_sensor.{{ state.attributes.device_class }}.{{ state.state }})
              {%- endif %}
          name: "{{ states['this.entity_id'].name | replace(' door', '') }}"
  card:
    type: entities
    title: Doors
    show_header_toggle: false

- type: custom:auto-entities
  sort:
    method: last_changed
  filter:
    include:
      - group: group.all_windows
        options:
          <<: *aggregate_row_options
          name: "{{ states['this.entity_id'].name | replace(' window', '') }}"
  card:
    type: entities
    title: Windows
    show_header_toggle: false

- type: custom:auto-entities
  sort:
    method: last_changed
  filter:
    include:
      - group: group.all_leaks
        options:
          <<: *aggregate_row_options
          name: "{{ states['this.entity_id'].name | replace(' leak', '') }}"
  card:
    type: entities
    title: Leaks
    show_header_toggle: false

- type: custom:auto-entities
  sort:
    method: last_changed
  filter:
    include:
      - group: group.all_motions
        options:
          <<: *aggregate_row_options
          name: "{{ states['this.entity_id'].name | replace(' motion', '') }}"
  card:
    type: entities
    title: Motion
    show_header_toggle: false

- type: entities
  title: Batteries
  show_header_toggle: false
  style: |
    :host {
      --paper-item-icon-active-color: var(--google-red-500)
    }
  entities:
    - entity: sensor.all_batteries
      name: Lowest
      secondary_info: last-changed

    - type: custom:auto-entities
      sort:
        method: state
        numeric: true
      options:
      filter:
        include:
          - group: group.all_batteries
            options:
              type: custom:template-entity-row
              name: >-
                {{ states['this.entity_id'].name | replace("'s battery", '') | replace(' battery', '') }}
              state: >-
                {% if states['this.entity_id'].state in ['unknown', 'unavailable'] -%}
                  _(state.default.{{ states['this.entity_id'].state }})
                {%- else -%}
                  {{ states['this.entity_id'].state_with_unit }}
                {%- endif %}
              secondary: "{{ states['this.entity_id'].attributes.battery_type }}"
              active: "{{ (states['this.entity_id'].state | int - states['this.entity_id'].attributes.battery_warning_level | default(25) | int) <= 0 }}"
      card:
        type: custom:fold-entity-row
        head:
          type: section
          label: Details