- type: entities
  title: Settings
  show_header_toggle: false
  entities:
    - input_boolean.guest_mode
    - input_boolean.automatic_night_theme
    - input_select.default_theme

- type: entities
  title: Notifications
  show_header_toggle: false
  entities:
    - entity: automation.notify_plant_problems
      name: Plant problems
    - entity: input_boolean.notify_power_outages
      name: Power outages

- type: custom:auto-entities
  sort:
    method: last_changed
  filter:
    include:
      - group: group.all_doors
        options:
          secondary_info: last-changed
  card:
    type: entities
    title: Doors
    show_header_toggle: false

- type: custom:auto-entities
  sort:
    method: last_changed
  filter:
    include:
      - group: group.all_windows
        options:
          secondary_info: last-changed
  card:
    type: entities
    title: Windows
    show_header_toggle: false

- type: custom:auto-entities
  sort:
    method: last_changed
  filter:
    include:
      - group: group.all_leaks
        options:
          secondary_info: last-changed
  card:
    type: entities
    title: Leaks
    show_header_toggle: false

- type: custom:auto-entities
  sort:
    method: last_changed
  filter:
    include:
      - group: group.all_motions
        options:
          secondary_info: last-changed
  card:
    type: entities
    title: Motion
    show_header_toggle: false

- type: entities
  title: Batteries
  show_header_toggle: false
  entities:
    - entity: sensor.all_batteries
      name: Lowest
      secondary_info: last-changed

    - type: custom:auto-entities
      sort:
        method: state
        numeric: true
      filter:
        include:
          - group: group.all_batteries
      card:
        type: custom:fold-entity-row
        head:
          type: section
          label: Details
        group_config:
          secondary_info: last-changed
