- alias: 'Notification: Update Available'
  hide_entity: True
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    - service: persistent_notification.create
      data_template:
        message: 'Home Assistant  {{ states("updater.updater") }} is available.'
      data:
        title: 'Home Assistant Update'
        notification_id: hass_update_available
    - service: notify.pushbullet
      data_template:
        message: 'Home Assistant  {{ states("updater.updater") }} is available.'
      data:
        title: 'Home Assistant Update'
        data:
          tag: update_available
          url: https://github.com/home-assistant/home-assistant/releases/latest
