alias: 'Notification: Device Down'
hide_entity: True
trigger:
  - platform: state
    entity_id:
      - sensor.hue_hub
action:
  service: notify.pushbullet
  data_template:
    message: "{{ trigger.to_state.name }} is {{ trigger.to_state.state | lower }}!"
    
