blueprint:
  name: Terrarium scheduling
  description: Manage a terarrium's lights and heaters.
  domain: automation
  input:
    scheduling_entity:
      name: Scheduling control entity
      description: A boolean input that enables/disables scheduling altogether.
      selector:
        entity:
          domain: input_boolean
    day_time_entity:
      name: Day time input entity
      description: The entity representing when day time starts for this terrarium.
      selector:
        entity:
          domain: input_datetime
    night_time_entity:
      name: Night time input entity
      description: The entity representing when night time starts for this terrarium.
      selector:
        entity:
          domain: input_datetime
    heat_bulb_switch:
      name: Heat bulb
      selector:
        entity:
          domain: switch
    heater_switch:
      name: Heater
      selector:
        entity:
          domain: switch
    uv_light_switch:
      name: UV light
      selector:
        entity:
          domain: switch

initial_state: true
mode: "restart"

trigger:
  - platform: time
    at:
      - !input day_time_entity
      - !input night_time_entity
  - platform: state
    entity_id: !input scheduling_entity
    from: "off"
    to: "on"
  - platform: event
    event_type: "zwave.network_ready"

variables:
  day_time_entity: !input day_time_entity
  night_time_entity: !input night_time_entity

condition:
  - condition: state
    entity_id: !input scheduling_entity
    state: "on"

action:
  - service: switch.turn_on
    entity_id: !input heater_switch

  - choose:
      # Day
      - conditions: >-
          {% set now = strptime(states('sensor.time'), '%H:%M:%S') %}
          {% set day_time = strptime(states(day_time_entity), '%H:%M:%S') %}
          {% set night_time = strptime(states(night_time_entity), '%H:%M:%S') %}
          {{ day_time <= now < night_time }}
        sequence:
          - service: switch.turn_on
            entity_id: !input uv_light_switch
    # Night
    default:
      - service: switch.turn_off
        entity_id:
          - !input heat_bulb_switch
          - !input uv_light_switch
