blueprint:
  name: Terrarium scheduling
  description: Manage a terarrium's lights and heaters.
  domain: automation
  input:
    scheduling_entity:
      name: Scheduling control entity
      description: A boolean input that enables/disables scheduling altogether.
      selector:
        entity:
          filter:
            - domain: input_boolean
    day_time_entity:
      name: Day time input entity
      description: The entity representing when day time starts for this terrarium.
      selector:
        entity:
          filter:
            - domain: input_datetime
    night_time_entity:
      name: Night time input entity
      description: The entity representing when night time starts for this terrarium.
      selector:
        entity:
          filter:
            - domain: input_datetime
    heat_bulb_switch:
      name: Heat bulb
      default: switch.dummy
      selector:
        entity:
          filter:
            - domain: switch
    heater_switch:
      name: Heater
      default: switch.dummy
      selector:
        entity:
          filter:
            - domain: switch
    uv_light_switch:
      name: UV light
      default: switch.dummy
      selector:
        entity:
          filter:
            - domain: switch

initial_state: true
mode: "restart"

triggers:
  - trigger: time
    at:
      - !input day_time_entity
      - !input night_time_entity
  - trigger: state
    entity_id:
      - !input day_time_entity
      - !input night_time_entity
  - trigger: state
    entity_id: !input scheduling_entity
    from: "off"
    to: "on"
  - trigger: homeassistant
    event: start

variables:
  heat_bulb_switch: !input heat_bulb_switch
  heater_switch: !input heater_switch
  uv_light_switch: !input uv_light_switch

conditions:
  - condition: state
    entity_id: !input scheduling_entity
    state: "on"

actions:
  - action: switch.turn_on
    enabled: "{{ heater_switch != 'switch.dummy' }}"
    target:
      entity_id: !input heater_switch

  - if:
      - condition: time
        after: !input day_time_entity
        before: !input night_time_entity
    then:
      - action: switch.turn_on
        enabled: "{{ heat_bulb_switch != 'switch.dummy' }}"
        target:
          entity_id: !input heat_bulb_switch
      - action: switch.turn_on
        enabled: "{{ uv_light_switch != 'switch.dummy' }}"
        target:
          entity_id: !input uv_light_switch
    else:
      - action: switch.turn_off
        enabled: "{{ heat_bulb_switch != 'switch.dummy' }}"
        target:
          entity_id: !input heat_bulb_switch
      - action: switch.turn_off
        enabled: "{{ uv_light_switch != 'switch.dummy' }}"
        target:
          entity_id: !input uv_light_switch
