blueprint:
  name: Terrarium scheduling
  description: Manage a terarrium's lights and heaters.
  domain: automation
  input:
    scheduling_entity:
      name: Scheduling control entity
      description: A boolean input that enables/disables scheduling altogether.
      selector:
        entity:
          domain: input_boolean
    day_time_entity:
      name: Day time input entity
      description: The entity representing when day time starts for this terrarium.
      selector:
        entity:
          domain: input_datetime
    night_time_entity:
      name: Night time input entity
      description: The entity representing when night time starts for this terrarium.
      selector:
        entity:
          domain: input_datetime
    heat_bulb_switch:
      name: Heat bulb
      selector:
        entity:
          domain: switch
    heater_switch:
      name: Heater
      selector:
        entity:
          domain: switch
    uv_light_switch:
      name: UV light
      selector:
        entity:
          domain: switch

initial_state: true
mode: "restart"

trigger:
  - platform: time
    at:
      - !input day_time_entity
      - !input night_time_entity
  - platform: state
    entity_id: !input scheduling_entity
    from: "off"
    to: "on"
  - platform: homeassistant
    event: start

variables:
  day_time_entity: !input day_time_entity
  night_time_entity: !input night_time_entity

condition:
  - condition: state
    entity_id: !input scheduling_entity
    state: "on"

action:
  - action: switch.turn_on
    target:
      entity_id: !input heater_switch

  - if:
      - condition: time
        after: !input day_time_entity
        before: !input night_time_entity
    then:
      - action: switch.turn_on
        target:
          entity_id: !input uv_light_switch
    else:
      - action: switch.turn_off
        target:
          entity_id:
            - !input heat_bulb_switch
            - !input uv_light_switch
