google_assistant:
  project_id: !secret google_assistant_project_id
  api_key: !secret google_assistant_api_key
  expose_by_default: False
  exposed_domains: []

automation:
  - alias: "Sync Google Assistant"
    hide_entity: True
    initial_state: True
    trigger:
      - platform: event
        # This should leave plenty of time for HA to be up and running.
        event_type: "zwave.network_ready"
      - platform: time
        at: "04:00:00"
    action:
      - service: google_assistant.request_sync
        data:
          agent_user_id: "d81d86b73a3f4ae78e22362a8ab9a2bb"
