notify:
  - platform: html5
    name: "html5"
    vapid_email: !secret notifier_vapid_email
    vapid_pub_key: !secret notifier_vapid_public_key
    vapid_prv_key: !secret notifier_vapid_private_key

  - platform: group
    name: "admin"
    services:
      - service: mobile_app_chris_moto_g7
      - service: html5_chris_aero_arch_chrome

  - platform: group
    name: "household"
    services:
      - service: admin
      - service: mobile_app_karine_pixel_1

tts:
  - platform: google_cloud
    key_file: ".secrets/gcp.json"
    service_name: google_cloud_say
    voice: "en-US-Wavenet-D"  # https://cloud.google.com/text-to-speech/docs/voices
    profiles:
      - "small-bluetooth-speaker-class-device"

custom_storage:
  broadcast_notifications:
    enable_persistence: true

group:
  broadcast_media_players:
    name: "Broadcast enabled media players"
    icon: "mdi:speaker-multiple"
    all: true
    entities: &broadcast_media_players
      - media_player.laundry_room_google_home
      - media_player.living_room_google_home
      - media_player.lounge_google_home
      - media_player.master_bedroom_google_home
      - media_player.office_sonos

script:
  broadcast_notification:
    alias: "Broadcast notification"
    description: "Synchronize `group.broadcast_media_players` and broadcast an audio message"
    fields:
      message:
        description: "The message to play on the speakers."
        example: "Today is a fine day. Don't forget to charge your phone."
    sequence:
      - service: media_player.turn_on
        data:
          entity_id: "group.broadcast_media_players"
      - wait_template: >-  # yet again, expanding groups doesn't infer all entities
          {{
            expand(
              'media_player.laundry_room_google_home',
              'media_player.living_room_google_home',
              'media_player.lounge_google_home',
              'media_player.master_bedroom_google_home',
              'media_player.office_sonos'
            ) | selectattr('state', '==', 'off')
              | first is undefined
          }}
        timeout: "00:00:30"

      - service: tts.google_cloud_say
        data_template:
          entity_id: "group.broadcast_media_players"
          message: "{{ message }}"

      - delay: "00:00:02"
      - wait_template: >-
          {{
            expand(
              'media_player.laundry_room_google_home',
              'media_player.living_room_google_home',
              'media_player.lounge_google_home',
              'media_player.master_bedroom_google_home',
              'media_player.office_sonos'
            ) | selectattr('state', '==', 'playing')
              | first is undefined
          }}
        timeout: "00:02:00"

automation:
  - alias: broadcast_notifications
    initial_state: true

    trigger:
      - platform: homeassistant
        event: start
      - platform: state
        entity_id: "custom_storage.broadcast_notifications"
      - platform: state
        entity_id: "group.household"
        to: "home"
        for:
          minutes: 2
      - platform: time
        at: "8:00:00"
      - platform: time
        at: "9:30:00"

    condition:
      - condition: numeric_state
        entity_id: "custom_storage.broadcast_notifications"
        above: 0
      - condition: state
        entity_id: "group.household"
        state: "home"
      - condition: or
        conditions:
          - condition: time
            after: "8:00:00"
            before: "23:59:59"
            weekday:
              - mon
              - tue
              - wed
              - thu
              - fri
              - sat
          - condition: time
            after: "9:30:00"
            before: "23:59:59"
            weekday:
              - sun

    action:
      - service: automation.turn_off
        entity_id: "automation.broadcast_notifications"

      - service: script.broadcast_notification
        data_template:
          message: "Attention. {{ state_attr('custom_storage.broadcast_notifications', 'item_0_data') }}"
      - wait_template: "{{ is_state('script.broadcast_notification', 'off') }}"

      - service: automation.turn_on
        entity_id: "automation.broadcast_notifications"
      - service: custom_storage.remove
        data_template:
          object_id: "broadcast_notifications"
          id: "{{ state_attr('custom_storage.broadcast_notifications', 'item_0_id') }}"
