# Some workaround to ensure the HS-WD100+ devices status is correctly reported

zwave:
  autoheal: false
  usb_path: /dev/zwave
  config_path: /openzwave/config
  device_config:
    light.basement_bathroom_vanity:
      refresh_value: true
    light.basement_hallway:
      refresh_value: true
    light.dining_room:
      refresh_value: true
    light.lounge:
      refresh_value: true
    light.main_bathroom_spots:
      refresh_value: true
    light.office:
      refresh_value: true

automation:
  - alias: Notify Z-Wave network ready
    trigger:
      - event_type: zwave.network_ready
        platform: event
    action:
      - service: notify.admin
        data:
          message: Z-Wave network is ready.
          data: &data
            tag: zwave-status
  - alias: Notify Z-Wave network complete
    trigger:
      - event_type: zwave.network_complete
        platform: event
    action:
      - service: notify.admin
        data:
          message: Z-Wave network is complete.
          data: *data
