logger:
  default: "warn"

recorder:
  purge_interval: 2
  purge_keep_days: 14
  include: &recorder_inclusion
    entities:
      - binary_sensor.basement_bathroom_motion
      - binary_sensor.guest_east_window
      - binary_sensor.guest_west_window
      - binary_sensor.kitchen_door
      - binary_sensor.kitchen_sink_leak
      - binary_sensor.laundry_room_motion
      - binary_sensor.living_room_door
      - binary_sensor.lounge_window
      - binary_sensor.main_bathroom_motion
      - binary_sensor.ups_online_status
      - binary_sensor.water_heater_leak
      - binary_sensor.workshop_motion
      - group.household
      - group.person_chris
      - group.person_karine
      - input_boolean.automatic_night_theme
      - input_boolean.basement_bathroom_auto_lights
      - input_boolean.guest_mode
      - input_boolean.main_bathroom_auto_lights
      - input_boolean.notify_household_changes
      - input_boolean.notify_network_device_outages
      - input_boolean.notify_power_outages
      - input_boolean.power_outage_manage_devices
      - input_select.default_theme
      - light.basement_bathroom
      - light.basement_bathroom_vanity
      - light.basement_hallway
      - light.bedside_chris
      - light.bedside_karine
      - light.bookshelf
      - light.dining_room
      - light.downstairs
      - light.front_porch
      - light.kitchen
      - light.kitchen_lights
      - light.laundry_room
      - light.living_room_ambiance
      - light.lounge
      - light.lounge_ambiance
      - light.lounge_lights
      - light.main_bathroom_spots
      - light.main_bathroom_vanity
      - light.office
      - light.shed
      - light.side_porch
      - light.workshop
      - media_player.living_room_chromecast
      - media_player.living_room_google_home
      - plant.gaetan
      - plant.spidy
      - plant.viny
      - sensor.basement_bathroom_humidity
      - sensor.basement_bathroom_multisensor_battery
      - sensor.basement_bathroom_temperature
      - sensor.current_home_assistant_version
      - sensor.gaetan_battery
      - sensor.gaetan_brightness
      - sensor.gaetan_conductivity
      - sensor.gaetan_moisture
      - sensor.gaetan_temperature
      - sensor.kitchen_door_sensor_battery
      - sensor.kitchen_sink_leak_sensor_battery
      - sensor.latest_home_assistant_version
      - sensor.living_room_door_sensor_battery
      - sensor.main_bathroom_humidity
      - sensor.main_bathroom_multisensor_battery
      - sensor.main_bathroom_temperature
      - sensor.media_cpu_load
      - sensor.media_cpu_temp
      - sensor.media_ram_used
      - sensor.memory_use_percent
      - sensor.processor_temperature
      - sensor.processor_use
      - sensor.relay_north_cpu_load
      - sensor.relay_north_cpu_temp
      - sensor.relay_north_ram_used
      - sensor.relay_south_cpu_load
      - sensor.relay_south_cpu_temp
      - sensor.relay_south_ram_used
      - sensor.spidy_battery
      - sensor.spidy_brightness
      - sensor.spidy_conductivity
      - sensor.spidy_moisture
      - sensor.spidy_temperature
      - sensor.ups_battery
      - sensor.ups_battery_status
      - sensor.ups_input_voltage
      - sensor.ups_load
      - sensor.ups_status
      - sensor.ups_time_left
      - sensor.ups_time_on_battery
      - sensor.viny_battery
      - sensor.viny_brightness
      - sensor.viny_conductivity
      - sensor.viny_moisture
      - sensor.viny_temperature
      - sensor.water_heater_leak_sensor_battery
      - switch.basement_bathroom_fan
      - switch.bookshelf_outlet
      - switch.living_room_tv
      - switch.main_bathroom_fan
      - switch.network_media
      - switch.network_relay_north
      - switch.network_relay_south
      - switch.unused_rf_3
      - switch.unused_rf_4

history:
  include: *recorder_inclusion

logbook:
  include: *recorder_inclusion
