notify:

- platform: html5
  name: "html5"
  gcm_api_key: !secret notifier_gcm_key
  gcm_sender_id: !secret notifier_gcm_sender_id

- platform: group
  name: "default"
  services:
    - service: html5

- platform: group
  name: "admin"
  services:
    - service: html5
      data:
        target: ["chris aero chrome personal", "chris pixel chrome"]

- platform: group
  name: "household"
  services:
    - service: admin
    - service: html5
      data:
        target: ["karine nexus5 chrome"]
