# Quirks: https://github.com/dmulcahey/zha-device-handlers/blob/dev/zhaquirks/ikea/fivebtnremote.py#L126

blueprint:
  name: Master bedroom remote
  description: Map a 5 buttons IKEA remote to master bedroom actions
  domain: automation
  input:
    color_input_select:
      name: Color selector
      description: The input_select pointing the desired lamps color.
      selector:
        entity:
          domain: input_select
    device_ieee:
      name: Device IEEE
    entity_input_select:
      name: Entity selector
      description: The input_select pointing the lamp to control.
      selector:
        entity:
          domain: input_select

initial_state: true
max_exceeded: silent
mode: "queued"

trigger:
  - platform: event
    event_type: "zha_event"
    event_data:
      device_ieee: !input device_ieee
      endpoint_id: 1

variables:
  entity_input_select: !input entity_input_select

action:
  choose:
    - alias: Tap power button
      conditions: >-
        {{ {'command': 'toggle', 'cluster_id': 6, 'args': []}.items() <= trigger.event.data.items() }}
      sequence:
        - action: light.toggle
          target:
            entity_id: "{{ states(entity_input_select) }}"

    - alias: Hold power button
      conditions: >-
        {{ {'command': 'release', 'cluster_id': 5, 'args': [0]}.items() <= trigger.event.data.items() }}
      sequence:
        - action: light.toggle
          target:
            entity_id: light.master_bedroom_lights

    - alias: Tap dim up button
      conditions: >-
        {{ {'command': 'step_with_on_off', 'cluster_id': 8, 'args': [0, 43, 5]}.items() <= trigger.event.data.items() }}
      sequence:
        - action: light.turn_on
          target:
            entity_id: "{{ states(entity_input_select) }}"
          data:
            brightness_step_pct: 10

    - alias: Hold dim up button
      conditions: >-
        {{ {'command': 'move_with_on_off', 'cluster_id': 8, 'args': [0, 83]}.items() <= trigger.event.data.items() }}
      sequence:
        - action: input_select.select_next
          target:
            entity_id: !input color_input_select

    - alias: Tap dim down button
      conditions: >-
        {{ {'command': 'step', 'cluster_id': 8, 'args': [1, 43, 5]}.items() <= trigger.event.data.items() }}
      sequence:
        - action: light.turn_on
          target:
            entity_id: "{{ states(entity_input_select) }}"
          data:
            brightness_step_pct: -10

    - alias: Hold dim down button
      conditions: >-
        {{ {'command': 'move', 'cluster_id': 8, 'args': [1, 83]}.items() <= trigger.event.data.items() }}
      sequence:
        - action: input_select.select_previous
          target:
            entity_id: !input color_input_select

    - alias: Tap left button
      conditions: >-
        {{ {'command': 'press', 'cluster_id': 5, 'args': [257, 13, 0]}.items() <= trigger.event.data.items() }}
      sequence:
        - action: input_select.select_previous
          target:
            entity_id: !input entity_input_select
        - action: script.turn_on
          target:
            entity_id: script.flash_light
          data:
            variables:
              entity_id: "{{ states(entity_input_select) }}"

    - alias: Hold left button
      conditions: >-
        {{ {'command': 'hold', 'cluster_id': 5, 'args': [3329, 0]}.items() <= trigger.event.data.items() }}
      sequence:
        - action: script.bedtime

    - alias: Tap right button
      conditions: >-
        {{ {'command': 'press', 'cluster_id': 5, 'args': [256, 13, 0]}.items() <= trigger.event.data.items() }}
      sequence:
        - action: input_select.select_next
          target:
            entity_id: !input entity_input_select
        - action: script.turn_on
          target:
            entity_id: script.flash_light
          data:
            variables:
              entity_id: "{{ states(entity_input_select) }}"

    - alias: Hold right button
      conditions: >-
        {{ {'command': 'hold', 'cluster_id': 5, 'args': [3328, 0]}.items() <= trigger.event.data.items() }}
      sequence:
        - action: script.everything_off
