# Pineapple bush
 
homeassistant:
  customize:
    plant.gaetan:
      friendly_name: "Gaétan"
    sensor.gaetan_battery:
      friendly_name: "Gaétan's battery"
    sensor.gaetan_brightness:
      friendly_name: "Gaétan's brightness"
    sensor.gaetan_conductivity:
      friendly_name: "Gaétan's conductivity"
    sensor.gaetan_moisture:
      friendly_name: "Gaétan's moisture"
    sensor.gaetan_temperature:
      friendly_name: "Gaétan's temperature"

plant:
  gaetan:
    sensors:
      battery: sensor.gaetan_battery
      brightness: sensor.gaetan_brightness
      conductivity: sensor.gaetan_conductivity
      moisture: sensor.gaetan_moisture
      temperature: sensor.gaetan_temperature
    min_battery: 10
    min_moisture: 10
    min_temperature: 14

group:
  all_batteries:
    entities:
      - sensor.gaetan_battery

binary_sensor:
  - platform: template
    sensors:
      gaetan_problem:
        friendly_name: "Gaétan issues"
        device_class: "problem"
        icon_template: "mdi:flower"
        value_template: "{{ is_state('plant.gaetan', 'problem') }}"

sensor:
  - platform: mqtt
    name: "gaetan_battery"
    force_update: True
    device_class: "battery"
    unit_of_measurement: "%"
    state_topic: "plants/gaetan"
    value_template: "{{ value_json.battery }}"
    json_attributes:
      - timestamp
  - platform: mqtt
    name: "gaetan_brightness"
    force_update: True
    device_class: "illuminance"
    unit_of_measurement: "lx"
    state_topic: "plants/gaetan"
    value_template: "{{ value_json.brightness }}"
    json_attributes:
      - timestamp
  - platform: mqtt
    name: "gaetan_conductivity"
    force_update: True
    unit_of_measurement: "µS/cm"
    icon: "mdi:poop"
    state_topic: "plants/gaetan"
    value_template: "{{ value_json.conductivity }}"
    json_attributes:
      - timestamp
  - platform: mqtt
    name: "gaetan_moisture"
    force_update: True
    device_class: "humidity"
    unit_of_measurement: "%"
    state_topic: "plants/gaetan"
    value_template: "{{ value_json.moisture }}"
    json_attributes:
      - timestamp
  - platform: mqtt
    name: "gaetan_temperature"
    force_update: True
    device_class: "temperature"
    unit_of_measurement: "°C"
    state_topic: "plants/gaetan"
    value_template: "{{ value_json.temperature }}"
    json_attributes:
      - timestamp
