 # Pineapple bush
 
homeassistant:
  customize:
    plant.gaetan:
      friendly_name: "Gaétan"
      group:
        group.plant_gaetan:
          friendly_name: "Status"
    sensor.gaetan_battery:
      friendly_name: "Battery"
      icon: "mdi:battery"
      state_card_mode: "badges"
    sensor.gaetan_conductivity:
      friendly_name: "Conductivity"
      icon: "mdi:flash"
      state_card_mode: "badges"
    sensor.gaetan_light_intensity:
      friendly_name: "Light"
      icon: "mdi:white-balance-sunny"
      state_card_mode: "badges"
    sensor.gaetan_moisture:
      friendly_name: "Moisture"
      icon: "mdi:water-percent"
      state_card_mode: "badges"
    sensor.gaetan_temperature:
      friendly_name: "Temperature"
      icon: "mdi:thermometer"
      state_card_mode: "badges"

group:
  plant_gaetan:
    name: "Gaétan"
    icon: "mdi:flower"
    entities:
      - plant.gaetan
      - sensor.gaetan_battery
      - sensor.gaetan_conductivity
      - sensor.gaetan_light_intensity
      - sensor.gaetan_moisture
      - sensor.gaetan_temperature

plant:
  gaetan:
    sensors:
      battery: sensor.gaetan_battery
      conductivity: sensor.gaetan_conductivity
      brightness: sensor.gaetan_light_intensity
      moisture: sensor.gaetan_moisture
      temperature: sensor.gaetan_temperature
    min_battery: 10
    min_moisture: 10
    min_temperature: 17

sensor:
  - platform: miflora
    mac: "C4:7C:8D:62:76:66"
    name: "Gaetan"
    median: 3
    timeout: 15
    retries: 3
    monitored_conditions:
      - battery
      - conductivity
      - light
      - moisture
      - temperature

