 # Pineapple bush
 
homeassistant:
  customize:
    plant.gaetan:
      friendly_name: "Gaétan"

plant:
  gaetan:
    sensors:
      battery: sensor.gaetan_battery
      conductivity: sensor.gaetan_conductivity
      brightness: sensor.gaetan_light_intensity
      moisture: sensor.gaetan_moisture
      temperature: sensor.gaetan_temperature
    min_battery: 10
    min_moisture: 10
    min_temperature: 17

sensor:
  - platform: miflora
    mac: "C4:7C:8D:62:76:66"
    name: "Gaetan"
    median: 3
    timeout: 15
    retries: 3
    monitored_conditions:
      - battery
      - conductivity
      - light
      - moisture
      - temperature

