homeassistant:
  customize:
    automation.notify_plant_problems:
      friendly_name: "Notify plant problems"
      icon: "mdi:message-settings-variant"

automation:
  - alias: notify_plant_problems
    initial_state: True
    trigger:
      - platform: state
        entity_id:
          - plant.gaetan
          - plant.spidy
          - plant.viny
        to: "problem"
    condition:
      condition: template
      value_template: "{{ not is_state_attr(trigger.to_state, 'problem', 'battery low') }}"
    action:
      - service: python_script.notify
        data_template:
          persistent: True
          push_target: "household"
          tag: "plant_{{ trigger.to_state.object_id }}"
          url: "/lovelace/plants"
          title: "Check {{ trigger.to_state.name }}"
          message: "{{ trigger.to_state.name }} has some problems: {{ trigger.to_state.attributes.problem }}"
