homeassistant:
  customize:
    plant.spidy:
      friendly_name: "Spidy"
    sensor.spidy_battery:
      friendly_name: "Spidy's battery"
      battery_type: "CR2032 3V"
    sensor.spidy_brightness:
      friendly_name: "Spidy's brightness"
    sensor.spidy_conductivity:
      friendly_name: "Spidy's conductivity"
    sensor.spidy_moisture:
      friendly_name: "Spidy's moisture"
    sensor.spidy_temperature:
      friendly_name: "Spidy's temperature"

plant:
  spidy:
    sensors:
      battery: sensor.spidy_battery
      brightness: sensor.spidy_brightness
      conductivity: sensor.spidy_conductivity
      moisture: sensor.spidy_moisture
      temperature: sensor.spidy_temperature
    min_battery: 20
    min_moisture: 10
    min_temperature: 14

sensor:
  - platform: mqtt
    name: "spidy_battery"
    force_update: True
    device_class: "battery"
    unit_of_measurement: "%"
    state_topic: "plants/spidy"
    value_template: "{{ value_json.battery | int('unknown') }}"
    json_attributes:
      - timestamp
  - platform: mqtt
    name: "spidy_brightness"
    force_update: True
    device_class: "illuminance"
    unit_of_measurement: "lx"
    state_topic: "plants/spidy"
    value_template: "{{ value_json.brightness | int('unknown') }}"
    json_attributes:
      - timestamp
  - platform: mqtt
    name: "spidy_conductivity"
    force_update: True
    unit_of_measurement: "µS/cm"
    icon: "mdi:poop"
    state_topic: "plants/spidy"
    value_template: "{{ value_json.conductivity | int('unknown') }}"
    json_attributes:
      - timestamp
  - platform: mqtt
    name: "spidy_moisture"
    force_update: True
    device_class: "humidity"
    unit_of_measurement: "%"
    state_topic: "plants/spidy"
    value_template: "{{ value_json.moisture | int('unknown') }}"
    json_attributes:
      - timestamp
  - platform: mqtt
    name: "spidy_temperature"
    force_update: True
    device_class: "temperature"
    unit_of_measurement: "°C"
    state_topic: "plants/spidy"
    value_template: "{{ value_json.temperature | float('unknown') }}"
    json_attributes:
      - timestamp
