 # Spider plant
 
homeassistant:
  customize:
    plant.spidy:
      friendly_name: "Spidy"

plant:
  spidy:
    sensors:
      battery: sensor.spidy_battery
      conductivity: sensor.spidy_conductivity
      brightness: sensor.spidy_light_intensity
      moisture: sensor.spidy_moisture
      temperature: sensor.spidy_temperature
    min_battery: 10
    min_moisture: 15
    min_temperature: 15

sensor:
  - platform: miflora
    mac: "C4:7C:8D:63:6F:A3"
    name: "Spidy"
    median: 3
    monitored_conditions:
      - battery
      - conductivity
      - light
      - moisture
      - temperature

