 # Black-Eyed Susan vine
 
homeassistant:
  customize:
    plant.susan:
      friendly_name: "Status"
    sensor.susan_battery:
      friendly_name: "Battery"
      icon: "mdi:battery"
    sensor.susan_conductivity:
      friendly_name: "Conductivity"
      icon: "mdi:flash"
    sensor.susan_light_intensity:
      friendly_name: "Light"
      icon: "mdi:white-balance-sunny"
    sensor.susan_moisture:
      friendly_name: "Moisture"
      icon: "mdi:water-percent"
    sensor.susan_temperature:
      friendly_name: "Temperature"
      icon: "mdi:thermometer"

group:
  plant_susan:
    name: "Susan"
    icon: "mdi:flower"
    entities:
      - plant.susan
      - sensor.susan_battery
      - sensor.susan_conductivity
      - sensor.susan_light_intensity
      - sensor.susan_moisture
      - sensor.susan_temperature

plant:
  susan:
    sensors:
      battery: sensor.susan_battery
      conductivity: sensor.susan_conductivity
      brightness: sensor.susan_light_intensity
      moisture: sensor.susan_moisture
      temperature: sensor.susan_temperature
    min_moisture: 20
    min_battery: 15
    min_temperature: 10

sensor:
  - platform: miflora
    mac: "C4:7C:8D:63:62:3E"
    name: "Susan"
    timeout: 30
    monitored_conditions:
      - battery
      - conductivity
      - light
      - moisture
      - temperature

