homeassistant:
  customize:
    plant.viny:
      friendly_name: "Viny"

plant:
  viny:
    sensors:
      battery: sensor.viny_battery
      conductivity: sensor.viny_conductivity
      brightness: sensor.viny_light_intensity
      moisture: sensor.viny_moisture
      temperature: sensor.viny_temperature
    min_battery: 10
    min_moisture: 20
    min_temperature: 15

sensor:
  - platform: miflora
    mac: "C4:7C:8D:63:62:3E"
    name: "Viny"
    median: 3
    monitored_conditions:
      - battery
      - conductivity
      - light
      - moisture
      - temperature

