homeassistant:
  customize:
    plant.viny:
      friendly_name: "Viny"
    sensor.viny_battery:
      friendly_name: "Battery"
      icon: "mdi:battery"
    sensor.viny_conductivity:
      friendly_name: "Conductivity"
      icon: "mdi:flash"
    sensor.viny_light_intensity:
      friendly_name: "Light"
      icon: "mdi:white-balance-sunny"
    sensor.viny_moisture:
      friendly_name: "Moisture"
      icon: "mdi:water-percent"
    sensor.viny_temperature:
      friendly_name: "Temperature"
      icon: "mdi:thermometer"

group:
  plant_viny:
    name: "Viny"
    icon: "mdi:flower"
    entities:
      - plant.viny
      - sensor.viny_battery
      - sensor.viny_conductivity
      - sensor.viny_light_intensity
      - sensor.viny_moisture
      - sensor.viny_temperature

plant:
  viny:
    sensors:
      battery: sensor.viny_battery
      conductivity: sensor.viny_conductivity
      brightness: sensor.viny_light_intensity
      moisture: sensor.viny_moisture
      temperature: sensor.viny_temperature
    min_moisture: 20
    min_battery: 15
    min_temperature: 10

sensor:
  - platform: miflora
    mac: "C4:7C:8D:63:62:3E"
    name: "Viny"
    timeout: 30
    monitored_conditions:
      - battery
      - conductivity
      - light
      - moisture
      - temperature

