homeassistant:
  customize:
    plant.viny:
      friendly_name: "Viny"
    sensor.viny_battery:
      friendly_name: "Viny's battery"
    sensor.viny_brightness:
      friendly_name: "Viny's brightness"
    sensor.viny_conductivity:
      friendly_name: "Viny's conductivity"
    sensor.viny_moisture:
      friendly_name: "Viny's moisture"
    sensor.viny_temperature:
      friendly_name: "Viny's temperature"

plant:
  viny:
    sensors:
      battery: sensor.viny_battery
      brightness: sensor.viny_brightness
      conductivity: sensor.viny_conductivity
      moisture: sensor.viny_moisture
      temperature: sensor.viny_temperature
    min_battery: 10
    min_moisture: 10
    min_temperature: 14

group:
  all_batteries:
    entities:
      - sensor.viny_battery

binary_sensor:
  - platform: template
    sensors:
      viny_problem:
        friendly_name: "Viny issues"
        device_class: "problem"
        icon_template: "mdi:flower"
        value_template: "{{ is_state('plant.viny', 'problem') }}"

sensor:
  - platform: mqtt
    name: "viny_battery"
    force_update: True
    device_class: "battery"
    unit_of_measurement: "%"
    state_topic: "plants/viny"
    value_template: "{{ value_json.battery }}"
    json_attributes:
      - timestamp
  - platform: mqtt
    name: "viny_brightness"
    force_update: True
    device_class: "illuminance"
    unit_of_measurement: "lx"
    state_topic: "plants/viny"
    value_template: "{{ value_json.brightness }}"
    json_attributes:
      - timestamp
  - platform: mqtt
    name: "viny_conductivity"
    force_update: True
    unit_of_measurement: "µS/cm"
    icon: "mdi:poop"
    state_topic: "plants/viny"
    value_template: "{{ value_json.conductivity }}"
    json_attributes:
      - timestamp
  - platform: mqtt
    name: "viny_moisture"
    force_update: True
    device_class: "humidity"
    unit_of_measurement: "%"
    state_topic: "plants/viny"
    value_template: "{{ value_json.moisture }}"
    json_attributes:
      - timestamp
  - platform: mqtt
    name: "viny_temperature"
    force_update: True
    device_class: "temperature"
    unit_of_measurement: "°C"
    state_topic: "plants/viny"
    value_template: "{{ value_json.temperature }}"
    json_attributes:
      - timestamp
