homeassistant:
  customize:
    group.default_View:
      order: 0
    group.media_view:
      order: 1
    group.weather_view:
      order: 2
    group.plants_view:
      order: 4
    group.settings_view:
      order: 6
    group.monitoring_view:
      order: 8

group:
  general_settings:
    name: "Settings"
    icon: "mdi:settings"
    control: "hidden"
    entities:
      - input_boolean.guest_mode
      - automation.close_outdoor_lights

  general_notifications:
    name: "Notifications"
    icon: "mdi:message-settings-variant"
    control: "hidden"
    entities:
      - automation.notify_plant_problems

  monitoring_notifications:
    name: "Notifications"
    icon: "mdi:message-settings-variant"
    control: "hidden"
    entities:
      - input_boolean.notify_household_changes
      - input_boolean.notify_power_changes
      - automation.notify_failed_login_attempt
      - automation.notify_update_available
      - automation.notify_new_network_device
      - automation.notify_network_device_state
      - automation.notify_ups_replace_battery

  celestial_bodies:
    name: "Celestial bodies"
    icon: "mdi:star-face"
    entities:
      - sun.sun
      - sensor.moon

  default_view:
    name: "Home"
    icon: "mdi:home"
    view: true
    entities:
      - group.household
      - group.outdoor
      - group.kitchen
      - group.dining_room
      - group.master_bedroom
      - group.living_room
      - group.lounge
      - group.office
      - group.main_bathroom
      - group.basement_bathroom
      - group.laundry_room

  media_view:
    name: "Media"
    icon: "mdi:music"
    view: True
    entities:
      - media_player.living_room_chromecast
      - media_player.living_room_google_home


  plants_view:
    name: "Plants"
    icon: "mdi:flower"
    view: true
    entities:
      - plant.gaetan
      - plant.spidy
      - plant.viny

  weather_view:
    name: "Weather"
    icon: "mdi:weather-partlycloudy"
    view: true
    entities:
      - weather.dark_sky
      - group.celestial_bodies

  settings_view:
    name: "Settings"
    icon: "mdi:settings"
    view: true
    entities:
      - group.general_settings
      - group.general_notifications
      - group.wake_up_alarm

  monitoring_view:
    name: "Monitoring"
    icon: "mdi:stethoscope"
    view: true
    entities:
      - group.monitoring_notifications
      - group.network_devices
      - group.monitoring_hass
      - group.ups
      - group.automate_monitor
      - group.media_monitor
      - group.relay_south_monitor
      - group.relay_north_monitor
