google_assistant:
  entity_config:
    light.basement_bathroom:
      expose: True
      room: "Basement bathroom"
      aliases:
        - "Basement bathroom light"
    light.basement_bathroom_vanity:
      expose: True
      room: "Basement bathroom"
      aliases:
        - "Basement bathroom vanity light"
        - "Basement bathroom vanity"
    switch.basement_bathroom_fan:
      expose: True
      room: "Basement bathroom"
      aliases:
        - "Basement bathroom fan"

light:
  - platform: group
    name: "Basement bathroom lights"
    entities:
      - light.basement_bathroom
      - light.basement_bathroom_vanity

  - platform: template
    lights:
      basement_bathroom:
        friendly_name: "Basement bathroom light"
        value_template: "{{ is_state('switch.basement_bathroom_light', 'on') }}"
        turn_on:
          service: "switch.turn_on"
          data:
            entity_id: "switch.basement_bathroom_light"
        turn_off:
          service: "switch.turn_off"
          data:
            entity_id: "switch.basement_bathroom_light"

automation:
  - alias: "basement_bathroom_lights_triple_up"
    hide_entity: True
    initial_state: True
    trigger:
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.basement_bathroom_vanity_light_dimmer"
          scene_id: 1
          scene_data: 7920
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.basement_bathroom_light_switch"
          scene_id: 1
          scene_data: 7920
    action:
      service: light.turn_on
      data:
        entity_id: "light.basement_bathroom_lights"
  - alias: "basement_bathroom_lights_triple_down"
    hide_entity: True
    initial_state: True
    trigger:
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.basement_bathroom_vanity_light_dimmer"
          scene_id: 2
          scene_data: 7920
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.basement_bathroom_light_switch"
          scene_id: 2
          scene_data: 7920
    action:
      service: light.turn_off
      data:
        entity_id: "light.basement_bathroom_lights"

