homeassistant:
  customize:
    sensor.kitchen_door_sensor_battery:
      battery_type: "Sensative Strip"
    sensor.kitchen_sink_leak_sensor_battery:
      battery_type: "ER14250 3.6V"

google_assistant:
  entity_config:
    light.kitchen:
      expose: True
      room: "Kitchen"
      aliases:
        - "Kitchen light"
        - "Kitchen"

group:
  all_batteries:
    entities:
      - sensor.kitchen_door_sensor_battery
      - sensor.kitchen_sink_leak_sensor_battery
  all_water_leak_sensors:
    entities:
      - binary_sensor.kitchen_sink_leak

light:
  - platform: group
    name: "Kitchen lights"
    entities:
      - light.kitchen

  - platform: template
    lights:
      kitchen:
        friendly_name: "Kitchen light"
        value_template: "{{ is_state('switch.kitchen_light', 'on') }}"
        turn_on:
          service: "switch.turn_on"
          data:
            entity_id: "switch.kitchen_light"
        turn_off:
          service: "switch.turn_off"
          data:
            entity_id: "switch.kitchen_light"

binary_sensor:
  - platform: template
    sensors:
      kitchen_door:
        friendly_name: "Kitchen door"
        device_class: "door"
        value_template: "{{ is_state('sensor.kitchen_door_sensor_access_control', '22') }}"
      kitchen_sink_leak:
        friendly_name: "Kitchen sink leak"
        device_class: "moisture"
        value_template: "{{ is_state('sensor.kitchen_sink_leak_sensor_flood', '2') }}"

sensor:
  - platform: template
    sensors:
      kitchen_door_sensor_battery:
        friendly_name: "Kitchen door sensor battery"
        device_class: "battery"
        unit_of_measurement: "%"
        value_template: "{{ state_attr('zwave.kitchen_door_sensor', 'battery_level') }}"
      kitchen_sink_leak_sensor_battery:
        friendly_name: "Kitchen sink leak sensor battery"
        device_class: "battery"
        unit_of_measurement: "%"
        value_template: "{{ state_attr('zwave.kitchen_sink_leak_sensor', 'battery_level') }}"
