homeassistant:
  customize:
    switch.living_room_ambiance:
      friendly_name: "Ambiance outlet"
      icon: "mdi:lightbulb"
    switch.living_room_bookshelf:
      friendly_name: "Bookshelf outlet"
      icon: "mdi:lightbulb"

google_assistant:
  entity_config:
    switch.living_room_ambiance:
      expose: True
      room: "living room"
    switch.living_room_bookshelf:
      expose: True
      aliases:
        - "Xmas tree"
        - "Christmas tree"
      room: "living room"

cast:
  media_player:
    - host: !secret media_player_cast_host
    - host: !secret media_player_home_host

group:
  living_room:
    name: "Living Room"
    icon: "mdi:television"
    entities:
      - switch.living_room_ambiance
      - switch.living_room_bookshelf

switch:
  - platform: rpi_rf
    gpio: 17
    switches:
      living_room_ambiance:
        protocol: 1
        pulselength: 186
        signal_repetitions: 25
        code_on: 5330227
        code_off: 5330236
      living_room_bookshelf:
        protocol: 1
        pulselength: 186
        signal_repetitions: 15
        code_on: 5330371
        code_off: 5330380

