homeassistant:
  customize:
    switch.living_room_ambiance:
      friendly_name: "Ambiance outlet"
      icon: "mdi:lightbulb"
    switch.living_room_bookshelf:
      friendly_name: "Bookshelf outlet"
      icon: "mdi:lightbulb"

google_assistant:
  entity_config:
    switch.living_room_tv:
      expose: True
      room: "Living room"
      aliases:
        - "Living room TV"
        - "TV"
    switch.living_room_ambiance:
      expose: True
      room: "Living room"
    switch.living_room_bookshelf:
      expose: True
      aliases:
        - "Xmas tree"
        - "Christmas tree"
      room: "Living room"

cast:
  media_player:
    - host: !secret media_player_cast_host
    - host: !secret media_player_home_host

group:
  living_room:
    name: "Living Room"
    icon: "mdi:television"
    entities:
      - switch.living_room_tv
      - switch.living_room_ambiance
      - switch.living_room_bookshelf

switch:
  - platform: broadlink
    mac: !secret broadlink_living_room_mac
    host: !secret broadlink_living_room_host
    type: "rm2_pro_plus"
    switches:
      living_room_tv:
        friendly_name: "Living room TV"
        command_on: "JgBQAAABKJMTERQRFDUUERQRFBEUERQQFDYTNhQRFDUUNhM2FDYTNhQRFBEUEBQ2ExIUEBQRFBEUNRQ2EzYUERQ1FDYTNhQ2EwAFIwABKEgUAA0FAAAAAAAAAAA="
        command_off: "JgBYAAABKZITERQRFDUXDhUQFBEUEBUQFDYTNhUQFTQUNhQ1FTUUNRQRFBEUEBQ2FRESERQRFBEUNRQ2FDUUERQ1EzcUNRQ2FAAFIgABKEkUAAxPAAEoSBQADQU="

  - platform: rpi_rf
    gpio: 17
    switches:
      living_room_ambiance:
        protocol: 1
        pulselength: 186
        signal_repetitions: 25
        code_on: 5330227
        code_off: 5330236
      living_room_bookshelf:
        protocol: 1
        pulselength: 186
        signal_repetitions: 15
        code_on: 5330371
        code_off: 5330380

