homeassistant:
  customize:
    sensor.living_room_door_sensor_battery:
      battery_type: "Sensative Strip"

google_assistant:
  entity_config:
    switch.living_room_tv:
      expose: True
      room: "Living room"
      aliases:
        - "TV"
        - "Living room TV"
    light.living_room_ambiance:
      expose: True
      room: "Living room"
      aliases:
        - "Living room light"
    light.bookshelf:
      expose: True
      room: "Living room"
      aliases:
        - "Bookshelf light"
        - "Bookshelf"
    switch.bookshelf_outlet:
      expose: True
      room: "Living room"
      aliases:
        - "Bookshelf outlet"
        - "Christmas tree"
        - "Xmas tree"

group:
  all_batteries:
    entities:
      - sensor.living_room_door_sensor_battery

cast:
  media_player:
    - host: !secret media_player_cast_host
    - host: !secret media_player_home_host

light:
  - platform: group
    name: "Living room lights"
    entities:
      - light.living_room_ambiance
      - light.bookshelf

  - platform: template
    lights:
      living_room_ambiance:
        friendly_name: "Living room ambiance"
        value_template: "{{ is_state('switch.living_room_ambiance', 'on') }}"
        turn_on:
          service: "switch.turn_on"
          data:
            entity_id: "switch.living_room_ambiance"
        turn_off:
          service: "switch.turn_off"
          data:
            entity_id: "switch.living_room_ambiance"
      bookshelf:
        friendly_name: "Bookshelf light"
        value_template: "{{ is_state('switch.bookshelf_light', 'on') }}"
        turn_on:
          service: "switch.turn_on"
          data:
            entity_id: "switch.bookshelf_light"
        turn_off:
          service: "switch.turn_off"
          data:
            entity_id: "switch.bookshelf_light"

switch:
  - platform: broadlink
    mac: !secret broadlink_living_room_mac
    host: !secret broadlink_living_room_host
    type: "rm2_pro_plus"
    switches:
      living_room_tv:
        friendly_name: "Living room TV"
        command_on: "JgBQAAABKJMTERQRFDUUERQRFBEUERQQFDYTNhQRFDUUNhM2FDYTNhQRFBEUEBQ2ExIUEBQRFBEUNRQ2EzYUERQ1FDYTNhQ2EwAFIwABKEgUAA0FAAAAAAAAAAA="
        command_off: "JgBYAAABKZITERQRFDUXDhUQFBEUEBUQFDYTNhUQFTQUNhQ1FTUUNRQRFBEUEBQ2FRESERQRFBEUNRQ2FDUUERQ1EzcUNRQ2FAAFIgABKEkUAAxPAAEoSBQADQU="
      living_room_ambiance:
        friendly_name: "Ambiance outlet"
        command_on: "svAyABMHBhMTBwYTBhMHExMHBxMTBwYTEwcHExMHBxMTBwYTBxMTBxMHBxMHExMHEwcGvwYTAAAA"
        command_off: "ssoyAAYUEggGFBIIBhQGFAYUEggGFRIIBhQSCAYUEggGFBMHBhQGFBIIEggTCBIIBhQGFAbAAAAA"
      bookshelf_outlet:
        friendly_name: "Bookshelf outlet"
        command_on: "sggyAAYUEggGFBMIBhQGFAYUEgcGFBIIBhQSCAYUEggGFBIIEwcSCAYUBhQGFAcUEggSCAa/AAAA"
        command_off: "sgkyAAYUEgcGFBIHBhQGFAYUEgcGFBIHBhQSCAYUEggGFBIHEggSCAYUBhQSBxMHBhQGFAa/AAAA"

binary_sensor:
  - platform: template
    sensors:
      living_room_door:
        friendly_name: "Living room door"
        device_class: "door"
        value_template: "{{ is_state('sensor.living_room_door_sensor_access_control', '22') }}"

sensor:
  - platform: template
    sensors:
      living_room_door_sensor_battery:
        friendly_name: "Living room door sensor battery"
        device_class: "battery"
        unit_of_measurement: "%"
        value_template: "{{ state_attr('zwave.living_room_door_sensor', 'battery_level') }}"

automation:
  - alias: "double_up_bookshelf"
    hide_entity: True
    initial_state: True
    trigger:
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.bookshelf_light_switch"
          scene_id: 1
          scene_data: 7860
    action:
      service: light.turn_on
      data:
        entity_id: "light.living_room_ambiance"
  - alias: "double_down_bookshelf"
    hide_entity: True
    initial_state: True
    trigger:
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.bookshelf_light_switch"
          scene_id: 2
          scene_data: 7860
    action:
      service: light.turn_off
      data:
        entity_id: "light.living_room_ambiance"
