google_assistant:
  entity_config:
    light.lounge:
      expose: True
      room: "Lounge"
      aliases:
        - "Lounge spots"
        - "Lounge light"
        - "Lounge"
    light.lounge_ambiance:
      expose: True
      room: "Lounge"
      aliases:
        - "Lounge ambiance light"
        - "Lounge ambiance"
    light.basement_hallway:
      expose: True
      room: "Lounge"
      aliases:
        - "Basement hallway light"
        - "Basement hallway"
    light.downstairs:
      expose: True
      room: "Lounge"
      aliases:
        - "Downstairs light"
        - "Downstairs"

light:
  - platform: group
    name: "Lounge lights"
    entities:
      - light.lounge
      - light.lounge_ambiance
      - light.basement_hallway
      - light.downstairs

  - platform: template
    lights:
      downstairs:
        friendly_name: "Downstairs light"
        value_template: "{{ is_state('switch.downstairs_light', 'on') }}"
        turn_on:
          service: "switch.turn_on"
          data:
            entity_id: "switch.downstairs_light"
        turn_off:
          service: "switch.turn_off"
          data:
            entity_id: "switch.downstairs_light"

automation:
  - alias: "triple_up_downstairs_lights"
    hide_entity: True
    initial_state: True
    trigger:
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.basement_hallway_light_dimmer"
          scene_id: 1
          scene_data: 7920
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.downstairs_light_switch"
          scene_id: 1
          scene_data: 7920
    action:
      service: light.turn_on
      data:
        entity_id: "light.basement_lights"
  - alias: "triple_down_downstairs_lights"
    hide_entity: True
    initial_state: True
    trigger:
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.basement_hallway_light_dimmer"
          scene_id: 2
          scene_data: 7920
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.downstairs_light_switch"
          scene_id: 2
          scene_data: 7920
    action:
      service: light.turn_off
      data:
        entity_id: "light.basement_lights"

