google_assistant:
  entity_config:
    light.main_bathroom:
      expose: True
      room: "Main bathroom"
      aliases:
        - "Bathroom light"
        - "Main bathroom light"
    light.main_bathroom_vanity:
      expose: True
      room: "Main bathroom"
      aliases:
        - "Vanity light"
        - "Vanity"
        - "Bathroom vanity light"
        - "Main bathroom vanity light"
    switch.main_bathroom_fan:
      expose: True
      room: "Main bathroom"
      aliases:
        - "Bathroom fan"
        - "Main bathroom fan"

light:
  - platform: group
    name: "Main bathroom lights"
    entities:
      - light.main_bathroom
      - light.main_bathroom_vanity

  - platform: template
    lights:
      main_bathroom_vanity:
        friendly_name: "Main bathroom vanity light"
        value_template: "{{ is_state('switch.main_bathroom_vanity_light', 'on') }}"
        turn_on:
          service: "switch.turn_on"
          data:
            entity_id: "switch.main_bathroom_vanity_light"
        turn_off:
          service: "switch.turn_off"
          data:
            entity_id: "switch.main_bathroom_vanity_light"

automation:
  - alias: "double_up_main_bathroom_lights"
    hide_entity: True
    initial_state: True
    trigger:
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.main_bathroom_light_dimmer"
          scene_id: 1
          scene_data: 7860
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.main_bathroom_vanity_light_switch"
          scene_id: 1
          scene_data: 7860
    action:
      service: light.turn_on
      data:
        entity_id: "light.main_bathroom_lights"
  - alias: "double_down_main_bathroom_lights"
    hide_entity: True
    initial_state: True
    trigger:
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.main_bathroom_light_dimmer"
          scene_id: 2
          scene_data: 7860
      - platform: event
        event_type: "zwave.scene_activated"
        event_data:
          entity_id: "zwave.main_bathroom_vanity_light_switch"
          scene_id: 2
          scene_data: 7860
    action:
      service: light.turn_off
      data:
        entity_id: "light.main_bathroom_lights"
