homeassistant:
  customize:
    light.hue_color_lamp_1:
      friendly_name: "Bedside Chris"
      google_assistant: True
    light.hue_color_lamp_3:
      friendly_name: "Bedside Karine"
      google_assistant: True
    group.master_bedroom_light_bedside:
      google_assistant: True
      google_assistant_name: "Bedside lamps"
      google_assistant_type: light

group:
  master_bedroom:
    name: "Master Bedroom"
    icon: "mdi:hotel"
    entities:
      - light.hue_color_lamp_1
      - light.hue_color_lamp_3

  master_bedroom_light:
    name: "Master Bedroom - Lights"
    icon: "mdi:lightbulb"
    entities:
      - light.hue_color_lamp_1
      - light.hue_color_lamp_3

  master_bedroom_light_bedside:
    name: "Master Bedroom - Lights - Bedside"
    icon: "mdi:lightbulb"
    entities:
      - light.hue_color_lamp_1
      - light.hue_color_lamp_3
