homeassistant:
  customize:
    light.hue_color_lamp_1:
      friendly_name: "Bedside Chris"
    light.hue_color_lamp_3:
      friendly_name: "Bedside Karine"

group:
  master_bedroom:
    name: "Master Bedroom"
    icon: "mdi:hotel"
    entities:
      - light.hue_color_lamp_1
      - light.hue_color_lamp_3

  master_bedroom_light:
    name: "Master Bedroom - Lights"
    icon: "mdi:lightbulb"
    entities:
      - light.hue_color_lamp_1
      - light.hue_color_lamp_3

  master_bedroom_light_bedside:
    name: "Master Bedroom - Lights - Bedside"
    icon: "mdi:lightbulb"
    entities:
      - light.hue_color_lamp_1
      - light.hue_color_lamp_3
