homeassistant:
  customize:
    light.master_bedroom_lights:
      friendly_name: "Master Bedroom Lights"
      icon: "mdi:lightbulb"
    light.master_bedroom_bedside_lights:
      friendly_name: "Master Bedroom Bedside Lights"
      icon: "mdi:lightbulb"

group:
  master_bedroom:
    name: "Master Bedroom"
    icon: "mdi:hotel"
    entities:
      - light.master_bedroom_lights

light:
  - platform: group
    name: "master_bedroom_bedside_lights"
    entities:
      - light.bedside_chris
      - light.bedside_karine
  - platform: group
    name: "master_bedroom_lights"
    entities:
      - light.master_bedroom_bedside_lights
