homeassistant:
  customize:
    light.master_bedroom_bedsides:
      friendly_name: "Master bedroom bedside lights"
      icon: "mdi:lightbulb"

google_assistant:
  entity_config:
    light.bedside_chris:
      expose: True
      room: "Master bedroom"
      aliases:
        - "Bedside Chris"
    light.bedside_karine:
      expose: True
      room: "Master bedroom"
      aliases:
        - "Bedside Karine"

light:
  - platform: group
    name: "master_bedroom_bedsides"
    entities:
      - light.bedside_chris
      - light.bedside_karine

group:
  master_bedroom:
    name: "Master Bedroom"
    icon: "mdi:hotel"
    entities:
      - light.bedside_chris
      - light.bedside_karine
  master_bedroom_lights:
    name: "Master bedroom lights"
    icon: "mdi:lightbulb"
    entities:
      - light.master_bedroom_bedsides
