homeassistant:
  customize:
    light.master_bedroom_lights:
      friendly_name: "Master Bedroom Lights"
      icon: "mdi:lightbulb"
    light.master_bedroom_bedside_lights:
      friendly_name: "Master Bedroom Bedside Lights"
      icon: "mdi:lightbulb"

google_assistant:
  entity_config:
    light.master_bedroom_bedside_lights:
      expose: True
      room: "master bedroom"
      aliases:
        - "bedside lamps"
        - "bedroom lamps"
    light.bedside_chris:
      expose: True
      room: "master bedroom"
    light.bedside_karine:
      expose: True
      room: "master bedroom"

group:
  master_bedroom:
    name: "Master Bedroom"
    icon: "mdi:hotel"
    entities:
      - light.bedside_chris
      - light.bedside_karine

light:
  - platform: group
    name: "master_bedroom_bedside_lights"
    entities:
      - light.bedside_chris
      - light.bedside_karine
  - platform: group
    name: "master_bedroom_lights"
    entities:
      - light.master_bedroom_bedside_lights
