homeassistant:
  customize:
    light.outdoor_lights:
      friendly_name: "Outdoor Lights"
      icon: "mdi:home"

group:
  outdoor:
    name: "Outdoor"
    icon: "mdi:home"
    entities:
      - light.outdoor_lights

light:
  - platform: group
    name: outdoor_lights
    entities:
      - light.side_porch

