homeassistant:
  customize:
    light.outdoor_lights:
      friendly_name: "Outdoor Lights"
      icon: "mdi:home"

google_assistant:
  entity_config:
    light.outdoor_lights:
      expose: True
      room: "outdoor"
    light.side_porch:
      expose: True
      aliases:
        - "porch"
      room: "outdoor"

group:
  outdoor:
    name: "Outdoor"
    icon: "mdi:home"
    entities:
      - light.side_porch

light:
  - platform: group
    name: outdoor_lights
    entities:
      - light.side_porch

