homeassistant:
  customize:
    light.hue_color_lamp_2:
      friendly_name: "Side Porch"
      google_assistant: True
      aliases:
        - "porch"

group:
  outdoor:
    name: "Outdoor"
    icon: "mdi:home"
    entities:
      - light.hue_color_lamp_2

  outdoor_light:
    name: "Outdoor - Lights"
    icon: "mdi:home"
    entities:
      - light.hue_color_lamp_2

