homeassistant:
  customize:
    light.outdoor_lights:
      friendly_name: "Outdoor Lights"
      icon: "mdi:home"
    light.hue_color_lamp_2:
      friendly_name: "Side Porch"

group:
  outdoor:
    name: "Outdoor"
    icon: "mdi:home"
    entities:
      - light.hue_color_lamp_2

light:
  - platform: group
    name: outdoor_lights
    entities:
      - light.hue_color_lamp_2

