google_assistant:
  entity_config:
    switch.workshop_light:
      expose: True
      aliases:
        - "workshop light"
      room: "Workshop"

group:
  workshop:
    name: "Workshop"
    icon: "mdi:hammer"
    entities:
      - switch.workshop_light
      - binary_sensor.water_heater_leak

binary_sensor:
  - platform: template
    sensors:
      water_heater_leak:
        friendly_name: "Water heater leak"
        device_class: "moisture"
        value_template: "{{ is_state('sensor.water_heater_leak_sensor_flood', '2') }}"

