homeassistant:
  customize:
    sensor.water_heater_leak_sensor_battery:
      battery_type: "ER14250 3.6V"

google_assistant:
  entity_config:
    light.workshop:
      expose: True
      room: "Workshop"
      aliases:
        - "Workshop light"
        - "Workshop"

group:
  all_batteries:
    entities:
      - sensor.water_heater_leak_sensor_battery
  all_water_leak_sensors:
    entities:
      - binary_sensor.water_heater_leak

light:
  - platform: group
    name: "Workshop lights"
    entities:
      - light.workshop

  - platform: template
    lights:
      workshop:
        friendly_name: "Workshop light"
        value_template: "{{ is_state('switch.workshop_light', 'on') }}"
        turn_on:
          service: "switch.turn_on"
          data:
            entity_id: "switch.workshop_light"
        turn_off:
          service: "switch.turn_off"
          data:
            entity_id: "switch.workshop_light"

binary_sensor:
  - platform: template
    sensors:
      water_heater_leak:
        friendly_name: "Water heater leak"
        device_class: "moisture"
        value_template: "{{ is_state('sensor.water_heater_leak_sensor_flood', '2') }}"

sensor:
  - platform: template
    sensors:
      water_heater_leak_sensor_battery:
        friendly_name: "Water heater leak sensor battery"
        device_class: "battery"
        unit_of_measurement: "%"
        value_template: "{{ state_attr('zwave.water_heater_leak_sensor', 'battery_level') }}"

