input_boolean:
  use_heat_pump_virtual_probe:
    name: "Use virtual temperature probe"
    icon: "mdi:thermostat-auto"

input_number:
  heat_pump_eco_setpoint:
    name: "Heat pump eco setpoint"
    <<: &setpoint_config
      unit_of_measurement: "°C"
      icon: "mdi:thermometer-lines"
      mode: "box"
      min: 8
      max: 25
      step: 0.5
  heat_pump_comfort_setpoint:
    name: "Heat pump comfort setpoint"
    <<: *setpoint_config

input_select:
  heat_pump_auto_mode:
    name: "Heat pump auto mode"
    icon: mdi:home-thermometer-outline
    options: ["Comfort", "Eco"]
  heat_pump_mode:
    name: "Heat pump mode"
    icon: mdi:home-thermometer-outline
    options: ["Auto", "Manual"]

sensor:
  - platform: "min_max"
    unique_id: "c03b6317-af2a-4655-a07a-44e98c940437"
    name: "heat_pump_virtual_probe"
    type: "mean"
    round_digits: 1
    entity_ids:
      - "sensor.living_room_temperature"
      - "sensor.master_bedroom_temperature"
      - "sensor.office_temperature"

timer:
  heat_pump_manual_mode_reset:
    name: "Reset heat pump to auto mode"
    duration: "01:00:00"
    restore: true

automation:
  - id: "77087f1e-f617-4fa6-8520-22793f3c1bfb"
    alias: "Use internal heat pump temperature probe"
    description: "Switch to the internal heat pump temperature probe"
    mode: "restart"
    triggers:
      - trigger: "state"
        entity_id: "input_boolean.use_heat_pump_virtual_probe"
        to: "off"
    actions:
      - action: "esphome.ground_floor_heat_pump_use_internal_temperature"

  - id: "4c8cf214-db8a-4d0e-b039-f502dc5e21ed"
    alias: "Sync virtual heat pump temperature probe"
    description: "Keep the heat pump's external temperature prope in sync with thermostat readings"
    mode: "restart"
    triggers:
      - trigger: "homeassistant"
        event: "start"
      - trigger: "state"
        entity_id: "input_boolean.use_heat_pump_virtual_probe"
        to: "on"
      - trigger: "state"
        entity_id: "sensor.heat_pump_virtual_probe"
        for: 5
        not_to: "unavailable"
    conditions:
      - condition: "state"
        entity_id: "input_boolean.use_heat_pump_virtual_probe"
        state: "on"
      - not:
          - condition: "state"
            entity_id: "sensor.heat_pump_virtual_probe"
            state: "unavailable"
    actions:
      - action: "esphome.ground_floor_heat_pump_set_remote_temperature"
        data:
          temperature: "{{ states('sensor.heat_pump_virtual_probe') | round(precision = 0) }}"
