homeassistant:
  customize:
    sensor.manual_thermostats_count:
      friendly_name: "Thermostats in manual mode"

group:
  managed_thermostats:
    name: "Managed thermostats"
    icon: "mdi:thermostat-box"
    entities: &managed_thermostats
      - "climate.basement_hallway_thermostat"
      - "climate.dining_room_thermostat"
      - "climate.guest_bedroom_thermostat"
      - "climate.living_room_thermostat"
      - "climate.lounge_thermostat"
      - "climate.master_bedroom_thermostat"
      - "climate.office_thermostat"
      - "climate.studio_thermostat"

  managed_thermostat_modes:
    name: "Managed thermostat modes"
    icon: "mdi:home-thermometer"
    entities: &managed_thermostat_modes
      - input_select.basement_hallway_thermostat_mode
      - input_select.dining_room_thermostat_mode
      - input_select.guest_bedroom_thermostat_mode
      - input_select.living_room_thermostat_mode
      - input_select.lounge_thermostat_mode
      - input_select.master_bedroom_thermostat_mode
      - input_select.office_thermostat_mode
      - input_select.studio_thermostat_mode

  managed_thermostat_auto_modes:
    name: "Managed thermostat auto modes"
    icon: "mdi:home-thermometer"
    entities: &managed_thermostat_auto_modes
      - input_select.basement_hallway_thermostat_auto_mode
      - input_select.dining_room_thermostat_auto_mode
      - input_select.guest_bedroom_thermostat_auto_mode
      - input_select.living_room_thermostat_auto_mode
      - input_select.lounge_thermostat_auto_mode
      - input_select.master_bedroom_thermostat_auto_mode
      - input_select.office_thermostat_auto_mode
      - input_select.studio_thermostat_auto_mode

  managed_thermostat_eco_setpoints:
    name: "Managed thermostat eco setpoints"
    icon: "mdi:thermometer-lines"
    entities: &managed_thermostat_eco_setpoints
      - input_number.basement_hallway_thermostat_eco_setpoint
      - input_number.dining_room_thermostat_eco_setpoint
      - input_number.guest_bedroom_thermostat_eco_setpoint
      - input_number.living_room_thermostat_eco_setpoint
      - input_number.lounge_thermostat_eco_setpoint
      - input_number.master_bedroom_thermostat_eco_setpoint
      - input_number.office_thermostat_eco_setpoint
      - input_number.studio_thermostat_eco_setpoint

  managed_thermostat_comfort_setpoints:
    name: "Managed thermostat comfort setpoints"
    icon: "mdi:thermometer-lines"
    entities: &managed_thermostat_comfort_setpoints
      - input_number.basement_hallway_thermostat_comfort_setpoint
      - input_number.dining_room_thermostat_comfort_setpoint
      - input_number.guest_bedroom_thermostat_comfort_setpoint
      - input_number.living_room_thermostat_comfort_setpoint
      - input_number.lounge_thermostat_comfort_setpoint
      - input_number.master_bedroom_thermostat_comfort_setpoint
      - input_number.office_thermostat_comfort_setpoint
      - input_number.studio_thermostat_comfort_setpoint

  managed_thermostat_boost_setpoints:
    name: "Managed thermostat boost setpoints"
    icon: "mdi:thermometer-lines"
    entities: &managed_thermostat_boost_setpoints
      - input_number.basement_hallway_thermostat_boost_setpoint
      - input_number.dining_room_thermostat_boost_setpoint
      - input_number.guest_bedroom_thermostat_boost_setpoint
      - input_number.living_room_thermostat_boost_setpoint
      - input_number.lounge_thermostat_boost_setpoint
      - input_number.master_bedroom_thermostat_boost_setpoint
      - input_number.office_thermostat_boost_setpoint
      - input_number.studio_thermostat_boost_setpoint

template:
  sensor:
    - unique_id: "sensor.manual_thermostats_count"
      name: "manual_thermostats_count"
      icon: "mdi:thermometer-alert"
      state: |
        {{
          expand('group.managed_thermostat_modes')
            | selectattr('state', 'eq', 'Manual')
            | list
            | count
        }}
      attributes:
        entity_id: |
          {{
            expand('group.managed_thermostat_modes')
              | selectattr('state', 'eq', 'Manual')
              | map('attr', 'entity_id')
              | list
          }}

script:
  restore_climate_auto_mode:
    alias: "Restore auto mode on all thermostats"
    icon: "mdi:thermometer-alert"
    mode: "queued"
    max_exceeded: "silent"
    sequence:
      - service: input_select.select_option
        data:
          entity_id: "{{ expand('group.managed_thermostat_modes') | map(attribute = 'entity_id') | list }}"
          option: "Auto"

automation:
  - id: "5c387ec4-b18b-4ec6-9174-8d844e7e88e9"
    alias: "revert_manual_thermostat_mode"
    mode: "parallel"
    max: 9
    use_blueprint:
      path: "reset_input_select.yaml"
      input:
        default_option: "Auto"
        delay: 3600
        entity_id: *managed_thermostat_modes

  - id: "a8b031db-937a-4b34-bd64-a30f51900ed0"
    alias: "select_manual_thermostat_mode"
    initial_state: true
    mode: "parallel"
    max: 9

    trigger:
      - platform: state
        entity_id: *managed_thermostats
        attribute: "temperature"
        for: 5

    variables:
      <<: &climate_variables
        thermostat_name: >-
          {{
            trigger.to_state.object_id
              | replace('_auto_mode', '')
              | replace('_mode', '')
              | replace('_boost_setpoint', '')
              | replace('_comfort_setpoint', '')
              | replace('_eco_setpoint', '')
          }}
        auto_mode: "{{ states('input_select.{}_auto_mode'.format(thermostat_name)) | default('Eco') }}"
        mode: "{{ states('input_select.{}_mode'.format(thermostat_name)) | default('Auto') }}"
        planned_setpoint: "{{ states('input_number.{}_{}_setpoint'.format(thermostat_name, auto_mode | lower)) | float }}"
      current_setpoint: "{{ trigger.to_state.attributes.temperature | float }}"

    condition: "{{ trigger.to_state.attributes.preset_mode != 'none' or planned_setpoint != current_setpoint }}"

    action:
      - service: "input_select.select_option"
        data:
          entity_id: "input_select.{{ thermostat_name }}_mode"
          option: "Manual"

  - id: "0954c8e4-8429-4777-a8ba-4a1c99853ea2"
    alias: "update_thermostat_setpoint"
    initial_state: true
    mode: "queued"
    max: 9

    trigger:
      - platform: state
        entity_id: *managed_thermostat_modes
        to: "Auto"
      - platform: state
        entity_id: *managed_thermostat_auto_modes
      - platform: state
        entity_id: *managed_thermostat_boost_setpoints
        for: 5
      - platform: state
        entity_id: *managed_thermostat_comfort_setpoints
        for: 5
      - platform: state
        entity_id: *managed_thermostat_eco_setpoints
        for: 5

    variables:
      <<: *climate_variables
      current_setpoint: "{{ state_attr('climate.{}'.format(thermostat_name), 'temperature') | float }}"

    condition: "{{ mode == 'Auto' and planned_setpoint != current_setpoint }}"

    action:
      - service: "climate.set_temperature"
        data:
          entity_id: "climate.{{ thermostat_name }}"
          temperature: "{{ planned_setpoint }}"
