# Example messages:
#   `Reminder. Peak demand event - Winter Credit Option: today, Dec. 18, from 6 to 9 a.m.`
#   `Peak demand event notification - Winter Credit Option: tomorrow, Jan. 19, from 4 to 8 PM`

# This may lead to duplicates. The source notification is sent more than once. Need more
# data to filter out duplicates.

automation:
  - alias: "schedule_hydro_peak_event"
    initial_state: true
    mode: "parallel"

    trigger:
      - platform: state
        entity_id: "sensor.chris_moto_g7_last_notification"

    variables:
      text: "{{ trigger.to_state.attributes['android.text'] }}"

    condition:
      - "{{ trigger.to_state.attributes.package == 'com.hydroquebec.mf_android' }}"
      - "{{ 'Winter Credit Option:' in text }}"
      - "{{ 'Reminder.' not in text }}"

    action:
      - variables:
          text: "{{ text | replace('a.m.', 'AM') | replace('p.m.', 'PM') }}"
          pattern: '([a-z]+\.? \d{1,2}), from (\d{1,2}(?::\d{2})?)(?: (AM|PM))? to (\d{1,2}(?::\d{2})?)(?: (AM|PM)?)'
          count: "{{ (text | regex_replace(pattern, '___MATCH___', ignorecase = True)).count('___MATCH___') }}"
          events: >
            {% set ns = namespace(events = []) %}

            {% for index in range(count) %}
              {% set match = text | regex_findall_index(pattern, index = index, ignorecase = True) -%}
              {% set day = strptime(match[0] | regex_replace('[^a-zA-Z0-9 ]', ''), '%b %d') -%}
              {% set start_hour = strptime(
                  match[1]
                    ~ (':00' if ':' not in match[1])
                    ~ ' ' ~ (match[2] or match[4] or 'AM'),
                  '%I:%M %p') -%}
              {% set end_hour = strptime(
                  match[3]
                    ~ (':00' if ':' not in match[3])
                    ~ ' ' ~ (match[4] or match[2] or 'AM'),
                  '%I:%M %p') -%}

              {% if [day, start_hour, end_hour] | select('string') | first is undefined -%}
                {%- set start = day.replace(year = now().year, hour = start_hour.hour, minute = start_hour.minute) -%}
                {%- set end = day.replace(year = now().year, hour = end_hour.hour, minute = end_hour.minute) -%}
                {% set ns.events = ns.events + [{
                  'start': (start - timedelta(hours = 1, minutes = 30)) | as_timestamp | timestamp_local,
                  'end': start | as_timestamp | timestamp_local,
                  'preset': 'Active',
                }, {
                  'start': start | as_timestamp | timestamp_local,
                  'end': end | as_timestamp | timestamp_local,
                  'preset': 'Peak Event',
                }] -%}
              {% endif -%}
            {% endfor %}

            {{ ns.events }}

      - choose:
          - conditions:
              - "{{ count == 0 or count != events | length / 2 }}"
            sequence:
              - service: persistent_notification.create
                data:
                  title: "Failed to parse peak event notification"
                  message: |
                    <strong>{{ text }}</strong>
                    <hr>
                    <pre>{{ events }}</pre>

      - repeat:
          count: "{{ events | length }}"
          sequence:
            - service: google.add_event
              data:
                calendar_id: !secret gcal_climate_id
                summary: "{{ events[repeat.index - 1].preset }} #special"
                description: "{{ text }}"
                start_date_time: "{{ events[repeat.index - 1].start }}"
                end_date_time: "{{ events[repeat.index - 1].end }}"
