homeassistant:
  customize:
    sensor.scheduled_climate_preset:
      friendly_name: "Scheduled climate preset"

input_boolean:
  climate_scheduling_enabled:
    name: "Enable climate scheduling"
    icon: "mdi:thermometer-auto"

template:
  - sensor:
      - unique_id: "sensor.scheduled_climate_preset"
        name: "scheduled_climate_preset"
        icon: "mdi:thermometer-lines"
        state: >-
          {% set supported_presets = [
            'Active',
            'Away',
            'Bedtime',
            'Boost',
            'Sleep',
            'Winter Credit: Cool',
            'Winter Credit: Heat',
            'Winter Credit: Peak Event',
          ] -%}
          {% macro parse_calendar_preset(entity_id, default) -%}
            {% if is_state(entity_id, 'on') -%}
              {% set scheduled_preset = state_attr(entity_id, 'message').split('#')[0] | trim -%}
              {{ scheduled_preset if scheduled_preset in supported_presets else default }}
            {% else -%}
              {{ default }}
            {% endif -%}
          {% endmacro %}

          {% set self = 'sensor.scheduled_climate_preset' -%}
          {% set preset = 'Away' -%}
          {% set winter_credit_baseline_preset = states('sensor.winter_credit_baseline_climate_preset') -%}

          {% if winter_credit_baseline_preset in supported_presets %}
            {% set preset = winter_credit_baseline_preset %}
          {% elif is_state('group.household', 'home') -%}
            {% set preset = parse_calendar_preset(
                'calendar.climate',
                (states[self].state if states[self] else 'Active')
              ) -%}
          {% endif -%}

          {{ parse_calendar_preset('calendar.climate_exceptions', preset) }}

script:
  assign_climate_auto_mode:
    alias: "assign_climate_auto_mode"
    description: ""
    mode: "restart"
    fields:
      mode:
        description: "The setpoint mode to assign to all thermostat. One of Comfort or Eco."
        example: "Comfort"
      exceptions:
        description: "Dictionary of room IDs with their setpoint mode that differ from the default mode."
        example: "{\"office_thermostat\": \"Eco\"}"
    sequence:
      - action: scene.apply
        data:
          entities: >
            {% set ns = namespace(entries = []) %}
            {% for entity_id in expand('group.managed_climate_auto_modes') | map(attribute = 'entity_id') %}
              {% set ns.entries = ns.entries + ['"{}": "{}"'.format(entity_id, mode)] %}
            {% endfor %}
            {% for room_key, override_preset in (exceptions | default({})).items() %}
              {% set ns.entries = ns.entries + ['"input_select.{}_auto_mode": "{}"'.format(room_key, override_preset)] %}
            {% endfor %}
            {{ "{{\n{}\n}}".format(ns.entries | join(',\n')) | from_json }}

  apply_scheduled_climate_preset:
    alias: "apply_scheduled_climate_preset"
    description: "Set auto climate modes based on the pre-configured schedule"
    icon: "mdi:thermometer-lines"
    mode: "restart"
    variables:
      preset: "{{ states('sensor.scheduled_climate_preset') | lower }}"
    sequence:
      - choose:
          - conditions: "{{ preset == 'active' }}"
            sequence:
              - action: script.assign_climate_auto_mode
                data:
                  mode: "Comfort"
                  exceptions:
                    dining_room_thermostat: "Eco"
                    living_room_thermostat: "Eco"
                    master_bedroom_thermostat: "Eco"
                    office_thermostat: "Eco"
          - conditions: "{{ preset == 'away' }}"
            sequence:
              - action: script.assign_climate_auto_mode
                data:
                  mode: "Eco"
                  exceptions:
                    studio_thermostat: "Comfort"
          - conditions: "{{ preset == 'bedtime' }}"
            sequence:
              - action: script.assign_climate_auto_mode
                data:
                  mode: "Eco"
                  exceptions:
                    heat_pump: "Comfort"
                    guest_bedroom_thermostat: "Comfort"
                    studio_thermostat: "Comfort"
          - conditions: "{{ preset == 'boost' }}"
            sequence:
              - action: script.assign_climate_auto_mode
                data:
                  mode: "Comfort"
          - conditions: "{{ preset == 'sleep' }}"
            sequence:
              - action: script.assign_climate_auto_mode
                data:
                  mode: "Eco"
                  exceptions:
                    heat_pump: "Comfort"

          # Winter Credit presets
          - conditions: "{{ preset == 'winter credit: cool' }}"
            sequence:
              - action: script.assign_climate_auto_mode
                data:
                  mode: "Eco"  # TODO: heat_pump=OFF
          - conditions: "{{ preset == 'winter credit: heat' }}"
            sequence:
              - action: script.assign_climate_auto_mode
                data:
                  mode: "Comfort"
                  exceptions:
                    heat_pump: "Eco"
          - conditions: "{{ preset == 'winter credit: peak event' }}"
            sequence:
              - action: script.assign_climate_auto_mode
                data:
                  mode: "Eco"  # TODO: heat_pump=OFF

        default:
          - action: "system_log.write"
            data:
              level: "warning"
              message: "Invalid scheduled climate preset: '{{ preset }}'."

automation:
  - id: "fd33012e-1f9a-4205-8c29-3639015bd2ad"
    alias: "apply_scheduled_climate_preset"
    initial_state: true
    mode: "restart"
    triggers:
      - trigger: "state"
        entity_id: "sensor.scheduled_climate_preset"
        to: ~
      - trigger: "state"
        entity_id: "input_boolean.climate_scheduling_enabled"
        to: "on"
    conditions:
      - condition: "state"
        entity_id: "input_boolean.climate_scheduling_enabled"
        state: "on"
      - "{{ has_value('sensor.scheduled_climate_preset') }}"
    actions:
      - action: "script.apply_scheduled_climate_preset"
