# Example messages:
#   `Reminder. Peak demand event - Winter Credit Option: today, Dec. 18, from 6 to 9 a.m.`
#   `Peak demand event notification - Winter Credit Option: tomorrow, Jan. 19, from 4 to 8 p.m.`
#   `Peak demand event notification - Winter Credit Option: tomorrow, Jan. 21, from 6 to 9 a.m. and from 4 to 8 p.m.`

homeassistant:
  customize:
    sensor.winter_credit_baseline_climate_preset:
      friendly_name: "Winter credit: baseline climate preset"

template:
  - binary_sensor:
      - unique_id: "4ff23e99-f31f-4b96-9cb8-dd53b3796354"
        name: "winter_credit_enabled"
        state: >-
          {% set date = states('sensor.date') | as_datetime -%}
          {{
            date is not none and (date.month <= 3 or date.month == 12)
          }}
      - unique_id: "42ce95f4-91ce-41dd-8d33-61fba466e7f6"
        name: "winter_credit_peak_event"
        icon: "mdi:snowflake-alert"
        state: >-
          {% set special_schedule = state_attr('calendar.climate_exceptions', 'message') | default('', True) -%}
          {{ 'Winter Credit: Peak Event' in special_schedule }}

    sensor:
      - unique_id: "sensor.winter_credit_baseline_climate_preset"
        name: "winter_credit_baseline_climate_preset"
        icon: "mdi:snowflake-thermometer"
        state: >-
          {% set cooling_delta = 3 %}
          {% set peak_events = [range(6, 9), range(16, 20)] %}

          {% set hour = states('sensor.hour') | int(0) %}
          {% set ns = namespace(preset = '') %}

          {% if is_state('binary_sensor.winter_credit_enabled', 'on') %}
            {% for event in peak_events if not ns.preset %}
              {% if hour in event %}
                {% set ns.preset = 'Winter Credit: Heat' %}
              {% elif hour in range(event[0] - cooling_delta, event[0]) %}
                {% set ns.preset = 'Winter Credit: Cool' %}
              {% endif %}
            {% endfor %}
          {% endif %}

          {{ ns.preset }}

automation:
  - id: "dc44848a-cdb1-4b0b-bd76-711a2f81e4b2"
    alias: "schedule_hydro_peak_event"
    initial_state: true
    mode: "parallel"

    trigger:
      - platform: state
        entity_id: "sensor.chris_pixel_6_last_notification"
        to: ~

    variables:
      text: "{{ trigger.to_state.attributes['android.text'] | default('') }}"

    condition:
      - "{{ is_state('binary_sensor.winter_credit_enabled', 'on') }}"
      - "{{ trigger.to_state.attributes['package'] | default('') == 'com.hydroquebec.mf_android' }}"
      - "{{ 'Winter Credit Option:' in text }}"
      - "{{ 'Reminder.' not in text }}"

    action:
      - variables:
          text: "{{ text | replace('a.m.', 'AM') | replace('p.m.', 'PM') }}"
          # yamllint disable-line rule:quoted-strings
          pattern: '(?:([a-z]+\.? \d{1,2}), )?from (\d{1,2}(?::\d{2})?)(?: (AM|PM))? to (\d{1,2}(?::\d{2})?)(?: (AM|PM)?)'
          date_time_format: "%Y-%m-%d %H:%M:%S"
          count: "{{ text | regex_findall(pattern, ignorecase = True) | length }}"
          events: >
            {% set ns = namespace(day = undefined, events = []) %}

            {% for match in (text | regex_findall(pattern, ignorecase = True)) %}
              {% set ns.day = strptime(match[0] | regex_replace('[^a-zA-Z0-9 ]', ''), '%b %d') | default(ns.day, True) -%}
              {% set start_hour = strptime(
                  match[1]
                    ~ (':00' if ':' not in match[1])
                    ~ ' ' ~ (match[2] or match[4] or 'AM'),
                  '%I:%M %p') -%}
              {% set end_hour = strptime(
                  match[3]
                    ~ (':00' if ':' not in match[3])
                    ~ ' ' ~ (match[4] or match[2] or 'AM'),
                  '%I:%M %p') -%}

              {% if [ns.day, start_hour, end_hour] | select('string') | first is undefined -%}
                {%- set start = ns.day.replace(year = now().year, hour = start_hour.hour, minute = start_hour.minute) -%}
                {%- set end = ns.day.replace(year = now().year, hour = end_hour.hour, minute = end_hour.minute) -%}
                {% set ns.events = ns.events + [{
                  'start': (start - timedelta(hours = 1, minutes = 30)) | as_timestamp | timestamp_custom(date_time_format),
                  'end': start | as_timestamp | timestamp_custom(date_time_format),
                  'preset': 'Boost',
                }, {
                  'start': start | as_timestamp | timestamp_custom(date_time_format),
                  'end': end | as_timestamp | timestamp_custom(date_time_format),
                  'preset': 'Winter Credit: Peak Event',
                }, {
                  'start': end | as_timestamp | timestamp_custom(date_time_format),
                  'end': (end + timedelta(minutes = 90)) | as_timestamp | timestamp_custom(date_time_format),
                  'preset': 'Boost',
                }] -%}
              {% endif -%}
            {% endfor %}

            {{ ns.events }}

      - if: "{{ count == 0 or count != events | length / 2 }}"
        then:
          - service: "persistent_notification.create"
            data:
              title: "Failed to parse peak event notification"
              message: |
                <strong>{{ text }}</strong>
                <hr>
                <pre>{{ events }}</pre>

      - repeat:
          for_each: "{{ events }}"
          sequence:
            - service: "calendar.create_event"
              target:
                entity_id: "calendar.climate_exceptions"
              data:
                summary: "{{ repeat.item.preset }}"
                description: "{{ text }}"
                start_date_time: "{{ repeat.item.start }}"
                end_date_time: "{{ repeat.item.end }}"
