- platform: group
  name: 'default'
  services:
    - service: pushbullet
    - service: html5

- platform: group
  name: 'admin'
  services:
    - service: pushbullet
    - service: html5
      data:
        target: ['chris chrome', 'chris mobile']

