- platform: template
  sensors:
    hue_hub:
      friendly_name: 'Hue Hub'
      entity_id:
        - device_tracker.hue_hub
      value_template: '{% if is_state("device_tracker.hue_hub", "home") %}Online{% else %}Offline{% endif %}'
