- platform: template
  sensors:
    network_avatar_media:
      entity_id: device_tracker.avatar_media
      value_template: '{% if is_state("device_tracker.avatar_media", "home") %}Online{% else %}Offline{% endif %}'
    network_hue_hub:
      entity_id: device_tracker.hue_hub
      value_template: '{% if is_state("device_tracker.hue_hub", "home") %}Online{% else %}Offline{% endif %}'
