- platform: snmp
  host: !secret device_tracker_router_host
  community: "public"
  baseoid: "1.3.6.1.2.1.4.22.1.2"

  # Options shared by all trackers
  track_new_devices: false
  interval_seconds: 10 # seconds between each scan
  consider_home: 60 # seconds unseen but considered home

#- platform: nmap_tracker
#  home_interval: 1
#  hosts: !secret device_tracker_hosts
#  home_interval: 1

- platform: tomato
  host: !secret device_tracker_router_host
  username: !secret device_tracker_tomato_username
  password: !secret device_tracker_tomato_password
  http_id: !secret device_tracker_tomato_http_id

- platform: owntracks
  max_gps_accuracy: 200
  waypoints: false
