settings_view:
  name: "Settings"
  icon: "mdi:settings"
  view: true
  entities:
    - group.global_settings
    - group.wake_up_alarm

global_settings:
  name: "Global Settings"
  icon: "mdi:settings-box"
  entities:
    - input_boolean.guest_mode
    - input_boolean.debug_mode
    - input_boolean.publish_state_persistence
