script:
  active_climate_preset:
    alias: "Active climate preset"
    sequence:
      - service: scene.apply
        data_template:
          entities:
            input_select.basement_bathroom_thermostat_mode: "{% if is_state('input_select.basement_bathroom_thermostat_mode', 'Manual') %}Manual{% else %}Comfort{% endif %}"
            input_select.basement_hallway_thermostat_mode: "{% if is_state('input_select.basement_hallway_thermostat_mode', 'Manual') %}Manual{% else %}Comfort{% endif %}"
            input_select.dining_room_thermostat_mode: "{% if is_state('input_select.dining_room_thermostat_mode', 'Manual') %}Manual{% else %}Comfort{% endif %}"
            input_select.guest_bedroom_thermostat_mode: "{% if is_state('input_select.guest_bedroom_thermostat_mode', 'Manual') %}Manual{% else %}Comfort{% endif %}"
            input_select.living_room_thermostat_mode: "{% if is_state('input_select.living_room_thermostat_mode', 'Manual') %}Manual{% else %}Comfort{% endif %}"
            input_select.lounge_thermostat_mode: "{% if is_state('input_select.lounge_thermostat_mode', 'Manual') %}Manual{% else %}Comfort{% endif %}"
            input_select.master_bedroom_thermostat_mode: "{% if is_state('input_select.master_bedroom_thermostat_mode', 'Manual') %}Manual{% else %}Comfort{% endif %}"
            input_select.office_thermostat_mode: "{% if is_state('input_select.office_thermostat_mode', 'Manual') %}Manual{% else %}Comfort{% endif %}"
            input_select.studio_thermostat_mode: "{% if is_state('input_select.studio_thermostat_mode', 'Manual') %}Manual{% else %}Comfort{% endif %}"

  away_climate_preset:
    alias: "Away climate preset"
    sequence:
      - service: scene.apply
        data_template:
          entities:
            input_select.basement_bathroom_thermostat_mode: "{% if is_state('input_select.basement_bathroom_thermostat_mode', 'Manual') %}Manual{% else %}Eco{% endif %}"
            input_select.basement_hallway_thermostat_mode: "{% if is_state('input_select.basement_hallway_thermostat_mode', 'Manual') %}Manual{% else %}Eco{% endif %}"
            input_select.dining_room_thermostat_mode: "{% if is_state('input_select.dining_room_thermostat_mode', 'Manual') %}Manual{% else %}Eco{% endif %}"
            input_select.guest_bedroom_thermostat_mode: "{% if is_state('input_select.guest_bedroom_thermostat_mode', 'Manual') %}Manual{% else %}Eco{% endif %}"
            input_select.living_room_thermostat_mode: "{% if is_state('input_select.living_room_thermostat_mode', 'Manual') %}Manual{% else %}Eco{% endif %}"
            input_select.lounge_thermostat_mode: "{% if is_state('input_select.lounge_thermostat_mode', 'Manual') %}Manual{% else %}Eco{% endif %}"
            input_select.master_bedroom_thermostat_mode: "{% if is_state('input_select.master_bedroom_thermostat_mode', 'Manual') %}Manual{% else %}Eco{% endif %}"
            input_select.office_thermostat_mode: "{% if is_state('input_select.office_thermostat_mode', 'Manual') %}Manual{% else %}Eco{% endif %}"
            input_select.studio_thermostat_mode: "{% if is_state('input_select.studio_thermostat_mode', 'Manual') %}Manual{% else %}Eco{% endif %}"

  bedtime_climate_preset:
    alias: "Bedtime climate preset"
    sequence:
      - service: scene.apply
        data_template:
          entities:
            input_select.basement_bathroom_thermostat_mode: "{% if is_state('input_select.basement_bathroom_thermostat_mode', 'Manual') %}Manual{% else %}Eco{% endif %}"
            input_select.basement_hallway_thermostat_mode: "{% if is_state('input_select.basement_hallway_thermostat_mode', 'Manual') %}Manual{% else %}Eco{% endif %}"
            input_select.dining_room_thermostat_mode: "{% if is_state('input_select.dining_room_thermostat_mode', 'Manual') %}Manual{% else %}Eco{% endif %}"
            input_select.guest_bedroom_thermostat_mode: "{% if is_state('input_select.guest_bedroom_thermostat_mode', 'Manual') %}Manual{% else %}Eco{% endif %}"
            input_select.living_room_thermostat_mode: "{% if is_state('input_select.living_room_thermostat_mode', 'Manual') %}Manual{% else %}Eco{% endif %}"
            input_select.lounge_thermostat_mode: "{% if is_state('input_select.lounge_thermostat_mode', 'Manual') %}Manual{% else %}Eco{% endif %}"
            input_select.master_bedroom_thermostat_mode: "{% if is_state('input_select.master_bedroom_thermostat_mode', 'Manual') %}Manual{% else %}Comfort{% endif %}"
            input_select.office_thermostat_mode: "{% if is_state('input_select.office_thermostat_mode', 'Manual') %}Manual{% else %}Eco{% endif %}"
            input_select.studio_thermostat_mode: "{% if is_state('input_select.studio_thermostat_mode', 'Manual') %}Manual{% else %}Eco{% endif %}"

  sleep_climate_preset:
    alias: "Sleep climate preset"
    sequence:
      - service: scene.apply
        data_template:
          entities:
            input_select.basement_bathroom_thermostat_mode: "{% if is_state('input_select.basement_bathroom_thermostat_mode', 'Manual') %}Manual{% else %}Eco{% endif %}"
            input_select.basement_hallway_thermostat_mode: "{% if is_state('input_select.basement_hallway_thermostat_mode', 'Manual') %}Manual{% else %}Eco{% endif %}"
            input_select.dining_room_thermostat_mode: "{% if is_state('input_select.dining_room_thermostat_mode', 'Manual') %}Manual{% else %}Eco{% endif %}"
            input_select.guest_bedroom_thermostat_mode: "{% if is_state('input_select.guest_bedroom_thermostat_mode', 'Manual') %}Manual{% else %}Eco{% endif %}"
            input_select.living_room_thermostat_mode: "{% if is_state('input_select.living_room_thermostat_mode', 'Manual') %}Manual{% else %}Eco{% endif %}"
            input_select.lounge_thermostat_mode: "{% if is_state('input_select.lounge_thermostat_mode', 'Manual') %}Manual{% else %}Eco{% endif %}"
            input_select.master_bedroom_thermostat_mode: "{% if is_state('input_select.master_bedroom_thermostat_mode', 'Manual') %}Manual{% else %}Eco{% endif %}"
            input_select.office_thermostat_mode: "{% if is_state('input_select.office_thermostat_mode', 'Manual') %}Manual{% else %}Eco{% endif %}"
            input_select.studio_thermostat_mode: "{% if is_state('input_select.studio_thermostat_mode', 'Manual') %}Manual{% else %}Eco{% endif %}"

  scheduled_climate_preset:
    alias: "Scheduled climate preset"
    sequence:
      - service: script.turn_on
        data_template:
          entity_id: "script.{{ states('sensor.climate_scheduled_preset') | lower }}_climate_preset"

sensor:
  - platform: template
    sensors:
      climate_scheduled_preset:
        friendly_name: "Scheduled climate preset"
        icon_template: "mdi:calendar-clock"
        entity_id: sensor.time
        value_template: |
          {% set schedule = [
            [{"time": 0, "preset": "Sleep"}, {"time": 630, "preset": "Active"}, {"time": 2300, "preset": "Bedtime"}],
            [{"time": 0, "preset": "Sleep"}, {"time": 630, "preset": "Active"}, {"time": 2300, "preset": "Bedtime"}],
            [{"time": 0, "preset": "Sleep"}, {"time": 630, "preset": "Active"}, {"time": 2300, "preset": "Bedtime"}],
            [{"time": 0, "preset": "Sleep"}, {"time": 630, "preset": "Active"}, {"time": 2300, "preset": "Bedtime"}],
            [{"time": 0, "preset": "Sleep"}, {"time": 630, "preset": "Active"}, {"time": 2300, "preset": "Bedtime"}],
            [{"time": 0, "preset": "Sleep"}, {"time": 630, "preset": "Active"}, {"time": 2300, "preset": "Bedtime"}],
            [{"time": 0, "preset": "Sleep"}, {"time": 730, "preset": "Active"}, {"time": 2300, "preset": "Bedtime"}],
          ] %}

          {% set day_index = now().weekday() %}
          {% set time_index = states("sensor.time") | replace(":", "") | int %}
          {% set days = (range(day_index + 1, 7) | list + range(0, day_index) | list) | reverse | list %}

          {% set match = namespace(
            day = day_index,
            preset = schedule[day_index] | rejectattr("time", ">", time_index) | map(attribute = "preset") | list | last
          ) %}

          {% for day in days if match.preset is not defined %}
          {% set match.day = day %}
          {% set match.preset = schedule[day] | map(attribute = "preset") | list | last %}
          {% endfor %}

          {{ match.preset | default('Away') }}

automation:
  - alias: apply_scheduled_climate_preset
    hide_entity: True
    initial_state: True
    trigger:
      - platform: state
        entity_id: "group.household"
        to: "home"
      - platform: time_pattern
        minutes: "/15"
    condition:
      - condition: state
        entity_id: "group.household"
        state: "home"
    action:
      - service: script.scheduled_climate_preset

  - alias: "cleanup_manual_thermostat_mode"
    hide_entity: True
    initial_state: True
    trigger:
      - platform: state
        entity_id:
          - input_select.basement_bathroom_thermostat_mode
          - input_select.basement_hallway_thermostat_mode
          - input_select.dining_room_thermostat_mode
          - input_select.guest_bedroom_thermostat_mode
          - input_select.living_room_thermostat_mode
          - input_select.lounge_thermostat_mode
          - input_select.master_bedroom_thermostat_mode
          - input_select.office_thermostat_mode
          - input_select.studio_thermostat_mode
        to: "Manual"
        for: "02:00:00"
    action:
      - service: input_select.select_option
        data_template:
          entity_id: "{{ trigger.to_state.entity_id }}"
          option: "Eco"