homeassistant:
  customize:
    person.chris:
      entity_picture: !secret people_chris_picture_url
    person.karine:
      entity_picture: !secret people_karine_picture_url

group:
  household:
    name: "Household"
    icon: "mdi:account-multiple"
    entities:
      - person.chris
      - person.karine
