homeassistant:
  customize:
    person.chris:
      entity_picture: /local/secrets/chris.webp
    person.karine:
      entity_picture: /local/secrets/karine.webp

group:
  household:
    name: "Household"
    icon: "mdi:account-multiple"
    entities:
      - person.chris
      - person.karine

person:
  - id: "chris"
    name: "Chris"
    user_id: "221fad543e1a4c05af8aaac8c68e985e"
    device_trackers:
      - device_tracker.chris_router_pixel_1
      - device_tracker.chris_mobile_app_pixel_1
  - id: "karine"
    name: "Karine"
    user_id: "ef6743938a1646d2a1e8706e1bc00e34"
    device_trackers:
      - device_tracker.karine_router_pixel_1
      - device_tracker.karine_mobile_app_pixel_1
