homeassistant:
  customize:
    person.chris:
      entity_picture: /local/secrets/chris.webp
    person.karine:
      entity_picture: /local/secrets/karine.webp

person:
  - id: "chris"
    name: "Chris"
    user_id: "221fad543e1a4c05af8aaac8c68e985e"
    device_trackers:
      - device_tracker.chris_router_pixel_1
      - device_tracker.chris_mobile_app_pixel_1
  - id: "karine"
    name: "Karine"
    user_id: "ef6743938a1646d2a1e8706e1bc00e34"
    device_trackers:
      - device_tracker.karine_router_pixel_1
      - device_tracker.karine_mobile_app_pixel_1

group:
  household:
    name: "Household"
    icon: "mdi:account-multiple"
    entities:
      - person.chris
      - person.karine

input_boolean:
  guest_mode:
    name: "Guest mode"
    icon: "mdi:human-greeting"
  notify_household_changes:
    name: "Notify household changes"
    icon: "mdi:message-settings-variant"

automation:
  - alias: notify_guest_arrives
    initial_state: True
    trigger:
      platform: state
      entity_id: "group.guests"
      to: "home"
    action:
      - service: python_script.notify
        data_template:
          persistent: True
          push_target: "household"
          title: "Guest arrival"
          message: "A new guest has just arrived at home."

  - alias: notify_household_person_arrives
    initial_state: True
    trigger:
      platform: state
      entity_id:
        - person.chris
        - person.karine
      to: "home"
    condition:
      condition: state
      entity_id: input_boolean.notify_household_changes
      state: "on"
    action:
      - service: python_script.notify
        data_template:
          push_target: "admin"
          tag: "presence_{{ trigger.to_state.object_id }}"
          title: "{{ trigger.to_state.name }} arrived home."
          message: "Household is {{ states('group.household') }}."

  - alias: notify_household_person_leaves
    initial_state: True
    trigger:
      platform: state
      entity_id:
        - person.chris
        - person.karine
      from: "home"
    condition:
      condition: state
      entity_id: input_boolean.notify_household_changes
      state: "on"
    action:
      - service: python_script.notify
        data_template:
          push_target: "admin"
          tag: "presence_{{ trigger.to_state.object_id }}"
          title: "{{ trigger.to_state.name }} left home."
          message: "Household is {{ states('group.household') }}."
