group:
  ups:
    name: "UPS"
    icon: "mdi:power-plug"
    entities:
      - sensor.ups_status
      - sensor.ups_load
      - sensor.ups_battery
      - sensor.ups_input_voltage
      - sensor.ups_time_left
      - sensor.ups_time_on_battery

apcupsd:
  host: !secret ups_host
  port: !secret ups_port

binary_sensor:
  - platform: apcupsd

sensor:
  - platform: apcupsd
    resources:
      - bcharge # Battery Charge
      - linev # Input Voltage
      - loadpct # Load %
      - status
      - timeleft # Time Left on Battery
      - tonbatt # Time on Battery

automation:
  - alias: notify_ups_state
    hide_entity: true
    trigger:
      platform: state
      entity_id: "binary_sensor.ups_online_status"
    action:
      service: notify.admin
      data_template:
        message: "UPS is running {% if is_state('binary_sensor.ups_online_status', 'on') %}back on power!{% else %}on battery! Shutting down media soon.{% endif %}"
      data:
        data:
          tag: "ups_state"

  - alias: notify_ups_replace_battery
    hide_entity: true
    trigger:
      platform: template
      value_template: "{{ 'REPLACEBATT' in states('sensor.ups_status') }}"
    action:
      - service: persistent_notification.create
        data:
          notification_id: "change_ups_battery"
          title: "Replace UPS battery"
          message: "UPS battery must be replaced. Search on amazon: http://amzn.to/2fJo3Ax"
      - service: notify.admin
        data:
          message: "UPS battery must be replaced."
          data:
            tag: "ups_battery"

  - alias: ups_power_off
    hide_entity: true
    trigger:
      platform: state
      entity_id: "binary_sensor.ups_online_status"
      to: "off"
      for:
        seconds: 70 # UPS is polled every 60 secs, this *must* be higher to outlast short power outages.
    action:
      service: switch.turn_off
      entity_id:
        - switch.network_media

  - alias: ups_power_on
    hide_entity: true
    trigger:
      platform: state
      entity_id: "binary_sensor.ups_online_status"
      to: "on"
      for:
        seconds: 30 # Power can come back for a couple seconds then cut again. Been there done that.
    action:
      service: switch.turn_on
      entity_id:
        - switch.network_media
