homeassistant:
  customize:
    group.default_View:
      order: 0
    group.weather_view:
      order: 2
    group.plants_view:
      order: 4
    group.settings_view:
      order: 6
    group.monitoring_view:
      order: 8

group:
  general_settings:
    name: "Settings"
    icon: "mdi:settings"
    control: "hidden"
    entities:
      - input_boolean.guest_mode
      - automation.close_outdoor_lights

  general_notifications:
    name: "Notifications"
    icon: "mdi:message-settings-variant"
    control: "hidden"
    entities:
      - automation.notify_plant_problems

  monitoring_notifications:
    name: "Notifications"
    icon: "mdi:message-settings-variant"
    control: "hidden"
    entities:
      - input_boolean.notify_household_changes
      - input_boolean.notify_power_changes
      - automation.notify_failed_login_attempt
      - automation.notify_update_available
      - automation.notify_network_device_state
      - automation.notify_ups_replace_battery

  default_view:
    name: "Home"
    icon: "mdi:home"
    view: true
    entities:
      - group.household
      - group.outdoor
      - group.master_bedroom
      - group.top_living_room

  plants_view:
    name: "Plants"
    icon: "mdi:flower"
    view: true
    entities:
      - group.plant_gaetan
      - group.plant_spidy
      - group.plant_viny

  weather_view:
    name: "Weather"
    icon: "mdi:weather-partlycloudy"
    view: true
    entities:
      - group.weather

  settings_view:
    name: "Settings"
    icon: "mdi:settings"
    view: true
    entities:
      - group.general_settings
      - group.general_notifications
      - group.wake_up_alarm

  monitoring_view:
    name: "Monitoring"
    icon: "mdi:stethoscope"
    view: true
    entities:
      - updater.updater
      - sensor.connected_clients
      - configurator.philips_hue
      - group.monitoring_notifications
      - group.automate_monitor
      - group.media_monitor
      - group.network_devices
      - group.ups
