homeassistant:
  customize:
    group.default_View:
      order: 0
    group.weather_view:
      order: 2
    group.plants_view:
      order: 4
    group.settings_view:
      order: 6
    group.monitoring_view:
      order: 8

group:
  general_settings:
    name: "Settings"
    icon: "mdi:settings"
    entities:
      - input_boolean.guest_mode
      - automation.close_outdoor_lights

  monitoring_settings:
    name: "Settings"
    icon: "mdi:settings"
    entities:
      - input_boolean.home_presence_notifications

  default_view:
    name: "Home"
    icon: "mdi:home"
    view: true
    entities:
      - group.household
      - group.outdoor
      - group.master_bedroom
      - group.top_living_room

  plants_view:
    name: "Plants"
    icon: "mdi:flower"
    view: true
    entities:
      - group.plant_susan

  weather_view:
    name: "Weather"
    icon: "mdi:weather-partlycloudy"
    view: true
    entities:
      - group.weather

  settings_view:
    name: "Settings"
    icon: "mdi:settings"
    view: true
    entities:
      - group.general_settings
      - group.wake_up_alarm

  monitoring_view:
    name: "Monitoring"
    icon: "mdi:stethoscope"
    view: true
    entities:
      - updater.updater
      - sensor.connected_clients
      - configurator.philips_hue
      - group.monitoring_settings
      - group.automate_monitor
      - group.media_monitor
      - group.network_devices
      - group.ups
