weather:
  - platform: environment_canada
    name: "Québec"
    station: &env_canada_station "QC/s0000620"

sun: {}

sensor:
  - platform: moon

  - platform: environment_canada
    entity_namespace: "weather_quebec"
    station: *env_canada_station
