homeassistant:
  customize:
    weather.dark_sky:
      friendly_name: "Weather"

weather:
  - platform: darksky
    api_key: !secret weather_dark_sky_api_key
    mode: "daily"

sun: {}

sensor:
  - platform: moon
  - platform: darksky
    api_key: !secret weather_dark_sky_api_key
    forecast:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
    language: "en"
    monitored_conditions:
      - humidity
      - icon
      - summary
      - temperature
      - uv_index
    scan_interval: "00:15"
