homeassistant:
  customize:
    sensor.yr_humidity:
      friendly_name: "Humidity"
    sensor.yr_symbol:
      friendly_name: "Weather"
    sensor.yr_temperature:
      friendly_name: "Temperature"

sensor:
  - platform: yr
    monitored_conditions:
      - symbol
      - temperature
      - humidity

group:
  weather_view:
    name: "Weather"
    icon: "mdi:weather-partlycloudy"
    view: true
    entities:
      - group.weather

  weather:
    name: "Weather"
    icon: "mdi:weather-partlycloudy"
    entities:
      - sun.sun
      - sensor.yr_humidity
      - sensor.yr_temperature
      - sensor.yr_symbol

